module

public import Stellmacher.Recognition.FongWreathedBorelData
public import Theory.GroupAction.SimpleCosets
public import Theory.GroupTheory.NormalizedSupCard
public import Mathlib.GroupTheory.Complement

/-!
# Subgroup consequences in Fong's degree-28 construction

Given the actual subgroup witnesses on Fong p.75, the cyclic group generated
by `F` complements `Q` in `B`: their orders are eight and twenty-seven.
Consequently `B` has order 216 and its quotient by `Q` is cyclic of order
eight. In a simple ambient group of order 6048, the coset action is faithful
and has degree 28.

These consequences are shared by the permutation-character argument and
the final construction in `FongWreathedBorel`. All public declarations retain
their original names and are re-exported by that assembly module.
Source: Fong, J. Algebra 6 (1967), p.75, final paragraph.
-/

namespace Stellmacher.Recognition.FongWreathed.BorelSubgroups

variable {G : Type*} [Group G] {S : Sylow 2 G}
variable {P : ABG.Wreathed.Presentation S 2} (b : BorelSubgroups P)

public theorem Q_le_B : b.Q ≤ b.B := by
  rw [b.B_eq]
  exact le_sup_right

public theorem zpowers_F_le_B : Subgroup.zpowers (F P) ≤ b.B := by
  rw [b.B_eq]
  exact le_sup_left

public theorem F_mem_B : F P ∈ b.B :=
  b.zpowers_F_le_B (Subgroup.mem_zpowers _)

public instance normal_Q_in_B : (b.Q.subgroupOf b.B).Normal :=
  Subgroup.normal_subgroupOf_of_le_normalizer b.Q_normalized

public theorem R_mem_Q : b.R ∈ b.Q :=
  Subgroup.map_subtype_le (Subgroup.center b.Q) b.R_mem_center

public theorem zpowers_F_sq_le_B : Subgroup.zpowers (F P ^ 2) ≤ b.B :=
  Subgroup.zpowers_le.mpr (b.B.pow_mem b.F_mem_B 2)

public theorem centralizer_R_le_B : Subgroup.centralizer ({b.R} : Set G) ≤ b.B := by
  rw [b.centralizer_R]
  exact sup_le b.zpowers_F_sq_le_B b.Q_le_B

public theorem disjoint_F_Q : Disjoint (Subgroup.zpowers (F P)) b.Q := by
  apply Subgroup.disjoint_of_coprime_natCard
  rw [Nat.card_zpowers, orderOf_F, b.card_Q]
  decide

public theorem disjoint_F_sq_Q : Disjoint (Subgroup.zpowers (F P ^ 2)) b.Q := by
  apply Subgroup.disjoint_of_coprime_natCard
  rw [Nat.card_zpowers, orderOf_F_sq, b.card_Q]
  decide

public theorem card_centralizer_R : Nat.card (Subgroup.centralizer ({b.R} : Set G)) = 108 := by
  rw [b.centralizer_R, sup_comm,
    Subgroup.card_sup_eq_mul_of_normalizes_of_disjoint b.Q _
      (b.zpowers_F_sq_le_B.trans b.Q_normalized) b.disjoint_F_sq_Q.symm,
    b.card_Q, Nat.card_zpowers, orderOf_F_sq]

public theorem card_F_in_B : Nat.card ((Subgroup.zpowers (F P)).subgroupOf b.B) = 8 := by
  rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe b.zpowers_F_le_B).toEquiv,
    Nat.card_zpowers, orderOf_F]

public theorem card_Q_in_B : Nat.card (b.Q.subgroupOf b.B) = 27 := by
  rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe b.Q_le_B).toEquiv, b.card_Q]

public theorem complement :
    ((Subgroup.zpowers (F P)).subgroupOf b.B).IsComplement' (b.Q.subgroupOf b.B) := by
  have hdis : Disjoint ((Subgroup.zpowers (F P)).subgroupOf b.B) (b.Q.subgroupOf b.B) := by
    apply Subgroup.disjoint_of_coprime_natCard
    rw [b.card_F_in_B, b.card_Q_in_B]
    decide
  have hgen : (Subgroup.zpowers (F P)).subgroupOf b.B ⊔ b.Q.subgroupOf b.B = ⊤ := by
    rw [← Subgroup.subgroupOf_sup b.zpowers_F_le_B b.Q_le_B, ← b.B_eq,
      Subgroup.subgroupOf_self]
  refine ⟨Subgroup.mul_injective_of_disjoint hdis, fun g => ?_⟩
  have hg : g ∈ (Subgroup.zpowers (F P)).subgroupOf b.B ⊔ b.Q.subgroupOf b.B := by
    rw [hgen]
    trivial
  obtain ⟨a, ha, q, hq, he⟩ := Subgroup.mem_sup_of_normal_right.mp hg
  exact ⟨(⟨a, ha⟩, ⟨q, hq⟩), he⟩

public theorem card_B : Nat.card b.B = 216 := by
  have h := b.complement.card_mul_card
  rw [b.card_F_in_B, b.card_Q_in_B] at h
  omega

/-- An actual isomorphism from `B/Q` to the ambient cyclic group generated by `F`. -/
public noncomputable def quotientEquiv :
    (b.B ⧸ b.Q.subgroupOf b.B) ≃* Subgroup.zpowers (F P) :=
  b.complement.QuotientMulEquiv.trans (Subgroup.subgroupOfEquivOfLe b.zpowers_F_le_B)

public theorem quotient_cyclic : IsCyclic (b.B ⧸ b.Q.subgroupOf b.B) :=
  isCyclic_of_injective b.quotientEquiv.toMonoidHom b.quotientEquiv.injective

public theorem card_quotient : Nat.card (b.B ⧸ b.Q.subgroupOf b.B) = 8 := by
  rw [Nat.card_congr b.quotientEquiv.toEquiv, Nat.card_zpowers, orderOf_F]

public theorem index_B (hG : Nat.card G = 6048) : b.B.index = 28 := by
  have h := b.B.card_mul_index
  rw [b.card_B, hG] at h
  omega

public theorem card_cosets (hG : Nat.card G = 6048) : Nat.card (G ⧸ b.B) = 28 :=
  (Subgroup.index_eq_card b.B).symm.trans (b.index_B hG)

public theorem faithful_cosets [IsSimpleGroup G] (hG : Nat.card G = 6048) :
    FaithfulSMul G (G ⧸ b.B) := by
  apply b.B.faithfulSMul_quotient_of_simple
  intro htop
  have h := b.index_B hG
  rw [htop, Subgroup.index_top] at h
  omega

end Stellmacher.Recognition.FongWreathed.BorelSubgroups
