module

public import Stellmacher.Recognition.GTwoAbelianBase
public import Theory.GroupTheory.CyclicFourQuaternionProductGeometry
public import ABG.ChapterII.Section1.C4SquareWreathedRecognition
public import ABG.ChapterII.Section2.SylowShapeTransport

/-!
# Wreathed Sylow groups of order 32 in the G₂ local type

The original `IsOfGTwoTwoDerivedType` data determine a wreathed Sylow
2-subgroup of height two whenever the ambient Sylow has order 32. No
simplicity, N₂, odd-core or ambient-generation hypothesis is required.

The actual next vertex's normal 2-core embeds in the distinguished ambient
Sylow intersection. Its quaternion-by-quaternion central-product alternative
would give that vertex a Sylow 2-subgroup of order 64, so the order-32 premise
forces the cyclic-four-by-quaternion alternative. The central-product
geometry supplies an order-16 subgroup with cyclic center generated by
involutions. Together with the normal `C4 × C4` base, the generic wreathed
criterion gives the presentation; Sylow conjugacy transports it to the
prescribed ambient Sylow subgroup.

This is the order-32 local calculation for Stellmacher, *N-Gruppen*,
(8.6)(a1,a2), journal p. 41, with the original local-type definition on p. 45.
The order-64 alternative and global recognition are separate obligations.
-/

namespace Stellmacher.Recognition

open Later SectionsFiveToSeven SevenSix

private theorem embedded_quaternion_geometry
    {K S : Type*} [Group K] [Finite K] [Group S]
    (Q : Subgroup K) (hQ : IsCentralProductModel Q C4 Q8)
    (f : Q →* S) (hf : Function.Injective f) :
    ∃ B : Subgroup S, Nat.card B = 16 ∧ IsCyclic (Subgroup.center B) ∧
      Subgroup.closure {x : S | x ∈ B ∧ x ^ 2 = 1} = B := by
  have hcardQ := SectionEight.eight_six_c4_quaternion_card hQ
  obtain ⟨U, V, ⟨eU⟩, ⟨eV⟩, hUV, hinter, hcomm, _⟩ := hQ
  have hUQ : U ≤ Q := hUV ▸ le_sup_left
  have hVQ : V ≤ Q := hUV ▸ le_sup_right
  let UQ := U.subgroupOf Q
  let VQ := V.subgroupOf Q
  let U' := UQ.map f
  let V' := VQ.map f
  let B := U' ⊔ V'
  let eU' : U' ≃* C4 := ((UQ.equivMapOfInjective f hf).symm.trans
    (Subgroup.subgroupOfEquivOfLe hUQ)).trans eU
  let eV' : V' ≃* Q8 := ((VQ.equivMapOfInjective f hf).symm.trans
    (Subgroup.subgroupOfEquivOfLe hVQ)).trans eV
  have hUVtop : UQ ⊔ VQ = ⊤ := by
    rw [← Subgroup.subgroupOf_sup hUQ hVQ, ← hUV]
    exact Subgroup.subgroupOf_self Q
  have hBrange : B = f.range := by
    change UQ.map f ⊔ VQ.map f = _
    rw [← Subgroup.map_sup, hUVtop, MonoidHom.range_eq_map]
  have hcardB : Nat.card B = 16 := by
    rw [hBrange, ← Nat.card_congr (MonoidHom.ofInjective hf).toEquiv]
    exact hcardQ
  have hinter' : Nat.card (U' ⊓ V' : Subgroup S) = 2 := by
    rw [show U' ⊓ V' = (UQ ⊓ VQ).map f from (Subgroup.map_inf UQ VQ f hf).symm,
      Subgroup.card_map_of_injective hf]
    change Nat.card ((U ⊓ V).subgroupOf Q) = 2
    rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe
      (show U ⊓ V ≤ Q from inf_le_left.trans hUQ)).toEquiv, hinter]
  have hcomm' : ∀ u ∈ U', ∀ v ∈ V', u * v = v * u := by
    rintro _ ⟨u, hu, rfl⟩ _ ⟨v, hv, rfl⟩
    rw [← map_mul, ← map_mul]
    apply congrArg f
    exact Subtype.ext (hcomm u hu v hv)
  obtain ⟨hcenter, hgen⟩ := Subgroup.cyclicFour_quaternion_product_geometry
    U' V' ⟨eU'⟩ ⟨eV'⟩ hinter' hcomm'
  let eC : Subgroup.center B ≃* U' :=
    ((Subgroup.center B).equivMapOfInjective B.subtype B.subtype_injective).trans
      (MulEquiv.subgroupCongr hcenter)
  exact ⟨B, hcardB, (eC.trans eU').isCyclic.mpr inferInstance, hgen⟩

private theorem quotient_sl2_card {K : Type*} [Group K] [Finite K]
    (P Q : Subgroup K) (hQP : Q ≤ P) (hmodel : QuotientIsModel P Q SL2Two) :
    Nat.card P = 6 * Nat.card Q := by
  obtain ⟨projection, hsurj, hker⟩ := hmodel
  have hcount := projection.ker.index_mul_card
  rw [Subgroup.index_ker, projection.range_eq_top_of_surjective hsurj,
    Subgroup.card_top, hker] at hcount
  rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hQP).toEquiv] at hcount
  have hmodelCard : Nat.card SL2Two = 6 :=
    SectionOne.RankOneThreeGroupAssembly.isSL2Two_card ⟨MulEquiv.refl _⟩
  rw [hmodelCard] at hcount
  exact hcount.symm

/-- The actual order-32 Sylow subgroup of the G₂ local type is wreathed of height two. -/
public theorem wreathed_of_gTwoTwoDerived_type_of_card32
    {G : Type*} [Group G] [Finite G] (S0 : Sylow 2 G)
    (hType : IsOfGTwoTwoDerivedType G) (hcard : Nat.card S0 = 32) :
    ABG.IsWreathedOfHeight S0 2 := by
  obtain ⟨data⟩ := hType
  let := data.groupK
  let := data.finiteK
  let S := data.sylowIntersection
  let P := GAt data.Γ data.criticalPath.firstStep
  let Q := QAt data.Γ data.criticalPath.firstStep
  have hQ : Q = twoCoreIn P := data.Γ.twoCoreAt_def _
  have hQP : Q ≤ P := by rw [hQ]; exact twoCoreIn_le P
  have hQN : (Q.subgroupOf P).Normal := by rw [hQ]; exact twoCoreIn_normal P
  let Pm := P.map data.embedding
  let Qm := Q.map data.embedding
  have hQmPm : Qm ≤ Pm := Subgroup.map_mono hQP
  have hSP : (S : Subgroup G) ≤ Pm := by
    rw [← data.intersection_eq]
    exact inf_le_right
  have hScard : Nat.card S = 32 := (Nat.card_congr (S.equiv S0).toEquiv).trans hcard
  have hQmN : (Qm.subgroupOf Pm).Normal := by
    apply (Subgroup.normal_subgroupOf_iff_le_normalizer hQmPm).mpr
    exact (Subgroup.map_mono
      ((Subgroup.normal_subgroupOf_iff_le_normalizer hQP).mp hQN)).trans
      (Subgroup.le_normalizer_map data.embedding)
  have hQmS : Qm ≤ (S : Subgroup G) := by
    let := hQmN
    have htwo : IsPGroup 2 Q := by
      rw [hQ]
      exact pCore_isPGroup.map P.subtype
    have hm : IsPGroup 2 (Qm.subgroupOf Pm) :=
      (htwo.map data.embedding).of_equiv (Subgroup.subgroupOfEquivOfLe hQmPm).symm
    have hle := hm.le_sylow_of_normal (S.subtype hSP)
    intro x hx
    exact hle (show (⟨x, hQmPm hx⟩ : Pm) ∈ Qm.subgroupOf Pm from hx)
  have hsmall : IsCentralProductModel Q C4 Q8 := by
    rcases data.caseA.next_twoCore.1 with hsmall | hlarge
    · exact hsmall
    have hQcard : Nat.card Q = 32 := SectionEight.eight_six_quaternion_quaternion_card hlarge
    have hPcard : Nat.card P = 192 := by
      rw [quotient_sl2_card P Q hQP (data.caseA.local_quotients _), hQcard]
    let T : Sylow 2 Pm := S.subtype hSP
    have hTcard : Nat.card T = 32 :=
      (Nat.card_congr (Subgroup.subgroupOfEquivOfLe hSP).toEquiv).trans hScard
    rw [T.card_eq_multiplicity, Subgroup.card_map_of_injective data.embedding_injective,
      hPcard] at hTcard
    change 2 ^ (3 * 2 ^ 6).factorization 2 = 32 at hTcard
    rw [Nat.factorization_mul (by decide) (by decide), Nat.factorization_pow] at hTcard
    norm_num [Nat.prime_two.factorization, Nat.prime_three.factorization] at hTcard
  let f : Q →* S := (data.embedding.comp Q.subtype).codRestrict (S : Subgroup G)
    (fun q => hQmS ⟨q, q.property, rfl⟩)
  have hf : Function.Injective f := by
    intro x y h
    apply Subtype.ext
    exact data.embedding_injective (congrArg Subtype.val h)
  obtain ⟨B, hBcard, hBC, hBI⟩ := embedded_quaternion_geometry Q hsmall f hf
  obtain ⟨A, hAN, hA, _⟩ := exists_normal_c4_prod_c4_of_gTwoTwoDerived_type S ⟨data⟩
  have hW := ABG.isWreathedOfHeight_two_of_normal_c4_square hScard A B hAN hA hBcard hBC hBI
  exact ABG.wreathed_equiv (S.equiv S0) hW

end Stellmacher.Recognition
