module

public import Stellmacher.Recognition.NormalEightSeparatedActorTransport
public import Theory.GroupTheory.PGroup.NormalFourNormalizerGrowth
public import Stellmacher.Recognition.NormalEightSeparatedMovingActor
public import Theory.GroupTheory.PGroup.NormalEightCenterTwoElementaryBound
public import Theory.GroupTheory.PGroup.MaximalElementaryCentralizer

/-!
# Separated normalizer actors

The central-omega-two rank bound makes the elementary sixteen generated by
a disjoint commuting returning pair maximal. Its centralizer therefore has
first omega equal to that sixteen. Normalizer growth and separated conjugate
rigidity supply a fixed-point-free moving four. Transport switches the two
factors and supplies the symmetric actor, completing the cross action.
No elementary rank bound is inferred for arbitrary subgroups from the
normal-only exclusion.

Source: Janko–Thompson, Math. Z. 113 (1970), printed pp.394–395.
-/

namespace Stellmacher.Recognition.NormalEightSeparatedActors

open Subgroup

/-- Apply the normalizer-growth step inside the original Sylow. Only the
first omega of this particular centralizer needs to be identified. -/
public theorem exists_moving_four_of_omega_centralizer
    {G : Type*} [Group G] [Finite G] (S : Sylow 2 G)
    (hno : ¬ ∃ D : Subgroup S, D.Normal ∧ IsElementaryAbelian 2 D ∧ 8 ≤ Nat.card D)
    (W B : Subgroup S) [W.Normal]
    [IsElementaryAbelian 2 W] [IsElementaryAbelian 2 B]
    (hBW : B ≤ centralizer (W : Set S)) (hlarge : 8 ≤ Nat.card (W ⊔ B : Subgroup S))
    (hOmega : (omega₁ (centralizer ((W ⊔ B : Subgroup S) : Set S)) (p := 2)).map
      (centralizer ((W ⊔ B : Subgroup S) : Set S)).subtype = W ⊔ B) :
    ∃ s : S,
      B.map (MulAut.conj s).toMonoidHom ≤ normalizer ((W ⊔ B : Subgroup S) : Set S) ∧
      B.map (MulAut.conj s).toMonoidHom ≤ centralizer (W : Set S) ∧
      ¬ B.map (MulAut.conj s).toMonoidHom ≤
        centralizer ((W ⊔ B : Subgroup S) : Set S) :=
  exists_conjugate_normalizing_sup_not_centralizing S.isPGroup' hno W B hBW hlarge hOmega

open NormalFourCentralOmegaTwo NormalEightSeparatedFusion

variable {G : Type*} [Group G] [Finite G]

/-- The returning pair generates a largest elementary subgroup, so the first
omega of its centralizer is precisely its join. -/
public theorem omega_centralizer_returning_pair
    (S : Sylow 2 G)
    (hno : ¬ ∃ D : Subgroup S, D.Normal ∧ IsElementaryAbelian 2 D ∧ 8 ≤ Nat.card D)
    (hZ : Nat.card (omega₁ (center S) (p := 2)) = 2)
    (W : Subgroup S) [W.Normal] [IsElementaryAbelian 2 W] (hW : Nat.card W = 4)
    (hunique : ∀ F : Subgroup S, F.Normal → IsElementaryAbelian 2 F →
      Nat.card F = 4 → F = W)
    (g : G)
    (hreturn : (W.map (S : Subgroup G).subtype).map (MulAut.conj g).toMonoidHom ≤
      (S : Subgroup G))
    (hdisjoint : Disjoint (W.map (S : Subgroup G).subtype)
      ((W.map (S : Subgroup G).subtype).map (MulAut.conj g).toMonoidHom))
    (hcommute : (W.map (S : Subgroup G).subtype).map (MulAut.conj g).toMonoidHom ≤
      centralizer (W.map (S : Subgroup G).subtype : Set G)) :
    let B :=
      ((W.map (S : Subgroup G).subtype).map (MulAut.conj g).toMonoidHom).subgroupOf
        (S : Subgroup G)
    let Y := centralizer ((W ⊔ B : Subgroup S) : Set S)
    (omega₁ Y (p := 2)).map Y.subtype = W ⊔ B := by
  let W₀ := W.map (S : Subgroup G).subtype
  let W₁ := W₀.map (MulAut.conj g).toMonoidHom
  let B := W₁.subgroupOf (S : Subgroup G)
  let : IsElementaryAbelian 2 W₀ := IsElementaryAbelian.map_subtype
  let : IsElementaryAbelian 2 W₁ := IsElementaryAbelian.map _
  let : IsElementaryAbelian 2 B := IsElementaryAbelian.subgroupOf hreturn
  have hB4 : Nat.card B = 4 := by
    rw [Nat.card_congr (subgroupOfEquivOfLe hreturn).toEquiv,
      card_map_of_injective (MulAut.conj g).injective,
      card_map_of_injective (S : Subgroup G).subtype_injective, hW]
  have hBW : B ≤ centralizer (W : Set S) := by
    intro b hb w hw
    exact Subtype.ext (hcommute hb w (mem_map_of_mem _ hw))
  have hdWB : Disjoint W B := by
    apply disjoint_def.mpr
    intro x hxW hxB
    exact Subtype.ext (disjoint_def.mp hdisjoint (mem_map_of_mem _ hxW) hxB)
  let : IsElementaryAbelian 2 (W ⊔ B : Subgroup S) :=
    IsElementaryAbelian.sup_of_le_centralizer hBW
  have hcard : Nat.card (W ⊔ B : Subgroup S) = 16 := by
    rw [card_sup_eq_mul_of_normalizes_of_disjoint W B
      (hBW.trans (Subgroup.centralizer_le_normalizer _)) hdWB, hW, hB4]
  apply omega_one_centralizer_map_eq_of_elementary_card_le (W ⊔ B)
  intro D hD
  rw [hcard]
  exact S.isPGroup'.elementary_card_le_sixteen_of_center_omega_two_of_unique_normal_four
    hno hZ W hW hunique D hD

/-- Construct both fixed-point-free normalizer actors from a disjoint commuting
returning pair. The centralizer omega identity is discharged by the rank bound. -/
public theorem crossAction_of_returning_pair
    (S : Sylow 2 G)
    (hno : ¬ ∃ D : Subgroup S, D.Normal ∧ IsElementaryAbelian 2 D ∧ 8 ≤ Nat.card D)
    (hZ : Nat.card (omega₁ (center S) (p := 2)) = 2)
    (W : Subgroup S) [W.Normal] [IsElementaryAbelian 2 W] (hW : Nat.card W = 4)
    (hunique : ∀ F : Subgroup S, F.Normal → IsElementaryAbelian 2 F →
      Nat.card F = 4 → F = W) [(fourImage S W).Normal]
    (z : S) (hzW : z ∈ W) (hzC : z ∈ center S) (hz : orderOf z = 2)
    (hsep : Separated S W z) (hfactor : CentralizerFactorization S W)
    (hcontrol : LocalCentralizerControl S W) (g : G)
    (hreturn : (W.map (S : Subgroup G).subtype).map (MulAut.conj g).toMonoidHom ≤
      (S : Subgroup G))
    (hdisjoint : Disjoint (W.map (S : Subgroup G).subtype)
      ((W.map (S : Subgroup G).subtype).map (MulAut.conj g).toMonoidHom))
    (hcommute : (W.map (S : Subgroup G).subtype).map (MulAut.conj g).toMonoidHom ≤
      centralizer (W.map (S : Subgroup G).subtype : Set G)) :
    Nonempty (CrossAction (W.map (S : Subgroup G).subtype)) := by
  apply crossAction_of_one_sided_actors S hno hZ W hW hunique z hzW hzC hz
    (g := g) (hreturn := hreturn) (hdisjoint := hdisjoint) (hcommute := hcommute)
  intro k hk hd hc
  exact NormalEightSeparatedMovingActor.exists_oneSidedActor S hno hZ W hW hunique
    z hzW hzC hz hsep hfactor hcontrol k hk hd hc
    (omega_centralizer_returning_pair S hno hZ W hW hunique k hk hd hc)

end Stellmacher.Recognition.NormalEightSeparatedActors
