module
public import Theory.SpecificGroups.PSL3Three.NodeExtensions.Check
public import Theory.SpecificGroups.PSL3Three.CosetCover.Node48
/-!
# Exact extensions of node 48

The untrusted words and conjugators are generated by `NodeExtensions/Generate.py`.
Each row is checked against the actual matrix `Cosets48.rep`. Both containments
are certified for proper targets; ambient generator words certify top targets.
Source: the exact extension criterion in `SubgroupEnumeration`.
-/
namespace Matrix.PSL3Three.CertifiedEnumeration.Extensions48
open Theory.GroupTheory.SubgroupEnumeration CosetCheck ExtensionCheck
set_option maxRecDepth 100000
@[expose] public def block0 : Lean.RArray (Witness 4) := (.branch 6 (.branch 3 (.branch 1 (.leaf (.proper 48 2432 ({ forward := ![[0, 3, 0, 1, 2], [0, 3, 3, 3, 0], [0, 3, 2, 1, 2], [2, 1, 1, 1, 2]], newGenerator := [], backward := ![[0, 3, 0, 1, 2], [0, 3, 3, 3, 0], [0, 3, 2, 1, 2], [2, 1, 1, 1, 2]] } : ExtensionWords 4 4))) (.branch 2 (.leaf (.top ![[0, 3, 2, 4, 2], [2, 5, 3, 5], [0, 5, 0, 1, 2], [0, 4, 3, 4]])) (.leaf (.top ![[0, 3, 2, 4, 1, 0, 1], [1, 5, 3, 2, 4, 1], [3, 2, 3, 2, 5, 1, 2], [2, 1, 5, 5, 3, 0]])))) (.branch 4 (.leaf (.top ![[3, 4, 2, 5, 3, 5], [3, 0, 1, 5, 3, 0], [4, 1, 4, 0, 5, 1], [2, 1, 4, 3, 2, 1]])) (.branch 5 (.leaf (.top ![[5, 2, 3, 4, 4], [4, 0, 4, 1], [4, 4, 1, 0, 4], [3, 5, 2, 5]])) (.leaf (.top ![[2, 4, 1, 5, 5, 1], [2, 4, 0, 5, 0], [1, 2, 5, 5, 1, 5], [2, 4, 2, 5, 0]]))))) (.branch 9 (.branch 7 (.leaf (.top ![[2, 5, 0], [5, 1, 4, 1], [2, 4, 0], [3, 5, 3, 4]])) (.branch 8 (.leaf (.top ![[0, 1, 4, 1, 4, 0], [1, 4, 2, 5, 3], [2, 4, 0, 5, 0, 4], [0, 4, 1, 1, 5]])) (.leaf (.top ![[3, 2, 1, 2, 5, 0], [0, 4, 0, 5, 2], [1, 5, 0, 5, 3, 4], [0, 4, 2, 5, 2]])))) (.branch 11 (.branch 10 (.leaf (.top ![[0, 4, 1, 4, 2, 4], [2, 4, 0, 3, 0, 3, 5], [3, 0, 1, 1, 4, 2], [4, 1, 2, 1, 2, 5, 0]])) (.leaf (.top ![[5], [4, 1, 1, 2, 5, 0], [4], [0, 3, 4, 3, 3, 4]]))) (.branch 12 (.leaf (.top ![[0, 3, 3, 0, 5, 2], [0, 4, 2, 1, 1, 5], [0, 4, 2, 1, 1, 2], [2, 3, 5, 1, 0, 3]])) (.leaf (.top ![[0, 3, 4, 3, 3], [5, 0, 3, 0], [1, 1, 5, 1, 2], [2, 1, 2, 4]]))))))
@[expose] public def witness (j : Fin 13) : Witness 4 :=
  ((.leaf block0) : Lean.RArray (Lean.RArray (Witness 4))).get (j.val / 16) |>.get (j.val % 16)
@[expose] public def rowCheck (k : Nat) : Bool :=
  let j : Fin 13 := ⟨k % 13, Nat.mod_lt _ (by decide)⟩
  check (nodeGenerator 48) (Cosets48.rep j) (witness j)
set_option maxHeartbeats 8000000 in
private theorem checked0 : checkRange rowCheck 0 13 = true := by decide +kernel
public theorem represented (j : Fin 13) :
    Represented node (properNode 48 ⊔ Subgroup.zpowers (Cosets48.rep j)) := by
  apply ExtensionCheck.sound 48 _ (witness j)
  exact checkRange_fin (by decide) (fun j => check (nodeGenerator 48)
    (Cosets48.rep j) (witness j)) checked0 j
end Matrix.PSL3Three.CertifiedEnumeration.Extensions48
