module

public import Theory.Representation.CoefficientDescent
public import Theory.Representation.Induction
public import Theory.Character.Induction
public import Theory.Character.Cyclotomic

/-!
# Cyclotomic models of induced linear characters

Every character induced from a one-dimensional complex character has a model
over the order generated by a primitive root of order `|G|`. In coset
coordinates the action matrices are monomial, and their nonzero entries are
values of the inducing character. These values are roots of unity of order
dividing `|G|`, so the matrix descent theorem applies.

This is the monomial-model step in the cyclotomic splitting theorem; passing
from these induced characters to arbitrary irreducibles additionally requires
integral Brauer induction and descent of virtual characters. See Serre,
*Linear Representations of Finite Groups*, Chapter 12.
-/

public section

noncomputable section
open scoped BigOperators
attribute [local instance] Fintype.ofFinite

namespace Representation
variable {R G : Type*} [CommRing R] [Group G] [Finite G]

/-- Induce a linear character whose values lift through an injective ring map. -/
theorem exists_induced_linear_model_of_range
    (f : R →+* ℂ) (hf : Function.Injective f)
    (H : Subgroup G) (χ : H →* ℂ) (hχ : ∀ h, ∃ r, f r = χ h) :
    ∃ (n : ℕ) (σ : Representation R G (Fin n → R)),
      ∀ g, (mapCoefficients f σ).character g = inducedClassFunction H χ g := by
  classical
  let ρ : Representation ℂ H ℂ := (Algebra.lsmul ℂ ℂ ℂ).toMonoidHom.comp χ
  have hρ (h : H) : ρ h = χ h • LinearMap.id := by
    rfl
  have hchar (h : H) : ρ.character h = χ h := by
    simp [character, hρ, LinearMap.trace_id]
  let e := coindVEquivQuotient H ρ
  let τ : Representation ℂ G (RightCosets H → ℂ) :=
    (e.conjAlgEquiv ℂ).toMonoidHom.comp (coind H.subtype ρ)
  have hτ (g : G) : τ g = coindCoordinateEnd H ρ g := rfl
  obtain ⟨σ, hσ⟩ := exists_model_of_basis_entries f hf τ
    (Pi.basisFun ℂ (RightCosets H)) (by
      intro g i j
      change ∃ r, f r = LinearMap.toMatrix' (τ g) i j
      rw [LinearMap.toMatrix'_apply, hτ, coindCoordinateEnd_apply]
      change ∃ r, f r = χ (rightCosetCorrection H (Quotient.out i * g)) *
        (Pi.single j (1 : ℂ) : RightCosets H → ℂ) (Quotient.mk _ (Quotient.out i * g))
      by_cases h : Quotient.mk (QuotientGroup.rightRel H) (Quotient.out i * g) = j
      · simpa [h] using hχ (rightCosetCorrection H (Quotient.out i * g))
      · exact ⟨0, by simp [Pi.single_eq_of_ne h]⟩)
  refine ⟨Fintype.card (RightCosets H), σ, fun g => ?_⟩
  change LinearMap.trace ℂ _ (mapCoefficients f σ g) = _
  rw [hσ]
  have he (g : G) : τ.character g = (coind H.subtype ρ).character g :=
    LinearMap.trace_conj' _ e
  change τ.character g = _
  rw [he, ← char_iso (indCoindEquiv H ρ), induced_character_formula]
  simp_rw [hchar]
  unfold inducedClassFunction
  congr 1
  exact Fintype.sum_equiv (Equiv.inv G) _ _ (fun x => by simp)
end Representation

namespace Representation
variable {G : Type*} [Group G] [Finite G]

/-- Values of a subgroup linear character lie in the ambient cyclotomic order. -/
theorem linear_value_mem_cyclotomicOrder {η : ℂ}
    (hη : IsPrimitiveRoot η (Nat.card G)) (H : Subgroup G) (χ : H →* ℂ) (h : H) :
    χ h ∈ cyclotomicOrder η := by
  apply root_mem_cyclotomicOrder_of_pow_eq_one_of_dvd hη
    (Nat.card_pos (α := G)).ne' (n := orderOf h)
  · rw [← map_pow, pow_orderOf_eq_one, map_one]
  · exact (orderOf_dvd_natCard h).trans H.card_subgroup_dvd_card

/-- Induced linear characters have actual matrix models over the cyclotomic order. -/
theorem exists_induced_linear_cyclotomic_model {η : ℂ}
    (hη : IsPrimitiveRoot η (Nat.card G)) (H : Subgroup G) (χ : H →* ℂ) :
    ∃ (n : ℕ) (σ : Representation (cyclotomicOrder η) G (Fin n → cyclotomicOrder η)),
      ∀ g, (mapCoefficients (cyclotomicOrder η).subtype σ).character g =
        inducedClassFunction H χ g := by
  apply exists_induced_linear_model_of_range (cyclotomicOrder η).subtype Subtype.val_injective H χ
  intro h
  exact ⟨⟨χ h, linear_value_mem_cyclotomicOrder hη H χ h⟩, rfl⟩
end Representation
