module

public import Theory.SpecificGroups.UnitaryThree.HermitianMatrices

/-!
# The full special unitary matrix group in Hermitian coordinates

`matrixGroup` consists of all determinant-one matrices preserving the
anti-diagonal Gram matrix, not just the subgroup generated by the displayed
root and torus matrices. Conjugation by the explicit isotropic basis identifies
it with `identityMatrixGroup`, the special unitary group for the identity form.

Source: Suzuki, J. Algebra 2 (1965), Sections IV–VI; change of Gram matrix.
-/

public section

open FiniteField Matrix
namespace UnitaryThree

abbrev SL := SpecialLinearGroup (Fin 3) Nine

/-- The determinant-one isometries of a specified Gram matrix. -/
@[expose] def isometryGroup (J : Matrix (Fin 3) (Fin 3) Nine) : Subgroup SL where
  carrier := {A | A.valᴴ * J * A.val = J}
  one_mem' := by simp
  mul_mem' {A B} hA hB := by
    change (A.val * B.val)ᴴ * J * (A.val * B.val) = J
    calc
      _ = B.valᴴ * (A.valᴴ * J * A.val) * B.val := by
        simp only [Matrix.conjTranspose_mul, Matrix.mul_assoc]
      _ = J := by rw [hA, hB]
  inv_mem' {A} hA := by
    change (A⁻¹).valᴴ * J * (A⁻¹).val = J
    have hc : A.val * (A⁻¹).val = 1 := by
      have h := congrArg (fun B : SL => (B : Matrix (Fin 3) (Fin 3) Nine))
        (mul_inv_cancel A)
      simpa only [SpecialLinearGroup.coe_mul, SpecialLinearGroup.coe_one] using h
    calc
      _ = (A⁻¹).valᴴ * (A.valᴴ * J * A.val) * (A⁻¹).val := by rw [hA]
      _ = (A.val * (A⁻¹).val)ᴴ * J * (A.val * (A⁻¹).val) := by
        simp only [Matrix.conjTranspose_mul, Matrix.mul_assoc]
      _ = J := by rw [hc]; simp

@[expose] def matrixGroup : Subgroup SL := isometryGroup gram
@[expose] def identityMatrixGroup : Subgroup SL := isometryGroup 1

@[simp] theorem mem_matrixGroup (A : SL) :
    A ∈ matrixGroup ↔ A.valᴴ * gram * A.val = gram := Iff.rfl

@[simp] theorem mem_identityMatrixGroup (A : SL) :
    A ∈ identityMatrixGroup ↔ A.valᴴ * A.val = 1 := by
  change A.valᴴ * 1 * A.val = 1 ↔ _
  rw [mul_one]

@[expose] def matrixRoot (p : Root) : matrixGroup := ⟨rootMatrix p, rootMatrix_isometry p⟩
@[expose] def matrixTorus (r : Nineˣ) : matrixGroup := ⟨torusMatrix r, torusMatrix_isometry r⟩
@[expose] def matrixSwap : matrixGroup := ⟨swapMatrix, swapMatrix_isometry⟩

private def conjugate (S : GL (Fin 3) Nine) (A : SL) : SL :=
  ⟨(S : Matrix (Fin 3) (Fin 3) Nine) * A.val *
      ((S⁻¹ : GL (Fin 3) Nine) : Matrix (Fin 3) (Fin 3) Nine), by
    rw [Matrix.det_mul, Matrix.det_mul, A.property, mul_one,
      ← Matrix.det_mul, Units.mul_inv, Matrix.det_one]⟩

private theorem conjugate_toGL (S : GL (Fin 3) Nine) (A : SL) :
    SpecialLinearGroup.toGL (conjugate S A) =
      S * SpecialLinearGroup.toGL A * S⁻¹ := Units.ext rfl

/-- Conjugation on determinant-one matrices by the isotropic basis. -/
def basisConjugation : SL ≃* SL where
  toFun := conjugate basisGL
  invFun := conjugate basisGL⁻¹
  left_inv A := by
    apply SpecialLinearGroup.toGL_injective
    simp only [conjugate_toGL, inv_inv]
    group
  right_inv A := by
    apply SpecialLinearGroup.toGL_injective
    simp only [conjugate_toGL, inv_inv]
    group
  map_mul' A B := by
    apply SpecialLinearGroup.toGL_injective
    simp only [conjugate_toGL, map_mul]
    group

theorem basisConjugation_val (A : SL) :
    (basisConjugation A).val = basisMatrix * A.val *
      ((basisGL⁻¹ : GL (Fin 3) Nine) : Matrix (Fin 3) (Fin 3) Nine) := by
  change (basisGL : Matrix (Fin 3) (Fin 3) Nine) * A.val * _ = _
  rw [basisGL_coe]

theorem basisConjugation_mem (A : SL) :
    basisConjugation A ∈ identityMatrixGroup ↔ A ∈ matrixGroup := by
  rw [mem_identityMatrixGroup, mem_matrixGroup, basisConjugation_val]
  constructor
  · intro h
    have hc : ((basisGL⁻¹ : GL (Fin 3) Nine) : Matrix (Fin 3) (Fin 3) Nine) *
        basisMatrix = 1 := Units.inv_mul basisGL
    have he : (basisMatrix * A.val *
        ((basisGL⁻¹ : GL (Fin 3) Nine) : Matrix (Fin 3) (Fin 3) Nine)) * basisMatrix =
        basisMatrix * A.val := by rw [Matrix.mul_assoc, Matrix.mul_assoc, hc, mul_one]
    calc
      _ = (basisMatrix * A.val)ᴴ * (basisMatrix * A.val) := by
        rw [Matrix.conjTranspose_mul, ← basisMatrix_gram]
        simp only [Matrix.mul_assoc]
      _ = basisMatrixᴴ *
          ((basisMatrix * A.val *
            ((basisGL⁻¹ : GL (Fin 3) Nine) : Matrix (Fin 3) (Fin 3) Nine))ᴴ *
          (basisMatrix * A.val *
            ((basisGL⁻¹ : GL (Fin 3) Nine) : Matrix (Fin 3) (Fin 3) Nine))) *
          basisMatrix := by
        conv_lhs => rw [← he]
        simp only [Matrix.conjTranspose_mul, Matrix.mul_assoc]
      _ = gram := by rw [h, mul_one, basisMatrix_gram]
  · exact change_form_isometry A.val

/-- The full groups for the two Gram matrices are isomorphic. -/
def matrixEquivIdentity : matrixGroup ≃* identityMatrixGroup where
  toFun A := ⟨basisConjugation A.val, (basisConjugation_mem A.val).mpr A.property⟩
  invFun B := ⟨basisConjugation.symm B.val, (basisConjugation_mem _).mp (by
    simpa only [MulEquiv.apply_symm_apply] using B.property)⟩
  left_inv A := Subtype.ext (basisConjugation.symm_apply_apply A.val)
  right_inv B := Subtype.ext (basisConjugation.apply_symm_apply B.val)
  map_mul' A B := Subtype.ext (basisConjugation.map_mul A.val B.val)

end UnitaryThree
end
