module
public import Stellmacher.SectionTwo.GlobalOffenderActionFactors
public import Stellmacher.SectionOne.OneSevenProductSaturation
public import Stellmacher.SectionOne.OffenderSelectedProduct

/-!
# Baumann containment from a smaller Thompson action

Let T lie in the chosen Sylow subgroup and contain both the original
Section Two module V and the kernel of its faithful quotient action.
If the selected product generated by the image of J(T) contains the
quotient's three-core, then the ambient Baumann subgroup lies in T.

Maximal elementary abelian subgroups of T map to offenders on V because
V lies in T. Their selected product is global by factor saturation, so
the image of J(T) equals the global action-defined J. The Baumann
fixed-space theorem and (1.7) put the Baumann image in this J. Containment
of the quotient kernel in T then lifts the result.

This isolates the last comparison in Stellmacher (8.3), journal p38.
Its caller supplies the three-core containment using (3.4) and the full
odd residual. The action is exactly the caller's Section Two quotient
action, with no replacement of the original V.
Source: refs/latex/stellmacher-n-group.tex.
-/

namespace Stellmacher.SectionTwo
universe u

public theorem baumann_le_of_thompson_image_threeCore
    {G : Type u} [Group G] [Finite G] (h : Hypotheses G) (S : Sylow 2 G)
    {X : Type u} [Group X] [Finite X]
    (q : G →* X) (hq : Function.Surjective q) (hker : q.ker = cSubgroup S)
    (B T : Subgroup G)
    (hB : B = (S : Subgroup G) ⊓ Subgroup.centralizer
      (omegaOneCenterAmbient (elementaryAbelianMaxJ (S : Subgroup G)) : Set G))
    (hTS : T ≤ (S : Subgroup G)) (hVT : vSubgroup S ≤ T) (hCT : q.ker ≤ T)
    (hthree : pCore 3 X ≤ ⁅pPrimeCore 2 X, (elementaryAbelianMaxJ T).map q⁆ ⊔
      (elementaryAbelianMaxJ T).map q) :
    letI : IsElementaryAbelian 2 (vSubgroup S) :=
      (vSubgroup_le_twoCore_and_elementaryAbelian h S).2
    letI := quotientConjugationAction S q hq hker
    SectionOne.Hypotheses X (vSubgroup S) → B ≤ T := by
  classical
  let V := vSubgroup S
  let _ : V.Normal := Subgroup.normalClosure_normal
  let _ : IsElementaryAbelian 2 V := (vSubgroup_le_twoCore_and_elementaryAbelian h S).2
  let _ := quotientConjugationAction S q hq hker
  intro hOne
  let U := S.mapSurjective hq
  let J := (elementaryAbelianMaxJ T).map q
  let I := {A : Subgroup G // A ∈ elementaryAbelianMaxSubgroups T}
  let A : I → Subgroup X := fun a => a.val.map q
  have hA (a : I) : SectionOne.oneA (V := V) (U : Subgroup X) (A a) := by
    have hb := maxElementary_card_le_fixed_mul_image T V a.val hVT a.property q hker
    rw [← quotientConjugationAction_fixedPoints_card S q hq hker a.val] at hb
    refine ⟨Subgroup.map_mono (a.property.1.trans hTS), a.property.2.1.map q, ?_⟩
    unfold SectionOne.m
    have hpos : 0 < (Nat.card (FixedPoints.subgroup (A a) V) : ℚ) *
        (Nat.card (A a) : ℚ) := by
      exact_mod_cast Nat.mul_pos Nat.card_pos Nat.card_pos
    apply (div_le_one hpos).mpr
    exact_mod_cast hb
  have hJ : J = ⨆ a, A a := by
    apply le_antisymm
    · apply Subgroup.map_le_iff_le_comap.mpr
      apply sSup_le
      intro a ha
      exact Subgroup.map_le_iff_le_comap.mp (le_iSup A (⟨a, ha⟩ : I))
    · exact iSup_le fun a => Subgroup.map_mono (le_sSup a.property)
  obtain ⟨hJinf, _, _, n, D, hprod, _, hD, _, _⟩ :=
    SectionOne.offender_generated_selected_product hOne U A hA J hJ
  have hEsat := SectionOne.oneSevenGenerated_eq_of_threeCore_le hOne D hD
    (⁅pPrimeCore 2 X, J⁆ ⊔ J) hprod.1 hthree
  have hJglobal : J = SectionOne.oneJ (V := V) (U : Subgroup X) := by
    rw [hJinf]
    change (U : Subgroup X) ⊓ (⁅pPrimeCore 2 X, J⁆ ⊔ J) = _
    rw [hEsat]
    exact (SectionOne.oneSeven_global_identification hOne U).1.symm
  have hmaxJ := elementaryAbelianMaxJ_map_le_oneJ h S q hq hker
  have hBfix := baumann_image_fixes_thompson_fixedPoints h S q hq hker B
    (hB ▸ inf_le_right)
  have hBJ : B.map q ≤ J := by
    rw [hJglobal, ← SectionOne.oneSeven_baumann_eq_j hOne U]
    refine le_inf (Subgroup.map_mono (hB ▸ inf_le_left)) ?_
    intro b hb
    rw [mem_fixingSubgroup_iff]
    intro v hv
    apply ((mem_fixingSubgroup_iff (M := X)).mp (hBfix hb)) v
    intro a
    exact hv (⟨a, hmaxJ a.property⟩ : SectionOne.oneJ (V := V) (U : Subgroup X))
  have hBT : B.map q ≤ T.map q := hBJ.trans (Subgroup.map_mono (sSup_le fun a ha => ha.1))
  calc
    B ≤ (B.map q).comap q := Subgroup.le_comap_map q B
    _ ≤ (T.map q).comap q := Subgroup.comap_mono hBT
    _ = T := by rw [Subgroup.comap_map_eq, sup_eq_left.mpr hCT]

end Stellmacher.SectionTwo

