module

public import Stellmacher.Recognition.Parrott.DerivedVHyperplane
public import Theory.GroupTheory.C5C4SquareRoot
public import Theory.GroupTheory.CyclicExtensionDerivedImage

/-!
# The square acting on the derived-core centralizer hyperplane

The image of V=C_H(v) in H/J has order two. In the C₅ ⋊ C₄ model it
is generated by g² for an element g of order four. Choosing a representative
of g² in V shows that its conjugation preserves C_J(v), and hence its image
U in J/J′. This supplies the square invariance for the derived displacement
calculation without assuming any noninvariance or line cardinality.
The cyclic-extension commutator calculation then identifies the actual image
of V′ with the displacement of U under this square.

Source: D. Parrott, *A characterization of the Tits' simple group* (1972),
pp.673–674 and the first paragraph of p.677.
-/

open Subgroup

namespace Stellmacher.Recognition

/-- The order-two image of the local centralizer is generated by a square
of an order-four element, with a representative in the local centralizer. -/
public theorem parrott_derived_local_square_generator
    {G : Type*} [Group G] [Finite G]
    (z : G) (h : ParrottCentralizerHypotheses z) :
    let H := centralizer ({z} : Set G)
    let J := pCore 2 H
    let i := H.subtype.comp J.subtype
    let E := (commutator J).map i
    ∀ v : G, v ∈ E → v ∉ zpowers z →
      ∀ V : Subgroup G, H ⊓ centralizer ({v} : Set G) = V →
        Nat.card V = 512 →
        ∃ g : H ⧸ J, orderOf g = 4 ∧
          (V.subgroupOf H).map (QuotientGroup.mk' J) = zpowers (g ^ 2) ∧
          ∃ t : H, (t : G) ∈ V ∧ QuotientGroup.mk' J t = g ^ 2 := by
  intro H J i E v hv hvz V hV hcard
  let A := (V.subgroupOf H).map (QuotientGroup.mk' J)
  have hA : Nat.card A = 2 :=
    parrott_derived_local_centralizer_quotient_card z h v hv hvz V hV hcard
  obtain ⟨φ, _, ⟨e⟩⟩ := h.quotient_model
  have hAe : Nat.card (A.map e.toMonoidHom) = 2 := by
    rw [card_map_of_injective e.injective, hA]
  obtain ⟨g, hg, hgen⟩ := SemidirectProduct.two_subgroup_eq_zpowers_square φ
    (A.map e.toMonoidHom) hAe
  have hgen' : A = zpowers ((e.symm g) ^ 2) := by
    apply (map_injective (f := e.toMonoidHom) e.injective)
    rw [hgen, MonoidHom.map_zpowers, map_pow, MulEquiv.coe_toMonoidHom, MulEquiv.apply_symm_apply]
  refine ⟨e.symm g, (orderOf_injective e.symm.toMonoidHom e.symm.injective g).trans hg,
    hgen', ?_⟩
  have hm : (e.symm g) ^ 2 ∈ A := hgen' ▸ mem_zpowers _
  obtain ⟨t, ht, heq⟩ := hm
  exact ⟨t, ht, heq⟩

/-- A representative of g² in the local centralizer preserves its actual
core-centralizer image in J/J′. -/
public theorem parrott_derived_local_square_stable
    {G : Type*} [Group G] [Finite G]
    (z : G) (h : ParrottCentralizerHypotheses z) :
    let H := centralizer ({z} : Set G)
    let J := pCore 2 H
    let i := H.subtype.comp J.subtype
    let E := (commutator J).map i
    let q := QuotientGroup.mk' (commutator J)
    ∀ v : G, v ∈ E → v ∉ zpowers z →
      ∀ V : Subgroup G, H ⊓ centralizer ({v} : Set G) = V →
        Nat.card V = 512 →
        let U := ((centralizer ({v} : Set G)).comap i).map q
        ∀ f : (H ⧸ J) →* MulAut (J ⧸ commutator J),
          (∀ (a : H) (b b' : J), (b' : H) = a * (b : H) * a⁻¹ →
            f (QuotientGroup.mk' J a) (q b) = q b') →
          ∃ g : H ⧸ J, orderOf g = 4 ∧
            (V.subgroupOf H).map (QuotientGroup.mk' J) = zpowers (g ^ 2) ∧
            (∀ u ∈ U, f g (f g u) ∈ U) ∧
            ∃ t : H, (t : G) ∈ V ∧ QuotientGroup.mk' J t = g ^ 2 := by
  intro H J i E q v hv hvz V hV hcard U f heval
  obtain ⟨g, hg, hgen, t, ht, htq⟩ :=
    parrott_derived_local_square_generator z h v hv hvz V hV hcard
  refine ⟨g, hg, hgen, ?_, t, ht, htq⟩
  rintro u ⟨b, hb, rfl⟩
  have hbJ : t * (b : H) * t⁻¹ ∈ J := Subgroup.Normal.conj_mem (inferInstance : J.Normal) b b.property t
  let b' : J := ⟨t * (b : H) * t⁻¹, hbJ⟩
  have hb' : b' ∈ (centralizer ({v} : Set G)).comap i := by
    have ht' : (t : G) ∈ centralizer ({v} : Set G) := (hV ▸ ht).2
    exact (centralizer ({v} : Set G)).mul_mem
      ((centralizer ({v} : Set G)).mul_mem ht' hb)
      ((centralizer ({v} : Set G)).inv_mem ht')
  have heq : f g (f g (q b)) = q b' := by
    have hh := heval t b b' rfl
    rw [htq, map_pow] at hh
    exact hh
  rw [heq]
  exact mem_map_of_mem q hb'

/-- The actual derived image of the local centralizer is the square displacement
of its core-centralizer image. No noninvariance or line size is assumed. -/
public theorem parrott_derived_image_eq_square_displacement
    {G : Type*} [Group G] [Finite G]
    (z : G) (h : ParrottCentralizerHypotheses z) :
    let H := centralizer ({z} : Set G)
    let J := pCore 2 H
    let i := H.subtype.comp J.subtype
    let E := (commutator J).map i
    let q := QuotientGroup.mk' (commutator J)
    ∀ v : G, v ∈ E → v ∉ zpowers z →
      ∀ V : Subgroup G, H ⊓ centralizer ({v} : Set G) = V →
        Nat.card V = 512 →
        let U := ((centralizer ({v} : Set G)).comap i).map q
        let D := (commutator V).map V.subtype
        let K := D.comap i
        ∀ f : (H ⧸ J) →* MulAut (J ⧸ commutator J), Function.Injective f →
          (∀ (a : H) (b b' : J), (b' : H) = a * (b : H) * a⁻¹ →
            f (QuotientGroup.mk' J a) (q b) = q b') →
          ∃ g : H ⧸ J, orderOf g = 4 ∧
            (∀ u ∈ U, f g (f g u) ∈ U) ∧
            (∀ s : (J ⧸ commutator J) →* (J ⧸ commutator J),
              (∀ w, s w = f g (f g w) * w) → K.map q = U.map s) := by
  intro H J i E q v hv hvz V hV hcard U D K f _hf heval
  obtain ⟨g, hg, hgen, hstable, t, ht, htq⟩ :=
    parrott_derived_local_square_stable z h v hv hvz V hV hcard f heval
  refine ⟨g, hg, hstable, ?_⟩
  let VH := V.subgroupOf H
  have hVH : V ≤ H := hV ▸ inf_le_left
  have hC : VH.comap J.subtype = (centralizer ({v} : Set G)).comap i := by
    ext b
    change (b : H).val ∈ V ↔ i b ∈ centralizer ({v} : Set G)
    rw [← hV]
    exact and_iff_right (b : H).property
  have hD : ((commutator VH).map VH.subtype).map H.subtype = D := by
    rw [map_subtype_commutator, map_commutator]
    change ⁅(V.subgroupOf H).map H.subtype, (V.subgroupOf H).map H.subtype⁆ = D
    rw [map_subgroupOf_eq_of_le hVH]
    exact V.map_subtype_commutator.symm
  have hK : ((commutator VH).map VH.subtype).comap J.subtype = K := by
    change _ = D.comap (H.subtype.comp J.subtype)
    rw [← hD, ← comap_comap, comap_map_eq_self_of_injective H.subtype_injective]
  let : IsElementaryAbelian 2 (J ⧸ commutator J) :=
    (parrott_core_abelianization_structure z h).1
  change QuotientGroup.mk' J t = g ^ 2 at htq
  have htorder : orderOf (QuotientGroup.mk' J t) = 2 := by
    rw [htq, orderOf_pow, hg]
    norm_num
  intro s hs
  have himage := Theory.GroupTheory.cyclic_extension_derived_image J VH f heval t ht
    htorder (by simpa only [htq] using hgen) s (by
      intro w
      rw [htq, map_pow]
      exact hs w)
  simpa only [hC, hK] using himage

end Stellmacher.Recognition
