module

public import Stellmacher.Recognition.Parrott.TwoSubgroupDerived
public import Stellmacher.Recognition.Parrott.CosetSelection
public import Stellmacher.Recognition.Parrott.DerivedVQuotientLine
public import Theory.GroupTheory.CyclicLiftElementaryKernel

/-!
# Lifting the derived quotient line in Parrott's local centralizer

Write H=C_G(z), J=O₂(H), and E=J′. The derived subgroup of a
two-subgroup V of H lies in J. If its image in J/E is a line whose
nonidentity coset has centralizer index different from five, Lemma 4
excludes involutory lifts. Since E and J/E are elementary abelian,
the resulting cyclic lift has order four.

The first theorem separates this lifting step from the quotient-line
calculation. The final theorem applies that calculation to the actual
order-512 centralizer and obtains the lift without a fusion assumption.

Source: D. Parrott, *A characterization of the Tits' simple group* (1972),
pp.673–675 and the first paragraph of p.677.
-/

open Subgroup

namespace Stellmacher.Recognition

/-- The two quotient facts needed to lift V′: its image is a line, and
nonidentity elements of that line do not have the involution coset index. -/
public theorem parrott_derived_cyclic_lift_of_quotient_line
    {G : Type*} [Group G] [Finite G] {z : G}
    (h : ParrottCentralizerHypotheses z) (V : Subgroup G)
    (hVH : V ≤ centralizer ({z} : Set G)) (hp : IsPGroup 2 V) :
    let H := centralizer ({z} : Set G)
    let J := pCore 2 H
    let i := H.subtype.comp J.subtype
    let D := (commutator V).map V.subtype
    let K := D.comap i
    let DH := (commutator J).map J.subtype
    Nat.card (K.map (QuotientGroup.mk' (commutator J))) = 2 →
    (∀ b : J, i b ∈ D → b ∉ commutator J →
      (centralizer ({QuotientGroup.mk' DH (b : H)} : Set (H ⧸ DH))).index ≠ 5) →
    ∃ b : J, i b ∈ D ∧ orderOf b = 4 ∧
      D ≤ (zpowers b ⊔ commutator J).map i := by
  intro H J i D K DH hcard hindex
  have hDcore := parrott_two_subgroup_derived_le_core h V hVH hp
  have hDrange : D ≤ i.range := by
    intro x hx
    obtain ⟨a, ha, rfl⟩ := hDcore hx
    exact ⟨⟨a, ha⟩, rfl⟩
  have hKmap : K.map i = D := map_comap_eq_self hDrange
  obtain ⟨_, _, _, _, _, hElem, _, _⟩ := parrott_centralizer_structure z h
  let : IsElementaryAbelian 2 (commutator J) := hElem
  let : IsElementaryAbelian 2 (J ⧸ commutator J) :=
    (parrott_core_abelianization_structure z h).1
  have hno : ∀ b ∈ K, b ∉ commutator J → orderOf b ≠ 2 := by
    intro b hb hbE hb2
    have hbDH : (b : H) ∉ DH := by
      rintro ⟨a, ha, heq⟩
      exact hbE (J.subtype_injective heq ▸ ha)
    have hbH2 : orderOf (b : H) = 2 := (Subgroup.orderOf_coe b).trans hb2
    exact hindex b hb hbE
      (parrott_core_involution_coset_centralizer_index z h (b : H) b.property hbH2 hbDH)
  obtain ⟨b, hb, hb4, hgen⟩ :=
    exists_order_four_lift_of_quotient_card_two (commutator J) K hcard hno
  refine ⟨b, hb, hb4, ?_⟩
  rw [← hKmap]
  exact map_mono hgen

/-- The derived subgroup of the order-512 local centralizer has a cyclic
supplement modulo the derived core generated by an element of order four.
The lift is unconditional: no fusion or additional center geometry is needed. -/
public theorem parrott_derived_cyclic_lift
    {G : Type*} [Group G] [Finite G]
    (z : G) (h : ParrottCentralizerHypotheses z) :
    let H := centralizer ({z} : Set G)
    let J := pCore 2 H
    let i := H.subtype.comp J.subtype
    let E := (commutator J).map i
    ∀ v : G, v ∈ E → v ∉ zpowers z →
      ∀ V : Subgroup G, H ⊓ centralizer ({v} : Set G) = V →
        Nat.card V = 512 →
        ∃ b : J, i b ∈ (commutator V).map V.subtype ∧ orderOf b = 4 ∧
          (commutator V).map V.subtype ≤ (zpowers b ⊔ commutator J).map i := by
  intro H J i E v hv hvz V hV hcard
  have hVH : V ≤ H := hV ▸ inf_le_left
  have hp : IsPGroup 2 V := isPGroup_iff_card_dvd_pow.mpr ⟨9, by rw [hcard]; decide⟩
  obtain ⟨hline, hindex⟩ := parrott_derived_quotient_line z h v hv hvz V hV hcard
  exact parrott_derived_cyclic_lift_of_quotient_line h V hVH hp hline hindex

end Stellmacher.Recognition
