module
public import Stellmacher.Recognition.Parrott.NormalizerElementaryFusion
public import Stellmacher.Recognition.Parrott.NormalizerInvolutionCosets

/-!
# Derived lines of omega involution centralizers

Put N=N_G(F), K=O₂(N), and W=Ω₁(K), viewed in G. For every involution
l in W outside Z(W), the derived subgroup of C_W(l) is an involution
line in Z(K). This is the local calculation used in the second
centralizer's weak-closure argument.

For l in the original derived core E outside Z(W), the subgroup
Z(W)⟨l⟩ is a hyperplane of E. Its centralizer in the original core J
is C_W(l), of order 64. Every such overgroup of E has derived subgroup
⟨z⟩: modulo Z(J), E is central and the overgroup is generated by E
and one element; self-centralization of E excludes an abelian overgroup.
The known normalizer orbit on F−Z(W) handles the remaining points of F.
Finally, the supplied Sylow-three subgroup transports every involution
of K into E∨F, whose involutions lie in E or F. Conjugation by N
preserves W and Z(K), hence preserves the asserted form of the derived line.

Source: D. Parrott, *A characterization of the Tits' simple group* (1972),
§4, Lemma 8, printed p.682; the local structure used here is established
on pp.673–678. The overgroup calculation extends `ElementaryJoin`'s
proof for E∨F to arbitrary order-64 overgroups of E in J.
-/

open Subgroup
open scoped commutatorElement IsMulCommutative
namespace Stellmacher.Recognition.ParrottSecondElementaryData
variable {G : Type*} [Group G] [Finite G] {z : G}

private theorem core_overgroup_derived
    (h : ParrottCentralizerHypotheses z) :
    let H := centralizer ({z} : Set G)
    let J := pCore 2 H
    let E := (commutator J).map (H.subtype.comp J.subtype)
    ∀ B : Subgroup G, E ≤ B → B ≤ J.map H.subtype → Nat.card B = 64 →
      (commutator B).map B.subtype = zpowers z := by
  intro H J E B hEB hBJ hBcard
  let embed := H.subtype.comp J.subtype
  let D := commutator J
  have hEcard : Nat.card E = 32 :=
    (card_map_of_injective (K := D) (H.subtype_injective.comp J.subtype_injective)).trans
      (parrott_centralizer_structure z h).2.2.2.2.2.2.1
  have hi : E.relIndex B = 2 := by
    have hh := relIndex_mul_relIndex (⊥ : Subgroup G) E B bot_le hEB
    rw [relIndex_bot_left, relIndex_bot_left, hEcard, hBcard] at hh
    omega
  obtain ⟨b, hb, hbE, hcases⟩ := relIndex_eq_two_iff_exists_notMem_and.mp hi
  have hgen : E ⊔ zpowers b = B := by
    refine le_antisymm (sup_le hEB (zpowers_le.mpr hb)) ?_
    intro x hx
    rcases hcases x hx with hxb | hxE
    · simpa using (E ⊔ zpowers b).mul_mem (mem_sup_left hxb)
        ((E ⊔ zpowers b).inv_mem (mem_sup_right (mem_zpowers b)))
    · exact mem_sup_left hxE
  obtain ⟨bH, hbJ, heq⟩ := hBJ hb
  let a : J := ⟨bH, hbJ⟩
  let B₀ := D ⊔ zpowers a
  have hmap : B₀.map embed = B := by
    rw [Subgroup.map_sup, MonoidHom.map_zpowers]
    change E ⊔ zpowers (embed a) = B
    rw [show embed a = b from heq, hgen]
  obtain ⟨hcenter, _, _, _, hUpper, _, _, _⟩ := parrott_centralizer_structure z h
  let q := QuotientGroup.mk' (center J)
  have hDcentral : D.map q ≤ center (J ⧸ center J) := by
    rintro x ⟨b, hb, rfl⟩
    rw [Subgroup.mem_center_iff]
    intro y
    obtain ⟨c, rfl⟩ := QuotientGroup.mk'_surjective (center J) y
    apply Eq.symm
    apply commutatorElement_eq_one_iff_mul_comm.mp
    rw [← map_commutatorElement]
    apply (QuotientGroup.eq_one_iff _).mpr
    have hcomm : ⁅D, ⊤⁆ ≤ center J := by
      rw [show D = Subgroup.upperCentralSeries J 2 from hUpper]
      simpa only [Subgroup.upperCentralSeries_one] using
        commutator_upperCentralSeries_top_le J 1
    exact hcomm (commutator_mem_commutator hb (mem_top c))
  have hqcomm : ⁅B₀.map q, B₀.map q⁆ = ⊥ := by
    apply commutator_eq_bot_iff_le_centralizer.mpr
    rw [show B₀.map q = D.map q ⊔ zpowers (q a) by
      rw [show B₀ = D ⊔ zpowers a from rfl, Subgroup.map_sup, MonoidHom.map_zpowers]]
    apply sup_le
    · exact hDcentral.trans (center_le_centralizer _)
    · apply le_centralizer_iff.mpr
      exact sup_le (hDcentral.trans (center_le_centralizer _)) (le_centralizer _)
  have hbound₀ : ⁅B₀, B₀⁆ ≤ center J := by
    have hh : (⁅B₀, B₀⁆).map q = ⊥ := (map_commutator _ _ _).trans hqcomm
    simpa only [q, QuotientGroup.ker_mk'] using (Subgroup.map_eq_bot_iff _).mp hh
  have hbound : ⁅B, B⁆ ≤ zpowers z := by
    have hm := map_mono (f := embed) hbound₀
    rwa [map_commutator, hmap, hcenter] at hm
  have hne : ⁅B, B⁆ ≠ ⊥ := by
    intro he
    have hc := commutator_eq_bot_iff_le_centralizer.mp he
    have hbC := centralizer_le hEB (hc hb)
    rw [parrott_derived_centralizer z h] at hbC
    exact hbE hbC
  rw [map_subtype_commutator]
  apply eq_of_le_of_card_ge hbound
  rw [Nat.card_zpowers, h.involution]
  exact Nat.succ_le_of_lt ((one_lt_card_iff_ne_bot _).mpr hne)


/-- The omega centralizer of a point of E outside its center has derived line z. -/
public theorem omega_derived_point_centralizer_commutator
    (d : ParrottSecondElementaryData z)
    (h : ParrottCentralizerHypotheses z) (hN : IsNTwoGroup G)
    (hproper : (d.sylow : Subgroup G) < normalizer (d.F : Set G)) :
    let H := centralizer ({z} : Set G)
    let J := pCore 2 H
    let E := (commutator J).map (H.subtype.comp J.subtype)
    let N := normalizer (d.F : Set G)
    let K := pCore 2 N
    let U := omega₁ K (p := 2)
    let i := N.subtype.comp K.subtype
    let W := U.map i
    let ZW := (center U).map (i.comp U.subtype)
    ∀ l ∈ E, l ∉ ZW →
      let B := W ⊓ centralizer ({l} : Set G)
      (commutator B).map B.subtype = zpowers z := by
  intro H J E N K U i W ZW l hl hlZ B
  let L := J.map H.subtype
  let X := K.map N.subtype
  let S := ZW ⊔ zpowers l
  have hWX : W ≤ X := by
    rintro x ⟨k, _, rfl⟩
    exact mem_map_of_mem N.subtype k.property
  have hWN : W ≤ N := hWX.trans (map_subtype_le K)
  have hWT : W ≤ (d.sylow : Subgroup G) := hWX.trans d.normalizer_core_le_sylow
  have hEW : E ≤ W := le_sup_left.trans (d.elementary_join_le_normalizer_core_omega h hN hproper)
  have hZE : ZW ≤ E := (d.normalizer_core_omega_structure h hN hproper).2.2.1.trans inf_le_left
  have hSE : S ≤ E := sup_le hZE (zpowers_le.mpr hl)
  have hWdef : W = X ⊓ centralizer (ZW : Set G) :=
    (d.normalizer_core_omega_structure h hN hproper).2.2.2
  have hWC : W ≤ centralizer (ZW : Set G) := by
    rw [hWdef]
    exact inf_le_right
  have hzS : zpowers z ≤ S := (zpowers_le.mpr
    (d.normalizer_core_omega_inclusions.2.1 d.z_mem_normalizer_core_center)).trans le_sup_left
  let : IsElementaryAbelian 2 (commutator J) :=
    (parrott_centralizer_structure z h).2.2.2.2.2.1
  let : IsElementaryAbelian 2 E := IsElementaryAbelian.map (H.subtype.comp J.subtype)
  have hScard : Nat.card S = 16 := by
    have hZcard : Nat.card ZW = 8 :=
      (card_map_of_injective ((N.subtype_injective.comp K.subtype_injective).comp
        U.subtype_injective)).trans (d.normalizer_core_omega_structure h hN hproper).2.1
    rw [show S = ZW ⊔ zpowers l from rfl,
      card_sup_zpowers_of_normalizing_involution ZW l
        (elemPow_eq_one_of_isElementaryAbelian l hl) hlZ
        (d.normalizer_core_centers_normalized.2 (hWN (hEW hl))), hZcard]
  have hBL : B ≤ L := by
    intro x hx
    by_contra hxL
    exact hlZ (d.sylow_outer_derived_fixed_le_omega_center h hN hproper x
      (hWT hx.1) hxL ⟨hl, mem_centralizer_singleton_iff.mpr
        (mem_centralizer_singleton_iff.mp hx.2).symm⟩)
  have hB : B = L ⊓ centralizer (S : Set G) := by
    apply le_antisymm
    · intro x hx
      refine ⟨hBL hx, ?_⟩
      have hh : S ≤ centralizer ({x} : Set G) := sup_le
        (fun a ha => mem_centralizer_singleton_iff.mpr (hWC hx.1 a ha))
        (zpowers_le.mpr (mem_centralizer_singleton_iff.mpr
          (mem_centralizer_singleton_iff.mp hx.2).symm))
      intro a ha
      exact mem_centralizer_singleton_iff.mp (hh ha)
    · intro x hx
      have hxZ : x ∈ centralizer (ZW : Set G) := centralizer_le (fun a ha => (le_sup_left : ZW ≤ S) ha) hx.2
      obtain ⟨t, _, htz, _, _, _, hcenter⟩ :=
        d.exists_normalizer_core_center_generator h hN hproper
      have htK : t ∈ (center K).map i := by
        rw [hcenter]
        exact mem_sup_right (mem_zpowers t)
      have hxX : x ∈ X := by
        have hXdef : X = (d.sylow : Subgroup G) ⊓ centralizer ({t} : Set G) :=
          d.normalizer_core_eq_sylow_centralizer h hN hproper t htK htz
        rw [hXdef]
        exact ⟨d.core_le_sylow hx.1, mem_centralizer_singleton_iff.mpr
          (hxZ t (d.normalizer_core_omega_inclusions.2.1 htK)).symm⟩
      refine ⟨?_, mem_centralizer_singleton_iff.mpr
        (hx.2 l (mem_sup_right (mem_zpowers l))).symm⟩
      rw [hWdef]
      exact ⟨hxX, hxZ⟩
  have hBcard : Nat.card B = 64 := by
    have hh := parrott_core_subgroup_centralizer_card z h S hzS hSE
    have heq : (centralizer (S : Set G)).subgroupOf L = B.subgroupOf L := by
      rw [hB]
      ext x
      simp only [mem_subgroupOf, mem_inf, x.property, true_and]
    rw [heq, Nat.card_congr (subgroupOfEquivOfLe hBL).toEquiv, hScard] at hh
    omega
  apply core_overgroup_derived h B ?_ hBL hBcard
  exact le_inf hEW (fun e he => mem_centralizer_singleton_iff.mpr (setLike_mul_comm he hl))


omit [Finite G] in
private theorem derived_line_of_conjugate (W Z : Subgroup G) (g : G)
    (hgW : g ∈ normalizer (W : Set G)) (hgZ : g ∈ normalizer (Z : Set G))
    (l : G)
    (hline : let B := W ⊓ centralizer ({g * l * g⁻¹} : Set G)
      ∃ u ∈ Z, orderOf u = 2 ∧ (commutator B).map B.subtype = zpowers u) :
    let B := W ⊓ centralizer ({l} : Set G)
    ∃ u ∈ Z, orderOf u = 2 ∧ (commutator B).map B.subtype = zpowers u := by
  let e := MulAut.conj g
  let B := W ⊓ centralizer ({l} : Set G)
  let C := W ⊓ centralizer ({e l} : Set G)
  obtain ⟨u, hu, hu2, hCu⟩ := hline
  change (commutator C).map C.subtype = zpowers u at hCu
  have hCmap : B.map e.toMonoidHom = C := by
    have hWe : W.map e.toMonoidHom = W := mem_normalizer_iff_map_conj_eq.mp hgW
    rw [map_inf _ _ _ e.injective, hWe]
    congr 1
    apply le_antisymm
    · simpa only [Set.image_singleton, MulEquiv.coe_toMonoidHom] using
        map_centralizer_le_centralizer_image ({l} : Set G) e.toMonoidHom
    · intro x hx
      refine ⟨e.symm x, mem_centralizer_singleton_iff.mpr ?_, e.apply_symm_apply x⟩
      apply e.injective
      simpa only [map_mul, e.apply_symm_apply] using mem_centralizer_singleton_iff.mp hx
  refine ⟨e.symm u, ?_, (e.symm.orderOf_eq u).trans hu2, ?_⟩
  · apply (mem_normalizer_iff.mp hgZ (e.symm u)).mpr
    change e (e.symm u) ∈ Z
    simpa only [e.apply_symm_apply] using hu
  · rw [map_subtype_commutator]
    apply map_injective (f := e.toMonoidHom) e.injective
    rw [map_commutator, hCmap, MonoidHom.map_zpowers,
      MulEquiv.coe_toMonoidHom, e.apply_symm_apply]
    exact (map_subtype_commutator C).symm.trans hCu

/-- Every noncentral omega involution has a centralizer whose derived subgroup
is an involution line in the center of the normalizer core. -/
public theorem omega_involution_centralizer_derived_line
    (d : ParrottSecondElementaryData z)
    (h : ParrottCentralizerHypotheses z) (hN : IsNTwoGroup G)
    (hproper : (d.sylow : Subgroup G) < normalizer (d.F : Set G))
    (Q : Sylow 3 (normalizer (d.F : Set G)))
    (hCD : let N := normalizer (d.F : Set G)
      let X := (pCore 2 N).map N.subtype
      let D := (commutator X).map X.subtype
      let A := (Q : Subgroup N).map N.subtype
      X ⊓ centralizer (A : Set G) ≤ D) :
    let N := normalizer (d.F : Set G)
    let K := pCore 2 N
    let U := omega₁ K (p := 2)
    let i := N.subtype.comp K.subtype
    let W := U.map i
    let ZK := (center K).map i
    let ZW := (center U).map (i.comp U.subtype)
    ∀ l ∈ W, orderOf l = 2 → l ∉ ZW →
      let B := W ⊓ centralizer ({l} : Set G)
      ∃ u ∈ ZK, orderOf u = 2 ∧ (commutator B).map B.subtype = zpowers u := by
  intro N K U i W ZK ZW
  let H := centralizer ({z} : Set G)
  let J := pCore 2 H
  let E := (commutator J).map (H.subtype.comp J.subtype)
  let P := fun l : G => let B := W ⊓ centralizer ({l} : Set G)
    ∃ u ∈ ZK, orderOf u = 2 ∧ (commutator B).map B.subtype = zpowers u
  have hNW : N ≤ normalizer (W : Set G) := by
    let V := U.map K.subtype
    let : U.Characteristic := omega₁_characteristic K
    let : V.Normal := ConjAct.normal_of_characteristic_of_normal
    have hh := le_normalizer_map (H := V) N.subtype
    rw [normalizer_eq_top] at hh
    simpa only [← MonoidHom.range_eq_map, range_subtype, V, W, i, map_map] using hh
  have hNZK : N ≤ normalizer (ZK : Set G) := d.normalizer_core_centers_normalized.1
  have hNZW : N ≤ normalizer (ZW : Set G) := d.normalizer_core_centers_normalized.2
  have htransport (n : N) (l : G) : P ((n : G) * l * (n : G)⁻¹) → P l :=
    derived_line_of_conjugate W ZK n (hNW n.property) (hNZK n.property) l
  have hE (l : G) (hl : l ∈ E) (hlZ : l ∉ ZW) : P l :=
    ⟨z, d.z_mem_normalizer_core_center, h.involution,
      d.omega_derived_point_centralizer_commutator h hN hproper l hl hlZ⟩
  have hF (l : G) (hl : l ∈ d.F) (hlZ : l ∉ ZW) : P l := by
    have hZcard : Nat.card ZW = 8 :=
      (card_map_of_injective ((N.subtype_injective.comp K.subtype_injective).comp
        U.subtype_injective)).trans (d.normalizer_core_omega_structure h hN hproper).2.1
    have hnot : ¬ E ⊓ d.F ≤ ZW := by
      intro hh
      have hc := card_le_of_le hh
      rw [show Nat.card (E ⊓ d.F : Subgroup G) = 16 from d.inf_card, hZcard] at hc
      omega
    obtain ⟨w, hw, hwZ⟩ := SetLike.not_le_iff_exists.mp hnot
    obtain ⟨n, hn⟩ := d.normalizer_elementary_outside_omega_center_fusion_of_centralizer_card
      h hN hproper w hw.2 hwZ
      (d.normalizer_elementary_outside_omega_center_centralizer_card h hN hproper w hw hwZ)
      l hl hlZ
    apply htransport n⁻¹ l
    have heq : ((n⁻¹ : N) : G) * l * ((n⁻¹ : N) : G)⁻¹ = w := by
      rw [← hn]
      change (n : G)⁻¹ * ((n : G) * w * (n : G)⁻¹) * ((n : G)⁻¹)⁻¹ = w
      group
    rw [heq]
    exact hE w hw.1 hwZ
  intro l hl hl2 hlZ
  have hlX : l ∈ K.map N.subtype := by
    obtain ⟨k, _, rfl⟩ := hl
    exact mem_map_of_mem N.subtype k.property
  obtain ⟨q, hq⟩ := d.normalizer_core_involution_transport h hN hproper Q hCD l hlX
    (hl2 ▸ pow_orderOf_eq_one l)
  let n : N := q
  let m := (n : G) * l * (n : G)⁻¹
  have hmZ : m ∉ ZW := fun hm => hlZ ((mem_normalizer_iff.mp (hNZW n.property) l).mpr hm)
  have hm2 : m ^ 2 = 1 := by
    change (MulAut.conj (n : G) l) ^ 2 = 1
    rw [← map_pow, show l ^ 2 = 1 from hl2 ▸ pow_orderOf_eq_one l, map_one]
  apply htransport n l
  rcases d.elementary_join_involution h m hq hm2 with hm | hm
  · exact hE m hm hmZ
  · exact hF m hm hmZ

end Stellmacher.Recognition.ParrottSecondElementaryData
