module

public import Stellmacher.Recognition.Parrott.NormalizerFusion
public import Stellmacher.Recognition.Parrott.OuterFourFixedSpace
public import Theory.GroupTheory.CharacteristicCentralizerFusion
public import Theory.GroupAction.MarkedInvariantFlag

/-!
# The marked action on the literal derived central quotient

For H = C_G(z), J = O₂(H), D = J′ and Z = Z(J) ∩ D, the quotient
W = D/Z is elementary abelian of order sixteen. The literal ambient image
E of D maps onto W with kernel the subgroup generated by z. Evaluating
the faithful H/J action at x⁻¹ gives right conjugation by x on this map.

The normalizer of the supplied F preserves the characteristic centers of
K = O₂(N_G(F)) and Ω₁(K). Their ambient images are the supplied subgroups
⟨z,t⟩ and ⟨z,t,v⟩, so their quotient images give an invariant line and
plane. The existing bound of two fixed points forces the marked identities
b(tZ) = tZ and b(vZ)vZ = tZ, and makes the fixed-point count exact.
All choices of F, its Sylow subgroup, t and v are retained. Neither an
ambient N₂ hypothesis nor x⁴ = 1 is needed for this quotient calculation.

Source: D. Parrott, *A characterization of the Tits' simple group* (1972),
printed pp.674 and 677–678, the quotient action and equation (1).
-/

open Subgroup
open scoped IsMulCommutative
namespace Stellmacher.Recognition

/-- The literal derived quotient supplies the marked action inputs for
lifting the prescribed t,v coordinates in the supplied Sylow subgroup. -/
public theorem ParrottNormalizerFusionData.marked_quotient_action
    {G : Type*} [Group G] [Finite G] {z : G} {e : ParrottSecondElementaryData z}
    (n : ParrottNormalizerFusionData e) (h : ParrottCentralizerHypotheses z) :
    let H := centralizer ({z} : Set G)
    let J := pCore 2 H
    let D := commutator J
    let Z := (center J).subgroupOf D
    let W := D ⧸ Z
    let E := D.map (H.subtype.comp J.subtype)
    ∀ x : H, (x : G) ∈ (e.sylow : Subgroup G) →
      orderOf (QuotientGroup.mk' J x) = 4 →
      IsElementaryAbelian 2 W ∧ Nat.card W = 16 ∧
      ∃ (q : E →* W) (b : MulAut W),
        Function.Surjective q ∧ q.ker = (zpowers z).subgroupOf E ∧
        (∀ g g' : E, (g' : G) = (x : G)⁻¹ * (g : G) * (x : G) →
          b (q g) = q g') ∧
        Nat.card (FixedPoints.subgroup (zpowers b) W) = 2 ∧
        b (q ⟨n.t, n.t_mem_inf.1⟩) = q ⟨n.t, n.t_mem_inf.1⟩ ∧
        b (q ⟨n.v, n.v_mem_inf.1⟩) * q ⟨n.v, n.v_mem_inf.1⟩ =
          q ⟨n.t, n.t_mem_inf.1⟩ := by
  classical
  intro H J D Z W E x hx hxorder
  obtain ⟨hZmap, _, _, _, hUpper, hElem, hDcard, _⟩ := parrott_centralizer_structure z h
  change IsElementaryAbelian 2 D at hElem
  let : IsElementaryAbelian 2 D := hElem
  change Nat.card D = 32 at hDcard
  change D = Subgroup.upperCentralSeries J 2 at hUpper
  have hZD : center J ≤ D := by
    rw [hUpper]
    simpa only [Subgroup.upperCentralSeries_one] using
      Subgroup.upperCentralSeries_mono J (show 1 ≤ 2 by decide)
  have hZJcard : Nat.card (center J) = 2 := by
    have hh := card_map_of_injective (K := center J)
      (f := H.subtype.comp J.subtype) (H.subtype_injective.comp J.subtype_injective)
    rw [hZmap, Nat.card_zpowers, h.involution] at hh
    exact hh.symm
  have hZcard : Nat.card Z = 2 :=
    (Nat.card_congr (subgroupOfEquivOfLe hZD).toEquiv).trans hZJcard
  have hWcard : Nat.card W = 16 := by
    have hh := Z.index_mul_card
    change Nat.card W * Nat.card Z = Nat.card D at hh
    rw [hZcard, hDcard] at hh
    omega
  let : IsElementaryAbelian 2 W := {
    toIsMulCommutative := inferInstance
    exponent_dvd_p := (Group.exponent_quotient_dvd Z).trans
      (IsElementaryAbelian.exponent_dvd_p 2 D) }
  let i := H.subtype.comp J.subtype
  have hi : Function.Injective i := H.subtype_injective.comp J.subtype_injective
  let dE : D ≃* E := D.equivMapOfInjective i hi
  have hval (g : E) : i (dE.symm g : J) = (g : G) := by
    change (dE (dE.symm g) : G) = (g : G)
    rw [dE.apply_symm_apply]
  let q : E →* W := (QuotientGroup.mk' Z).comp dE.symm.toMonoidHom
  have hq : Function.Surjective q := (QuotientGroup.mk'_surjective Z).comp dE.symm.surjective
  have hker : q.ker = (zpowers z).subgroupOf E := by
    ext g
    change QuotientGroup.mk' Z (dE.symm g) = 1 ↔ (g : G) ∈ zpowers z
    rw [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff, ← hZmap]
    change (dE.symm g : J) ∈ center J ↔ (g : G) ∈ (center J).map i
    constructor
    · intro hg
      exact ⟨_, hg, hval g⟩
    · rintro ⟨a, ha, heq⟩
      have he : a = (dE.symm g : J) := hi (heq.trans (hval g).symm)
      exact he ▸ ha
  obtain ⟨f, hf, hformula⟩ := parrott_derived_quotient_action z h
  let b : MulAut W := f (QuotientGroup.mk' J x⁻¹)
  have hcompat (g g' : E)
      (heq : (g' : G) = (x : G)⁻¹ * (g : G) * (x : G)) : b (q g) = q g' := by
    apply hformula x⁻¹ (dE.symm g) (dE.symm g')
    apply H.subtype_injective
    change i (dE.symm g' : J) = (x : G)⁻¹ * i (dE.symm g : J) * ((x : G)⁻¹)⁻¹
    rw [hval, hval, inv_inv]
    exact heq
  have hbound : Nat.card (FixedPoints.subgroup (zpowers b) W) ≤ 2 :=
    parrott_derived_quotient_four_fixed_card_le z h f hf x⁻¹
      (by rw [map_inv, orderOf_inv]; exact hxorder)
  let N := normalizer (e.F : Set G)
  let K := pCore 2 N
  let U := omega₁ K (p := 2)
  let A := (center K).map (N.subtype.comp K.subtype)
  let B := (center U).map ((N.subtype.comp K.subtype).comp U.subtype)
  let : U.Characteristic := omega₁_characteristic K
  have hNA : N ≤ normalizer (A : Set G) := by
    have hh := (le_normalizer (H := N)).trans
      (normalizer_le_normalizer_characteristic_image N ((center K).map K.subtype))
    simpa only [map_map] using hh
  have hNB : N ≤ normalizer (B : Set G) := by
    have hh := (le_normalizer (H := N)).trans
      (normalizer_le_normalizer_characteristic_image N
        (((center U).map U.subtype).map K.subtype))
    simpa only [B, map_map, MonoidHom.comp_assoc] using hh
  have hAE : A ≤ E := n.core_center_le_omega_center.trans
    (n.omega_center_le_inf.trans inf_le_left)
  have hBE : B ≤ E := n.omega_center_le_inf.trans inf_le_left
  have hAeq : A = zpowers z ⊔ zpowers n.t := n.core_center_eq
  have hBeq : B = (zpowers z ⊔ zpowers n.t) ⊔ zpowers n.v := n.omega_center_eq
  have hAz : zpowers z ≤ A := by rw [hAeq]; exact le_sup_left
  have hzE : z ∈ E := hAE (hAz (mem_zpowers z))
  let zE : E := ⟨z, hzE⟩
  let tE : E := ⟨n.t, n.t_mem_inf.1⟩
  let vE : E := ⟨n.v, n.v_mem_inf.1⟩
  have hqz : q zE = 1 := by
    change zE ∈ q.ker
    rw [hker]
    exact mem_zpowers z
  have hAsub : A.subgroupOf E = zpowers zE ⊔ zpowers tE := by
    apply map_injective E.subtype_injective
    rw [map_subgroupOf_eq_of_le hAE, Subgroup.map_sup, MonoidHom.map_zpowers, MonoidHom.map_zpowers]
    exact n.core_center_eq
  have hBsub : B.subgroupOf E = (zpowers zE ⊔ zpowers tE) ⊔ zpowers vE := by
    apply map_injective E.subtype_injective
    rw [map_subgroupOf_eq_of_le hBE, Subgroup.map_sup, Subgroup.map_sup,
      MonoidHom.map_zpowers, MonoidHom.map_zpowers, MonoidHom.map_zpowers]
    exact n.omega_center_eq
  have hAq : (A.subgroupOf E).map q = zpowers (q tE) := by
    rw [hAsub, Subgroup.map_sup, MonoidHom.map_zpowers, MonoidHom.map_zpowers, hqz, zpowers_one_eq_bot, bot_sup_eq]
  have hBq : (B.subgroupOf E).map q = zpowers (q tE) ⊔ zpowers (q vE) := by
    rw [hBsub, Subgroup.map_sup, Subgroup.map_sup, MonoidHom.map_zpowers,
      MonoidHom.map_zpowers, MonoidHom.map_zpowers, hqz, zpowers_one_eq_bot, bot_sup_eq]
  have hxN : (x : G)⁻¹ ∈ N := N.inv_mem (e.sylow_le_normalizer hx)
  have stable (C : Subgroup G) (hCE : C ≤ E)
      (hxC : (x : G)⁻¹ ∈ normalizer (C : Set G)) (g : E) (hg : (g : G) ∈ C) :
      b (q g) ∈ (C.subgroupOf E).map q := by
    have hgC : (x : G)⁻¹ * (g : G) * (x : G) ∈ C := by
      simpa only [inv_inv] using (mem_normalizer_iff.mp hxC (g : G)).mp hg
    let g' : E := ⟨(x : G)⁻¹ * (g : G) * (x : G), hCE hgC⟩
    rw [hcompat g g' rfl]
    exact mem_map_of_mem q hgC
  have hline : b (q tE) ∈ zpowers (q tE) := by
    rw [← hAq]
    apply stable A hAE (hNA hxN)
    rw [hAeq]
    exact mem_sup_right (mem_zpowers n.t)
  have hplane : b (q vE) ∈ zpowers (q tE) ⊔ zpowers (q vE) := by
    rw [← hBq]
    apply stable B hBE (hNB hxN)
    rw [hBeq]
    exact mem_sup_right (mem_zpowers n.v)
  have ht : q tE ≠ 1 := by
    intro hh
    have hh' : tE ∈ q.ker := hh
    rw [hker] at hh'
    exact n.t_not_mem_zpowers hh'
  have hv : q vE ≠ 1 := by
    intro hh
    have hh' : vE ∈ q.ker := hh
    rw [hker] at hh'
    exact n.v_not_mem_core_center (hAz hh')
  have hvt : q vE ≠ q tE := by
    intro hh
    have hd : vE / tE ∈ q.ker := by rw [MonoidHom.mem_ker, map_div, hh, div_eq_mul_inv, mul_inv_cancel]
    rw [hker] at hd
    have hdA : n.v / n.t ∈ A := hAz hd
    have htA : n.t ∈ A := by rw [hAeq]; exact mem_sup_right (mem_zpowers n.t)
    exact n.v_not_mem_core_center (by simpa only [div_mul_cancel] using A.mul_mem hdA htA)
  obtain ⟨hbt, hbv, hfixed⟩ := Theory.GroupAction.marked_invariant_flag b (q tE) (q vE)
    ht hv hvt hline hplane hbound
  exact ⟨inferInstance, hWcard, q, b, hq, hker, hcompat, hfixed, hbt, hbv⟩

end Stellmacher.Recognition
