module

public import Mathlib.Algebra.Group.Defs
public import Mathlib.Data.Finite.Defs
public import Mathlib.GroupTheory.Perm.Centralizer
public import Mathlib.GroupTheory.SpecificGroups.Alternating
public import Mathlib.GroupTheory.Subgroup.Centralizer
public import GorensteinWalter.Classification

noncomputable section

namespace GorensteinWalter

universe u

open Equiv

/-- A concrete element of `A₇` with cycle type `4 · 2`; it belongs to a
Sylow `2`-subgroup of `A₇`. -/
public abbrev a7rho : alternatingGroup (Fin 7) :=
  ⟨d8rho, d8rho_mem⟩

/-- The cycle type of `a7rho` is `{4,2}`. -/
public theorem a7rho_cycleType :
    (a7rho : Equiv.Perm (Fin 7)).cycleType = {4, 2} := by
  decide

/-- The centralizer of `a7rho` in the symmetric group on seven letters has
order `8`; hence it is a `2`-group. -/
public theorem a7rho_centralizer_card_sym :
    Nat.card (Subgroup.centralizer
      ({(a7rho : Equiv.Perm (Fin 7))} : Set (Equiv.Perm (Fin 7)))) = 8 := by
  have hr : (a7rho : Equiv.Perm (Fin 7)).cycleType = {4, 2} := a7rho_cycleType
  rw [Equiv.Perm.nat_card_centralizer, hr]
  simp

/-- An odd-order subgroup of `A₇` centralizing the cycle-type-`(4,2)`
element `a7rho` is trivial. -/
public theorem a7rho_centralizer_odd_trivial
    (P : Subgroup (alternatingGroup (Fin 7)))
    (hPodd : Odd (Nat.card P))
    (hPcent : P ≤ Subgroup.centralizer ({(a7rho : alternatingGroup (Fin 7))} : Set
      (alternatingGroup (Fin 7)))) :
    P = ⊥ := by
  classical
  let A := alternatingGroup (Fin 7)
  let rho : Equiv.Perm (Fin 7) := (a7rho : A)
  have hPmapC : P.map A.subtype ≤
      Subgroup.centralizer ({rho} : Set (Equiv.Perm (Fin 7))) := by
    intro y hy
    rcases Subgroup.mem_map.mp hy with ⟨x, hx, rfl⟩
    rw [Subgroup.mem_centralizer_iff]
    intro z hz
    have hzrho : z = rho := by simpa [rho] using hz
    subst z
    have hxcent : x * a7rho = a7rho * x := by
      have hmem : x ∈ Subgroup.centralizer
          ({(a7rho : A)} : Set A) := hPcent hx
      exact ((Subgroup.mem_centralizer_iff.mp hmem) a7rho (by simp)).symm
    exact (congrArg Subtype.val hxcent).symm
  have hdvd : Nat.card (P.map A.subtype) ∣ 8 := by
    have hle : P.map A.subtype ≤
        Subgroup.centralizer ({rho} : Set (Equiv.Perm (Fin 7))) := hPmapC
    have hcard : Nat.card (Subgroup.centralizer
        ({rho} : Set (Equiv.Perm (Fin 7)))) = 8 := a7rho_centralizer_card_sym
    rw [← hcard]
    exact Subgroup.card_dvd_of_le hle
  have hmapOdd : Odd (Nat.card (P.map A.subtype)) := by
    have hcard : Nat.card (P.map A.subtype) = Nat.card P :=
      Subgroup.card_map_of_injective A.subtype_injective
    rwa [hcard]
  have hmapbot : P.map A.subtype = ⊥ := by
    apply le_bot_iff.mp
    intro x hx
    have hxcard : orderOf x ∣ Nat.card (P.map A.subtype) :=
      Subgroup.orderOf_dvd_natCard (P.map A.subtype) hx
    have hxodd : Odd (orderOf x) := Odd.of_dvd_nat hmapOdd hxcard
    have hx2 : orderOf x ∣ 2 ^ 3 := by
      have htrans : orderOf x ∣ 8 := hxcard.trans hdvd
      simpa [show (8 : ℕ) = 2 ^ 3 by norm_num] using htrans
    -- odd order dividing 2^3 is 1
    have hx1 : orderOf x = 1 := by
      rcases (Nat.dvd_prime_pow Nat.prime_two).mp hx2 with ⟨n, hn, hxeq⟩
      have hn0 : n = 0 := by
        by_contra hn0
        have h2dvd : 2 ∣ orderOf x := by
          rw [hxeq]
          exact ⟨2 ^ (n - 1), by
            rw [show n = (n - 1) + 1 by omega, pow_succ']
            rfl⟩
        exact hxodd.not_two_dvd_nat h2dvd
      simpa [hn0] using hxeq
    rw [Subgroup.mem_bot]
    exact orderOf_eq_one_iff.mp hx1
  apply (Subgroup.map_injective (f := A.subtype) A.subtype_injective)
  simpa [hmapbot]

/-- The concrete `(4,2)`-element of `A₇`, identified with the generator of
the concrete D₈ Sylow `2`-subgroup from `Classification`. -/
public abbrev a7D8rho : alternatingGroup (Fin 7) :=
  a7rho

/-- The concrete Sylow `2`-subgroup of `A₇` generated by `a7rho` and the
concrete reflection. -/
public abbrev a7SylowD8 : Sylow 2 (alternatingGroup (Fin 7)) :=
  sylowD8

/-- The concrete `(4,2)`-element lies in the concrete Sylow `2`-subgroup. -/
public theorem a7D8rho_mem :
    a7D8rho ∈ (a7SylowD8 : Subgroup (alternatingGroup (Fin 7))) := by
  simpa [a7D8rho, a7SylowD8] using d8rho_mem_sylowD8

/-- The concrete `(4,2)`-element of `A₇` lies in the concrete Sylow
`2`-subgroup. -/
public theorem a7rho_mem_a7SylowD8 :
    a7rho ∈ (a7SylowD8 : Subgroup (alternatingGroup (Fin 7))) := by
  simpa [a7D8rho] using a7D8rho_mem

/-- Every Sylow `2`-subgroup of `A₇` contains an element conjugate to the
concrete `(4,2)`-element `a7rho`. -/
public theorem exists_mem_sylow_isConj_a7rho
    (S : Sylow 2 (alternatingGroup (Fin 7))) :
    ∃ r : alternatingGroup (Fin 7),
      r ∈ (S : Subgroup (alternatingGroup (Fin 7))) ∧
        IsConj r a7rho := by
  classical
  obtain ⟨g, hg⟩ :=
    MulAction.exists_smul_eq (alternatingGroup (Fin 7)) S a7SylowD8
  have hS : g⁻¹ • a7SylowD8 = S := by
    have h := congrArg (fun P : Sylow 2 (alternatingGroup (Fin 7)) =>
      g⁻¹ • P) hg
    simpa [smul_smul] using h.symm
  let r : alternatingGroup (Fin 7) := g⁻¹ * a7rho * g
  refine ⟨r, ?_, ?_⟩
  · have hrS : r ∈ (g⁻¹ • a7SylowD8 : Sylow 2 (alternatingGroup (Fin 7))) := by
      change r ∈ ((g⁻¹ • a7SylowD8 : Sylow 2 (alternatingGroup (Fin 7))) :
        Subgroup (alternatingGroup (Fin 7)))
      rw [Sylow.coe_subgroup_smul]
      exact Set.mem_smul_set.mpr ⟨a7rho, a7rho_mem_a7SylowD8, by
        change MulAut.conj (g⁻¹) a7rho = r
        simp [r, MulAut.conj_apply]⟩
    simpa [r] using (hS ▸ hrS)
  · rw [isConj_iff]
    refine ⟨g, ?_⟩
    simp [r]
    group

/-- Let `f : G → A₇`.  If an odd-order subgroup `B₀` centralizes a
subgroup `S₀` containing an element mapped to `a7rho`, then `B₀` lies in
the kernel of `f`. -/
public theorem a7rho_centralizer_odd_trivial_of_map
    {G : Type u} [Group G] [Finite G]
    (f : G →* alternatingGroup (Fin 7))
    (B0 S0 : Subgroup G)
    (hBodd : Odd (Nat.card B0))
    (hBcentS : B0 ≤ Subgroup.centralizer (S0 : Set G))
    {r : G} (hrS : r ∈ S0)
    (hr : f r = a7rho) :
    B0 ≤ f.ker := by
  classical
  let A := alternatingGroup (Fin 7)
  let PB : Subgroup A := B0.map f
  have hPBodd : Odd (Nat.card PB) := by
    have hdvd : Nat.card PB ∣ Nat.card B0 := Subgroup.card_map_dvd B0 f
    exact Odd.of_dvd_nat hBodd hdvd
  have hPBcent : PB ≤ Subgroup.centralizer ({(a7rho : A)} : Set A) := by
    intro y hy
    rcases Subgroup.mem_map.mp hy with ⟨b, hb, rfl⟩
    rw [Subgroup.mem_centralizer_singleton_iff]
    have hbcent : b * r * b⁻¹ = r := by
      have hbcent' : b ∈ Subgroup.centralizer (S0 : Set G) := hBcentS hb
      have hcomm : r * b = b * r :=
        (Subgroup.mem_centralizer_iff.mp hbcent') r hrS
      calc
        b * r * b⁻¹ = (r * b) * b⁻¹ := by rw [hcomm]
        _ = r := by group
    have hconj : f (b * r * b⁻¹) = a7rho := by
      rw [hbcent]
      exact hr
    have hconj' : f b * a7rho * (f b)⁻¹ = a7rho := by
      calc
        f b * a7rho * (f b)⁻¹ = f b * f r * (f b)⁻¹ := by rw [hr]
        _ = a7rho := by simpa [map_mul, map_inv] using hconj
    exact mul_inv_eq_iff_eq_mul.mp (by simpa [mul_assoc] using hconj')
  have hPBbot : PB = ⊥ :=
    a7rho_centralizer_odd_trivial PB hPBodd hPBcent
  intro b hb
  rw [MonoidHom.mem_ker]
  have hbPB : f b ∈ PB := Subgroup.mem_map.mpr ⟨b, hb, rfl⟩
  have hb1 : f b = 1 := by
    have hb0 : f b ∈ (⊥ : Subgroup A) := by
      simpa [hPBbot] using hbPB
    exact Subgroup.mem_bot.mp hb0
  exact hb1

/-- If an odd-order subgroup `B₀` centralizes a subgroup `S₀` whose image
under `f : G → A₇` is a Sylow `2`-subgroup, then `B₀` lies in the kernel
of `f`. -/
public theorem a7rho_centralizer_odd_trivial_of_sylow_image
    {G : Type u} [Group G] [Finite G]
    (f : G →* alternatingGroup (Fin 7))
    (B0 S0 : Subgroup G)
    (hBodd : Odd (Nat.card B0))
    (hBcentS : B0 ≤ Subgroup.centralizer (S0 : Set G))
    (Sbar : Sylow 2 (alternatingGroup (Fin 7)))
    (hS0 : S0.map f = (Sbar : Subgroup (alternatingGroup (Fin 7)))) :
    B0 ≤ f.ker := by
  classical
  let A := alternatingGroup (Fin 7)
  obtain ⟨y, hySbar, hyconj⟩ := exists_mem_sylow_isConj_a7rho Sbar
  rw [isConj_iff] at hyconj
  rcases hyconj with ⟨g, hg⟩
  have hyS0 : y ∈ S0.map f := by
    simpa [hS0] using hySbar
  rcases (Subgroup.mem_map.mp hyS0) with ⟨r, hrS0, hr⟩
  let f' : G →* A := (MulAut.conj g).toMonoidHom.comp f
  have hr' : f' r = a7rho := by
    simp [f', MulAut.conj_apply, hr, hg]
  have hker : B0 ≤ f'.ker :=
    a7rho_centralizer_odd_trivial_of_map f' B0 S0 hBodd hBcentS hrS0 hr'
  have hker_eq : f'.ker = f.ker := by
    ext x
    constructor
    · intro hx
      have hconj : g * f x * g⁻¹ = 1 := by
        simpa [f', MulAut.conj_apply] using hx
      have hfx : f x = 1 := by
        calc
          f x = g⁻¹ * (g * f x * g⁻¹) * g := by group
          _ = g⁻¹ * 1 * g := by rw [hconj]
          _ = 1 := by simp
      exact hfx
    · intro hx
      simpa [f', MulAut.conj_apply, hx]
  simpa [hker_eq] using hker

end GorensteinWalter
