module

public import Mathlib.GroupTheory.SpecificGroups.Dihedral
public import Mathlib.GroupTheory.Index

/-!
# Index of the dihedral rotation subgroup

The subgroup generated by the basic rotation has index two in every
nondegenerate finite dihedral group.
-/

namespace GorensteinWalter

/-- The rotation subgroup of a nondegenerate finite dihedral group has
index two. -/
public theorem dihedral_rotation_index_two {n : ℕ} [NeZero n] :
    (Subgroup.zpowers (DihedralGroup.r 1 : DihedralGroup n)).index = 2 := by
  let R : Subgroup (DihedralGroup n) :=
    Subgroup.zpowers (DihedralGroup.r 1)
  have hcardR : Nat.card R = n := by
    dsimp [R]
    rw [Nat.card_zpowers, DihedralGroup.orderOf_r_one]
  have hcardD : Nat.card (DihedralGroup n) = 2 * n :=
    DihedralGroup.nat_card
  have hmul := R.index_mul_card
  rw [hcardR, hcardD] at hmul
  have hnpos : 0 < n := Nat.pos_of_neZero n
  apply Nat.eq_of_mul_eq_mul_left hnpos
  simpa [mul_comm, mul_left_comm, mul_assoc] using hmul

end GorensteinWalter
