name = "CFSG"
defaultTargets = ["FeitThompson", "BenderSuzuki"]
lintDriver = "batteries/runLinter"

enableArtifactCache = true
restoreAllArtifacts = true

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[lean_lib]]
name = "FeitThompson"

[[lean_lib]]
name = "BenderSuzuki"

[[lean_lib]]
name = "Challenge"
srcDir = "comparator"

[[lean_lib]]
name = "Solution"
srcDir = "comparator"

[[lean_lib]]
name = "Defs"
srcDir = "comparator"

[[lean_lib]]
name = "ZJDefs"
srcDir = "comparator"

[[lean_lib]]
name = "ZJChallenge"
srcDir = "comparator"

[[lean_lib]]
name = "ZJSolution"
srcDir = "comparator"

[[lean_lib]]
name = "BenderSuzukiChallenge"
srcDir = "comparator"
