name = "CFSG"
defaultTargets = [
    "BenderSuzuki",
    "FeitThompson",
    "Comparator",
    "Theory",
]
lintDriver = "batteries/runLinter"

enableArtifactCache = true
restoreAllArtifacts = true

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[lean_lib]]
name = "FeitThompson"

[[lean_lib]]
name = "BenderSuzuki"

[[lean_lib]]
name = "Comparator"

[[lean_lib]]
name = "Theory"
