module  -- shake: keep-all --deprecated_module: ignore

public import Theory.Character
public import Theory.Character.BrauerPermutation
public import Theory.Character.BrauerSuzuki
public import Theory.Character.CharacterValues
public import Theory.Character.ClassFunction
public import Theory.Character.Completeness
public import Theory.Character.ConjClassFunction
public import Theory.Character.CrossCharBrauer
public import Theory.Character.Cyclotomic
public import Theory.Character.DegreeBounds
public import Theory.Character.Divisibility
public import Theory.Character.Induction
public import Theory.Character.Integrality
public import Theory.Character.Orthogonality
public import Theory.Character.SimpleCriteria
public import Theory.Representation
public import Theory.Representation.AbsolutelyIrreducible
public import Theory.Representation.Clifford
public import Theory.Representation.CompleteReducibility
public import Theory.Representation.ConjugateRep
public import Theory.Representation.CyclicQuotientExtension
public import Theory.Representation.ElementaryAbelianAction
public import Theory.Representation.ExtendScalars
public import Theory.Representation.ExtraspecialFixedPoints
public import Theory.Representation.FreeBasis
public import Theory.Representation.InducedIrreducible
public import Theory.Representation.Induction
public import Theory.Representation.Isotypic
public import Theory.Representation.JacobsonDensity
public import Theory.Representation.KrullSchmidt
public import Theory.Representation.Maschke
public import Theory.Representation.PermutationBasisOrbits
public import Theory.Representation.RepEnd
public import Theory.Representation.RepEquiv
public import Theory.Representation.RepMap
public import Theory.Representation.ScalarDescent
public import Theory.Representation.SolvableDimension
public import Theory.Representation.SubrepresentationLattice
public import Theory.Representation.TwoDimensionalOddOrder
public import Theory.Representation.Unbundled
public import Theory.Representation.kerRepresentation
