module
public import Stellmacher.SectionsOneToFourDefs

/-!
# The two-core of a centralizer containing an involution

A subgroup C containing and centralizing a nonidentity involution w has
nontrivial two-core. The membership theorem also records that w itself lies
in the two-core, for the subsequent common-core intersection argument.
The cyclic subgroup generated by w is central in C,
hence normal, and its exponent two puts it in O₂(C).

This elementary finite-group observation is the core input for the local
family selection in Stellmacher (6.4), Journal of Algebra 190 (1997), p.32;
source: `refs/files/stellmacher-n-group.pdf`. It is shared by the conditional
factor extraction and the Sylow-controlled supplement construction.
-/

namespace Stellmacher
universe u

public theorem central_involution_mem_twoCore
    {H : Type u} [Group H] [Finite H]
    (C : Subgroup H) (w : H) (hwC : w ∈ C)
    (hC : C ≤ Subgroup.centralizer ({w} : Set H))
    (hw2 : w ^ 2 = 1) :
    w ∈ twoCoreAmbient C := by
  let x : C := ⟨w, hwC⟩
  have hxcent : x ∈ Subgroup.center C := by
    apply Subgroup.mem_center_iff.mpr
    intro y
    apply Subtype.ext
    exact (Subgroup.mem_centralizer_iff.mp (hC y.property) w rfl).symm
  let Q := Subgroup.zpowers x
  have hQcent : Q ≤ Subgroup.center C := Subgroup.zpowers_le.mpr hxcent
  let _ : Q.Normal := ⟨fun q hq c => by
    have heq := Subgroup.mem_center_iff.mp (hQcent hq) c
    simpa [heq, mul_assoc] using hq⟩
  have hx2 : x ^ 2 = 1 := Subtype.ext hw2
  have hQp : IsPGroup 2 Q := (IsElementaryAbelian.zpowers_of_pow_eq_one (p := 2) hx2).isPGroup 2 _
  have hQcore : Q ≤ pCore 2 C := le_sSup ⟨inferInstance, hQp⟩
  exact Subgroup.mem_map_of_mem C.subtype (hQcore (Subgroup.mem_zpowers x))

public theorem centralizer_twoCore_ne_bot
    {H : Type u} [Group H] [Finite H]
    (C : Subgroup H) (w : H) (hwC : w ∈ C)
    (hC : C ≤ Subgroup.centralizer ({w} : Set H))
    (hw2 : w ^ 2 = 1) (hwne : w ≠ 1) :
    twoCoreAmbient C ≠ ⊥ := by
  intro hbot
  have hwcore := central_involution_mem_twoCore C w hwC hC hw2
  rw [hbot] at hwcore
  exact hwne hwcore


end Stellmacher
