module

public import Stellmacher.ResidualCommutatorIdempotence
public import Stellmacher.LaterDefs
public import BenderSuzuki.External.Huppert.IV.ResidualGenerators
public import Theory.GroupTheory.CyclicTwoAut

/-!
# Residual-action collapse inside a quaternion subgroup

Every proper subgroup of Q8 is cyclic of order at most four. The proof uses
kernel-checked quaternion normal forms, then transports the result through an
actual subgroup model. A cyclic two-group has a two-group of automorphisms,
so any normalizing group generated by odd-order elements centralizes it.

Consequently, a nontrivial subgroup of Q8 equal to its commutator with such
a group is the whole quaternion subgroup. The ambient two-residual satisfies
the generation hypothesis by the Huppert residual generator theorem. The
final corollary uses ambient residual commutator idempotence directly.

This is the residual-action step for the C4-central-Q8 model in Stellmacher
(1997), Section 8, (8.6)(a2). Normalization of the quaternion container is not
needed once containment and commutator idempotence have been established:
idempotence already supplies normalization of the subgroup being acted on.
-/

open Subgroup
open scoped commutatorElement

namespace QuaternionGroup

public theorem proper_subgroup_cyclic_card_le_four (H : Subgroup (QuaternionGroup 2))
    (hproper : H ≠ ⊤) : IsCyclic H ∧ Nat.card H ≤ 4 := by
  classical
  have hcyclic : IsCyclic H := by
    by_cases hsquare : ∀ element ∈ H, element ^ 2 = 1
    · apply Subgroup.isCyclic_of_le (H' := zpowers (a 2 : QuaternionGroup 2))
      intro element helement
      have hsmall : ∀ element : QuaternionGroup 2, element ^ 2 = 1 →
          element = 1 ∨ element = a 2 := by decide
      rcases hsmall element (hsquare element helement) with rfl | rfl
      · exact one_mem _
      · exact mem_zpowers _
    · push Not at hsquare
      obtain ⟨generator, hgenerator, hsquare⟩ := hsquare
      apply Subgroup.isCyclic_of_le (H' := zpowers generator)
      intro element helement
      by_contra hout
      have hnormal : ∀ generator element : QuaternionGroup 2,
          generator ^ 2 ≠ 1 →
          element ≠ 1 → element ≠ generator → element ≠ generator ^ 2 →
          element ≠ generator ^ 3 → ∀ other : QuaternionGroup 2,
          other = 1 ∨ other = generator ∨ other = generator ^ 2 ∨
          other = generator ^ 3 ∨ other = element ∨ other = generator * element ∨
          other = generator ^ 2 * element ∨ other = generator ^ 3 * element := by
        decide
      have hnotone : element ≠ 1 := fun heq => hout (heq ▸ one_mem _)
      have hnotgen : element ≠ generator := fun heq => hout (heq ▸ mem_zpowers _)
      have hnotpow (power : ℕ) : element ≠ generator ^ power :=
        fun heq => hout (heq ▸ pow_mem (mem_zpowers _) power)
      apply hproper
      apply top_unique
      intro other _
      rcases hnormal generator element hsquare hnotone hnotgen (hnotpow 2)
          (hnotpow 3) other with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
      · exact one_mem H
      · exact hgenerator
      · exact H.pow_mem hgenerator 2
      · exact H.pow_mem hgenerator 3
      · exact helement
      · exact H.mul_mem hgenerator helement
      · exact H.mul_mem (H.pow_mem hgenerator 2) helement
      · exact H.mul_mem (H.pow_mem hgenerator 3) helement
  refine ⟨hcyclic, ?_⟩
  have hcard : Nat.card (QuaternionGroup 2) = 8 := by
    rw [Nat.card_eq_fintype_card, QuaternionGroup.card]
  have hdiv := H.card_subgroup_dvd_card
  rw [hcard] at hdiv
  have hlt : Nat.card H < 8 := by
    by_contra hnot
    exact hproper (H.eq_top_of_le_card (hcard ▸ Nat.le_of_not_gt hnot))
  have hposs : ∀ divisor : ℕ, divisor ∣ 8 → divisor < 8 → divisor ≤ 4 := by
    intro divisor hdivisor hbound
    interval_cases divisor <;> norm_num at *
  exact hposs _ hdiv hlt

end QuaternionGroup

namespace Stellmacher
open Later

public theorem proper_quaternion_model_subgroup_cyclic_card_le_four
    {G : Type*} [Group G] [Finite G] (container target : Subgroup G)
    (hmodel : IsModel container Q8) (hcontain : target ≤ container)
    (hproper : target ≠ container) : IsCyclic target ∧ Nat.card target ≤ 4 := by
  obtain ⟨model⟩ := hmodel
  let embedding : target →* Q8 := model.toMonoidHom.comp (Subgroup.inclusion hcontain)
  have hinjective : Function.Injective embedding :=
    model.injective.comp (Subgroup.inclusion_injective hcontain)
  have hrange : embedding.range ≠ ⊤ := by
    intro heq
    apply hproper
    apply le_antisymm hcontain
    intro element helement
    have hmem : model ⟨element, helement⟩ ∈ embedding.range := heq ▸ mem_top _
    obtain ⟨original, horiginal⟩ := hmem
    have hvalue : (original : G) = element :=
      congrArg Subtype.val (model.injective horiginal)
    exact hvalue ▸ original.property
  obtain ⟨hcyclic, hcard⟩ :=
    QuaternionGroup.proper_subgroup_cyclic_card_le_four embedding.range hrange
  let : IsCyclic embedding.range := hcyclic
  let equivalence := MonoidHom.ofInjective hinjective
  refine ⟨isCyclic_of_injective equivalence.toMonoidHom equivalence.injective, ?_⟩
  rwa [Nat.card_congr equivalence.toEquiv]

end Stellmacher

namespace Stellmacher

public theorem twoResidualAmbient_eq_closure_coprime_orderOf
    {G : Type*} [Group G] [Finite G] (actors : Subgroup G) :
    twoResidualAmbient actors =
      closure {element : G | element ∈ actors ∧ Nat.Coprime 2 (orderOf element)} := by
  let : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  rw [twoResidualAmbient, SectionThree.twoResidualSubgroup_eq_hktPResidual',
    BenderSuzuki.External.hktPResidual_eq_closure_coprime_orderOf, MonoidHom.map_closure]
  congr 1
  ext element
  constructor
  · rintro ⟨original, hcoprime, rfl⟩
    exact ⟨original.property, by simpa using hcoprime⟩
  · rintro ⟨hmem, hcoprime⟩
    exact ⟨⟨element, hmem⟩, by simpa using hcoprime, rfl⟩

public theorem twoResidualAmbient_eq_closure_own_coprime_orderOf
    {G : Type*} [Group G] [Finite G] (actors : Subgroup G) :
    twoResidualAmbient actors = closure {element : G |
      element ∈ twoResidualAmbient actors ∧ Nat.Coprime 2 (orderOf element)} := by
  apply le_antisymm
  · rw [twoResidualAmbient_eq_closure_coprime_orderOf actors]
    apply (closure_le _).mpr
    intro element helement
    exact subset_closure ⟨subset_closure helement, helement.2⟩
  · exact (closure_le _).mpr fun _ helement => helement.1

public theorem coprime_generated_le_centralizer_of_cyclic_two
    {G : Type*} [Group G] [Finite G] (residual target : Subgroup G)
    (hgenerated : residual = closure {element : G |
      element ∈ residual ∧ Nat.Coprime 2 (orderOf element)})
    [IsCyclic target] (htwo : IsPGroup 2 target)
    (hnormalize : residual ≤ normalizer (target : Set G)) :
    residual ≤ centralizer (target : Set G) := by
  let : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  let action : residual →* MulAut target :=
    target.normalizerMonoidHom.comp (Subgroup.inclusion hnormalize)
  have haut : IsPGroup 2 (MulAut target) := htwo.mulAut_of_isCyclic_two
  rw [hgenerated]
  apply (closure_le _).mpr
  intro element helement
  let actor : residual := ⟨element, helement.1⟩
  obtain ⟨power, hpower⟩ := haut.exists_orderOf_eq_pow (action actor)
  have hcoprime : Nat.Coprime (orderOf (action actor)) (orderOf actor) := by
    rw [hpower]
    exact (show Nat.Coprime 2 (orderOf actor) by
      simpa only [actor, Subgroup.orderOf_mk] using helement.2).pow_left power
  have hone : action actor = 1 := by
    apply orderOf_eq_one_iff.mp
    exact Nat.eq_one_of_dvd_coprimes hcoprime (dvd_refl _)
      (orderOf_map_dvd action actor)
  have hkernel : (⟨element, hnormalize helement.1⟩ : normalizer (target : Set G)) ∈
      target.normalizerMonoidHom.ker := hone
  rw [normalizerMonoidHom_ker] at hkernel
  exact hkernel

end Stellmacher

namespace Stellmacher
open Later

public theorem quaternion_coprime_generated_action_eq
    {G : Type*} [Group G] [Finite G] (container target residual : Subgroup G)
    (hmodel : IsModel container Q8) (hcontain : target ≤ container)
    (hgenerated : residual = closure {element : G |
      element ∈ residual ∧ Nat.Coprime 2 (orderOf element)})
    (hidempotent : ⁅target, residual⁆ = target) (hnontrivial : target ≠ ⊥) :
    target = container := by
  by_contra hproper
  obtain ⟨hcyclic, _⟩ :=
    proper_quaternion_model_subgroup_cyclic_card_le_four container target
      hmodel hcontain hproper
  let : IsCyclic target := hcyclic
  obtain ⟨model⟩ := hmodel
  have hcontainer : IsPGroup 2 container := by
    apply IsPGroup.of_card (n := 3)
    rw [Nat.card_congr model.toEquiv, Nat.card_eq_fintype_card, QuaternionGroup.card]
    norm_num
  have hnormalize : residual ≤ normalizer (target : Set G) :=
    le_normalizer_iff_commutator_le_left.mpr hidempotent.le
  have hcentral := coprime_generated_le_centralizer_of_cyclic_two residual target
    hgenerated (hcontainer.to_le hcontain) hnormalize
  exact hnontrivial (hidempotent.symm.trans
    (commutator_eq_bot_iff_le_centralizer.mpr (le_centralizer_iff.mp hcentral)))

public theorem quaternion_twoResidualAmbient_action_eq
    {G : Type*} [Group G] [Finite G] (container target actors : Subgroup G)
    (hmodel : IsModel container Q8) (hcontain : target ≤ container)
    (hidempotent : ⁅target, twoResidualAmbient actors⁆ = target)
    (hnontrivial : target ≠ ⊥) : target = container := by
  exact quaternion_coprime_generated_action_eq container target (twoResidualAmbient actors)
    hmodel hcontain (twoResidualAmbient_eq_closure_own_coprime_orderOf actors)
    hidempotent hnontrivial

public theorem quaternion_nontrivial_residual_commutator_eq
    {G : Type*} [Group G] [Finite G] (whole actors container : Subgroup G)
    (hmodel : IsModel container Q8) (htwo : IsPGroup 2 whole)
    (hnormalize : actors ≤ normalizer (whole : Set G))
    (hcontain : ⁅whole, twoResidualAmbient actors⁆ ≤ container)
    (hnontrivial : ⁅whole, twoResidualAmbient actors⁆ ≠ ⊥) :
    ⁅whole, twoResidualAmbient actors⁆ = container := by
  exact quaternion_twoResidualAmbient_action_eq container
    (⁅whole, twoResidualAmbient actors⁆) actors hmodel hcontain
    (commutator_twoResidualAmbient_idempotent whole actors htwo hnormalize) hnontrivial

end Stellmacher
