module
public import Theory.GroupTheory.CentralProductEquivalence
public import Mathlib.GroupTheory.SpecificGroups.Cyclic
public import Mathlib.GroupTheory.Subgroup.Center

/-!
# Cyclic central products with a two-element shared center

For finite groups generated by a cyclic central subgroup and a second
subgroup whose center has order two, an intersection of order two determines
the overlap completely. Any equivalences of corresponding factors extend
to an ambient equivalence, preserving both prescribed factor maps.

Centrality puts the factor intersection inside the second factor's center;
equal cardinalities make them equal. A finite cyclic group has only one
nonidentity element whose square is one, so the factor equivalences preserve
the shared involution. Applying the compatible-factor gluing theorem then
constructs the required ambient equivalence.

This proves the central-product uniqueness step used in ABG II.3
Proposition 3, article p.26. Its finite cyclic and exact center/intersection
hypotheses are explicit; the concrete determinant matrix groups supply them
in the subsequent recognition theorem.
The exact intersection with the second factor's center is also public,
so source central-layer consumers can identify their actual central kernel
without repeating the cardinality argument.
-/

namespace Subgroup

private theorem cyclic_square_one_unique {A : Type*} [Group A] [Finite A] [IsCyclic A]
    (a b : A) (ha : a ^ 2 = 1) (hb : b ^ 2 = 1) (ha1 : a ≠ 1) (hb1 : b ≠ 1) :
    a = b := by
  classical
  let : Fintype A := Fintype.ofFinite A
  by_contra hab
  have hcard := IsCyclic.card_pow_eq_one_le (α := A) (by decide : 0 < 2)
  have hsub : ({1, a, b} : Finset A) ⊆ {x ∈ (Finset.univ : Finset A) | x ^ 2 = 1} := by
    intro x hx
    simp only [Finset.mem_insert, Finset.mem_singleton] at hx
    rcases hx with rfl | rfl | rfl
    · simp
    · simp only [Finset.mem_filter, Finset.mem_univ, ha, and_self]
    · simp only [Finset.mem_filter, Finset.mem_univ, hb, and_self]
  have hle := (Finset.card_le_card hsub).trans hcard
  simp [hab, Ne.symm ha1, Ne.symm hb1] at hle

public theorem overlap_center {G : Type*} [Group G] [Finite G]
    (Z L : Subgroup G) (hZ : Z ≤ center G)
    (hc : Nat.card (center L) = 2) (hi : Nat.card (Z ⊓ L : Subgroup G) = 2) :
    Z.subgroupOf L = center L := by
  have hle : Z.subgroupOf L ≤ center L := by
    intro x hx
    apply mem_center_iff.mpr
    intro y
    exact Subtype.ext (mem_center_iff.mp (hZ hx) y)
  apply eq_of_le_of_card_ge hle
  have hcard : Nat.card (Z.subgroupOf L) = 2 := by
    rw [← card_map_of_injective (K := Z.subgroupOf L) L.subtype_injective,
      subgroupOf_map_subtype]
    exact hi
  omega

private theorem overlap_preserved
    {G H : Type*} [Group G] [Group H] [Finite G] [Finite H]
    (Z L : Subgroup G) (Z' L' : Subgroup H) [IsCyclic Z']
    (hc : Nat.card (center L) = 2)
    (hi : Z.subgroupOf L = center L) (hi' : Z'.subgroupOf L' = center L')
    (eZ : Z ≃* Z') (eL : L ≃* L') (z : Z) (l : L)
    (hzl : (z : G) = (l : G)) : (eZ z : H) = (eL l : H) := by
  by_cases hz1 : z = 1
  · have hl1 : l = 1 := Subtype.ext (hzl.symm.trans (by simp [hz1]))
    simp [hz1, hl1]
  have hlc : l ∈ center L := by
    rw [← hi]
    change (l : G) ∈ Z
    rw [← hzl]
    exact z.property
  have hl2 : l ^ 2 = 1 := by
    have h := congrArg Subtype.val (pow_card_eq_one' (x := (⟨l, hlc⟩ : center L)))
    simpa only [hc, coe_pow, coe_one] using h
  have hz2 : z ^ 2 = 1 := by
    apply Subtype.ext
    have h := congrArg Subtype.val hl2
    simpa only [coe_pow, coe_one, ← hzl] using h
  have helc : eL l ∈ center L' := (centerCongr eL ⟨l, hlc⟩).property
  have heZ : (eL l : H) ∈ Z' := by
    change eL l ∈ Z'.subgroupOf L'
    rw [hi']
    exact helc
  let b : Z' := ⟨eL l, heZ⟩
  have hb2 : b ^ 2 = 1 := by
    apply Subtype.ext
    change ((eL l : L') : H) ^ 2 = 1
    exact congrArg Subtype.val (by simpa only [map_pow, map_one] using congrArg eL hl2)
  have ha2 : (eZ z) ^ 2 = 1 := by simpa only [map_pow, map_one] using congrArg eZ hz2
  have ha1 : eZ z ≠ 1 := by
    intro h
    exact hz1 (eZ.injective (h.trans eZ.map_one.symm))
  have hb1 : b ≠ 1 := by
    intro h
    have hbval : (eL l : H) = 1 := congrArg Subtype.val h
    have hl1 : eL l = 1 := Subtype.ext hbval
    have hl : l = 1 := eL.injective (hl1.trans eL.map_one.symm)
    apply hz1
    exact Subtype.ext (hzl.trans (by simp [hl]))
  exact congrArg Subtype.val (cyclic_square_one_unique (eZ z) b ha2 hb2 ha1 hb1)

public theorem exists_mulEquiv_of_cyclic_central_products
    {G H : Type*} [Group G] [Group H] [Finite G] [Finite H]
    (Z L : Subgroup G) (Z' L' : Subgroup H) [IsCyclic Z] [IsCyclic Z']
    (hZ : Z ≤ center G) (hZ' : Z' ≤ center H)
    (hgen : Z ⊔ L = ⊤) (hgen' : Z' ⊔ L' = ⊤)
    (hc : Nat.card (center L) = 2)
    (hi : Nat.card (Z ⊓ L : Subgroup G) = 2)
    (hi' : Nat.card (Z' ⊓ L' : Subgroup H) = 2)
    (eZ : Z ≃* Z') (eL : L ≃* L') :
    ∃ e : G ≃* H, (∀ z : Z, e z = (eZ z : H)) ∧
      ∀ l : L, e l = (eL l : H) := by
  have hc' : Nat.card (center L') = 2 :=
    (Nat.card_congr (centerCongr eL).toEquiv).symm.trans hc
  have hI := overlap_center Z L hZ hc hi
  have hI' := overlap_center Z' L' hZ' hc' hi'
  apply exists_mulEquiv_of_central_products Z L Z' L'
    (fun z l => (mem_center_iff.mp (hZ z.property) l).symm)
    (fun z l => (mem_center_iff.mp (hZ' z.property) l).symm)
    hgen hgen' eZ eL
  intro z l
  constructor
  · exact overlap_preserved Z L Z' L' hc hI hI' eZ eL z l
  · intro h
    have hh := overlap_preserved Z' L' Z L hc' hI' hI eZ.symm eL.symm (eZ z) (eL l) h
    simpa only [eZ.symm_apply_apply, eL.symm_apply_apply] using hh

end Subgroup
