module

public import Theory.GroupTheory.PGroup.IsolatedFour
public import Theory.GroupTheory.ElementaryCommutingTwoGroup
public import Theory.GroupTheory.PGroup.NormalSubgroups
public import Mathlib.GroupTheory.NoncommCoprod

/-!
# Isolated four-groups in finite two-groups

Let `P` have elementary binary rank at least three, let `U` be a normal
elementary four-group, and let `V` be an isolated elementary four-group.
The intersection of `V` with `U`, or with `C_P(U)`, is a central subgroup
of order two. For `a ∈ V \ U`, the centralizer of `V` is the centralizer
of `a` and is the internal direct product of `⟨a⟩` and
`C_P(V) ∩ C_P(U)`. The second factor has a unique involution and order
greater than two.

The proof uses a central involution of `U` and the index-two centralizer
of `U`. Isolation forces every involution centralizing `V` into `V`.
The cyclic-index-two obstruction excludes a centralizer of order four.

Source: GLS, volume 2, Lemma 10.21(iii), printed pages 67–68 of
`books/KGroup/GLS_Number2_ChapterG_GeneralGroupTheory.pdf`. In the proof,
the book's `K = C_R(A) = C_R(a)` is essential: several occurrences of
`R` were transcribed as `P` in `refs/KGroup/GLS2/ChapterC.tex`.
-/

namespace Subgroup
open scoped IsMulCommutative

/-- An isolated elementary four-group is maximal among elementary subgroups. -/
public theorem maximal_elementary_of_isolated_four
    {G : Type*} [Group G] [Finite G]
    (V : Subgroup G) [IsElementaryAbelian 2 V] (hV : Nat.card V = 4)
    (hiso : ∀ W : Subgroup G, IsElementaryAbelian 2 W → Nat.card W = 4 →
      W ≤ centralizer (V : Set G) → W = V)
    (B : Subgroup G) (hB : IsElementaryAbelian 2 B) (hVB : V ≤ B) : B ≤ V := by
  let : IsElementaryAbelian 2 B := hB
  let : Nontrivial V := Finite.one_lt_card_iff_nontrivial.mp (by omega)
  obtain ⟨v, hv1⟩ := exists_ne (1 : V)
  have hvne : (v : G) ≠ 1 := by simpa using hv1
  intro b hb
  by_contra hbV
  have hb1 : b ≠ 1 := fun h => hbV (h ▸ V.one_mem)
  have hvb : (v : G) ≠ b := fun h => hbV (h ▸ v.property)
  have hcomm : Commute (v : G) b :=
    congrArg Subtype.val (mul_comm (⟨v, hVB v.property⟩ : B) ⟨b, hb⟩)
  let W := closure ({(v : G), b} : Set G)
  let : IsKleinFour W := isKleinFour_closure_pair (v : G) b
    (by simpa only [pow_two] using elemPow_eq_one_of_isElementaryAbelian (p := 2) (v : G) v.property)
    (by simpa only [pow_two] using elemPow_eq_one_of_isElementaryAbelian (p := 2) b hb)
    hvne hb1 hvb hcomm
  have hWe : IsElementaryAbelian 2 W := {
    toIsMulCommutative := IsKleinFour.isMulCommutative
    exponent_dvd_p := by simp }
  have hWB : W ≤ B := (closure_le _).mpr (by
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl
    · exact hVB v.property
    · exact hb)
  have hWV : W = V := hiso W hWe IsKleinFour.card_four (by
    intro w hw x hx
    exact congrArg Subtype.val (mul_comm (⟨x, hVB hx⟩ : B) ⟨w, hWB hw⟩))
  exact hbV (hWV ▸ (subset_closure (by simp) : b ∈ W))

private theorem four_pair_generates
    {G : Type*} [Group G] [Finite G]
    (V : Subgroup G) [IsElementaryAbelian 2 V] (hV : Nat.card V = 4)
    (x y : G) (hx : x ∈ V) (hy : y ∈ V)
    (hx1 : x ≠ 1) (hy1 : y ≠ 1) (hxy : x ≠ y) :
    closure ({x, y} : Set G) = V := by
  let : IsKleinFour (closure ({x, y} : Set G)) :=
    isKleinFour_closure_pair x y
      (by simpa only [pow_two] using elemPow_eq_one_of_isElementaryAbelian (p := 2) x hx)
      (by simpa only [pow_two] using elemPow_eq_one_of_isElementaryAbelian (p := 2) y hy)
      hx1 hy1 hxy
      (congrArg Subtype.val (mul_comm (⟨x, hx⟩ : V) ⟨y, hy⟩))
  apply eq_of_le_of_card_ge
  · exact (closure_le _).mpr (by
      intro a ha
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha
      rcases ha with rfl | rfl <;> assumption)
  · rw [hV, IsKleinFour.card_four]

private theorem isolated_four_not_le_normal_four_centralizer
    {P : Type*} [Group P] [Finite P] (hP : IsPGroup 2 P)
    (E U V : Subgroup P) [IsElementaryAbelian 2 E] [IsElementaryAbelian 2 U]
    [IsElementaryAbelian 2 V] [U.Normal]
    (hE : 8 ≤ Nat.card E) (hU : Nat.card U = 4) (hV : Nat.card V = 4)
    (hiso : ∀ W : Subgroup P, IsElementaryAbelian 2 W → Nat.card W = 4 →
      W ≤ centralizer (V : Set P) → W = V) :
    ¬ V ≤ centralizer (U : Set P) := by
  intro hVC
  have hUC : U ≤ centralizer (V : Set P) := by
    intro u hu v hv
    exact (hVC hv u hu).symm
  have hUV := hiso U inferInstance hU hUC
  obtain ⟨B, hBe, hBc, hUB, -⟩ := exists_elementary_eight_above_normal_four hP U hU E hE
  have hBV := maximal_elementary_of_isolated_four V hV hiso B hBe (hUV ▸ hUB)
  have hc := card_le_of_le hBV
  omega

/-- The two intersections are generated by the same central involution;
the centralizer of the normal four-group has index two. -/
public theorem exists_central_generator_inf_of_isolated_four
    {P : Type*} [Group P] [Finite P] (hP : IsPGroup 2 P)
    (E U V : Subgroup P) [IsElementaryAbelian 2 E] [IsElementaryAbelian 2 U]
    [IsElementaryAbelian 2 V] [U.Normal]
    (hE : 8 ≤ Nat.card E) (hU : Nat.card U = 4) (hV : Nat.card V = 4)
    (hiso : ∀ W : Subgroup P, IsElementaryAbelian 2 W → Nat.card W = 4 →
      W ≤ centralizer (V : Set P) → W = V) :
    ∃ z : P, orderOf z = 2 ∧ z ∈ center P ∧ V ⊓ U = zpowers z ∧
      V ⊓ centralizer (U : Set P) = zpowers z ∧
      (centralizer (U : Set P)).index = 2 := by
  let T := centralizer (U : Set P)
  have hnot : ¬ V ≤ T :=
    isolated_four_not_le_normal_four_centralizer hP E U V hE hU hV hiso
  have hT : T.index = 2 := by
    have hb := centralizer_index_le_two_of_normal_four hP U hU
    have hz := T.index_ne_zero_of_finite
    have ho : T.index ≠ 1 := fun h => hnot (index_eq_one.mp h ▸ le_top)
    change T.index ≤ 2 at hb
    omega
  have hVT : Nat.card (V ⊓ T : Subgroup P) = 2 := by
    have hi : T.relIndex V = 2 := T.subgroupOf_index_eq_two V hT hnot
    have hc := relIndex_mul_relIndex (⊥ : Subgroup P) (V ⊓ T) V bot_le inf_le_left
    simp only [relIndex_bot_left, inf_relIndex_left, hi, hV] at hc
    omega
  let : Fact (IsPGroup 2 P) := ⟨hP⟩
  let : Nontrivial U := Finite.one_lt_card_iff_nontrivial.mp (by omega)
  obtain ⟨z, hz1, hzZ⟩ := exists_nontrivial_center_mem_normal U (p := 2)
  have hzpow := elemPow_eq_one_of_isElementaryAbelian (p := 2) (z : P) z.property
  have hzo : orderOf (z : P) = 2 := orderOf_eq_prime hzpow (by simpa using hz1)
  have hzV : (z : P) ∈ V := involution_mem_of_maximal_elementary_four V
    (maximal_elementary_of_isolated_four V hV hiso) z hzpow
    (fun v _ => mem_center_iff.mp hzZ v)
  have hUC : U ≤ T := by
    intro u hu v hv
    exact congrArg Subtype.val (mul_comm (⟨v, hv⟩ : U) ⟨u, hu⟩)
  have hL : zpowers (z : P) ≤ V ⊓ U := zpowers_le.mpr ⟨hzV, z.property⟩
  have hLcard : Nat.card (zpowers (z : P)) = 2 := by rw [Nat.card_zpowers, hzo]
  have hLT : zpowers (z : P) = V ⊓ T :=
    eq_of_le_of_card_ge (hL.trans (inf_le_inf_left V hUC)) (by omega)
  have hLU : V ⊓ U = zpowers (z : P) := le_antisymm
    (hLT ▸ inf_le_inf_left V hUC) hL
  exact ⟨z, hzo, hzZ, hLU, hLT.symm, hT⟩

/-- The intersection with a normal four-group is the central order-two
intersection with its centralizer. -/
public theorem inf_normal_four_of_isolated_four
    {P : Type*} [Group P] [Finite P] (hP : IsPGroup 2 P)
    (E U V : Subgroup P) [IsElementaryAbelian 2 E] [IsElementaryAbelian 2 U]
    [IsElementaryAbelian 2 V] [U.Normal]
    (hE : 8 ≤ Nat.card E) (hU : Nat.card U = 4) (hV : Nat.card V = 4)
    (hiso : ∀ W : Subgroup P, IsElementaryAbelian 2 W → Nat.card W = 4 →
      W ≤ centralizer (V : Set P) → W = V) :
    V ⊓ U = V ⊓ centralizer (U : Set P) ∧ Nat.card (V ⊓ U : Subgroup P) = 2 ∧
      V ⊓ U ≤ center P := by
  obtain ⟨z, hzo, hzZ, hVU, hVT, -⟩ :=
    exists_central_generator_inf_of_isolated_four hP E U V hE hU hV hiso
  refine ⟨hVU.trans hVT.symm, ?_, ?_⟩
  · rw [hVU, Nat.card_zpowers, hzo]
  · rw [hVU]
    exact zpowers_le.mpr hzZ

private theorem centralizer_four_eq_of_central_generator
    {P : Type*} [Group P] [Finite P]
    (V : Subgroup P) [IsElementaryAbelian 2 V] (hV : Nat.card V = 4)
    (z a : P) (hzV : z ∈ V) (haV : a ∈ V) (hz1 : z ≠ 1) (ha1 : a ≠ 1)
    (hza : z ≠ a) (hzZ : z ∈ center P) :
    centralizer (V : Set P) = centralizer ({a} : Set P) := by
  have hgen := four_pair_generates V hV z a hzV haV hz1 ha1 hza
  apply le_antisymm
  · intro x hx
    exact mem_centralizer_singleton_iff.mpr (hx a haV).symm
  · intro x hx
    have hVx : V ≤ centralizer ({x} : Set P) := by
      rw [← hgen]
      apply (closure_le _).mpr
      intro y hy
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hy
      rcases hy with rfl | rfl
      · exact mem_centralizer_singleton_iff.mpr (mem_center_iff.mp hzZ x).symm
      · exact mem_centralizer_singleton_iff.mpr
          (mem_centralizer_singleton_iff.mp hx).symm
    intro v hv
    exact mem_centralizer_singleton_iff.mp (hVx hv)

/-- Outside the normal four-group, either involution of the isolated
four-group has the same centralizer as the whole four-group. -/
public theorem centralizer_eq_of_mem_isolated_four
    {P : Type*} [Group P] [Finite P] (hP : IsPGroup 2 P)
    (E U V : Subgroup P) [IsElementaryAbelian 2 E] [IsElementaryAbelian 2 U]
    [IsElementaryAbelian 2 V] [U.Normal]
    (hE : 8 ≤ Nat.card E) (hU : Nat.card U = 4) (hV : Nat.card V = 4)
    (hiso : ∀ W : Subgroup P, IsElementaryAbelian 2 W → Nat.card W = 4 →
      W ≤ centralizer (V : Set P) → W = V)
    (a : P) (haV : a ∈ V) (haU : a ∉ U) :
    centralizer (V : Set P) = centralizer ({a} : Set P) := by
  obtain ⟨z, hzo, hzZ, hVU, -, -⟩ :=
    exists_central_generator_inf_of_isolated_four hP E U V hE hU hV hiso
  have hzVU : z ∈ V ⊓ U := hVU ▸ mem_zpowers z
  apply centralizer_four_eq_of_central_generator V hV z a hzVU.1 haV
  · intro hz1
    simp [hz1] at hzo
  · exact fun ha1 => haU (ha1 ▸ U.one_mem)
  · exact fun hza => haU (hza ▸ hzVU.2)
  · exact hzZ

/-- The centralizer of an isolated four-group is strictly larger than it. -/
public theorem lt_centralizer_of_isolated_four
    {P : Type*} [Group P] [Finite P] (hP : IsPGroup 2 P)
    (E U V : Subgroup P) [IsElementaryAbelian 2 E] [IsElementaryAbelian 2 U]
    [IsElementaryAbelian 2 V] [U.Normal]
    (hE : 8 ≤ Nat.card E) (hU : Nat.card U = 4) (hV : Nat.card V = 4)
    (hiso : ∀ W : Subgroup P, IsElementaryAbelian 2 W → Nat.card W = 4 →
      W ≤ centralizer (V : Set P) → W = V) :
    V < centralizer (V : Set P) := by
  obtain ⟨z, hzo, hzZ, hVU, -, -⟩ :=
    exists_central_generator_inf_of_isolated_four hP E U V hE hU hV hiso
  have hzV : z ∈ V := (show z ∈ V ⊓ U from hVU ▸ mem_zpowers z).1
  refine lt_of_le_of_ne V.le_centralizer (Ne.symm ?_)
  apply centralizer_ne_self_of_four_of_central_involution hP E V hE hV z hzV _ hzZ
  intro hz1
  simp [hz1] at hzo

private theorem mem_zpowers_involution
    {P : Type*} [Group P] [Finite P] {a b : P}
    (ha : orderOf a = 2) (hb : b ∈ zpowers a) : b = 1 ∨ b = a := by
  classical
  rw [mem_zpowers_iff_mem_range_orderOf, ha] at hb
  obtain ⟨n, hn, rfl⟩ := Finset.mem_image.mp hb
  have hn2 : n < 2 := Finset.mem_range.mp hn
  interval_cases n <;> simp

/-- The centralizer decomposition as an internal direct product, with the
actual factor `C_P(V) ∩ C_P(U)`. This factor has a unique involution and
order greater than two. -/
public theorem centralizer_structure_of_isolated_four
    {P : Type*} [Group P] [Finite P] (hP : IsPGroup 2 P)
    (E U V : Subgroup P) [IsElementaryAbelian 2 E] [IsElementaryAbelian 2 U]
    [IsElementaryAbelian 2 V] [U.Normal]
    (hE : 8 ≤ Nat.card E) (hU : Nat.card U = 4) (hV : Nat.card V = 4)
    (hiso : ∀ W : Subgroup P, IsElementaryAbelian 2 W → Nat.card W = 4 →
      W ≤ centralizer (V : Set P) → W = V)
    (a : P) (haV : a ∈ V) (haU : a ∉ U) :
    let C := centralizer (V : Set P)
    let K := C ⊓ centralizer (U : Set P)
    C = centralizer ({a} : Set P) ∧ zpowers a ⊔ K = C ∧
      Disjoint (zpowers a) K ∧ zpowers a ≤ centralizer (K : Set P) ∧
      (∃! k : K, orderOf k = 2) ∧ 2 < Nat.card K := by
  let C := centralizer (V : Set P)
  let T := centralizer (U : Set P)
  let K := C ⊓ T
  change C = centralizer ({a} : Set P) ∧ zpowers a ⊔ K = C ∧
    Disjoint (zpowers a) K ∧ zpowers a ≤ centralizer (K : Set P) ∧
    (∃! k : K, orderOf k = 2) ∧ 2 < Nat.card K
  obtain ⟨z, hzo, hzZ, hVU, hVT, hT⟩ :=
    exists_central_generator_inf_of_isolated_four hP E U V hE hU hV hiso
  have hCa : C = centralizer ({a} : Set P) :=
    centralizer_eq_of_mem_isolated_four hP E U V hE hU hV hiso a haV haU
  have haT : a ∉ T := by
    intro ha
    have hmem : a ∈ V ⊓ U := (hVU.trans hVT.symm) ▸ (show a ∈ V ⊓ T from ⟨haV, ha⟩)
    exact haU hmem.2
  have hapow := elemPow_eq_one_of_isElementaryAbelian (p := 2) a haV
  have hao : orderOf a = 2 := orderOf_eq_prime hapow (fun h => haU (h ▸ U.one_mem))
  have haC : a ∈ C := V.le_centralizer haV
  have hAC : zpowers a ≤ C := zpowers_le.mpr haC
  have hprod : zpowers a ⊔ K = C := by
    apply le_antisymm (sup_le hAC inf_le_left)
    intro c hc
    by_cases hcT : c ∈ T
    · exact (le_sup_right : K ≤ zpowers a ⊔ K) ⟨hc, hcT⟩
    have hacK : a * c ∈ K := ⟨C.mul_mem haC hc,
      (T.mul_mem_iff_of_index_two hT).mpr (by simp [haT, hcT])⟩
    have haS : a ∈ zpowers a ⊔ K :=
      (le_sup_left : zpowers a ≤ zpowers a ⊔ K) (mem_zpowers a)
    have hacS : a * c ∈ zpowers a ⊔ K := (le_sup_right : K ≤ zpowers a ⊔ K) hacK
    have hcancel : a * (a * c) = c := by rw [← mul_assoc, ← pow_two, hapow, one_mul]
    exact hcancel ▸ (zpowers a ⊔ K).mul_mem haS hacS
  have hdisj : Disjoint (zpowers a) K := disjoint_def.mpr (by
    intro b hbA hbK
    rcases mem_zpowers_involution hao hbA with hb1 | rfl
    · exact hb1
    · exact (haT hbK.2).elim)
  have hcomm : zpowers a ≤ centralizer (K : Set P) := zpowers_le.mpr (by
    intro k hk
    exact (hk.1 a haV).symm)
  have hzVU : z ∈ V ⊓ U := hVU ▸ mem_zpowers z
  have hzK : z ∈ K := ⟨V.le_centralizer hzVU.1, U.le_centralizer hzVU.2⟩
  have hunique : ∃! k : K, orderOf k = 2 := by
    refine ⟨⟨z, hzK⟩, by simpa using hzo, ?_⟩
    intro k hk
    have hko : orderOf (k : P) = 2 := by simpa using hk
    have hkpow : (k : P) ^ 2 = 1 := by simpa [hko] using pow_orderOf_eq_one (k : P)
    have hkV : (k : P) ∈ V := involution_mem_of_maximal_elementary_four V
      (maximal_elementary_of_isolated_four V hV hiso) k hkpow k.property.1
    have hkL : (k : P) ∈ zpowers z := hVT ▸ (show (k : P) ∈ V ⊓ T from ⟨hkV, k.property.2⟩)
    rcases mem_zpowers_involution hzo hkL with hk1 | hkz
    · simp [hk1] at hko
    · exact Subtype.ext hkz
  have hKcard : 2 < Nat.card K := by
    have hLK : zpowers z ≤ K := zpowers_le.mpr hzK
    have hLc : Nat.card (zpowers z) = 2 := by rw [Nat.card_zpowers, hzo]
    have hbound := card_le_of_le hLK
    by_contra hsmall
    have hKL : K = zpowers z := (eq_of_le_of_card_ge hLK (by omega)).symm
    have hCV : C ≤ V := by
      rw [← hprod, hKL]
      exact sup_le (zpowers_le.mpr haV) (zpowers_le.mpr hzVU.1)
    exact (lt_centralizer_of_isolated_four hP E U V hE hU hV hiso).not_ge hCV
  exact ⟨hCa, hprod, hdisj, hcomm, hunique, hKcard⟩

private theorem exists_mulEquiv_of_internal_product
    {P : Type*} [Group P] (A K C : Subgroup P)
    (hprod : A ⊔ K = C) (hdisj : Disjoint A K)
    (hcomm : A ≤ centralizer (K : Set P)) :
    ∃ e : A × K ≃* C, ∀ a k, (e (a, k) : P) = (a : P) * (k : P) := by
  have hc : ∀ a : A, ∀ k : K, Commute (a : P) (k : P) := by
    intro a k
    exact (hcomm a.property k k.property).symm
  let f : A × K →* P := A.subtype.noncommCoprod K.subtype hc
  have hfr : f.range = C := (MonoidHom.noncommCoprod_range A.subtype K.subtype hc).trans
    (by simpa only [range_subtype] using hprod)
  let g : A × K →* C := f.codRestrict C (fun x => hfr ▸ ⟨x, rfl⟩)
  have hg : Function.Bijective g := by
    constructor
    · intro x y hxy
      exact mul_injective_of_disjoint hdisj (congrArg Subtype.val hxy)
    · intro c
      obtain ⟨x, hx⟩ := (show (c : P) ∈ f.range from hfr ▸ c.property)
      exact ⟨x, Subtype.ext hx⟩
  exact ⟨MulEquiv.ofBijective g hg, fun _ _ => rfl⟩

/-- Multiplication itself gives the direct-product isomorphism, so the
centralizer decomposition retains both specified embedded factors. -/
public theorem exists_centralizer_mulEquiv_of_isolated_four
    {P : Type*} [Group P] [Finite P] (hP : IsPGroup 2 P)
    (E U V : Subgroup P) [IsElementaryAbelian 2 E] [IsElementaryAbelian 2 U]
    [IsElementaryAbelian 2 V] [U.Normal]
    (hE : 8 ≤ Nat.card E) (hU : Nat.card U = 4) (hV : Nat.card V = 4)
    (hiso : ∀ W : Subgroup P, IsElementaryAbelian 2 W → Nat.card W = 4 →
      W ≤ centralizer (V : Set P) → W = V)
    (a : P) (haV : a ∈ V) (haU : a ∉ U) :
    let C := centralizer (V : Set P)
    let K := C ⊓ centralizer (U : Set P)
    ∃ e : zpowers a × K ≃* C, ∀ b k, (e (b, k) : P) = (b : P) * (k : P) := by
  obtain ⟨-, hprod, hdisj, hcomm, -, -⟩ :=
    centralizer_structure_of_isolated_four hP E U V hE hU hV hiso a haV haU
  exact exists_mulEquiv_of_internal_product _ _ _ hprod hdisj hcomm

/-- The intersection of an isolated four-group with the Frattini subgroup
lies in the subgroup generated by any of its central involutions. -/
public theorem inf_frattini_le_zpowers_of_isolated_four
    {P : Type*} [Group P] [Finite P] (hP : IsPGroup 2 P)
    (E U V : Subgroup P) [IsElementaryAbelian 2 E] [IsElementaryAbelian 2 U]
    [IsElementaryAbelian 2 V] [U.Normal]
    (hE : 8 ≤ Nat.card E) (hU : Nat.card U = 4) (hV : Nat.card V = 4)
    (hiso : ∀ W : Subgroup P, IsElementaryAbelian 2 W → Nat.card W = 4 →
      W ≤ centralizer (V : Set P) → W = V)
    (t : P) (htV : t ∈ V) (ht : orderOf t = 2) (htZ : t ∈ center P) :
    V ⊓ frattini P ≤ zpowers t := by
  obtain ⟨z, hzo, -, -, hVT, hT⟩ :=
    exists_central_generator_inf_of_isolated_four hP E U V hE hU hV hiso
  let T := centralizer (U : Set P)
  have hPhi : frattini P ≤ T := by
    apply frattini_le_coatom
    refine ⟨?_, ?_⟩
    · intro htop
      change T.index = 2 at hT
      simp [htop] at hT
    · intro B hB
      have hb := index_strictAnti hB
      have hz := B.index_ne_zero_of_finite
      change T.index = 2 at hT
      rw [hT] at hb
      exact index_eq_one.mp (by omega)
  have htT : t ∈ T := center_le_centralizer _ htZ
  have hline : zpowers t = V ⊓ T := by
    have hle : zpowers t ≤ V ⊓ T := zpowers_le.mpr ⟨htV, htT⟩
    apply eq_of_le_of_card_ge hle
    rw [hVT, Nat.card_zpowers, Nat.card_zpowers, hzo, ht]
  rw [hline]
  exact inf_le_inf_left V hPhi

/-- Rank-three version of strict centralizer containment, with no chosen
normal four-group among the hypotheses. -/
public theorem lt_centralizer_of_isolated_four_of_rank_three
    {P : Type*} [Group P] [Finite P] (hP : IsPGroup 2 P)
    (E V : Subgroup P) [IsElementaryAbelian 2 E] [IsElementaryAbelian 2 V]
    (hE : 8 ≤ Nat.card E) (hV : Nat.card V = 4)
    (hiso : ∀ W : Subgroup P, IsElementaryAbelian 2 W → Nat.card W = 4 →
      W ≤ centralizer (V : Set P) → W = V) :
    V < centralizer (V : Set P) := by
  obtain ⟨U, hUn, hUe, hU⟩ := hP.exists_normal_elementaryAbelian_four E hE
  let : U.Normal := hUn
  let : IsElementaryAbelian 2 U := hUe
  exact lt_centralizer_of_isolated_four hP E U V hE hU hV hiso

/-- Rank-three version of the Frattini bound, with no chosen normal
four-group among the hypotheses. -/
public theorem inf_frattini_le_zpowers_of_isolated_four_of_rank_three
    {P : Type*} [Group P] [Finite P] (hP : IsPGroup 2 P)
    (E V : Subgroup P) [IsElementaryAbelian 2 E] [IsElementaryAbelian 2 V]
    (hE : 8 ≤ Nat.card E) (hV : Nat.card V = 4)
    (hiso : ∀ W : Subgroup P, IsElementaryAbelian 2 W → Nat.card W = 4 →
      W ≤ centralizer (V : Set P) → W = V)
    (t : P) (htV : t ∈ V) (ht : orderOf t = 2) (htZ : t ∈ center P) :
    V ⊓ frattini P ≤ zpowers t := by
  obtain ⟨U, hUn, hUe, hU⟩ := hP.exists_normal_elementaryAbelian_four E hE
  let : U.Normal := hUn
  let : IsElementaryAbelian 2 U := hUe
  exact inf_frattini_le_zpowers_of_isolated_four hP E U V hE hU hV hiso t htV ht htZ

/-- An isolated four in a rank-three Sylow contains a Sylow-central
involution. This transports the normal-four structure inside the actual Sylow. -/
public theorem exists_central_involution_of_isolated_four_in_sylow
    {G : Type*} [Group G] [Finite G]
    (S : Sylow 2 G) (A V : Subgroup G)
    [IsElementaryAbelian 2 A] [IsElementaryAbelian 2 V]
    (hA : 8 ≤ Nat.card A) (hV : Nat.card V = 4)
    (hAS : A ≤ S) (hVS : V ≤ S)
    (hiso : ∀ W : Subgroup G, IsElementaryAbelian 2 W → Nat.card W = 4 →
      W ≤ S → W ≤ Subgroup.centralizer (V : Set G) → W = V) :
    ∃ t : G, orderOf t = 2 ∧ t ∈ V ∧
      (S : Subgroup G) ≤ Subgroup.centralizer ({t} : Set G) := by
  let AS := A.subgroupOf (S : Subgroup G)
  let VS := V.subgroupOf (S : Subgroup G)
  let : IsElementaryAbelian 2 AS := IsElementaryAbelian.subgroupOf hAS
  let : IsElementaryAbelian 2 VS := IsElementaryAbelian.subgroupOf hVS
  have hAS8 : 8 ≤ Nat.card AS := by
    rwa [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hAS).toEquiv]
  have hVS4 : Nat.card VS = 4 :=
    (Nat.card_congr (Subgroup.subgroupOfEquivOfLe hVS).toEquiv).trans hV
  have hisoS : ∀ W : Subgroup S, IsElementaryAbelian 2 W → Nat.card W = 4 →
      W ≤ Subgroup.centralizer (VS : Set S) → W = VS := by
    intro W hWe hW hWC
    let : IsElementaryAbelian 2 W := hWe
    have hm : W.map (S : Subgroup G).subtype = V :=
      hiso _ (IsElementaryAbelian.map _) (by
        simpa only [Subgroup.card_map_of_injective
          (S : Subgroup G).subtype_injective] using hW)
        (Subgroup.map_subtype_le _) (by
          rintro x ⟨w, hw, rfl⟩ v hv
          exact congrArg Subtype.val (hWC hw ⟨v, hVS hv⟩ hv))
    apply Subgroup.map_injective (S : Subgroup G).subtype_injective
    rw [hm, Subgroup.map_subgroupOf_eq_of_le hVS]
  obtain ⟨U, hUn, hUe, hU⟩ := S.isPGroup'.exists_normal_elementaryAbelian_four AS hAS8
  let : U.Normal := hUn
  let : IsElementaryAbelian 2 U := hUe
  obtain ⟨t, ht, htZ, hVU, -, -⟩ :=
    Subgroup.exists_central_generator_inf_of_isolated_four
      S.isPGroup' AS U VS hAS8 hU hVS4 hisoS
  have htV : t ∈ VS :=
    (show t ∈ VS ⊓ U from hVU ▸ Subgroup.mem_zpowers t).1
  refine ⟨t, by simpa using ht, htV, ?_⟩
  intro s hs
  exact Subgroup.mem_centralizer_singleton_iff.mpr
    (congrArg Subtype.val (Subgroup.mem_center_iff.mp htZ (⟨s, hs⟩ : S)))

/-- An involution centralizing a Sylow two-subgroup belongs to every isolated
four in that Sylow. This needs neither simplicity nor a rank-three actor. -/
public theorem mem_isolated_four_of_involution_centralizing_sylow
    {G : Type*} [Group G] [Finite G]
    (S : Sylow 2 G) (V : Subgroup G) [IsElementaryAbelian 2 V]
    (hV : Nat.card V = 4) (hVS : V ≤ S)
    (hiso : ∀ W : Subgroup G, IsElementaryAbelian 2 W → Nat.card W = 4 →
      W ≤ S → W ≤ centralizer (V : Set G) → W = V)
    (t : G) (ht : orderOf t = 2)
    (hSC : (S : Subgroup G) ≤ centralizer ({t} : Set G)) : t ∈ V := by
  have ht2 : t ^ 2 = 1 := by rw [← ht]; exact pow_orderOf_eq_one t
  let T := zpowers t
  let : IsElementaryAbelian 2 T := IsElementaryAbelian.zpowers_of_pow_eq_one ht2
  have hTC : T ≤ centralizer (S : Set G) := by
    apply zpowers_le.mpr
    intro s hs
    exact mem_centralizer_singleton_iff.mp (hSC hs)
  have hjoin : IsPGroup 2 ((S : Subgroup G) ⊔ T : Subgroup G) :=
    S.isPGroup'.to_sup_of_normal_left' (IsElementaryAbelian.isPGroup 2 T)
      (hTC.trans (centralizer_le_normalizer _))
  have htS : t ∈ S := by
    change t ∈ (S : Subgroup G)
    rw [← S.is_maximal' hjoin le_sup_left]
    exact (le_sup_right : T ≤ (S : Subgroup G) ⊔ T) (mem_zpowers t)
  by_contra htV
  let : Nontrivial V := Finite.one_lt_card_iff_nontrivial.mp (by omega)
  obtain ⟨v, hv⟩ := exists_ne (1 : V)
  have hvne : (v : G) ≠ 1 := fun h => hv (Subtype.ext h)
  let W := closure ({(v : G), t} : Set G)
  let : IsKleinFour W := isKleinFour_closure_pair (v : G) t
    (by simpa only [pow_two] using
      elemPow_eq_one_of_isElementaryAbelian (p := 2) (v : G) v.property)
    (by simpa only [pow_two] using ht2) hvne
    (fun h => htV (h ▸ V.one_mem)) (fun h => htV (h ▸ v.property))
    (mem_centralizer_singleton_iff.mp (hSC (hVS v.property)))
  have hWe : IsElementaryAbelian 2 W := {
    toIsMulCommutative := IsKleinFour.isMulCommutative
    exponent_dvd_p := by simp }
  have hWS : W ≤ S := (closure_le _).mpr (by
    intro x hx
    rcases hx with rfl | hx
    · exact hVS v.property
    · exact Set.mem_singleton_iff.mp hx ▸ htS)
  have hWC : W ≤ centralizer (V : Set G) := (closure_le _).mpr (by
    intro x hx
    rcases hx with rfl | hx
    · intro y hy
      exact congrArg Subtype.val (mul_comm (⟨y, hy⟩ : V) v)
    · rw [Set.mem_singleton_iff.mp hx]
      exact (centralizer_le hVS) (hTC (mem_zpowers t)))
  exact htV (hiso W hWe IsKleinFour.card_four hWS hWC ▸
    (subset_closure (by simp) : t ∈ W))

end Subgroup
