module
public import Theory.GroupTheory.NormalClosureCentralizerCover
public import Mathlib.Algebra.Group.Subgroup.Pointwise
public import Mathlib.Tactic.Group

/-!
# A selected module spans under a normal supplement

Suppose V is normal, is normally generated by Z, and is contained in its
commutator with the ambient group. If Z centralizes S, G = AS, and [V,A]
lies in W <= V, then the normal closure of W equals V. If also G = LS
with L normal and normalizing W, the S-conjugates of W therefore generate V.

Modulo the normal closure of W, A centralizes the image of V. The quotient
centralizer-cover criterion makes the image of V trivial. To pass to the
S-orbit, write every ambient conjugator as sl; the l factor preserves W.
This proves the selected-coordinate spanning assertion in Stellmacher (4.6),
journal p26, without assuming arbitrary product factors are permuted.
Source: refs/latex/stellmacher-n-group.tex.
-/

namespace Subgroup

public theorem eq_iSup_conjugates_of_selected_module
    {G : Type*} [Group G] (Z V W A L S : Subgroup G) [V.Normal] [L.Normal]
    (hZV : Z ≤ V) (hV : V = normalClosure (Z : Set G))
    (hZS : Z ≤ centralizer (S : Set G))
    (hcomm : V ≤ ⁅V, (⊤ : Subgroup G)⁆)
    (hWV : W ≤ V) (hAS : A ⊔ S = ⊤) (hVA : ⁅V, A⁆ ≤ W)
    (hLS : L ⊔ S = ⊤) (hLW : L ≤ normalizer (W : Set G)) :
    V = ⨆ s : S, W.map (MulAut.conj (s : G)).toMonoidHom := by
  let U := normalClosure (W : Set G)
  let _ : U.Normal := normalClosure_normal
  let π := QuotientGroup.mk' U
  have hAcent : A.map π ≤ centralizer (V.map π : Set (G ⧸ U)) := by
    apply le_centralizer_iff.mp
    apply commutator_eq_bot_iff_le_centralizer.mp
    rw [← map_commutator]
    apply bot_unique
    have hkill : W.map π = ⊥ := (map_eq_bot_iff W).mpr (by
      simpa only [π, QuotientGroup.ker_mk'] using (le_normalClosure : W ≤ U))
    exact (map_mono hVA).trans_eq hkill
  have hcover : centralizer (V.map π : Set (G ⧸ U)) ⊔ S.map π = ⊤ := by
    apply top_unique
    rw [← map_top_of_surjective π (QuotientGroup.mk'_surjective U), ← hAS, map_sup]
    exact sup_le (hAcent.trans le_sup_left) le_sup_right
  have hVU : V ≤ U := normalClosure_le_of_centralizer_cover Z V U S hZV hV hZS hcomm hcover
  have hUV : U ≤ V := normalClosure_le_normal hWV
  have hVUeq : V = U := le_antisymm hVU hUV
  rw [hVUeq]
  apply le_antisymm
  · apply (closure_le _).mpr
    intro x hx
    obtain ⟨w, hw, hconj⟩ := Group.mem_conjugatesOfSet_iff.mp hx
    obtain ⟨g, rfl⟩ := isConj_iff.mp hconj
    have hg : g ∈ S ⊔ L := by rw [sup_comm, hLS]; trivial
    obtain ⟨s, hs, l, hl, rfl⟩ := mem_sup_of_normal_right.mp hg
    have hlw : l * w * l⁻¹ ∈ W := (mem_normalizer_iff.mp (hLW hl) w).mp hw
    apply (le_iSup (fun s : S => W.map (MulAut.conj (s : G)).toMonoidHom) ⟨s, hs⟩)
    refine ⟨l * w * l⁻¹, hlw, ?_⟩
    simp only [MulAut.conj_apply, MulEquiv.coe_toMonoidHom]
    group
  · apply iSup_le
    intro s
    apply map_le_iff_le_comap.mpr
    intro w hw
    exact (normalClosure_normal (s := (W : Set G))).conj_mem w (le_normalClosure hw) s

end Subgroup
