module

public import Theory.GroupTheory.PGroup.NormalFourInvolutionRoots
public import Theory.GroupTheory.PGroup.NormalEightFour
public import Theory.GroupTheory.FusedFourTransport
public import Theory.GroupTheory.SpecificGroups.KleinFourGenerators

/-!
# Central conjugacy classes in a weakly closed normal four

Under the no-normal-eight hypothesis, a weakly closed normal four contains
every returning conjugate of a central involution. A returning conjugate
centralizing the four is transported to the central involution together with
the four, so weak closure already puts it in the four. In the other case,
the maximal-normal-abelian argument supplies a commuting square root.
Transporting that root makes the transported central involution a square,
which centralizes the four. The first argument puts this square in the four;
the four generated by the original and returning involutions is consequently
a conjugate of the given four, and weak closure finishes the proof.

Source: Janko--Thompson, Math. Z. 113 (1970), section 6, printed p.395.
Only normal elementary subgroups are bounded, not arbitrary elementary ones.
-/

open Subgroup

namespace Sylow

variable {G : Type*} [Group G] [Finite G]

/-- A returning central-involution conjugate centralizing a weakly closed
normal four belongs to that four. -/
public theorem mem_four_of_centralizing_isConj_of_weakly_closed
    (S : Sylow 2 G) (E : Subgroup S) [IsElementaryAbelian 2 E]
    (z : S) (hzC : z ∈ center S) (hzE : z ∈ E)
    (hweak : ∀ g : G,
      (E.map (S : Subgroup G).subtype).map (MulAut.conj g).toMonoidHom ≤
        (S : Subgroup G) →
      (E.map (S : Subgroup G).subtype).map (MulAut.conj g).toMonoidHom =
        E.map (S : Subgroup G).subtype)
    (t : S) (hconj : IsConj (z : G) (t : G))
    (htC : t ∈ centralizer (E : Set S)) : t ∈ E := by
  let W := E.map (S : Subgroup G).subtype
  let R := W ⊔ zpowers (t : G)
  have hRS : R ≤ (S : Subgroup G) := sup_le (map_subtype_le E)
    (zpowers_le.mpr t.property)
  have hp : IsPGroup 2 R :=
    S.isPGroup'.of_injective (inclusion hRS) (inclusion_injective hRS)
  have hRC : R ≤ centralizer ({(t : G)} : Set G) := by
    apply sup_le
    · rintro w ⟨e, he, rfl⟩
      exact mem_centralizer_singleton_iff.mpr (congrArg Subtype.val (htC e he))
    · exact zpowers_le.mpr (mem_centralizer_singleton_iff.mpr rfl)
  obtain ⟨k, hkS, hkt⟩ := S.transport_centralizing_two_subgroup z hzC (t : G)
    hconj.symm R hp hRC
  have hWk : W.map (MulAut.conj k).toMonoidHom = W :=
    hweak k ((map_mono le_sup_left).trans hkS)
  have hq : (MulAut.conj k) (t : G) ∈ W := hkt ▸ mem_map_of_mem _ hzE
  obtain ⟨w, hw, heq⟩ := mem_map.mp (hWk.symm ▸ hq)
  have hwt : w = (t : G) := (MulAut.conj k).injective heq
  obtain ⟨e, he, het⟩ := mem_map.mp (hwt ▸ hw)
  exact (Subtype.ext het : e = t) ▸ he

/-- Weak closure confines the returning central-involution class to the four
under the normal-only elementary bound. -/
public theorem mem_four_of_isConj_of_weakly_closed_of_no_normal_eight
    (S : Sylow 2 G)
    (hno : ¬ ∃ B : Subgroup S, B.Normal ∧ IsElementaryAbelian 2 B ∧ 8 ≤ Nat.card B)
    (hZ : Nat.card (omega₁ (center S) (p := 2)) = 2)
    (A : Subgroup S) [IsElementaryAbelian 2 A] (hA : 8 ≤ Nat.card A)
    (E : Subgroup S) [E.Normal] [IsElementaryAbelian 2 E] (hE : Nat.card E = 4)
    (hweak : ∀ g : G,
      (E.map (S : Subgroup G).subtype).map (MulAut.conj g).toMonoidHom ≤
        (S : Subgroup G) →
      (E.map (S : Subgroup G).subtype).map (MulAut.conj g).toMonoidHom =
        E.map (S : Subgroup G).subtype)
    (z t : S) (hzC : z ∈ center S) (hz : orderOf z = 2)
    (hconj : IsConj (z : G) (t : G)) : t ∈ E := by
  classical
  have hzE : z ∈ E := omega_one_center_le_normal_four_of_no_normal_eight hno E hE
    (mem_map.mpr ⟨⟨z, hzC⟩, subset_closure (by
      apply Subtype.ext
      simpa [hz] using pow_orderOf_eq_one z), rfl⟩)
  by_cases htC : t ∈ centralizer (E : Set S)
  · exact S.mem_four_of_centralizing_isConj_of_weakly_closed E z hzC hzE hweak t hconj htC
  have ht : orderOf t = 2 := by
    obtain ⟨g, hg⟩ := isConj_iff.mp hconj
    rw [← orderOf_coe t, ← hg]
    change orderOf ((MulAut.conj g) (z : G)) = 2
    exact ((MulAut.conj g).orderOf_eq _).trans ((orderOf_coe z).trans hz)
  obtain ⟨x, hx, hxt⟩ := S.isPGroup'.exists_commuting_square_root_of_noncentral_action_on_normal_four
    hno hZ A hA E hE z t hzC hzE hz ht htC
  let W := E.map (S : Subgroup G).subtype
  let R := zpowers (x : G) ⊔ zpowers (t : G)
  have hRS : R ≤ (S : Subgroup G) :=
    sup_le (zpowers_le.mpr x.property) (zpowers_le.mpr t.property)
  have hp : IsPGroup 2 R :=
    S.isPGroup'.of_injective (inclusion hRS) (inclusion_injective hRS)
  have hRC : R ≤ centralizer ({(t : G)} : Set G) := sup_le
    (zpowers_le.mpr (mem_centralizer_singleton_iff.mpr (congrArg Subtype.val hxt.eq)))
    (zpowers_le.mpr (mem_centralizer_singleton_iff.mpr rfl))
  obtain ⟨k, hkS, hkt⟩ := S.transport_centralizing_two_subgroup z hzC (t : G)
    hconj.symm R hp hRC
  let q := MulAut.conj k
  let v : S := ⟨q (x : G), hkS (mem_map_of_mem _ ((le_sup_left : zpowers (x : G) ≤ R)
    (mem_zpowers (x : G))))⟩
  have hqz : q (z : G) = (v : G) ^ 2 := by
    rw [← hx, Subgroup.coe_pow, map_pow]
  have hvC : v ^ 2 ∈ centralizer (E : Set S) :=
    sq_mem_of_index_two
      (centralizer_index_eq_two_of_normal_four_of_card_omega_one_center_eq_two
        S.isPGroup' hZ E hE) v
  have hvconj : IsConj (z : G) ((v ^ 2 : S) : G) :=
    isConj_iff.mpr ⟨k, hqz⟩
  have hvE : v ^ 2 ∈ E :=
    S.mem_four_of_centralizing_isConj_of_weakly_closed E z hzC hzE hweak (v ^ 2) hvconj hvC
  by_cases htE : t ∈ E
  · exact htE
  have hzt : z ≠ t := fun h => htE (h ▸ hzE)
  let F := closure ({(z : G), (t : G)} : Set G)
  have hFS : F ≤ (S : Subgroup G) := (closure_le _).mpr (by
    intro b hb
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hb
    rcases hb with rfl | rfl
    · exact z.property
    · exact t.property)
  let : IsKleinFour F := isKleinFour_closure_pair_of_orderOf (z : G) (t : G)
    ((orderOf_coe z).trans hz) ((orderOf_coe t).trans ht)
    (fun h => hzt (Subtype.ext h))
    (congrArg Subtype.val (mem_center_iff.mp hzC t).symm)
  have hFW : F.map q.toMonoidHom = W := by
    apply eq_of_le_of_card_ge
    · apply map_le_iff_le_comap.mpr
      apply (closure_le _).mpr
      intro b hb
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hb
      rcases hb with rfl | rfl
      · change q (z : G) ∈ W
        rw [hqz]
        exact mem_map_of_mem _ hvE
      · change q (t : G) ∈ W
        rw [show q (t : G) = z from hkt]
        exact mem_map_of_mem _ hzE
    · have hcF : Nat.card (F.map q.toMonoidHom) = 4 := by
        rw [card_map_of_injective q.injective, IsKleinFour.card_four]
      have hcW : Nat.card W = 4 := by
        rw [card_map_of_injective (S : Subgroup G).subtype_injective, hE]
      omega
  have hWF : W.map (MulAut.conj k⁻¹).toMonoidHom = F := by
    rw [← hFW, map_map]
    have hid : (MulAut.conj k⁻¹).toMonoidHom.comp q.toMonoidHom = MonoidHom.id G := by
      ext b
      simp [q, mul_assoc]
    rw [hid, map_id]
  have hFeq : F = W := hWF.symm.trans (hweak k⁻¹ (hWF ▸ hFS))
  have htW : (t : G) ∈ W := hFeq ▸ subset_closure (by simp : (t : G) ∈ {(z : G), (t : G)})
  obtain ⟨e, he, het⟩ := mem_map.mp htW
  exact (Subtype.ext het : e = t) ▸ he

end Sylow
