module

public import Theory.GroupTheory.NormalizerPCoreWitness
public import Theory.GroupTheory.PGroup.CharacteristicSeriesAutomorphisms
public import Theory.GroupTheory.PGroup.Omega
public import Theory.GroupTheory.CharacteristicCentralizerFusion

/-!
# Normalizer witnesses from involutions and squares

In a finite two-group, an automorphism lies in the automorphism two-core if
its displacements are involutions, its displacements on involutions are
products of squares, and it fixes all squares. Apply the characteristic-series
kernel to
the subgroup generated by involutions and the subgroup generated by squares.
The latter need only be characteristic in the whole group.

The finite certificate interface proves the same conclusion for a normalizer
witness outside a subgroup generated by a finite family. A transition table
certifies an exhaustive list of words, and all further obligations are group
identities on that list. No externally computed group fact is trusted.

Source: the elementary characteristic-series argument in
PGroup.CharacteristicSeriesAutomorphisms.
-/

namespace Subgroup
variable {G : Type*} [Group G]

/-- The involution/square displacement conditions place an automorphism in the two-core. -/
public theorem mem_pCore_of_involution_square_actions [Finite G]
    (hG : IsPGroup 2 G) (f : MulAut G)
    (hdis : ∀ x, (x⁻¹ * f x) ^ 2 = 1)
    (hinv : ∀ x, x ^ 2 = 1 → ∃ w : List G,
      (w.map (fun y => y ^ 2)).prod = x⁻¹ * f x)
    (hsq : ∀ x, f (x ^ 2) = x ^ 2) : f ∈ pCore 2 (MulAut G) := by
  let C := omega₁ G (p := 2)
  let D := closure (Set.range (fun x : G => x ^ 2))
  let : C.Characteristic := omega₁_characteristic G
  let : D.Characteristic := closure_range_pow_characteristic 2
  have hUC : ∀ x, x⁻¹ * f x ∈ C := by
    intro x
    exact subset_closure (by simpa only [Set.mem_ofPred_eq, pow_one] using hdis x)
  have hCD : ∀ x ∈ C, x⁻¹ * f x ∈ D := by
    have hh : C ≤ ((QuotientGroup.mk' D).comp (MonoidHom.id G)).eqLocus
        ((QuotientGroup.mk' D).comp f.toMonoidHom) := by
      apply (closure_le _).mpr
      intro x hx
      obtain ⟨w, hw⟩ := hinv x (by simpa only [Set.mem_ofPred_eq, pow_one] using hx)
      apply QuotientGroup.eq.mpr
      change x⁻¹ * f x ∈ D
      rw [← hw]
      apply list_prod_mem
      intro y hy
      obtain ⟨z, _, rfl⟩ := List.mem_map.mp hy
      exact subset_closure ⟨z, rfl⟩
    exact fun x hx => QuotientGroup.eq.mp (hh hx)
  have hD : ∀ x ∈ D, f x = x := by
    apply MonoidHom.eqOn_closure (f := f.toMonoidHom) (g := MonoidHom.id G)
    rintro _ ⟨x, rfl⟩
    exact hsq x
  have hle : characteristicStepKernel ⊤ C ⊓ characteristicStepKernel C D ⊓
      characteristicStepKernel D ⊥ ≤ pCore 2 (MulAut G) :=
    le_sSup ⟨inferInstance, isPGroup_threeStepKernel hG C D⟩
  apply hle
  refine ⟨⟨fun x _ => hUC x, hCD⟩, ?_⟩
  intro x hx
  change x⁻¹ * f x = 1
  rw [hD x hx, inv_mul_cancel]

/-- An outside normalizer element satisfying the involution/square tests gives a two-core witness. -/
public theorem hasPCoreNormalizerWitness_of_involution_square_actions [Finite G]
    (U : Subgroup G) (hU : IsPGroup 2 U) (g : normalizer (U : Set G))
    (hout : (g : G) ∉ U)
    (hdis : ∀ x ∈ U, (x⁻¹ * ((g : G) * x * (g : G)⁻¹)) ^ 2 = 1)
    (hinv : ∀ x ∈ U, x ^ 2 = 1 → ∃ w : List U,
      (w.map (fun y : U => (y : G) ^ 2)).prod = x⁻¹ * ((g : G) * x * (g : G)⁻¹))
    (hsq : ∀ x ∈ U, (g : G) * (x ^ 2) * (g : G)⁻¹ = x ^ 2) :
    U.HasPCoreNormalizerWitness 2 := by
  refine ⟨g, hout, mem_pCore_of_involution_square_actions hU _ ?_ ?_ ?_⟩
  · intro x
    exact Subtype.ext (hdis x x.property)
  · intro x hx
    obtain ⟨w, hw⟩ := hinv x x.property (congrArg Subtype.val hx)
    refine ⟨w, Subtype.ext ?_⟩
    change (((w.map (fun y => y ^ 2)).prod : U) : G) =
      (x : G)⁻¹ * ((g : G) * (x : G) * (g : G)⁻¹)
    simpa only [Subgroup.val_list_prod, List.map_map, Function.comp_def, Subgroup.coe_pow] using hw
  · intro x
    exact Subtype.ext (hsq x x.property)
end Subgroup

namespace Subgroup
variable {G : Type*} [Group G]

/-- Checked generator and inverse transitions certify that the listed words exhaust the closure. -/
public theorem closure_eq_range_of_word_transitions {m r : ℕ}
    (gen : Fin m → G) (rep : Fin r → G) (words : Fin r → List (Fin m))
    (base : Fin r) (next prev : Fin m → Fin r → Fin r)
    (hword : ∀ a, rep a = (List.map gen (words a)).prod)
    (hbase : rep base = 1)
    (hnext : ∀ i a, gen i * rep a = rep (next i a))
    (hprev : ∀ i a, (gen i)⁻¹ * rep a = rep (prev i a)) :
    (closure (Set.range gen) : Set G) = Set.range rep := by
  ext x
  constructor
  · intro hx
    induction hx using closure_induction_left with
    | one => exact ⟨base, hbase⟩
    | mul_left x hx y _ ih =>
      obtain ⟨i, rfl⟩ := hx
      obtain ⟨a, rfl⟩ := ih
      exact ⟨next i a, (hnext i a).symm⟩
    | inv_mul_cancel x hx y _ ih =>
      obtain ⟨i, rfl⟩ := hx
      obtain ⟨a, rfl⟩ := ih
      exact ⟨prev i a, (hprev i a).symm⟩
  · rintro ⟨a, rfl⟩
    rw [hword]
    apply list_prod_mem
    intro y hy
    obtain ⟨i, _, rfl⟩ := List.mem_map.mp hy
    exact subset_closure ⟨i, rfl⟩

/-- Finite word and action data for an involution-square witness. -/
public structure InvolutionSquareCertificate (G : Type*) (m r : ℕ) where
  rep : Fin r → G
  words : Fin r → List (Fin m)
  base : Fin r
  next : Fin m → Fin r → Fin r
  prev : Fin m → Fin r → Fin r
  outside : G
  conj : Fin r → Fin r
  unconj : Fin r → Fin r
  squareRoots : Fin r → List (Fin r)

/-- The finite identities checked by an involution-square certificate. -/
@[expose] public def InvolutionSquareCertificate.Valid {m r : ℕ}
    (c : InvolutionSquareCertificate G m r) (gen : Fin m → G) : Prop :=
  (∀ a, c.rep a = (List.map gen (c.words a)).prod) ∧
  c.rep c.base = 1 ∧
  (∀ i a, gen i * c.rep a = c.rep (c.next i a)) ∧
  (∀ i a, (gen i)⁻¹ * c.rep a = c.rep (c.prev i a)) ∧
  (∀ a, c.rep a ≠ c.outside) ∧
  (∀ a, c.outside * c.rep a * c.outside⁻¹ = c.rep (c.conj a)) ∧
  (∀ a, c.outside⁻¹ * c.rep a * c.outside = c.rep (c.unconj a)) ∧
  (∀ a, ((c.rep a)⁻¹ * (c.outside * c.rep a * c.outside⁻¹)) ^ 2 = 1) ∧
  (∀ a, (c.rep a) ^ 2 = 1 →
    ((c.squareRoots a).map (fun j => (c.rep j) ^ 2)).prod = (c.rep a)⁻¹ * (c.outside * c.rep a * c.outside⁻¹)) ∧
  ∀ a, c.outside * ((c.rep a) ^ 2) * c.outside⁻¹ = (c.rep a) ^ 2

public instance {m r : ℕ} [DecidableEq G] (c : InvolutionSquareCertificate G m r)
    (gen : Fin m → G) : Decidable (c.Valid gen) :=
  inferInstanceAs (Decidable ((_ : Prop) ∧ (_ : Prop) ∧ (_ : Prop) ∧ (_ : Prop) ∧
    (_ : Prop) ∧ (_ : Prop) ∧ (_ : Prop) ∧ (_ : Prop) ∧ (_ : Prop) ∧ (_ : Prop)))

/-- A valid finite certificate constructs an outside normalizer two-core witness. -/
public theorem InvolutionSquareCertificate.sound [Finite G] {m r : ℕ}
    (hG : IsPGroup 2 G) (c : InvolutionSquareCertificate G m r) (gen : Fin m → G)
    (hc : c.Valid gen) : (closure (Set.range gen)).HasPCoreNormalizerWitness 2 := by
  obtain ⟨hw, hb, hn, hp, hout, hconj, hunconj, hd, hi, hs⟩ := hc
  let U := closure (Set.range gen)
  have he : ∀ x, x ∈ U ↔ ∃ a, c.rep a = x := by
    intro x
    change x ∈ (U : Set G) ↔ _
    rw [show (U : Set G) = Set.range c.rep from
      closure_eq_range_of_word_transitions gen c.rep c.words c.base c.next c.prev hw hb hn hp]
    rfl
  have hnorm : c.outside ∈ normalizer (U : Set G) := by
    intro x
    constructor
    · intro hx
      obtain ⟨a, rfl⟩ := (he x).mp hx
      exact (he _).mpr ⟨c.conj a, (hconj a).symm⟩
    · intro hx
      obtain ⟨a, ha⟩ := (he _).mp hx
      apply (he _).mpr
      refine ⟨c.unconj a, ?_⟩
      rw [← hunconj a, ha]
      simp [mul_assoc]
  apply hasPCoreNormalizerWitness_of_involution_square_actions U (hG.to_subgroup U)
    ⟨c.outside, hnorm⟩
  · rintro hh
    obtain ⟨a, ha⟩ := (he _).mp hh
    exact hout a ha
  · intro x hx
    obtain ⟨a, rfl⟩ := (he _).mp hx
    exact hd a
  · intro x hx hxx
    obtain ⟨a, rfl⟩ := (he _).mp hx
    refine ⟨(c.squareRoots a).map (fun j => (⟨c.rep j, (he _).mpr ⟨j, rfl⟩⟩ : U)), ?_⟩
    simpa only [List.map_map, Function.comp_def] using hi a hxx
  · intro x hx
    obtain ⟨a, rfl⟩ := (he _).mp hx
    exact hs a
end Subgroup
