module

public import Theory.GroupTheory.QuaternionCentralProductCenter
public import Theory.GroupTheory.QuaternionCentralProductFactors
public import Theory.GroupTheory.SpecificGroups.QuaternionEightAut
public import Mathlib.GroupTheory.Index

/-!
# Automorphism orders of a quaternion central product

The automorphism group of a group generated by two commuting quaternion
subgroups with intersection of order two has order dividing 1152. The two
quaternion factors are intrinsic, so a factor stabilizer has index at most
two. Restriction embeds this stabilizer into the product of the automorphism
groups of the factors, each of order 24.

This is the elementary factor-permutation argument for the central product
in Stellmacher (8.6)(a), `refs/latex/stellmacher-n-group.tex`.
-/

namespace Subgroup

open scoped Pointwise

/-- The automorphism order bound from the two intrinsic quaternion factors. -/
public theorem card_mulAut_dvd_of_quaternion_central_product
    {G : Type*} [Group G] [Finite G] (B C : Subgroup G)
    (hB : Nonempty (B ≃* QuaternionGroup 2))
    (hC : Nonempty (C ≃* QuaternionGroup 2))
    (hinter : Nat.card (B ⊓ C : Subgroup G) = 2)
    (hcomm : ∀ b ∈ B, ∀ c ∈ C, b * c = c * b)
    (hjoin : B ⊔ C = ⊤) : Nat.card (MulAut G) ∣ 1152 := by
  classical
  have hne : B ≠ C := by
    intro h
    obtain ⟨e⟩ := hB
    have hcard : Nat.card B = 8 := by
      rw [Nat.card_congr e.toEquiv, Nat.card_eq_fintype_card, QuaternionGroup.card]
    rw [← h, inf_idem, hcard] at hinter
    omega
  have himage (e : MulAut G) (D : Subgroup G)
      (hD : Nonempty (D ≃* QuaternionGroup 2)) :
      D.map e.toMonoidHom = B ∨ D.map e.toMonoidHom = C := by
    obtain ⟨eD⟩ := hD
    exact quaternion_subgroup_eq_factor B C _ hB hC hinter hcomm
      ⟨(e.subgroupMap D).symm.trans eD⟩ (by rw [hjoin]; exact le_top)
  let H := MulAction.stabilizer (MulAut G) B
  have hfixB (e : H) : B.map e.val.toMonoidHom = B := e.property
  have hfixC (e : H) : C.map e.val.toMonoidHom = C := by
    rcases himage e C hC with h | h
    · exact (hne (map_injective e.val.injective ((hfixB e).trans h.symm))).elim
    · exact h
  let restrict (D : Subgroup G) (hD : ∀ e : H, D.map e.val.toMonoidHom = D) :
      H →* MulAut D :=
    { toFun := fun e => (e.val.subgroupMap D).trans (MulEquiv.subgroupCongr (hD e))
      map_one' := by ext x; rfl
      map_mul' := by intro e f; ext x; rfl }
  let f : H →* MulAut B × MulAut C := (restrict B hfixB).prod (restrict C hfixC)
  have hf : Function.Injective f := by
    intro e d heq
    have hBfix : ∀ x ∈ B, e.val x = d.val x := by
      intro x hx
      exact congrArg (fun p : MulAut B × MulAut C => ((p.1 ⟨x, hx⟩ : B) : G)) heq
    have hCfix : ∀ x ∈ C, e.val x = d.val x := by
      intro x hx
      exact congrArg (fun p : MulAut B × MulAut C => ((p.2 ⟨x, hx⟩ : C) : G)) heq
    apply Subtype.ext
    apply MulEquiv.ext
    intro x
    have hx : x ∈ B ⊔ C := by rw [hjoin]; trivial
    exact (show B ⊔ C ≤ e.val.toMonoidHom.eqLocus d.val.toMonoidHom from
      sup_le hBfix hCfix) hx
  have hHcard : Nat.card H ∣ 576 := by
    have hd := card_dvd_of_injective f hf
    obtain ⟨eB⟩ := hB
    obtain ⟨eC⟩ := hC
    rw [Nat.card_prod, Nat.card_congr (MulAut.congr eB).toEquiv,
      Nat.card_congr (MulAut.congr eC).toEquiv,
      QuaternionGroup.card_mulAut_two] at hd
    exact hd
  have hindex : H.index ≤ 2 := by
    rw [MulAction.index_stabilizer]
    have hsubset : MulAction.orbit (MulAut G) B ⊆ {B, C} := by
      rintro D ⟨e, rfl⟩
      exact himage e B hB
    exact (Set.ncard_le_ncard hsubset).trans_eq (Set.ncard_pair hne)
  have hindexDvd : H.index ∣ 2 := by
    have hpos := H.index_ne_zero_of_finite
    have hor : H.index = 1 ∨ H.index = 2 := by omega
    rcases hor with h | h <;> simp [h]
  have hd := Nat.mul_dvd_mul hHcard hindexDvd
  rw [H.card_mul_index] at hd
  exact hd

/-- The same bound for the subgroup generated by the factors inside a larger group. -/
public theorem card_mulAut_join_dvd_of_quaternion_central_product
    {G : Type*} [Group G] [Finite G] (B C : Subgroup G)
    (hB : Nonempty (B ≃* QuaternionGroup 2))
    (hC : Nonempty (C ≃* QuaternionGroup 2))
    (hinter : Nat.card (B ⊓ C : Subgroup G) = 2)
    (hcomm : ∀ b ∈ B, ∀ c ∈ C, b * c = c * b) :
    Nat.card (MulAut (B ⊔ C : Subgroup G)) ∣ 1152 := by
  let J := B ⊔ C
  have hBJ : B ≤ J := le_sup_left
  have hCJ : C ≤ J := le_sup_right
  apply card_mulAut_dvd_of_quaternion_central_product (B.subgroupOf J) (C.subgroupOf J)
  · obtain ⟨e⟩ := hB
    exact ⟨(subgroupOfEquivOfLe hBJ).trans e⟩
  · obtain ⟨e⟩ := hC
    exact ⟨(subgroupOfEquivOfLe hCJ).trans e⟩
  · change Nat.card ((B.comap J.subtype) ⊓ (C.comap J.subtype) : Subgroup J) = 2
    rw [← comap_inf]
    exact (Nat.card_congr (subgroupOfEquivOfLe
      (show B ⊓ C ≤ J from inf_le_left.trans hBJ)).toEquiv).trans hinter
  · intro b hb c hc
    exact Subtype.ext (hcomm b hb c hc)
  · exact (codisjoint_subgroupOf_sup B C).eq_top

/-- A self-centralizing quaternion central product has normalizer order dividing 2304. -/
public theorem normalizer_card_dvd_of_quaternion_central_product
    {G : Type*} [Group G] [Finite G] (B C : Subgroup G)
    (hB : Nonempty (B ≃* QuaternionGroup 2))
    (hC : Nonempty (C ≃* QuaternionGroup 2))
    (hinter : Nat.card (B ⊓ C : Subgroup G) = 2)
    (hcomm : ∀ b ∈ B, ∀ c ∈ C, b * c = c * b)
    (hcentral : centralizer ((B ⊔ C : Subgroup G) : Set G) ≤ B ⊔ C) :
    Nat.card (normalizer ((B ⊔ C : Subgroup G) : Set G)) ∣ 2304 := by
  let X := B ⊔ C
  have hcenter : centralizer (X : Set G) = (center X).map X.subtype := by
    ext x
    constructor
    · intro hx
      refine ⟨⟨x, hcentral hx⟩, mem_center_iff.mpr ?_, rfl⟩
      intro y
      exact Subtype.ext (mem_centralizer_iff.mp hx y y.property)
    · rintro ⟨x, hx, rfl⟩
      intro y hy
      exact congrArg Subtype.val (mem_center_iff.mp hx ⟨y, hy⟩)
  have hcenterCard : Nat.card (centralizer (X : Set G)) = 2 := by
    rw [hcenter, card_map_of_injective X.subtype_injective]
    exact quaternion_central_product_center_card B C hB hC hinter hcomm
  let f := X.normalizerMonoidHom
  have hker : Nat.card f.ker = 2 := by
    rw [normalizerMonoidHom_ker,
      Nat.card_congr (subgroupOfEquivOfLe (centralizer_le_normalizer (X : Set G))).toEquiv]
    exact hcenterCard
  have hrange : Nat.card f.range ∣ 1152 :=
    f.range.card_subgroup_dvd_card.trans
      (card_mulAut_join_dvd_of_quaternion_central_product B C hB hC hinter hcomm)
  have hd := Nat.mul_dvd_mul_left 2 hrange
  have hcount := f.ker.card_mul_index
  rw [index_ker, hker] at hcount
  rw [hcount] at hd
  exact hd

end Subgroup
