module

public import Mathlib.GroupTheory.Sylow
public import Theory.GroupTheory.CharacteristicCentralizerFusion
import Mathlib.Tactic

/-!
# A normalized Sylow three-subgroup of a small centralizer

If an element `r` has order three, its centralizer has order 54, and the
ambient Sylow three-subgroups have order 27, then one such Sylow subgroup
contains `r`, centralizes `r`, and is normalized by the normalizer of `⟨r⟩`.

The centralizer's Sylow three-subgroups have order 27. Their number divides
two and is one modulo three, so there is a unique one. Uniqueness makes it
characteristic and forces it to contain `r`. Its ambient image is Sylow by
comparison of orders. Finally, the normalizer of `⟨r⟩` preserves the
centralizer and hence this characteristic subgroup.

Source: the Sylow-three normalizer argument in W. J. Wong,
*On finite groups whose 2-Sylow subgroups have cyclic subgroups of index 2*
(1964), p.109. The statement is independent of Wong's recognition hypotheses.
-/

namespace Theory.GroupTheory

open Subgroup

/-- The Sylow three-subgroup in an order-54 centralizer is preserved by the
normalizer of the cyclic subgroup generated by the centralizing element. -/
public theorem exists_normalized_sylow_three
    {G : Type*} [Group G] [Finite G]
    (r : G) (hr : orderOf r = 3)
    (hCcard : Nat.card (Subgroup.centralizer ({r} : Set G)) = 54)
    (hPcard : ∀ P : Sylow 3 G, Nat.card P = 27) :
    ∃ P : Sylow 3 G, r ∈ (P : Subgroup G) ∧
      (P : Subgroup G) ≤ Subgroup.centralizer ({r} : Set G) ∧
      Subgroup.normalizer (Subgroup.zpowers r : Set G) ≤
        Subgroup.normalizer (P : Set G) := by
  classical
  let _ : Fact (Nat.Prime 3) := ⟨Nat.prime_three⟩
  let C : Subgroup G := Subgroup.centralizer ({r} : Set G)
  have hQcard : ∀ Q : Sylow 3 C, Nat.card Q = 27 := by
    intro Q
    have h := Q.card_eq_multiplicity
    rw [hCcard] at h
    have hfac : Nat.factorization 54 3 = 3 := by
      rw [show 54 = 2 * 3 ^ 3 by norm_num,
        Nat.factorization_mul (by norm_num) (by norm_num), Nat.factorization_pow]
      norm_num [Nat.prime_two.factorization, Nat.prime_three.factorization]
    rw [hfac] at h
    norm_num at h ⊢
    exact h
  let Q : Sylow 3 C := Classical.choice inferInstance
  have hQcard' : Nat.card Q = 27 := hQcard Q
  have hQidx : Q.index = 2 := by
    have h := Q.card_mul_index
    rw [hQcard', hCcard] at h
    omega
  have hcount : Nat.card (Sylow 3 C) ≤ 2 := by
    have h := Q.card_dvd_index
    rw [hQidx] at h
    exact Nat.le_of_dvd (by omega) h
  have hmod := card_sylow_modEq_one 3 C
  have hnone : Nat.card (Sylow 3 C) = 1 := by
    change Nat.card (Sylow 3 C) % 3 = 1 % 3 at hmod
    omega
  let : Subsingleton (Sylow 3 C) := (Nat.card_eq_one_iff_unique.mp hnone).1
  have hQambientcard : Nat.card ((Q : Subgroup C).map C.subtype) = 27 := by
    rw [← Nat.card_congr ((Q : Subgroup C).equivMapOfInjective
      C.subtype C.subtype_injective).toEquiv]
    exact hQcard'
  obtain ⟨P, hle⟩ := (Q.isPGroup'.map C.subtype).exists_le_sylow
  have hPcoe : (P : Subgroup G) = (Q : Subgroup C).map C.subtype := by
    apply (Subgroup.eq_of_le_of_card_ge hle _).symm
    rw [hQambientcard, hPcard P]
  have hrC : r ∈ C := Subgroup.mem_centralizer_singleton_iff.mpr rfl
  let rC : C := ⟨r, hrC⟩
  have hcyclic : IsPGroup 3 (Subgroup.zpowers rC) := by
    apply IsPGroup.of_card (n := 1)
    rw [Nat.card_zpowers, ← Subgroup.orderOf_coe, hr]
    rfl
  obtain ⟨R, hR⟩ := hcyclic.exists_le_sylow
  have hrQ : rC ∈ (Q : Subgroup C) := by
    rw [← Subsingleton.elim R Q]
    exact hR (Subgroup.mem_zpowers rC)
  have hrP : r ∈ (P : Subgroup G) := by
    rw [hPcoe]
    exact ⟨rC, hrQ, rfl⟩
  have hPC : (P : Subgroup G) ≤ C := by
    rw [hPcoe]
    exact Subgroup.map_subtype_le _
  have hCeq : Subgroup.centralizer (Subgroup.zpowers r : Set G) = C := by
    rw [Subgroup.zpowers_eq_closure, Subgroup.centralizer_closure]
  have hnormP : Subgroup.normalizer (Subgroup.zpowers r : Set G) ≤
      Subgroup.normalizer (P : Set G) := by
    rw [show (P : Set G) = ((Q : Subgroup C).map C.subtype : Set G) from
      congrArg SetLike.coe hPcoe]
    apply le_trans (Subgroup.normalizer_le_normalizer_centralizer (Subgroup.zpowers r))
    rw [hCeq]
    exact Subgroup.normalizer_le_normalizer_characteristic_image C (Q : Subgroup C)
  exact ⟨P, hrP, hPC, hnormP⟩

end Theory.GroupTheory
