module
public import Stellmacher.SectionThree.LemmaThreeFour

/-!
# Local residual generation from a normalized actor image

For a solvable member P of the Section Three local family, let f have kernel
exactly the native two-core. If the distinguished Sylow image normalizes the
cyclic subgroup generated by a nontrivial actor image, that actor generates
the full residual image by commutators. The supplied map and actor are retained;
neither surjectivity onto the codomain nor a residual equality is assumed.

Pull the cyclic subgroup back through f. Its preimage lies in the Sylow
subgroup because the kernel is the two-core, and image normality makes that
preimage Sylow-normal. Apply (3.4), exclude core containment using the
nontrivial actor image, and map the resulting commutator equality forward.

Source: Stellmacher (3.4), printed p.22; the quotient-image transfer used in
(10.1)(13), printed p.63 of `refs/files/stellmacher-n-group.pdf`.
-/

namespace Stellmacher.SectionThree
universe u v

public theorem residual_image_eq_commutator_of_normal_actor
    {G : Type u} [Group G] [Finite G]
    {K : Type v} [Group K]
    (S : Subgroup G) (h : Hypotheses G S)
    (P : Subgroup G) (hP : P ∈ PSet (⊤ : Subgroup G) S)
    (hsolv : Group.IsSolvable P)
    (f : P →* K) (hker : f.ker = pCore 2 P)
    (t : P) (htS : t ∈ S.subgroupOf P) (ht : f t ≠ 1)
    (hnorm : (S.subgroupOf P).map f ≤ Subgroup.normalizer
      (Subgroup.zpowers (f t) : Set K)) :
    ⁅(twoResidualSubgroup P).map f, Subgroup.zpowers (f t)⁆ =
      (twoResidualSubgroup P).map f := by
  classical
  let SP := S.subgroupOf P
  let Y := (Subgroup.zpowers (f t)).comap f
  let N := Y.map P.subtype
  have hSP : S ≤ P := by
    obtain ⟨sylow, hsylow⟩ := hP.1.2.1
    rw [← hsylow]
    exact Subgroup.map_subtype_le _
  have hSPmap : SP.map P.subtype = S := Subgroup.map_subgroupOf_eq_of_le hSP
  have hcoreS : pCore 2 P ≤ SP := by
    obtain ⟨sylow, hsylow⟩ := hP.1.2.1
    have heq : (sylow : Subgroup P) = SP := by
      apply Subgroup.map_injective P.subtype_injective
      exact hsylow.trans hSPmap.symm
    rw [← heq]
    exact IsPGroup.le_sylow_of_normal (pCore_isPGroup (p:=2) (G:=P)) sylow
  have hY : Y = Subgroup.zpowers t ⊔ f.ker := by
    dsimp only [Y]
    rw [← MonoidHom.map_zpowers, Subgroup.comap_map_eq]
  have hYS : Y ≤ SP := by
    rw [hY,hker]
    exact sup_le (Subgroup.zpowers_le.mpr htS) hcoreS
  have hNS : N ≤ S := by
    rw [← hSPmap]
    exact Subgroup.map_mono hYS
  have hNnormalizer : S ≤ Subgroup.normalizer (N : Set G) := by
    apply Subgroup.le_normalizer_iff.mpr
    intro s hs n hn
    obtain ⟨nP, hnP, rfl⟩ := hn
    let sP : P := ⟨s,hSP hs⟩
    refine ⟨sP*nP*sP⁻¹,?_,rfl⟩
    change f (sP*nP*sP⁻¹) ∈ Subgroup.zpowers (f t)
    rw [map_mul,map_mul,map_inv]
    exact (Subgroup.mem_normalizer_iff.mp
      (hnorm (Subgroup.mem_map_of_mem f (show sP ∈ SP from hs))) (f nP)).mp hnP
  have hNnormal : (N.subgroupOf S).Normal :=
    (Subgroup.normal_subgroupOf_iff_le_normalizer hNS).mpr hNnormalizer
  have hcomm : ⁅twoResidualAmbient P,N⁆ = twoResidualAmbient P := by
    rcases lemma_three_four S h P hP N ⟨hNS,hNnormal⟩ hsolv with hbad | hgood
    · have htN : (t:G) ∈ N := Subgroup.mem_map_of_mem P.subtype
        (show t ∈ Y from Subgroup.mem_zpowers (f t))
      obtain ⟨k,hk,hkt⟩ := hbad htN
      have hkt' : k = t := P.subtype_injective hkt
      apply False.elim
      apply ht
      exact MonoidHom.mem_ker.mp (hker.symm ▸ (hkt' ▸ hk))
    · exact hgood
  have hnative : ⁅twoResidualSubgroup P,Y⁆ = twoResidualSubgroup P := by
    apply Subgroup.map_injective P.subtype_injective
    rw [Subgroup.map_commutator]
    exact hcomm
  have hYmap : Y.map f = Subgroup.zpowers (f t) := by
    dsimp only [Y]
    rw [Subgroup.map_comap_eq]
    exact inf_eq_right.mpr (Subgroup.zpowers_le.mpr (show f t ∈ f.range from ⟨t,rfl⟩))
  have hh := congrArg (Subgroup.map f) hnative
  rwa [Subgroup.map_commutator,hYmap] at hh
end Stellmacher.SectionThree
