import Stellmacher.SectionsOneToFourDefs
#print Stellmacher.IsInternalDirectProduct
#print Stellmacher.IsInternalDirectProductFamily
#print Stellmacher.SectionThree.IsMinimalNormalOver
#print Stellmacher.SectionThree.maxLSet
#print Stellmacher.SectionOne.LemmaOneSixConclusion
