module
public import Stellmacher.SectionFiveToSeven.Defs
public import Mathlib.GroupTheory.Coset.Basic
public import Mathlib.Combinatorics.SimpleGraph.Metric

/-!
# Construction of the Section 7 right-coset graph

For a finite group generated by two subgroups, this module constructs the
`CosetGraphContext` used in Sections 5--7. No local 2-group hypotheses are
needed: the parameter `S` is retained for compatibility with that interface.
Vertices are the disjoint union of the two right-coset quotient types, and an
edge joins cosets with a common representative. Right multiplication descends
to both quotients and supplies the stabilizers and the action kernel.

For connectedness, the elements whose first-type coset is reachable from the
identity coset form a subgroup: translate and concatenate walks for products,
and translate and reverse a walk for inverses. This subgroup contains both
generating subgroups, hence every element. Each second-type vertex shares an
edge with a first-type vertex. Mathlib's connected-graph distance then supplies
shortest walks, which are indexed by `Fin`; its triangle inequality bounds
the distance along any indexed path. The remaining subgroup fields are exactly
the definitions stipulated by the context.

Source: `refs/latex/stellmacher-n-group.tex`, the definition at the beginning
of Section 7 and the connectivity assertion in (7.1).
-/

open scoped Pointwise

universe u

namespace Stellmacher.SectionsFiveToSeven

variable {G : Type u} [Group G] (P1 P2 : Subgroup G)

private abbrev RC (P : Subgroup G) := Quotient (QuotientGroup.rightRel P)

private abbrev vertex := RC P1 ⊕ RC P2

private def coset1 (g : G) : vertex P1 P2 := Sum.inl (Quotient.mk _ g)

private def coset2 (g : G) : vertex P1 P2 := Sum.inr (Quotient.mk _ g)

private theorem coset1_eq (g h : G) :
    coset1 P1 P2 g = coset1 P1 P2 h ↔ h * g⁻¹ ∈ P1 := by
  simp only [coset1, Sum.inl.injEq, Quotient.eq, QuotientGroup.rightRel_apply]

private theorem coset2_eq (g h : G) :
    coset2 P1 P2 g = coset2 P1 P2 h ↔ h * g⁻¹ ∈ P2 := by
  simp only [coset2, Sum.inr.injEq, Quotient.eq, QuotientGroup.rightRel_apply]

private def rightMul (P : Subgroup G) (g : G) : RC P → RC P :=
  Quotient.map (fun h => h * g) (by
    intro a b hab
    simpa only [QuotientGroup.rightRel_apply, mul_inv_rev, mul_assoc,
      mul_inv_cancel_left] using hab)

private def act (g : G) : vertex P1 P2 → vertex P1 P2 :=
  Sum.map (rightMul P1 g) (rightMul P2 g)

private theorem vertex_cases (d : vertex P1 P2) :
    ∃ g, d = coset1 P1 P2 g ∨ d = coset2 P1 P2 g := by
  rcases d with d | d
  · obtain ⟨g, rfl⟩ := Quotient.exists_rep d
    exact ⟨g, Or.inl rfl⟩
  · obtain ⟨g, rfl⟩ := Quotient.exists_rep d
    exact ⟨g, Or.inr rfl⟩

private theorem act_one (d : vertex P1 P2) : act P1 P2 1 d = d := by
  obtain ⟨g, rfl | rfl⟩ := vertex_cases P1 P2 d <;>
    simp [act, rightMul, coset1, coset2]

private theorem act_mul (g h : G) (d : vertex P1 P2) :
    act P1 P2 (g * h) d = act P1 P2 h (act P1 P2 g d) := by
  obtain ⟨k, rfl | rfl⟩ := vertex_cases P1 P2 d <;>
    simp [act, rightMul, coset1, coset2, mul_assoc]

private def graph : SimpleGraph (vertex P1 P2) where
  Adj d l := (∃ g, d = coset1 P1 P2 g ∧ l = coset2 P1 P2 g) ∨
    (∃ g, l = coset1 P1 P2 g ∧ d = coset2 P1 P2 g)
  symm := ⟨fun _ _ h => h.symm⟩
  loopless := by
    constructor
    intro d hd
    rcases hd with ⟨g, h1, h2⟩ | ⟨g, h1, h2⟩ <;>
      simpa [coset1, coset2] using h1.symm.trans h2

private theorem common_edge (g : G) :
    (graph P1 P2).Adj (coset1 P1 P2 g) (coset2 P1 P2 g) :=
  Or.inl ⟨g, rfl, rfl⟩

private theorem adjacent_cosets (g h : G) :
    (graph P1 P2).Adj (coset1 P1 P2 g) (coset2 P1 P2 h) ↔
      (MulOpposite.op g • (P1 : Set G)) ∩
        (MulOpposite.op h • (P2 : Set G)) ≠ ∅ := by
  rw [← Set.nonempty_iff_ne_empty]
  constructor
  · rintro (⟨k, h1, h2⟩ | ⟨k, h1, h2⟩)
    · exact ⟨k, (mem_rightCoset_iff _).mpr ((coset1_eq P1 P2 g k).mp h1),
        (mem_rightCoset_iff _).mpr ((coset2_eq P1 P2 h k).mp h2)⟩
    · simp [coset1, coset2] at h1
  · rintro ⟨k, h1, h2⟩
    exact Or.inl ⟨k, (coset1_eq P1 P2 g k).mpr ((mem_rightCoset_iff _).mp h1),
      (coset2_eq P1 P2 h k).mpr ((mem_rightCoset_iff _).mp h2)⟩

private def actHom (g : G) : graph P1 P2 →g graph P1 P2 where
  toFun := act P1 P2 g
  map_rel' := by
    intro d l hadj
    rcases hadj with ⟨h, rfl, rfl⟩ | ⟨h, rfl, rfl⟩
    · exact Or.inl ⟨h * g, rfl, rfl⟩
    · exact Or.inr ⟨h * g, rfl, rfl⟩

private theorem connected (hgenerated : P1 ⊔ P2 = ⊤) :
    (graph P1 P2).Connected := by
  let K : Subgroup G :=
    { carrier := {g | (graph P1 P2).Reachable (coset1 P1 P2 1) (coset1 P1 P2 g)}
      one_mem' := .rfl
      mul_mem' := by
        intro g h hg hh
        have hmap := hg.map (actHom P1 P2 h)
        change (graph P1 P2).Reachable (coset1 P1 P2 (1 * h))
          (coset1 P1 P2 (g * h)) at hmap
        exact hh.trans (by simpa only [one_mul] using hmap)
      inv_mem' := by
        intro g hg
        change (graph P1 P2).Reachable _ _
        have hmap := hg.map (actHom P1 P2 g⁻¹)
        change (graph P1 P2).Reachable (coset1 P1 P2 (1 * g⁻¹))
          (coset1 P1 P2 (g * g⁻¹)) at hmap
        simpa only [one_mul, mul_inv_cancel] using hmap.symm }
  have h1 : P1 ≤ K := by
    intro g hg
    change (graph P1 P2).Reachable _ _
    have heq : coset1 P1 P2 1 = coset1 P1 P2 g :=
      (coset1_eq P1 P2 1 g).mpr (by simpa using hg)
    rw [heq]
  have h2 : P2 ≤ K := by
    intro g hg
    change (graph P1 P2).Reachable _ _
    have heq : coset2 P1 P2 1 = coset2 P1 P2 g :=
      (coset2_eq P1 P2 1 g).mpr (by simpa using hg)
    exact ((common_edge P1 P2 1).reachable.trans
      (heq ▸ (common_edge P1 P2 g).reachable.symm))
  have htop : (⊤ : Subgroup G) ≤ K := hgenerated ▸ sup_le h1 h2
  have hall (d : vertex P1 P2) :
      (graph P1 P2).Reachable (coset1 P1 P2 1) d := by
    obtain ⟨g, rfl | rfl⟩ := vertex_cases P1 P2 d
    · exact htop (Subgroup.mem_top g)
    · exact (htop (Subgroup.mem_top g)).trans (common_edge P1 P2 g).reachable
  let : Nonempty (vertex P1 P2) := ⟨coset1 P1 P2 1⟩
  exact ⟨fun d l => (hall d).symm.trans (hall l)⟩

private def stabilizer (d : vertex P1 P2) : Subgroup G where
  carrier := {g | act P1 P2 g d = d}
  one_mem' := act_one P1 P2 d
  mul_mem' := by
    intro g h hg hh
    change act P1 P2 (g * h) d = d
    rw [act_mul, hg, hh]
  inv_mem' := by
    intro g hg
    change act P1 P2 g⁻¹ d = d
    have heq := act_mul P1 P2 g g⁻¹ d
    rw [mul_inv_cancel, act_one, hg] at heq
    exact heq.symm

private theorem distance_path (hgenerated : P1 ⊔ P2 = ⊤) (d l : vertex P1 P2) :
    ∃ f : Fin ((graph P1 P2).dist d l + 1) → vertex P1 P2,
      f 0 = d ∧ f (Fin.last ((graph P1 P2).dist d l)) = l ∧
      ∀ i : Fin ((graph P1 P2).dist d l),
        (graph P1 P2).Adj (f i.castSucc) (f i.succ) := by
  obtain ⟨w, hw⟩ := (connected P1 P2 hgenerated).exists_walk_length_eq_dist d l
  refine ⟨fun i => w.getVert i, w.getVert_zero, ?_, ?_⟩
  · simpa only [Fin.val_last, ← hw] using w.getVert_length
  · intro i
    exact w.adj_getVert_succ (by simp [hw])

private theorem distance_le_of_path (hgenerated : P1 ⊔ P2 = ⊤)
    (n : ℕ) (f : Fin (n + 1) → vertex P1 P2)
    (hf : ∀ i : Fin n, (graph P1 P2).Adj (f i.castSucc) (f i.succ)) :
    (graph P1 P2).dist (f 0) (f (Fin.last n)) ≤ n := by
  induction n with
  | zero => simp [SimpleGraph.dist_self]
  | succ n ih =>
    calc
      (graph P1 P2).dist (f 0) (f (Fin.last (n + 1))) ≤
          (graph P1 P2).dist (f 0) (f (Fin.last n).castSucc) +
          (graph P1 P2).dist (f (Fin.last n).castSucc) (f (Fin.last (n + 1))) :=
        (connected P1 P2 hgenerated).dist_triangle
      _ ≤ n + 1 := Nat.add_le_add
        (ih (fun i => f i.castSucc) (fun i => hf i.castSucc))
        (le_of_eq (SimpleGraph.dist_eq_one_iff_adj.mpr (hf (Fin.last n))))

public theorem exists_cosetGraphContext [Finite G] (S P1 P2 : Subgroup G)
    (hgenerated : P1 ⊔ P2 = ⊤) : Nonempty (CosetGraphContext.{u,u} G S P1 P2) := by
  classical
  let Q := stabilizer P1 P2
  let neighbors := fun d => {l | (graph P1 P2).dist l d = 1}
  let Z := fun d => sSup {Z : Subgroup G | ∃ T : Sylow 2 (Q d),
    Z = omegaOneCenter ((T : Subgroup (Q d)).map (Q d).subtype)}
  refine ⟨{
    Vertex := vertex P1 P2
    adjacent := (graph P1 P2).Adj
    adjacent_symm := fun h => h.symm
    act := act P1 P2
    act_one := act_one P1 P2
    act_mul := act_mul P1 P2
    coset₁ := coset1 P1 P2
    coset₂ := coset2 P1 P2
    coset₁_surjective := vertex_cases P1 P2
    coset₁_eq_iff := fun g h => (coset1_eq P1 P2 g h).trans (rightCoset_eq_iff P1).symm
    coset₂_eq_iff := fun g h => (coset2_eq P1 P2 g h).trans (rightCoset_eq_iff P2).symm
    act_coset₁ := fun _ _ => rfl
    act_coset₂ := fun _ _ => rfl
    adj_cosets := adjacent_cosets P1 P2
    no_adj_coset₁_coset₁ := ?_
    no_adj_coset₂_coset₂ := ?_
    vertexStabilizer := Q
    stabilizer_def := fun _ => rfl
    distance := (graph P1 P2).dist
    distance_refl := fun _ => SimpleGraph.dist_self
    distance_symm := fun _ _ => SimpleGraph.dist_comm
    distance_zero_iff := fun _ _ => (connected P1 P2 hgenerated).dist_eq_zero_iff
    distance_path := distance_path P1 P2 hgenerated
    distance_le_of_path := distance_le_of_path P1 P2 hgenerated
    neighbors := neighbors
    neighbors_def := fun _ => rfl
    twoCoreAt := fun d => twoCoreIn (Q d)
    twoCoreAt_def := fun _ => rfl
    twoResidualAt := fun d => twoResidualIn (Q d)
    twoResidualAt_def := fun _ => rfl
    zAt := Z
    zAt_def := fun _ => rfl
    vAt := fun d => sSup {Z' : Subgroup G | ∃ l ∈ neighbors d, Z' = Z l}
    vAt_def := fun _ => rfl
    actionKernel := ⨅ d, Q d
    actionKernel_def := ?_
  }⟩
  · intro g h hadj
    rcases hadj with ⟨k, _, heq⟩ | ⟨k, _, heq⟩ <;>
      simp [coset1, coset2] at heq
  · intro g h hadj
    rcases hadj with ⟨k, heq, _⟩ | ⟨k, heq, _⟩ <;>
      simp [coset1, coset2] at heq
  · intro g
    simp only [Subgroup.mem_iInf]
    rfl

end Stellmacher.SectionsFiveToSeven
