module

public import Stellmacher.SectionTwo.LemmaTwoTwo

/-!
# The source-defined quotient endpoint in Stellmacher (5.2)

The final quotient in Stellmacher (5.2) is formed from a normal elementary
abelian subgroup `V` generated by the conjugates of `Omega_1(Z(T0))`, where
`T0` is an ambient Sylow subgroup.  It need not be the Section 2 subgroup
`vSubgroup SM` attached to a Sylow subgroup of the local group `M`.  This
module therefore proves the exact part of (2.2) used in (5.2) directly for an
arbitrary normal elementary abelian `V <= O_2(M)` whose centralizer quotient
has trivial 2-core.

The proof installs the faithful conjugation action of `M/C_M(V)` on `V`.
Images of maximum-order elementary abelian subgroups of `SM` are offenders by
the generic cardinal inequality.  The selected-product form of (1.7), weak
closure of the elementary Thompson subgroup, and the Baumann fixed-point
argument give a normal direct product of `SL_2(2)` factors and identify the
Baumann and Thompson images.  A subgroup equal to its commutator with that
image lies in the derived subgroup of this product, hence in `O_3` and has
trivial 2-core.

The source assembly supplies the explicit quotient-core premise from the
pullback argument following (5.2)(7), and transports the native Thompson and
Baumann subgroups from the chosen ambient Sylow subgroup.  No equality with
`vSubgroup SM` or `cSubgroup SM` is assumed.

Source: B. Stellmacher, *An Application of the Amalgam Method: The 2-Local
Structure of N-Groups of Characteristic 2 Type*, Journal of Algebra 190
(1997), proof of Lemma (5.2), pp. 28--29.
-/

open scoped BigOperators Pointwise commutatorElement

namespace Stellmacher.SectionsFiveToSeven

universe u

private noncomputable abbrev sourceQuotientConjugationAction
    {G : Type u} [Group G] (V : Subgroup G) [V.Normal]
    {barG : Type u} [Group barG] (q : G →* barG)
    (hq : Function.Surjective q)
    (hker : q.ker = Subgroup.centralizer (V : Set G)) :
    MulDistribMulAction barG V := by
  classical
  let act : G →* MulAut V := MulAut.conjNormal
  have hact : q.ker ≤ act.ker := by
    intro g hg
    rw [hker] at hg
    rw [Subgroup.mem_centralizer_iff] at hg
    apply MulEquiv.ext
    intro x
    apply Subtype.ext
    change g * (x : G) * g⁻¹ = x
    rw [← hg x x.property, mul_inv_cancel_right]
  exact MulDistribMulAction.compHom V
    (q.liftOfSurjective hq ⟨act, hact⟩)

private theorem sourceQuotientConjugationAction_smul_coe
    {G : Type u} [Group G] (V : Subgroup G) [V.Normal]
    {barG : Type u} [Group barG] (q : G →* barG)
    (hq : Function.Surjective q)
    (hker : q.ker = Subgroup.centralizer (V : Set G))
    (g : G) (x : V) :
    letI := sourceQuotientConjugationAction V q hq hker
    ((q g • x : V) : G) = g * (x : G) * g⁻¹ := by
  change (((q.liftOfSurjective hq _ : barG →* MulAut V) (q g)) x : G) = _
  rw [MonoidHom.liftOfRightInverse_comp_apply]
  rfl

private theorem sourceQuotientConjugationAction_faithful
    {G : Type u} [Group G] (V : Subgroup G) [V.Normal]
    {barG : Type u} [Group barG] (q : G →* barG)
    (hq : Function.Surjective q)
    (hker : q.ker = Subgroup.centralizer (V : Set G)) :
    letI := sourceQuotientConjugationAction V q hq hker
    fixingSubgroup barG (Set.univ : Set V) = ⊥ := by
  let := sourceQuotientConjugationAction V q hq hker
  apply bot_unique
  intro b hb
  obtain ⟨g, rfl⟩ := hq b
  have hg : g ∈ q.ker := by
    rw [hker]
    rw [Subgroup.mem_centralizer_iff]
    intro x hx
    rw [mem_fixingSubgroup_iff] at hb
    have hfix := hb ⟨x, hx⟩ (Set.mem_univ _)
    have heq := congrArg Subtype.val hfix
    rw [sourceQuotientConjugationAction_smul_coe V q hq hker] at heq
    exact (mul_inv_eq_iff_eq_mul.mp heq).symm
  exact hg

private theorem sourceQuotientConjugationAction_fixedPoints_image_map
    {G : Type u} [Group G] (V : Subgroup G) [V.Normal]
    {barG : Type u} [Group barG] (q : G →* barG)
    (hq : Function.Surjective q)
    (hker : q.ker = Subgroup.centralizer (V : Set G))
    (A : Subgroup G) :
    letI := sourceQuotientConjugationAction V q hq hker
    (FixedPoints.subgroup (A.map q) V).map V.subtype =
      V ⊓ Subgroup.centralizer (A : Set G) := by
  let := sourceQuotientConjugationAction V q hq hker
  ext x
  constructor
  · rintro ⟨y, hy, rfl⟩
    refine ⟨y.property, ?_⟩
    change (y : G) ∈ Subgroup.centralizer (A : Set G)
    rw [Subgroup.mem_centralizer_iff]
    intro a ha
    have hfix := (FixedPoints.mem_subgroup (M := A.map q) (a := y)).mp hy
      ⟨q a, Subgroup.mem_map_of_mem q ha⟩
    change q a • y = y at hfix
    have heq := congrArg Subtype.val hfix
    rw [sourceQuotientConjugationAction_smul_coe V q hq hker] at heq
    exact mul_inv_eq_iff_eq_mul.mp heq
  · rintro ⟨hxV, hxA⟩
    refine ⟨⟨x, hxV⟩, ?_, rfl⟩
    change (⟨x, hxV⟩ : V) ∈ FixedPoints.subgroup (A.map q) V
    rw [FixedPoints.mem_subgroup]
    intro a
    obtain ⟨a₀, ha₀, heq⟩ := a.property
    apply Subtype.ext
    change ((a.val • (⟨x, hxV⟩ : V) : V) : G) = x
    rw [← heq, sourceQuotientConjugationAction_smul_coe V q hq hker]
    change x ∈ Subgroup.centralizer (A : Set G) at hxA
    rw [Subgroup.mem_centralizer_iff] at hxA
    rw [hxA a₀ ha₀, mul_inv_cancel_right]

private theorem sourceQuotientConjugationAction_fixedPoints_card
    {G : Type u} [Group G] (V : Subgroup G) [V.Normal]
    {barG : Type u} [Group barG] (q : G →* barG)
    (hq : Function.Surjective q)
    (hker : q.ker = Subgroup.centralizer (V : Set G))
    (A : Subgroup G) :
    letI := sourceQuotientConjugationAction V q hq hker
    Nat.card (FixedPoints.subgroup (A.map q) V) =
      Nat.card (V ⊓ Subgroup.centralizer (A : Set G) : Subgroup G) := by
  let := sourceQuotientConjugationAction V q hq hker
  rw [← sourceQuotientConjugationAction_fixedPoints_image_map V q hq hker A,
    Subgroup.card_map_of_injective V.subtype_injective]

private theorem sourceMaxElementary_map_mem_oneA
    {G : Type u} [Group G] [Finite G]
    (S : Sylow 2 G) (V : Subgroup G) [V.Normal] [IsElementaryAbelian 2 V]
    (hVS : V ≤ (S : Subgroup G))
    {barG : Type u} [Group barG] [Finite barG]
    (q : G →* barG) (hq : Function.Surjective q)
    (hker : q.ker = Subgroup.centralizer (V : Set G))
    (A : Subgroup G)
    (hA : A ∈ elementaryAbelianMaxSubgroups (S : Subgroup G)) :
    letI := sourceQuotientConjugationAction V q hq hker
    SectionOne.oneA (V := V) ((S : Subgroup G).map q) (A.map q) := by
  let := sourceQuotientConjugationAction V q hq hker
  have hbound := maxElementary_card_le_fixed_mul_image
    (S : Subgroup G) V A hVS hA q hker
  rw [← sourceQuotientConjugationAction_fixedPoints_card V q hq hker A] at hbound
  refine ⟨Subgroup.map_mono hA.1, hA.2.1.map q, ?_⟩
  unfold SectionOne.m
  have hpos : 0 < (Nat.card (FixedPoints.subgroup (A.map q) V) : ℚ) *
      (Nat.card (A.map q) : ℚ) := by
    exact_mod_cast Nat.mul_pos Nat.card_pos Nat.card_pos
  apply (div_le_one hpos).mpr
  exact_mod_cast hbound

private theorem sourceBaumann_image_fixes_thompson_fixedPoints
    {G : Type u} [Group G] [Finite G]
    (S : Sylow 2 G) (V : Subgroup G) [V.Normal] [IsElementaryAbelian 2 V]
    (hVS : V ≤ (S : Subgroup G))
    {barG : Type u} [Group barG] [Finite barG]
    (q : G →* barG) (hq : Function.Surjective q)
    (hker : q.ker = Subgroup.centralizer (V : Set G))
    (B : Subgroup G)
    (hB : B ≤ Subgroup.centralizer
      (omegaOneCenterAmbient (elementaryAbelianMaxJ (S : Subgroup G)) : Set G)) :
    letI := sourceQuotientConjugationAction V q hq hker
    B.map q ≤ fixingSubgroup barG
      (FixedPoints.subgroup ((elementaryAbelianMaxJ (S : Subgroup G)).map q) V : Set V) := by
  let := sourceQuotientConjugationAction V q hq hker
  rintro b ⟨b₀, hb₀, rfl⟩
  rw [mem_fixingSubgroup_iff]
  intro v hv
  have hvC : (v : G) ∈ Subgroup.centralizer
      (elementaryAbelianMaxJ (S : Subgroup G) : Set G) := by
    rw [Subgroup.mem_centralizer_iff]
    intro j hj
    have hfix := (FixedPoints.mem_subgroup
      (M := (elementaryAbelianMaxJ (S : Subgroup G)).map q) (a := v)).mp hv
      ⟨q j, Subgroup.mem_map_of_mem q hj⟩
    change q j • v = v at hfix
    have heq := congrArg Subtype.val hfix
    rw [sourceQuotientConjugationAction_smul_coe V q hq hker] at heq
    exact mul_inv_eq_iff_eq_mul.mp heq
  let : IsElementaryAbelian 2 (Subgroup.zpowers (v : G)) :=
    IsElementaryAbelian.zpowers_of_pow_eq_one
      (elemPow_eq_one_of_isElementaryAbelian (p := 2) (v : G) v.property)
  have hvOmega : (v : G) ∈
      omegaOneCenterAmbient (elementaryAbelianMaxJ (S : Subgroup G)) :=
    elementary_centralizer_maxJ_le_omegaCenter (S : Subgroup G)
      (Subgroup.zpowers (v : G))
      (Subgroup.zpowers_le.mpr (hVS v.property))
      (Subgroup.zpowers_le.mpr hvC) (Subgroup.mem_zpowers (v : G))
  apply Subtype.ext
  rw [sourceQuotientConjugationAction_smul_coe V q hq hker]
  have hcomm := Subgroup.mem_centralizer_iff.mp (hB hb₀) v hvOmega
  rw [← hcomm, mul_inv_cancel_right]

private theorem sourceSL2_commutator_cube
    {H : Type u} [Group H] [Finite H] (h : IsSL2Two H)
    (x : H) (hx : x ∈ commutator H) : x ^ 3 = 1 := by
  obtain ⟨e⟩ := h
  have hmul : ∀ a b : Matrix.SpecialLinearGroup (Fin 2) (ZMod 2),
      a ^ 3 = 1 → b ^ 3 = 1 → (a * b) ^ 3 = 1 := by
    decide +kernel
  have hcomm : ∀ a b : Matrix.SpecialLinearGroup (Fin 2) (ZMod 2),
      ⁅a, b⁆ ^ 3 = 1 := by
    decide +kernel
  let C : Subgroup H :=
    { carrier := {x | (e x) ^ 3 = 1}
      one_mem' := by simp
      mul_mem' := by intro a b ha hb; simpa using hmul (e a) (e b) ha hb
      inv_mem' := by intro a ha; simp_all [inv_pow] }
  have hle : commutator H ≤ C := by
    rw [commutator_def, Subgroup.commutator_le]
    intro a _ b _
    change e ⁅a, b⁆ ^ 3 = 1
    rw [map_commutatorElement]
    exact hcomm _ _
  have hcube : e x ^ 3 = 1 := hle hx
  exact e.injective (by simpa using hcube)

private theorem sourceInternalSL2Product_commutator_isPGroup_three
    {G : Type u} [Group G] [Finite G]
    {n : ℕ} (E : Subgroup G) (D : Fin n → Subgroup G)
    (hprod : IsInternalDirectProductFamily E D)
    (hSL : ∀ i, IsSL2Two (D i)) :
    IsPGroup 3 (commutator E) := by
  classical
  let P := ∀ i : Fin n, (D i)
  have hcomm : Pairwise (fun i j : Fin n => ∀ x y : G,
      x ∈ D i → y ∈ D j → Commute x y) := by
    intro i j hij x y hx hy
    exact hprod.2.2 i j hij x hx y hy
  let f : P →* G := Subgroup.noncommPiCoprod hcomm
  have hf : f.range = E := (Subgroup.noncommPiCoprod_range).trans hprod.1.symm
  have hmap : (commutator P).map f = (commutator E).map E.subtype := by
    rw [map_commutator_eq, hf, Subgroup.map_subtype_commutator]
  have hPp : IsPGroup 3 (commutator P) := by
    intro x
    refine ⟨1, ?_⟩
    apply Subtype.ext
    funext i
    have heval : (x : P) i ∈ commutator (D i) := by
      have hm := Subgroup.mem_map_of_mem
        (Pi.evalMonoidHom (fun i : Fin n => (D i)) i) x.property
      rw [map_commutator_eq] at hm
      exact Subgroup.commutator_mono le_top le_top hm
    exact sourceSL2_commutator_cube (hSL i) _ heval
  have himage : IsPGroup 3 ((commutator E).map E.subtype) := by
    rw [← hmap]
    exact hPp.map f
  exact himage.of_equiv
    ((commutator E).equivMapOfInjective E.subtype E.subtype_injective).symm

private theorem sourceLocalQuotientEndpoint
    {G : Type u} [Group G] [Finite G]
    (S : Sylow 2 G) (V : Subgroup G)
    (hVnormal : V.Normal) (hVelem : IsElementaryAbelian 2 V)
    (hVS : V ≤ (S : Subgroup G))
    (hsolv : Group.IsSolvable G)
    {barG : Type u} [Group barG] [Finite barG]
    (q : G →* barG) (hq : Function.Surjective q)
    (hker : q.ker = Subgroup.centralizer (V : Set G))
    (hcore : pCore 2 barG = ⊥)
    (B : Subgroup G)
    (hB : B = (S : Subgroup G) ⊓
      Subgroup.centralizer
        (omegaOneCenterAmbient (elementaryAbelianMaxJ (S : Subgroup G)) : Set G))
    (hJne : (elementaryAbelianMaxJ (S : Subgroup G)).map q ≠ ⊥)
    (K : Subgroup barG) (hcomm : K = ⁅K, B.map q⁆) :
    K ≤ pCore 3 barG ∧ pCore 2 K = ⊥ := by
  classical
  let _ : V.Normal := hVnormal
  let _ : IsElementaryAbelian 2 V := hVelem
  let _ : Group.IsSolvable G := hsolv
  let := sourceQuotientConjugationAction V q hq hker
  let T : Sylow 2 barG := S.mapSurjective hq
  let J := (elementaryAbelianMaxJ (S : Subgroup G)).map q
  let E := ⁅SectionOne.oddCore barG, J⁆ ⊔ J
  have hJS : J ≤ (T : Subgroup barG) := by
    apply Subgroup.map_mono
    exact sSup_le fun A hA => hA.1
  have hSne : (T : Subgroup barG) ≠ ⊥ := by
    intro hbot
    apply hJne
    exact bot_unique (hbot ▸ hJS)
  have heven : Even (Nat.card barG) := by
    have htwo : 2 ∣ Nat.card T := by
      rcases T.isPGroup'.card_eq_or_dvd with hone | htwo
      · exact False.elim (hSne ((Subgroup.eq_bot_iff_card _).mpr hone))
      · exact htwo
    exact even_iff_two_dvd.mpr
      (htwo.trans (T : Subgroup barG).card_subgroup_dvd_card)
  have h1 : SectionOne.Hypotheses barG V :=
    ⟨Group.isSolvable_of_surjective hq, heven,
      sourceQuotientConjugationAction_faithful V q hq hker, hcore⟩
  let I := {A : Subgroup G // A ∈ elementaryAbelianMaxSubgroups (S : Subgroup G)}
  let A : I → Subgroup barG := fun a => a.val.map q
  have hA : ∀ a, SectionOne.oneA (V := V) (T : Subgroup barG) (A a) :=
    fun a => sourceMaxElementary_map_mem_oneA S V hVS q hq hker a.val a.property
  have hJgen : J = ⨆ a, A a := by
    apply le_antisymm
    · apply Subgroup.map_le_iff_le_comap.mpr
      apply sSup_le
      intro a ha
      exact Subgroup.map_le_iff_le_comap.mp (le_iSup A (⟨a, ha⟩ : I))
    · exact iSup_le fun a => Subgroup.map_mono (le_sSup a.property)
  obtain ⟨hJinf, hEN, hEnorm, n, D, hprod, hDin, hD, hDN, hmodule⟩ :=
    SectionOne.offender_generated_selected_product h1 T A hA J hJgen
  change IsInternalDirectProductFamily E D at hprod
  let N := SectionOne.oneSevenGenerated (G := barG) (V := V)
  let : N.Normal := (SectionOne.oneSeven_global_product h1 T).1
  have hJN : J ≤ N := (show J ≤ E from le_sup_right).trans hEN
  have hweak : ∀ b : barG, J.map (MulAut.conj b).toMonoidHom ≤ (T : Subgroup barG) →
      J.map (MulAut.conj b).toMonoidHom = J := by
    intro b hb
    exact weakly_closed_map_of_surjective S (elementaryAbelianMaxJ (S : Subgroup G))
      (sSup_le fun a ha => ha.1)
      (fun g hg => elementaryAbelianMaxJ_map_eq_of_le
        (S : Subgroup G) (MulAut.conj g) hg)
      q hq b hb
  have hNE : N ≤ Subgroup.normalizer (E : Set barG) :=
    (Subgroup.normal_subgroupOf_iff_le_normalizer hEN).mp hEnorm
  have hJE : Subgroup.normalizer (J : Set barG) ≤
      Subgroup.normalizer (E : Set barG) := by
    let W := SectionOne.oddCore barG
    let : W.Normal := pPrimeCore_normal
    intro b hb
    rw [Subgroup.mem_normalizer_iff_map_conj_eq]
    have hW : W.map (MulAut.conj b).toMonoidHom = W :=
      Subgroup.mem_normalizer_iff_map_conj_eq.mp
        (show b ∈ Subgroup.normalizer (W : Set barG) by
          rw [Subgroup.normalizer_eq_top]
          trivial)
    have hJ : J.map (MulAut.conj b).toMonoidHom = J :=
      Subgroup.mem_normalizer_iff_map_conj_eq.mp hb
    change (⁅W, J⁆ ⊔ J).map (MulAut.conj b).toMonoidHom = ⁅W, J⁆ ⊔ J
    rw [Subgroup.map_sup, Subgroup.map_commutator, hW, hJ]
  have hEnormal : E.Normal := normal_of_normalized_by_normal_and_weakly_closed_normalizer
    T N J E hJS hJN hweak hNE hJE
  have hJcard : Nat.card J = 2 ^ n := by
    rw [hJinf]
    exact SectionOne.sl2_family_sylow_inf_card T E hEnormal D hDin hprod
      (fun i => (hD i).1) hDN
  have hBcent : B ≤ Subgroup.centralizer
      (omegaOneCenterAmbient (elementaryAbelianMaxJ (S : Subgroup G)) : Set G) := by
    rw [hB]
    exact inf_le_right
  have hBfix : B.map q ≤ fixingSubgroup barG
      (FixedPoints.subgroup J V : Set V) :=
    sourceBaumann_image_fixes_thompson_fixedPoints S V hVS q hq hker B hBcent
  have hJp : IsPGroup 2 J := T.isPGroup'.to_le hJS
  have hBnorm (i : Fin n) : B.map q ≤ Subgroup.normalizer (D i : Set barG) := by
    have hDE : D i ≤ E := by rw [hprod.1]; exact le_iSup D i
    have hJnorm : J ≤ Subgroup.normalizer (D i : Set barG) :=
      (show J ≤ E from le_sup_right).trans
        ((Subgroup.normal_subgroupOf_iff_le_normalizer hDE).mp (hDN i))
    exact hBfix.trans
      (SectionOne.oneSevenFactor_fixedSpace_normalizes h1 (D i) J
        (hD i) hJp hJnorm)
  have hBfixE : B.map q ≤ fixingSubgroup barG
      (FixedPoints.subgroup E V : Set V) := by
    intro b hb
    rw [mem_fixingSubgroup_iff]
    intro v hv
    apply (mem_fixingSubgroup_iff (M := barG)).mp (hBfix hb) v
    change v ∈ FixedPoints.subgroup J V
    rw [FixedPoints.mem_subgroup]
    intro j
    exact (FixedPoints.mem_subgroup (M := E) (a := v)).mp hv
      ⟨j, (show J ≤ E from le_sup_right) j.property⟩
  have hBp : IsPGroup 2 (B.map q) :=
    (S.isPGroup'.to_le (show B ≤ (S : Subgroup G) by rw [hB]; exact inf_le_left)).map q
  have hBcard := SectionOne.moduleProduct_card_bound h1 (B.map q) E D hBnorm
    hmodule hBfixE hBp (fun i => (hD i).2.2.1)
  have hJBoriginal : elementaryAbelianMaxJ (S : Subgroup G) ≤ B := by
    rw [hB]
    refine le_inf (sSup_le fun a ha => ha.1) ?_
    intro j hj
    rw [Subgroup.mem_centralizer_iff]
    intro z hz
    exact ((mem_omegaOneCenterAmbient_iff _ _).mp hz).2.2 j hj |>.symm
  have hJB : J = B.map q := Subgroup.eq_of_le_of_card_ge
    (Subgroup.map_mono hJBoriginal) (by rwa [hJcard])
  have hBle : B.map q ≤ E := by
    rw [← hJB]
    exact le_sup_right
  have hKleE : K ≤ E := by
    rw [hcomm]
    exact (Subgroup.commutator_mono le_rfl hBle).trans
      (Subgroup.commutator_le_right K E)
  have hKleDerived : K ≤ (commutator E).map E.subtype := by
    rw [Subgroup.map_subtype_commutator]
    rw [hcomm]
    exact Subgroup.commutator_mono hKleE hBle
  have hderived : IsPGroup 3 (commutator E) :=
    sourceInternalSL2Product_commutator_isPGroup_three E D hprod
      (fun i => (hD i).1)
  let R : Subgroup barG := (commutator E).map E.subtype
  have hRthree : IsPGroup 3 R := hderived.map E.subtype
  have hRnormal : R.Normal := by
    change ((commutator E).map E.subtype).Normal
    rw [Subgroup.map_subtype_commutator]
    infer_instance
  have hRcore : R ≤ pCore 3 barG := le_sSup ⟨hRnormal, hRthree⟩
  have hKthree : IsPGroup 3 K := hRthree.to_le hKleDerived
  constructor
  · exact hKleDerived.trans hRcore
  · have htopThree : IsPGroup 3 (⊤ : Subgroup K) :=
      hKthree.of_equiv Subgroup.topEquiv.symm
    have hdis : Disjoint (pCore 2 K) (⊤ : Subgroup K) :=
      IsPGroup.disjoint_of_ne 2 3 (by decide) _ _ pCore_isPGroup htopThree
    simpa only [disjoint_top] using hdis

/-- The source-defined centralizer quotient in Stellmacher (5.2) has the
required odd-core endpoint.  Normality of `C0` is an instance because it is
needed to form the canonical quotient; at the source application it follows
immediately from `hC0` and normality of `V`. -/
public theorem five_two_source_local_quotient_endpoint
    {M : Type u} [Group M] [Finite M]
    (SM : Sylow 2 M) (V C0 B K : Subgroup M)
    [hVnormal : V.Normal] (hVelem : IsElementaryAbelian 2 V)
    (hVcore : V ≤ pCore 2 M)
    (hC0 : C0 = Subgroup.centralizer (V : Set M))
    [hC0normal : C0.Normal]
    (hM : SectionTwo.Hypotheses M)
    (hWbar : pCore 2 (M ⧸ C0) = ⊥)
    (hB : B = (SM : Subgroup M) ⊓
      Subgroup.centralizer
        (omegaOneCenterAmbient
          (elementaryAbelianMaxJ (SM : Subgroup M)) : Set M))
    (hJnot : ¬ elementaryAbelianMaxJ (SM : Subgroup M) ≤ C0)
    (hcomm : K = ⁅K, B⁆) :
    let q : M →* M ⧸ C0 := QuotientGroup.mk' C0
    K.map q ≤ pCore 3 (M ⧸ C0) ∧ pCore 2 (K.map q) = ⊥ := by
  let q : M →* M ⧸ C0 := QuotientGroup.mk' C0
  have hker : q.ker = Subgroup.centralizer (V : Set M) := by
    rw [QuotientGroup.ker_mk', hC0]
  have hVS : V ≤ (SM : Subgroup M) :=
    hVcore.trans (fitting_pCore_le_sylow SM)
  have hJne : (elementaryAbelianMaxJ (SM : Subgroup M)).map q ≠ ⊥ := by
    intro hbot
    have hle : elementaryAbelianMaxJ (SM : Subgroup M) ≤ q.ker :=
      (Subgroup.map_eq_bot_iff (f := q) _).mp hbot
    exact hJnot (by simpa [q, QuotientGroup.ker_mk'] using hle)
  have hbarcomm : K.map q = ⁅K.map q, B.map q⁆ := by
    rw [← Subgroup.map_commutator, ← hcomm]
  exact sourceLocalQuotientEndpoint SM V hVnormal hVelem hVS hM.solvable
    q (QuotientGroup.mk'_surjective C0) hker hWbar B hB hJne (K.map q) hbarcomm

end Stellmacher.SectionsFiveToSeven
