module

public import Stellmacher.SectionFiveToSeven.Result7_6.GraphFacts

/-!
# A neighbor module is generated by the conjugates of any neighbor center

For adjacent vertices d and l in the original Section Seven graph, the module
V_l is the normal closure of Z_d inside the actual stabilizer G_l, mapped back
to the ambient group. The statement retains the given graph and its action;
no critical path or length assumption is needed.

Lemma (7.3) puts Z_d inside G_l. By (7.1), G_l acts transitively on the
neighbors of l, so center covariance puts every neighbor center in that normal
closure. This proves V_l lies in the closure and hence in G_l. Stabilizer
invariance of V_l and its containment of Z_d give the reverse inclusion by
minimality of the normal closure. The conjugation uses the graph action's
inverse convention throughout.

This is the normal-closure interpretation of the Section Seven definition of
V_l used in Stellmacher (8.4)(4),(8), Journal of Algebra 190 (1997), pp.38–39,
refs/latex/stellmacher-n-group.tex.
-/

namespace Stellmacher.SectionsFiveToSeven
open CosetGraphContext SevenSix
universe u

/-- Every neighbor center normally generates the full module in the vertex stabilizer. -/
public theorem neighbor_module_eq_normalClosure_center
    {G : Type u} [Group G] [Finite G] {S P1 P2 : Subgroup G}
    (h : SectionSevenHypotheses G S P1 P2)
    (Γ : CosetGraphContext G S P1 P2) (d l : Γ.Vertex)
    (hdl : Γ.adjacent d l) :
    v Γ l = (Subgroup.normalClosure
      ((z Γ d).subgroupOf (stabilizer Γ l) : Set (stabilizer Γ l))).map
        (stabilizer Γ l).subtype := by
  let P := stabilizer Γ l
  let Z := z Γ d
  let N0 := Subgroup.normalClosure (Z.subgroupOf P : Set P)
  let N := N0.map P.subtype
  have hl : l ∈ neighborhood Γ d := (mem_neighborhood_iff_adjacent Γ).mpr hdl
  have hd : d ∈ neighborhood Γ l :=
    (mem_neighborhood_iff_adjacent Γ).mpr (Γ.adjacent_symm hdl)
  have hZQ : Z ≤ q Γ d := by
    apply (lemma_seven_three h Γ).center_core d l hl |>.trans
    unfold omegaOneCenter
    exact (Subgroup.map_mono (Subgroup.map_subtype_le _)).trans
      (Subgroup.map_subtype_le _)
  have hZP : Z ≤ P := hZQ.trans
    ((lemma_seven_three h Γ).sylow_and_core d l hl
      (default : Sylow 2 ↥(stabilizer Γ d ⊓ stabilizer Γ l))).2.2
  have hZN : Z ≤ N := by
    rw [← Subgroup.map_subgroupOf_eq_of_le hZP]
    exact Subgroup.map_mono Subgroup.le_normalClosure
  have hNP : N ≤ P := Subgroup.map_subtype_le _
  have hNn : (N.subgroupOf P).Normal := by
    change ((N0.map P.subtype).comap P.subtype).Normal
    rw [Subgroup.comap_map_eq_self_of_injective P.subtype_injective]
    infer_instance
  have hVN : v Γ l ≤ N := by
    rw [v, Γ.vAt_def]
    apply sSup_le
    rintro A ⟨m, hm, rfl⟩
    obtain ⟨g, hg⟩ := (lemma_seven_one h Γ).local_transitivity l hd hm
    change z Γ m ≤ N
    rw [← hg, z_act]
    have hgn := (Subgroup.normal_subgroupOf_iff_le_normalizer hNP).mp hNn
      (P.inv_mem g.property)
    have heq : N.map (MulAut.conj (g : G)⁻¹).toMonoidHom = N :=
      Subgroup.mem_normalizer_iff_map_conj_eq.mp hgn
    exact (Subgroup.map_mono hZN).trans_eq heq
  have hVP : v Γ l ≤ P := hVN.trans hNP
  have hZV : Z ≤ v Γ l := by
    rw [v, Γ.vAt_def]
    exact le_sSup ⟨d, hd, rfl⟩
  let _ : ((v Γ l).subgroupOf P).Normal :=
    (Subgroup.normal_subgroupOf_iff_le_normalizer hVP).mpr
      (stabilizer_le_normalizer_v Γ l)
  have hNV : N ≤ v Γ l := by
    have hn : N0 ≤ (v Γ l).subgroupOf P :=
      Subgroup.normalClosure_le_normal (fun x hx => hZV hx)
    rintro x ⟨y, hy, rfl⟩
    exact hn hy
  exact le_antisymm hVN hNV

end Stellmacher.SectionsFiveToSeven
