module
public import ABG.Recognition.ThreeDegreeFourCharacter
public import ABG.Recognition.ThreeDeterminantCharacter

/-!
# Wong's faithful degree-two characters of GL₂(3)

Induce a linear character of the cyclic subgroup generated by `threeRotation`,
and subtract the degree-four principal-series character. The resulting
virtual character has norm one and positive degree, hence is irreducible.
Its determinant twist gives the other faithful row. Finite induction counts
are checked by the kernel on matrices over ZMod 3.

Source: W. J. Wong, On finite groups whose 2-Sylow subgroups have cyclic
subgroups of index 2 (1964), Table 1, p. 97, DOI:10.1017/S1446788700022771.
-/

open Matrix Matrix.GeneralLinearGroup
open scoped BigOperators
namespace ABG
noncomputable section
private abbrev G := GL (Fin 2) (ZMod 3)
private abbrev M := Matrix (Fin 2) (Fin 2) (ZMod 3)
private abbrev C := Subgroup.zpowers threeRotation

private def zeta : ℂ := (Real.sqrt 2 : ℂ) / 2 * (1 + Complex.I)
private theorem zeta_sq : zeta ^ 2 = Complex.I := by
  have hs : (Real.sqrt 2 : ℂ)^2 = 2 := by
    exact_mod_cast Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 2)
  dsimp [zeta]
  calc
    _ = (Real.sqrt 2 : ℂ)^2 / 4 * (1 + 2 * Complex.I + Complex.I^2) := by ring
    _ = Complex.I := by rw [hs, Complex.I_sq]; ring
private theorem zeta_four : zeta ^ 4 = -1 := by
  calc _ = (zeta^2)^2 := by ring
       _ = -1 := by rw [zeta_sq, Complex.I_sq]
private theorem zeta_eight : zeta ^ 8 = 1 := by
  calc _ = (zeta^4)^2 := by ring
       _ = 1 := by rw [zeta_four]; norm_num
private theorem zeta_ne_zero : zeta ≠ 0 := by
  intro h
  simpa [h] using zeta_eight

/-- Wong's choice of square root of -2. -/
public def glTwoThreeOmega : ℂ := zeta + zeta^3
public theorem glTwoThreeOmega_sq : glTwoThreeOmega^2 = -2 := by
  dsimp [glTwoThreeOmega]
  calc
    _ = zeta^2 + 2 * zeta^4 + zeta^2 * zeta^4 := by ring
    _ = -2 := by rw [zeta_sq, zeta_four]; ring
public theorem glTwoThreeOmega_star : star glTwoThreeOmega = -glTwoThreeOmega := by
  have heq : glTwoThreeOmega = (Real.sqrt 2 : ℂ) * Complex.I := by
    unfold glTwoThreeOmega
    rw [pow_succ zeta 2, zeta_sq]
    dsimp [zeta]
    calc _ = (Real.sqrt 2 : ℂ) / 2 * (1 + 2 * Complex.I + Complex.I^2) := by ring
         _ = _ := by rw [Complex.I_sq]; ring
  rw [heq]
  simp

private theorem rotation_order : orderOf threeRotation = 8 :=
  three_conjugacy_data.2.1 6
private def cyclicGenerator : C := ⟨threeRotation, Subgroup.mem_zpowers threeRotation⟩
private theorem cyclicGenerator_generates (x : C) : x ∈ Subgroup.zpowers cyclicGenerator := by
  obtain ⟨n, hn⟩ := x.property
  exact ⟨n, Subtype.ext hn⟩
private def cyclicHom : C →* ℂˣ :=
  monoidHomOfForallMemZpowers cyclicGenerator_generates (g' := Units.mk0 zeta zeta_ne_zero)
    (by
      rw [← orderOf_injective C.subtype Subtype.val_injective cyclicGenerator]
      change orderOf (Units.mk0 zeta zeta_ne_zero) ∣ orderOf threeRotation
      rw [rotation_order, orderOf_dvd_iff_pow_eq_one]
      apply Units.ext
      exact zeta_eight)
private theorem cyclicHom_pow (n : ℕ) :
    (cyclicHom ⟨threeRotation^n, n, zpow_natCast _ _⟩ : ℂ) = zeta^n := by
  have h : cyclicHom cyclicGenerator = Units.mk0 zeta zeta_ne_zero :=
    monoidHomOfForallMemZpowers_apply_gen _ _
  change ((cyclicHom (cyclicGenerator^n)) : ℂ) = _
  rw [map_pow, h, Units.val_pow_eq_pow_val]
  rfl
private def cyclicEquiv : Fin 8 ≃ C :=
  (finCongr rotation_order.symm).trans (finEquivZPowers (isOfFinOrder_of_finite _))
private theorem cyclicEquiv_val (n : Fin 8) : (cyclicEquiv n).val = threeRotation^n.val := rfl
private theorem cyclic_card : Nat.card C = 8 := by rw [Nat.card_zpowers, rotation_order]

private def inducedCyclic : ClassFunction G :=
  inducedClassFunction C (fun c => (cyclicHom c : ℂ))
private theorem inducedCyclic_isCharacter : IsCharacter inducedCyclic := by
  let : Fintype C := Fintype.ofFinite _
  exact BenderGlauberman.isCharacter_induced _
    (BenderGlauberman.isCharacter_of_isIrreducibleCharacter
      (BenderGlauberman.isLinearCharacter_of_hom cyclicHom).1)

private def matrixEquiv : G ≃ {A : M // A.det ≠ 0} where
  toFun g := ⟨g.val, g.det_ne_zero⟩
  invFun A := mkOfDetNeZero A.val A.property
  left_inv _ := Units.ext rfl
  right_inv _ := Subtype.ext rfl

private def inductionCount (A : M) (n : Fin 8) : ℕ :=
  (Finset.univ.filter (fun B : M => B.det ≠ 0 ∧
    A * B = B * (threeRotation^n.val).val)).card

private theorem conjugate_eq_iff (g x : G) (n : Fin 8) :
    x⁻¹ * g * x = threeRotation^n.val ↔
      g.val * x.val = x.val * (threeRotation^n.val).val := by
  constructor
  · intro h
    exact congrArg Units.val (show g * x = x * threeRotation^n.val by
      rw [← h]; simp [mul_assoc])
  · intro h
    have hh : g * x = x * threeRotation^n.val := Units.ext h
    calc _ = x⁻¹ * (g * x) := by group
         _ = threeRotation^n.val := by rw [hh]; simp

private theorem inducedCyclic_apply (g : G) :
    inducedCyclic g = (∑ n : Fin 8, (inductionCount g.val n : ℂ) * zeta^n.val) / 8 := by
  classical
  have hterm (x : G) :
      (if h : x⁻¹ * g * x ∈ C then (cyclicHom ⟨x⁻¹ * g * x, h⟩ : ℂ) else 0) =
        ∑ n : Fin 8, if x⁻¹ * g * x = threeRotation^n.val then zeta^n.val else 0 := by
    by_cases hx : x⁻¹ * g * x ∈ C
    · obtain ⟨n, hn⟩ := cyclicEquiv.surjective ⟨x⁻¹ * g * x, hx⟩
      have hnval : threeRotation^n.val = x⁻¹ * g * x := congrArg Subtype.val hn
      rw [dif_pos hx, ← hn]
      rw [show (cyclicHom (cyclicEquiv n) : ℂ) = zeta^n.val from cyclicHom_pow n.val]
      symm
      rw [Finset.sum_eq_single n]
      · rw [if_pos hnval.symm]
      · intro m hm hmn
        apply if_neg
        intro heq
        apply hmn
        apply cyclicEquiv.injective
        apply Subtype.ext
        exact heq.symm.trans hnval.symm
      · simp
    · rw [dif_neg hx]
      symm
      apply Finset.sum_eq_zero
      intro n hn
      apply if_neg
      intro heq
      apply hx
      rw [heq]
      exact Subgroup.pow_mem _ (Subgroup.mem_zpowers _) _
  have hcount (n : Fin 8) :
      (∑ x : G, if x⁻¹ * g * x = threeRotation^n.val then zeta^n.val else 0) =
        (inductionCount g.val n : ℂ) * zeta^n.val := by
    simp_rw [conjugate_eq_iff]
    calc
      _ = ∑ B : {A : M // A.det ≠ 0},
          if g.val * B.val = B.val * (threeRotation^n.val).val then zeta^n.val else 0 :=
        Fintype.sum_equiv matrixEquiv _ _ (fun _ => rfl)
      _ = ∑ B ∈ Finset.univ.filter (fun B : M => B.det ≠ 0),
          if g.val * B = B * (threeRotation^n.val).val then zeta^n.val else 0 := by
        symm; exact Finset.sum_subtype _ (by simp) _
      _ = _ := by simp [← Finset.sum_filter, Finset.filter_filter, inductionCount]
  unfold inducedCyclic inducedClassFunction
  simp only [cyclic_card, hterm]
  rw [Finset.sum_comm]
  simp_rw [hcount]
  ring

private theorem induction_counts : ∀ i n : Fin 8,
    inductionCount (threeClassRepr i).val n =
      ![![48,0,0,0,0,0,0,0], ![0,0,0,0,48,0,0,0], ![0,0,8,0,0,0,8,0],
        ![0,0,0,0,0,0,0,0], ![0,0,0,0,0,0,0,0], ![0,0,0,0,0,0,0,0],
        ![0,8,0,8,0,0,0,0], ![0,0,0,0,0,8,0,8]] i n := by
  decide +kernel

private theorem inducedCyclic_values (i : Fin 8) :
    inducedCyclic (threeClassRepr i) = ![6,-6,0,0,0,0,glTwoThreeOmega,-glTwoThreeOmega] i := by
  have hsix : zeta^6 = -Complex.I := by
    calc _ = zeta^2 * zeta^4 := by ring
         _ = _ := by rw [zeta_sq, zeta_four]; ring
  have hfive : zeta^5 = -zeta := by rw [pow_succ, zeta_four]; ring
  have hseven : zeta^7 = -zeta^3 := by
    calc _ = zeta^3 * zeta^4 := by ring
         _ = _ := by rw [zeta_four]; ring
  rw [inducedCyclic_apply]
  simp_rw [induction_counts]
  fin_cases i <;>
    norm_num [Fin.sum_univ_succ, zeta_four, zeta_sq, hsix, hfive, hseven, glTwoThreeOmega] <;> ring

/-- Wong's first faithful degree-two row, constructed as an induced difference. -/
public def glTwoThreeFaithfulCharacter : ClassFunction (GL (Fin 2) (ZMod 3)) :=
  inducedCyclic - glTwoThreeDegreeFourCharacter

public theorem glTwoThreeFaithfulCharacter_values (i : Fin 8) :
    glTwoThreeFaithfulCharacter (threeClassRepr i) =
      ![2,-2,0,-1,1,0,glTwoThreeOmega,-glTwoThreeOmega] i := by
  change inducedCyclic (threeClassRepr i) - glTwoThreeDegreeFourCharacter (threeClassRepr i) = _
  rw [inducedCyclic_values, glTwoThreeDegreeFourCharacter_values]
  fin_cases i <;> norm_num

private theorem faithful_generalized : IsGeneralizedCharacter glTwoThreeFaithfulCharacter :=
  ⟨inducedCyclic, glTwoThreeDegreeFourCharacter, inducedCyclic_isCharacter,
    glTwoThreeDegreeFourCharacter_isCharacter, rfl⟩

-- An integer-valued matrix model for the squared absolute values of the row.
private def matrixWeight (A : M) : ℕ :=
  if A = 1 ∨ A = -1 then 4 else
    if A 0 0 + A 1 1 = 0 then 0 else if A.det = 1 then 1 else 2

private theorem weighted_coverage : ∀ A : M, A.det ≠ 0 →
    ∃ i : Fin 8, ∃ B : M, B.det ≠ 0 ∧ B * A = (threeClassRepr i).val * B ∧
      matrixWeight A = ![4,4,0,1,1,0,2,2] i := by
  decide +kernel

private theorem weight_sum :
    ∑ A ∈ Finset.univ.filter (fun A : M => A.det ≠ 0), matrixWeight A = 48 := by
  decide +kernel

private theorem faithful_abs_sq (g : G) :
    glTwoThreeFaithfulCharacter g * star (glTwoThreeFaithfulCharacter g) =
      (matrixWeight g.val : ℂ) := by
  obtain ⟨i, B, hB, hconj, hweight⟩ := weighted_coverage g.val g.det_ne_zero
  let b : G := mkOfDetNeZero B hB
  have heq : b * g = threeClassRepr i * b := Units.ext hconj
  have hconj' : b * g * b⁻¹ = threeClassRepr i := by rw [heq]; group
  have hc := BenderGlauberman.isClassFunction_of_isGeneralizedCharacter faithful_generalized g b
  rw [hconj'] at hc
  rw [← hc, glTwoThreeFaithfulCharacter_values, hweight]
  fin_cases i <;> norm_num [glTwoThreeOmega_star, ← pow_two, glTwoThreeOmega_sq]

private theorem faithful_norm :
    scalarProduct G glTwoThreeFaithfulCharacter glTwoThreeFaithfulCharacter = 1 := by
  classical
  have hcard : Nat.card G = 48 := by
    rw [Matrix.card_GL_field]; norm_num [Fin.prod_univ_two]
  have hsum : (∑ g : G, (matrixWeight g.val : ℂ)) = 48 := by
    calc
      _ = ∑ A : {A : M // A.det ≠ 0}, (matrixWeight A.val : ℂ) :=
        Fintype.sum_equiv matrixEquiv _ _ (fun _ => rfl)
      _ = ∑ A ∈ Finset.univ.filter (fun A : M => A.det ≠ 0), (matrixWeight A : ℂ) := by
        symm; exact Finset.sum_subtype _ (by simp) _
      _ = 48 := by exact_mod_cast weight_sum
  unfold scalarProduct
  simp_rw [faithful_abs_sq]
  rw [hcard, hsum]
  norm_num

public theorem glTwoThreeFaithfulCharacter_degree : glTwoThreeFaithfulCharacter 1 = 2 :=
  glTwoThreeFaithfulCharacter_values 0

/-- The positive-degree generalized character of norm one is genuinely irreducible. -/
public theorem glTwoThreeFaithfulCharacter_irreducible :
    IsIrreducibleCharacter glTwoThreeFaithfulCharacter := by
  obtain ⟨χ, hχ, heq | heq⟩ :=
    BenderGlauberman.norm_one_signed_irreducible faithful_generalized faithful_norm
  · exact heq ▸ hχ
  · obtain ⟨n, ρ, hρ, hχρ⟩ := hχ
    have hdeg := glTwoThreeFaithfulCharacter_degree
    rw [heq, hχρ] at hdeg
    simp only [Pi.neg_apply, Representation.char_one, Module.finrank_pi, Fintype.card_fin] at hdeg
    have hre := congrArg Complex.re hdeg
    norm_num at hre
    have hn : (0 : ℝ) ≤ n := Nat.cast_nonneg n
    linarith

/-- The determinant twist is Wong's second faithful degree-two row. -/
public def glTwoThreeFaithfulTwistCharacter : ClassFunction (GL (Fin 2) (ZMod 3)) :=
  glTwoThreeDeterminantCharacter * glTwoThreeFaithfulCharacter

public theorem glTwoThreeFaithfulTwistCharacter_values (i : Fin 8) :
    glTwoThreeFaithfulTwistCharacter (threeClassRepr i) =
      ![2,-2,0,-1,1,0,-glTwoThreeOmega,glTwoThreeOmega] i := by
  change glTwoThreeDeterminantCharacter (threeClassRepr i) *
    glTwoThreeFaithfulCharacter (threeClassRepr i) = _
  rw [glTwoThreeDeterminantCharacter_values, glTwoThreeFaithfulCharacter_values]
  fin_cases i <;> norm_num

public theorem glTwoThreeFaithfulTwistCharacter_irreducible :
    IsIrreducibleCharacter glTwoThreeFaithfulTwistCharacter :=
  BenderGlauberman.isIrreducibleCharacter_mul_linear
    glTwoThreeDeterminantCharacter_isLinear glTwoThreeFaithfulCharacter_irreducible

public theorem glTwoThreeFaithfulTwistCharacter_degree :
    glTwoThreeFaithfulTwistCharacter 1 = 2 :=
  glTwoThreeFaithfulTwistCharacter_values 0

public theorem glTwoThreeFaithfulCharacters_distinct :
    glTwoThreeFaithfulCharacter ≠ glTwoThreeFaithfulTwistCharacter := by
  intro heq
  have h := congrFun heq (threeClassRepr 6)
  rw [glTwoThreeFaithfulCharacter_values, glTwoThreeFaithfulTwistCharacter_values] at h
  have hz : glTwoThreeOmega = 0 := by
    change glTwoThreeOmega = -glTwoThreeOmega at h
    linear_combination (1 / 2 : ℂ) * h
  have hs := glTwoThreeOmega_sq
  rw [hz] at hs
  norm_num at hs

private theorem omega_ne_two : glTwoThreeOmega ≠ 2 := by
  intro h
  have hs := glTwoThreeOmega_sq
  norm_num [h] at hs
private theorem neg_omega_ne_two : -glTwoThreeOmega ≠ 2 := by
  intro h
  have heq : glTwoThreeOmega = -2 := neg_eq_iff_eq_neg.mp h
  have hs := glTwoThreeOmega_sq
  norm_num [heq] at hs

private theorem faithful_of_row (χ : ClassFunction G) (hχ : IsClassFunction χ)
    (hrow : ∀ i : Fin 8, χ (threeClassRepr i) = 2 ↔ i = 0) (g : G) :
    χ g = 2 ↔ g = 1 := by
  obtain ⟨i, hi, _⟩ := three_conjugacy_data.1 g
  have hc : χ g = χ (threeClassRepr i) := by
    obtain ⟨b, hb⟩ := isConj_iff.mp hi
    rw [← hb]
    exact (hχ g b).symm
  constructor
  · intro h
    have hi0 := (hrow i).mp (hc.symm.trans h)
    subst i
    exact isConj_one_left.mp hi
  · rintro rfl
    exact (hrow 0).mpr rfl

/-- The first row attains its degree only at the identity: it is faithful. -/
public theorem glTwoThreeFaithfulCharacter_eq_two_iff (g : GL (Fin 2) (ZMod 3)) :
    glTwoThreeFaithfulCharacter g = 2 ↔ g = 1 := by
  apply faithful_of_row _
    (BenderGlauberman.irreducibleCharacter_isClassFunction
      glTwoThreeFaithfulCharacter_irreducible) _ g
  intro i
  rw [glTwoThreeFaithfulCharacter_values]
  fin_cases i <;> norm_num [omega_ne_two, neg_omega_ne_two]

/-- The determinant twist likewise has trivial character kernel. -/
public theorem glTwoThreeFaithfulTwistCharacter_eq_two_iff (g : GL (Fin 2) (ZMod 3)) :
    glTwoThreeFaithfulTwistCharacter g = 2 ↔ g = 1 := by
  apply faithful_of_row _
    (BenderGlauberman.irreducibleCharacter_isClassFunction
      glTwoThreeFaithfulTwistCharacter_irreducible) _ g
  intro i
  rw [glTwoThreeFaithfulTwistCharacter_values]
  fin_cases i <;> norm_num [omega_ne_two, neg_omega_ne_two]

end
end ABG
