module
public import ABG.ChapterII.Section1.FusionPatterns
public import ABG.ChapterII.Section1.SemidihedralEquiv

/-!
# Transport of quasi-dihedral fusion frames

The quasi-dihedral branch of ABG Chapter II §2 Proposition 1 (article p.15)
chooses a conjugate Sylow two-subgroup whose center contains a given
involution, then regards that Sylow subgroup inside the involution centralizer.
This module transports the complete frame of §1 Proposition 1 through those
two operations. Restriction requires only that the new ambient subgroup
contain the chosen Sylow subgroup; conjugation requires no extra hypotheses.

The re-exported semidihedral presentation transports along multiplicative equivalences;
this transport is also exported for Sylow images in odd-core quotients.
Orders and the conjugation relation are preserved, and the image of the
subgroup generated by the two generators is the whole target group. The
four-group models transport by cardinality and exponent, and the quaternion
models by composition of their equivalences. All inclusions use the actual
Sylow subtype and conjugation constructions, so no replacement group
instances or finiteness assumptions enter the interface.
-/

namespace ABG

/-- Restrict a quasi-dihedral frame to any subgroup containing its Sylow subgroup. -/
public theorem quasiDihedralFusionFrame_subtype
    {G : Type*} [Group G] (S : Sylow 2 G) (T Q H : Subgroup G)
    (hSH : (S : Subgroup G) ≤ H) (hframe : QuasiDihedralFusionFrame S T Q) :
    QuasiDihedralFusionFrame (S.subtype hSH) (T.subgroupOf H) (Q.subgroupOf H) := by
  obtain ⟨hS, hTS, hQS, hT, hQ⟩ := hframe
  have hSHsemi : Stellmacher.IsSemidihedralGroup ((S : Subgroup G).subgroupOf H) :=
    semidihedral_equiv (Subgroup.subgroupOfEquivOfLe hSH).symm hS
  refine ⟨?_, ?_, ?_, ?_, ?_⟩
  · exact hSHsemi
  · exact Subgroup.subgroupOf_mono H hTS
  · exact Subgroup.subgroupOf_mono H hQS
  · let e := Subgroup.subgroupOfEquivOfLe (hTS.trans hSH)
    exact ⟨(Nat.card_congr e.toEquiv).trans hT.card_four,
      (Monoid.exponent_eq_of_mulEquiv e).trans hT.exponent_two⟩
  · obtain ⟨eQ⟩ := hQ
    exact ⟨(Subgroup.subgroupOfEquivOfLe (hQS.trans hSH)).trans eQ⟩

/-- Conjugate the Sylow subgroup and both chosen subgroups of a fusion frame. -/
public theorem quasiDihedralFusionFrame_smul
    {G : Type*} [Group G] (S : Sylow 2 G) (T Q : Subgroup G) (g : G)
    (hframe : QuasiDihedralFusionFrame S T Q) :
    QuasiDihedralFusionFrame (g • S) (T.map (MulAut.conj g).toMonoidHom)
      (Q.map (MulAut.conj g).toMonoidHom) := by
  obtain ⟨hS, hTS, hQS, hT, hQ⟩ := hframe
  refine ⟨semidihedral_equiv (S.equivSMul g) hS, ?_, ?_, ?_, ?_⟩
  · exact Subgroup.map_mono hTS
  · exact Subgroup.map_mono hQS
  · let e := (T.equivMapOfInjective (MulAut.conj g).toMonoidHom
      (MulAut.conj g).injective).symm
    exact ⟨(Nat.card_congr e.toEquiv).trans hT.card_four,
      (Monoid.exponent_eq_of_mulEquiv e).trans hT.exponent_two⟩
  · obtain ⟨eQ⟩ := hQ
    exact ⟨(Q.equivMapOfInjective (MulAut.conj g).toMonoidHom
      (MulAut.conj g).injective).symm.trans eQ⟩

end ABG
