module

public import Stellmacher.SectionOne.RankOneThreeGroupAssembly.Basic

/-!
# Generation by the four-point order-three factors

Conjugation preserves omega factors. Their normal join contains the odd core once all local commutators lie in it, by Lemma (1.5)(d).

This module supports the rank-at-least-two case of Stellmacher (1.6).
The action is on an elementary abelian two-group; the local hypotheses and
minimal-offender conditions are explicit in the declarations that use them.
Source: `refs/latex/stellmacher-n-group.tex`, proof of (1.6), journal pp.18–19.
-/

open scoped Pointwise symmDiff

namespace Stellmacher.SectionOne.RankOneThreeGroupAssembly

universe u v

@[expose] public noncomputable def oneOmegaFinset
    {G V : Type u} [Group G] [Group V] [Finite G] [Finite V]
    [MulDistribMulAction G V] : Finset (Subgroup G) := by
  classical
  letI : Fintype (Subgroup G) := Fintype.ofFinite (Subgroup G)
  exact Finset.univ.filter (oneOmega (G := G) (V := V))

public theorem mem_oneOmegaFinset_iff
    {G V : Type u} [Group G] [Group V] [Finite G] [Finite V]
    [MulDistribMulAction G V] (F : Subgroup G) :
    F ∈ oneOmegaFinset (G := G) (V := V) ↔
      oneOmega (G := G) (V := V) F := by
  classical
  simp [oneOmegaFinset]

@[expose] public noncomputable def oneOmegaGenerated
    {G V : Type u} [Group G] [Group V] [Finite G] [Finite V]
    [MulDistribMulAction G V] : Subgroup G :=
  ⨆ F : {F : Subgroup G //
    F ∈ oneOmegaFinset (G := G) (V := V)}, (F : Subgroup G)

/-- The subgroup generated by all ambient `oneOmega` subgroups is normal,
because the defining family is stable under ambient conjugacy. -/
private theorem oneOmegaGenerated_normal
    {G V : Type u} [Group G] [Group V] [Finite G] [Finite V]
    [MulDistribMulAction G V] :
    (oneOmegaGenerated (G := G) (V := V)).Normal := by
  classical
  refine ⟨?_⟩
  intro x hx g
  let W₀ : Subgroup G := oneOmegaGenerated (G := G) (V := V)
  have hmap_le : W₀.map (MulAut.conj g).toMonoidHom ≤ W₀ := by
    dsimp only [W₀, oneOmegaGenerated]
    rw [Subgroup.map_iSup]
    refine iSup_le ?_
    intro F
    have hFomega : oneOmega (G := G) (V := V) (F : Subgroup G) :=
      (mem_oneOmegaFinset_iff (G := G) (V := V) (F : Subgroup G)).mp F.property
    let Fg : {D : Subgroup G //
        D ∈ oneOmegaFinset (G := G) (V := V)} :=
      ⟨(F : Subgroup G).conjBy g,
        (mem_oneOmegaFinset_iff (G := G) (V := V) _).mpr
          (oneOmega_conjBy (F : Subgroup G) hFomega g)⟩
    exact le_iSup
      (fun D : {D : Subgroup G //
        D ∈ oneOmegaFinset (G := G) (V := V)} => (D : Subgroup G)) Fg
  exact hmap_le ⟨x, hx, rfl⟩

/-- Lemma (1.4) applied to the complete ambient `oneOmega` family.  When the
odd core is a `3`-group, the generated subgroup lies in `O₃(G)`. -/
public theorem oneOmegaGenerated_decomposition
    {G V : Type u} [Group G] [Group V] [Finite G] [Finite V]
    [IsElementaryAbelian 2 V] [MulDistribMulAction G V]
    (h : Hypotheses G V) (S : Sylow 2 G)
    (hWthree : IsPGroup 3 (oddCore G)) :
    LemmaOneFourConclusion (G := G) (V := V)
      (oneOmegaGenerated (G := G) (V := V))
      (oneOmegaFinset (G := G) (V := V)) := by
  have hW₀leW : oneOmegaGenerated (G := G) (V := V) ≤ oddCore G := by
    dsimp only [oneOmegaGenerated]
    refine iSup_le ?_
    intro F
    exact (mem_oneOmegaFinset_iff (G := G) (V := V)
      (F : Subgroup G)).mp F.property |>.1
  have hWleCore : oddCore G ≤ pCore 3 G := by
    exact le_sSup ⟨pPrimeCore_normal, hWthree⟩
  exact lemma_one_four h S (oneOmegaFinset (G := G) (V := V))
    (fun D => mem_oneOmegaFinset_iff (G := G) (V := V) D)
    (oneOmegaGenerated (G := G) (V := V)) rfl
    (hW₀leW.trans hWleCore)

/-- If a subgroup is generated by subgroups whose commutators with `S` lie
in a normal subgroup `N`, then its whole commutator with `S` lies in `N`.
The quotient by `N` makes the generation argument formal. -/
public theorem commutator_le_normal_of_eq_iSup
    {G : Type*} [Group G]
    (W S N : Subgroup G) [N.Normal]
    {I : Sort*} (K : I → Subgroup G)
    (hW : W = ⨆ i, K i)
    (hK : ∀ i, ⁅K i, S⁆ ≤ N) :
    ⁅W, S⁆ ≤ N := by
  let q : G →* G ⧸ N := QuotientGroup.mk' N
  have hKi (i : I) : ⁅(K i).map q, S.map q⁆ = ⊥ := by
    rw [← Subgroup.map_commutator]
    exact (Subgroup.map_eq_bot_iff (f := q) (H := ⁅K i, S⁆)).2 (by
      simpa [q, QuotientGroup.ker_mk'] using hK i)
  have hmapW : W.map q = ⨆ i, (K i).map q := by
    rw [hW, Subgroup.map_iSup]
  have hcommMap : ⁅W.map q, S.map q⁆ = ⊥ := by
    rw [hmapW, Subgroup.commutator_eq_bot_iff_le_centralizer]
    refine iSup_le ?_
    intro i
    exact Subgroup.commutator_eq_bot_iff_le_centralizer.mp (hKi i)
  have hmapBot : ⁅W, S⁆.map q = ⊥ := by
    rw [Subgroup.map_commutator, hcommMap]
  have hleker : ⁅W, S⁆ ≤ q.ker :=
    (Subgroup.map_eq_bot_iff (f := q) (H := ⁅W, S⁆)).mp hmapBot
  simpa [q, QuotientGroup.ker_mk'] using hleker

/-- Once every order-two local commutator is contained in the complete
`oneOmega` subgroup, Lemma (1.5)(d) and `W=[W,S]` force that subgroup to be
the whole odd core. -/
public theorem oddCore_eq_oneOmegaGenerated_of_local_commutators
    {G V : Type u} [Group G] [Group V] [Finite G] [Finite V]
    [IsElementaryAbelian 2 V] [MulDistribMulAction G V]
    (h : Hypotheses G V) (S : Sylow 2 G)
    (hS_elem : IsElementaryAbelian 2 (S : Subgroup G))
    (hScard : 4 ≤ Nat.card (S : Subgroup G))
    (hW : oddCore G = ⁅oddCore G, (S : Subgroup G)⁆)
    (hlocal : ∀ A : Subgroup G,
      oneAmax (G := G) (V := V) (S : Subgroup G) A →
      Nat.card A = 2 →
      ⁅oddCore G ⊓ Subgroup.centralizer (A : Set G),
        (S : Subgroup G)⁆ ≤
          oneOmegaGenerated (G := G) (V := V)) :
    oddCore G = oneOmegaGenerated (G := G) (V := V) := by
  let W₀ : Subgroup G := oneOmegaGenerated (G := G) (V := V)
  let _ : W₀.Normal := oneOmegaGenerated_normal
  let I := {A : Subgroup G //
    oneAmax (G := G) (V := V) (S : Subgroup G) A ∧ Nat.card A = 2}
  let K : I → Subgroup G := fun A =>
    oddCore G ⊓ Subgroup.centralizer ((A : Subgroup G) : Set G)
  have hgen : oddCore G = ⨆ A : I, K A := by
    simpa only [I, K] using
      (lemma_one_five h S (S : Subgroup G) le_rfl).part_d hS_elem hScard
  have hcomm : ⁅oddCore G, (S : Subgroup G)⁆ ≤ W₀ :=
    commutator_le_normal_of_eq_iSup
      (oddCore G) (S : Subgroup G) W₀ K hgen
      (fun A => hlocal (A : Subgroup G) A.property.1 A.property.2)
  apply le_antisymm
  · rw [hW]
    exact hcomm
  · dsimp only [W₀, oneOmegaGenerated]
    refine iSup_le ?_
    intro F
    exact (mem_oneOmegaFinset_iff (G := G) (V := V)
      (F : Subgroup G)).mp F.property |>.1

/-- Viewing an ambient subgroup inside an intermediate subgroup does not
change its action commutator on an invariant subgroup. -/
public theorem commutatorAction_subgroupOf_eq
    {G V : Type*} [Group G] [Group V] [MulDistribMulAction G V]
    (H F : Subgroup G) (U : Subgroup V)
    [IsInvariant H V U] (hFH : F ≤ H) :
    let _ : IsInvariant F V U := isInvariant_of_subgroup H F U hFH
    commutatorAction (F.subgroupOf H) U = commutatorAction F U := by
  dsimp only
  let _ : IsInvariant F V U := isInvariant_of_subgroup H F U hFH
  rw [commutatorAction_eq_closure, commutatorAction_eq_closure]
  congr 1
  ext x
  constructor
  · rintro ⟨a, u, rfl⟩
    let f : F := ⟨(a : H), a.property⟩
    refine ⟨f, u, ?_⟩
    rfl
  · rintro ⟨f, u, rfl⟩
    let a : F.subgroupOf H := ⟨⟨f, hFH f.property⟩, f.property⟩
    refine ⟨a, u, ?_⟩
    rfl

/-- Coprime idempotence identifies the ambient commutator with its
restriction to any invariant subgroup containing it.  This is the exact
bridge used in the generic branch when `[V,F] ≤ V_A`. -/
public theorem commutatorAction_restrict_eq_of_le_of_coprime
    {A V : Type*} [Group A] [Group V] [MulDistribMulAction A V]
    (U : Subgroup V) [IsInvariant A V U]
    (hle : commutatorAction A V ≤ U)
    (hcop : Nat.Coprime (Nat.card A) (Nat.card V)) :
    (commutatorAction A U).map U.subtype = commutatorAction A V := by
  let K : Subgroup V := commutatorAction A V
  let _ : IsInvariant A V K := commutatorAction_isInvariant
  apply le_antisymm
  · rw [commutatorAction_eq_closure, MonoidHom.map_closure,
      commutatorAction_eq_closure]
    refine Subgroup.closure_mono ?_
    rintro x ⟨z, ⟨a, u, rfl⟩, rfl⟩
    have hgen : (u : V)⁻¹ * a • (u : V) ∈
        {x : V | ∃ a : A, ∃ v : V, x = v⁻¹ * a • v} := by
      exact ⟨a, (u : V), rfl⟩
    exact hgen
  · rw [← commutatorAction₂_eq_commutatorAction_of_coprime hcop,
      ← commutatorAction_map_subtype_eq_commutatorAction₂]
    exact commutatorAction_map_subtype_mono K U hle

/-- A lifted local derived factor becomes a global member of `oneOmega` in
the generic case, namely when its ambient commutator lies in the fixed-point
module on which the quotient data was computed. -/
public theorem oneOmega_of_local_lift_of_commutator_le_fixedPoints
    {G V : Type u} [Group G] [Group V] [Finite G] [Finite V]
    [IsElementaryAbelian 2 V] [MulDistribMulAction G V]
    (H : Subgroup G) (A : Subgroup H) [A.Normal]
    (F : Subgroup G) (hFH : F ≤ H) (hFcore : F ≤ oddCore G)
    (hFcard : Nat.card F = 3)
    (D : Subgroup (H ⧸ A))
    (hDomega : oneOmega (G := H ⧸ A)
      (V := FixedPoints.subgroup A V) D)
    (hmap : (F.subgroupOf H).map (QuotientGroup.mk' A) = D)
    (hgeneric : commutatorAction F V ≤ FixedPoints.subgroup A V) :
    oneOmega (G := G) (V := V) F := by
  let U : Subgroup V := FixedPoints.subgroup A V
  let _ : IsInvariant H V U := fixedPoints_isInvariant_of_normal A
  let _ : IsInvariant F V U := isInvariant_of_subgroup H F U hFH
  have hcop : Nat.Coprime (Nat.card F) (Nat.card V) := by
    obtain ⟨n, hn⟩ := (IsElementaryAbelian.isPGroup 2 V).exists_card_eq
    rw [hFcard, hn]
    change Nat.Coprime (3 ^ 1) (2 ^ n)
    exact Nat.Coprime.pow 1 n (by decide)
  have hambient :
      (commutatorAction F U).map U.subtype = commutatorAction F V :=
    commutatorAction_restrict_eq_of_le_of_coprime U hgeneric hcop
  have hsubgroup :
      commutatorAction (F.subgroupOf H) U = commutatorAction F U :=
    commutatorAction_subgroupOf_eq H F U hFH
  have hlocalCard : Nat.card (commutatorAction (F.subgroupOf H) U) = 4 :=
    commutatorAction_lift_card_eq A (F.subgroupOf H) D hmap hDomega.2.2
  refine ⟨hFcore, hFcard, ?_⟩
  rw [← hambient, Subgroup.card_map_of_injective U.subtype_injective,
    ← hsubgroup]
  exact hlocalCard

end Stellmacher.SectionOne.RankOneThreeGroupAssembly
