module

public import Theory.SpecificGroups.Tits.R1Certificate.Base00
public import Theory.SpecificGroups.Tits.R1Certificate.Base01
public import Theory.SpecificGroups.Tits.R1Certificate.Base02
public import Theory.SpecificGroups.Tits.R1Certificate.Base03
public import Theory.SpecificGroups.Tits.R1Certificate.Base04
public import Theory.SpecificGroups.Tits.R1Certificate.Base05
public import Theory.SpecificGroups.Tits.R1Certificate.Base06
public import Theory.SpecificGroups.Tits.R1Certificate.Base07
public import Theory.SpecificGroups.Tits.R1Certificate.Base08
public import Theory.SpecificGroups.Tits.R1Certificate.Base09
public import Theory.SpecificGroups.Tits.R1Certificate.Base10
public import Theory.SpecificGroups.Tits.R1Certificate.Base11
public import Theory.SpecificGroups.Tits.R1Certificate.Base12
public import Theory.SpecificGroups.Tits.R1Certificate.Base13
public import Theory.SpecificGroups.Tits.R1Certificate.Base14
public import Theory.SpecificGroups.Tits.R1Certificate.Base15
public import Theory.SpecificGroups.Tits.R1Certificate.Base16
public import Theory.SpecificGroups.Tits.R1Certificate.Base17
public import Theory.SpecificGroups.Tits.R1Certificate.Base18
public import Theory.SpecificGroups.Tits.R1Certificate.Base19
public import Theory.SpecificGroups.Tits.R1Certificate.Base20
public import Theory.SpecificGroups.Tits.R1Certificate.Base21
public import Theory.SpecificGroups.Tits.R1Certificate.Base22
public import Theory.SpecificGroups.Tits.R1Certificate.Base23
public import Theory.SpecificGroups.Tits.R1Certificate.Base24
public import Theory.SpecificGroups.Tits.R1Certificate.Base25
public import Theory.SpecificGroups.Tits.R1Certificate.Base26
public import Theory.SpecificGroups.Tits.R1Certificate.Base27
public import Theory.SpecificGroups.Tits.R1Certificate.Base28
public import Theory.SpecificGroups.Tits.R1Certificate.Base29
public import Theory.SpecificGroups.Tits.R1Certificate.Base30
public import Theory.SpecificGroups.Tits.R1Certificate.Base31

/-! Independent initial facts for Parrott (1972), §5, p. 683.
Generated by `refs/original/n-group-global/parrott-r1-certificate/emit_chunks.py`. -/

public section
namespace Tits.R1Certificate
open Theory.GroupTheory Theory.GroupTheory.CosetEnumeration
attribute [local irreducible] input

end Tits.R1Certificate
