module

public import Theory.SpecificGroups.Tits.R1Certificate.Table
public import Theory.SpecificGroups.Tits.R1Certificate.Chunk146000

/-!
# Actual-group edges for rows 448 through 511

Literal data and kernel-checked finite assembly for the Parrott R₁ coset
certificate. Source: Parrott (1972), §5, p. 683. Generated by
`refs/original/n-group-global/parrott-r1-certificate/emit_table.py`.
-/

@[expose] public section
namespace Tits.R1Certificate
open Theory.GroupTheory Theory.GroupTheory.CosetEnumeration

attribute [local irreducible] input

theorem edges_row_448 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 448) [(a, true)]
      (index (table 448 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f20337
  · exact f83567
  · exact f83634
  · exact f81607
  · exact f80742
  · exact f20350
  · exact f70963
  · exact f20366
  · exact f66776
  · exact f20361

theorem edges_row_449 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 449) [(a, true)]
      (index (table 449 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f20867
  · exact f20480
  · exact f57728
  · exact f20474
  · exact f64739
  · exact f20461
  · exact f72423
  · exact f22369
  · exact f73619
  · exact f83729

theorem edges_row_450 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 450) [(a, true)]
      (index (table 450 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f83783
  · exact f74911
  · exact f50854
  · exact f74913
  · exact f74915
  · exact f74415
  · exact f50864
  · exact f83788
  · exact f51010
  · exact f83810

theorem edges_row_451 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 451) [(a, true)]
      (index (table 451 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f83830
  · exact f54620
  · exact f50848
  · exact f54623
  · exact f51153
  · exact f53700
  · exact f20490
  · exact f66886
  · exact f83835
  · exact f83904

theorem edges_row_452 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 452) [(a, true)]
      (index (table 452 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f20715
  · exact f20518
  · exact f83909
  · exact f20507
  · exact f49120
  · exact f22381
  · exact f83967
  · exact f20494
  · exact f83971
  · exact f84151

theorem edges_row_453 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 453) [(a, true)]
      (index (table 453 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f84198
  · exact f20526
  · exact f84203
  · exact f84279
  · exact f25177
  · exact f84321
  · exact f25089
  · exact f84405
  · exact f84482
  · exact f84518

theorem edges_row_454 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 454) [(a, true)]
      (index (table 454 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f84523
  · exact f20540
  · exact f84528
  · exact f84592
  · exact f84656
  · exact f84716
  · exact f84507
  · exact f81983
  · exact f20531
  · exact f84832

theorem edges_row_455 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 455) [(a, true)]
      (index (table 455 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f21064
  · exact f20553
  · exact f84837
  · exact f84842
  · exact f84908
  · exact f83776
  · exact f84912
  · exact f84162
  · exact f84916
  · exact f20544

theorem edges_row_456 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 456) [(a, true)]
      (index (table 456 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f20557
  · exact f58450
  · exact f84929
  · exact f84971
  · exact f58321
  · exact f85028
  · exact f58322
  · exact f58454
  · exact f85152
  · exact f83148

theorem edges_row_457 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 457) [(a, true)]
      (index (table 457 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f96969
  · exact f48304
  · exact f48308
  · exact f48310
  · exact f20566
  · exact f48312
  · exact f75509
  · exact f83965
  · exact f85218
  · exact f85289

theorem edges_row_458 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 458) [(a, true)]
      (index (table 458 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f74337
  · exact f48253
  · exact f59197
  · exact f75541
  · exact f64707
  · exact f20570
  · exact f59190
  · exact f85464
  · exact f85528
  · exact f85589

theorem edges_row_459 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 459) [(a, true)]
      (index (table 459 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f85602
  · exact f59063
  · exact f49259
  · exact f59065
  · exact f75186
  · exact f59068
  · exact f150440
  · exact f59086
  · exact f50991
  · exact f85695

theorem edges_row_460 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 460) [(a, true)]
      (index (table 460 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f85700
  · exact f53855
  · exact f49253
  · exact f53858
  · exact f49348
  · exact f53825
  · exact f20575
  · exact f85716
  · exact f85756
  · exact f85830

theorem edges_row_461 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 461) [(a, true)]
      (index (table 461 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f85054
  · exact f48241
  · exact f49301
  · exact f83164
  · exact f83020
  · exact f85503
  · exact f85850
  · exact f20579
  · exact f85854
  · exact f85945

theorem edges_row_462 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 462) [(a, true)]
      (index (table 462 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f85950
  · exact f48201
  · exact f48203
  · exact f85955
  · exact f48205
  · exact f86015
  · exact f48206
  · exact f86136
  · exact f86177
  · exact f86203

theorem edges_row_463 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 463) [(a, true)]
      (index (table 463 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f86208
  · exact f48236
  · exact f51129
  · exact f74672
  · exact f86213
  · exact f74667
  · exact f66297
  · exact f86300
  · exact f20584
  · exact f86352

theorem edges_row_464 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 464) [(a, true)]
      (index (table 464 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f85011
  · exact f48232
  · exact f86357
  · exact f86362
  · exact f110834
  · exact f110835
  · exact f86376
  · exact f110837
  · exact f86396
  · exact f20588

theorem edges_row_465 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 465) [(a, true)]
      (index (table 465 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f20593
  · exact f86409
  · exact f86432
  · exact f86437
  · exact f86453
  · exact f86455
  · exact f86482
  · exact f86484
  · exact f139213
  · exact f86528

theorem edges_row_466 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 466) [(a, true)]
      (index (table 466 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f86493
  · exact f51190
  · exact f53721
  · exact f86506
  · exact f58918
  · exact f20603
  · exact f53724
  · exact f150441
  · exact f86013
  · exact f86546

theorem edges_row_467 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 467) [(a, true)]
      (index (table 467 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f83047
  · exact f20616
  · exact f51016
  · exact f75205
  · exact f65518
  · exact f31186
  · exact f51022
  · exact f86559
  · exact f86595
  · exact f86803

theorem edges_row_468 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 468) [(a, true)]
      (index (table 468 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f86469
  · exact f24954
  · exact f83185
  · exact f58711
  · exact f86823
  · exact f106416
  · exact f87092
  · exact f20622
  · exact f80969
  · exact f87314

theorem edges_row_469 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 469) [(a, true)]
      (index (table 469 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f83095
  · exact f50500
  · exact f86052
  · exact f85568
  · exact f86671
  · exact f50504
  · exact f87319
  · exact f50507
  · exact f24564
  · exact f87374

theorem edges_row_470 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 470) [(a, true)]
      (index (table 470 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f86451
  · exact f51321
  · exact f87379
  · exact f87384
  · exact f87427
  · exact f150443
  · exact f87436
  · exact f87425
  · exact f87440
  · exact f20629

theorem edges_row_471 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 471) [(a, true)]
      (index (table 471 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f67147
  · exact f67149
  · exact f67152
  · exact f67155
  · exact f67158
  · exact f67159
  · exact f75414
  · exact f67163
  · exact f87474
  · exact f87632

theorem edges_row_472 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 472) [(a, true)]
      (index (table 472 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f87692
  · exact f64153
  · exact f64696
  · exact f64156
  · exact f20639
  · exact f64159
  · exact f56798
  · exact f87719
  · exact f81459
  · exact f87848

theorem edges_row_473 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 473) [(a, true)]
      (index (table 473 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f87875
  · exact f63674
  · exact f66558
  · exact f78691
  · exact f112669
  · exact f63676
  · exact f66485
  · exact f87880
  · exact f64763
  · exact f87957

theorem edges_row_474 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 474) [(a, true)]
      (index (table 474 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f150446
  · exact f49814
  · exact f49816
  · exact f76583
  · exact f49635
  · exact f49820
  · exact f20643
  · exact f69856
  · exact f52512
  · exact f87967

theorem edges_row_475 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 475) [(a, true)]
      (index (table 475 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f20675
  · exact f20659
  · exact f86829
  · exact f22398
  · exact f72113
  · exact f20669
  · exact f87301
  · exact f20647
  · exact f82286
  · exact f84896

theorem edges_row_476 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 476) [(a, true)]
      (index (table 476 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f145937
  · exact f20683
  · exact f88138
  · exact f85260
  · exact f23669
  · exact f88230
  · exact f23569
  · exact f88311
  · exact f88369
  · exact f136176

theorem edges_row_477 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 477) [(a, true)]
      (index (table 477 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f88415
  · exact f20697
  · exact f84777
  · exact f88420
  · exact f82793
  · exact f84585
  · exact f87625
  · exact f88458
  · exact f20688
  · exact f143870

theorem edges_row_478 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 478) [(a, true)]
      (index (table 478 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f20721
  · exact f20710
  · exact f88517
  · exact f84177
  · exact f88522
  · exact f20726
  · exact f143966
  · exact f84869
  · exact f88530
  · exact f20701

theorem edges_row_479 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 479) [(a, true)]
      (index (table 479 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f51033
  · exact f48096
  · exact f49316
  · exact f20740
  · exact f81179
  · exact f48098
  · exact f75614
  · exact f88543
  · exact f88640
  · exact f88802

theorem edges_row_480 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 480) [(a, true)]
      (index (table 480 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f88807
  · exact f59055
  · exact f49322
  · exact f59057
  · exact f20744
  · exact f51443
  · exact f72451
  · exact f87071
  · exact f88834
  · exact f88900

theorem edges_row_481 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 481) [(a, true)]
      (index (table 481 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f51045
  · exact f48104
  · exact f59229
  · exact f48106
  · exact f60759
  · exact f20748
  · exact f59224
  · exact f69986
  · exact f88920
  · exact f89032

theorem edges_row_482 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 482) [(a, true)]
      (index (table 482 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f51039
  · exact f48385
  · exact f87984
  · exact f88552
  · exact f86593
  · exact f69613
  · exact f86871
  · exact f20772
  · exact f89115
  · exact f89242

theorem edges_row_483 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 483) [(a, true)]
      (index (table 483 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f82085
  · exact f48064
  · exact f73816
  · exact f89269
  · exact f89358
  · exact f49382
  · exact f79134
  · exact f48067
  · exact f20777
  · exact f88816

theorem edges_row_484 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 484) [(a, true)]
      (index (table 484 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f51027
  · exact f83828
  · exact f89494
  · exact f89499
  · exact f150449
  · exact f89057
  · exact f89530
  · exact f89261
  · exact f127216
  · exact f20781

theorem edges_row_485 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 485) [(a, true)]
      (index (table 485 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f49240
  · exact f47302
  · exact f49098
  · exact f20790
  · exact f85330
  · exact f47304
  · exact f72404
  · exact f89534
  · exact f89623
  · exact f89768

theorem edges_row_486 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 486) [(a, true)]
      (index (table 486 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f85418
  · exact f20800
  · exact f49110
  · exact f85384
  · exact f58674
  · exact f35242
  · exact f121532
  · exact f87144
  · exact f84969
  · exact f89788

theorem edges_row_487 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 487) [(a, true)]
      (index (table 487 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f109163
  · exact f53863
  · exact f49104
  · exact f109166
  · exact f20805
  · exact f49310
  · exact f75412
  · exact f89819
  · exact f85059
  · exact f89903

theorem edges_row_488 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 488) [(a, true)]
      (index (table 488 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f49228
  · exact f47288
  · exact f51377
  · exact f47290
  · exact f49077
  · exact f20809
  · exact f45583
  · exact f89908
  · exact f90013
  · exact f90083

theorem edges_row_489 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 489) [(a, true)]
      (index (table 489 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f49223
  · exact f47238
  · exact f90110
  · exact f89543
  · exact f61442
  · exact f89957
  · exact f90209
  · exact f20814
  · exact f52566
  · exact f90273

theorem edges_row_490 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 490) [(a, true)]
      (index (table 490 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f110356
  · exact f47215
  · exact f90305
  · exact f90403
  · exact f48899
  · exact f79053
  · exact f47218
  · exact f79113
  · exact f23195
  · exact f90585

theorem edges_row_491 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 491) [(a, true)]
      (index (table 491 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f49235
  · exact f89786
  · exact f90590
  · exact f123483
  · exact f90620
  · exact f90108
  · exact f90624
  · exact f90293
  · exact f90628
  · exact f20821

theorem edges_row_492 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 492) [(a, true)]
      (index (table 492 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f99140
  · exact f48271
  · exact f20826
  · exact f83924
  · exact f85526
  · exact f86894
  · exact f89971
  · exact f48273
  · exact f88357
  · exact f90643

theorem edges_row_493 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 493) [(a, true)]
      (index (table 493 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f82176
  · exact f60982
  · exact f85483
  · exact f60985
  · exact f53683
  · exact f69421
  · exact f90648
  · exact f150452
  · exact f86175
  · exact f87399

theorem edges_row_494 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 494) [(a, true)]
      (index (table 494 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f90817
  · exact f58991
  · exact f87760
  · exact f87826
  · exact f20831
  · exact f58995
  · exact f58997
  · exact f58998
  · exact f91020
  · exact f91083

theorem edges_row_495 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 495) [(a, true)]
      (index (table 495 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f91136
  · exact f89990
  · exact f89938
  · exact f91184
  · exact f69892
  · exact f90202
  · exact f91273
  · exact f69849
  · exact f82300
  · exact f150454

theorem edges_row_496 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 496) [(a, true)]
      (index (table 496 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f82411
  · exact f22100
  · exact f87911
  · exact f69129
  · exact f61732
  · exact f69618
  · exact f20835
  · exact f69952
  · exact f82320
  · exact f91495

theorem edges_row_497 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 497) [(a, true)]
      (index (table 497 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f147141
  · exact f20843
  · exact f86093
  · exact f84414
  · exact f22144
  · exact f91552
  · exact f22009
  · exact f84319
  · exact f81029
  · exact f91732

theorem edges_row_498 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 498) [(a, true)]
      (index (table 498 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f91737
  · exact f20857
  · exact f91742
  · exact f81989
  · exact f81063
  · exact f91891
  · exact f90798
  · exact f84607
  · exact f20848
  · exact f91954

theorem edges_row_499 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 499) [(a, true)]
      (index (table 499 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f20873
  · exact f21069
  · exact f91959
  · exact f83747
  · exact f91964
  · exact f84857
  · exact f91968
  · exact f20884
  · exact f91972
  · exact f20861

theorem edges_row_500 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 500) [(a, true)]
      (index (table 500 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f92004
  · exact f101189
  · exact f20893
  · exact f88239
  · exact f24067
  · exact f85273
  · exact f22508
  · exact f87356
  · exact f92009
  · exact f150457

theorem edges_row_501 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 501) [(a, true)]
      (index (table 501 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f101177
  · exact f20905
  · exact f88290
  · exact f20898
  · exact f82930
  · exact f88194
  · exact f92082
  · exact f84002
  · exact f92140
  · exact f92185

theorem edges_row_502 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 502) [(a, true)]
      (index (table 502 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f101151
  · exact f20923
  · exact f85270
  · exact f88153
  · exact f90058
  · exact f20916
  · exact f91065
  · exact f62678
  · exact f80657
  · exact f92190

theorem edges_row_503 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 503) [(a, true)]
      (index (table 503 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f92195
  · exact f72802
  · exact f48633
  · exact f72804
  · exact f92257
  · exact f92666
  · exact f20931
  · exact f72806
  · exact f92755
  · exact f92795

theorem edges_row_504 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 504) [(a, true)]
      (index (table 504 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f101184
  · exact f20947
  · exact f83332
  · exact f83990
  · exact f92814
  · exact f76372
  · exact f92889
  · exact f20935
  · exact f93039
  · exact f93061

theorem edges_row_505 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 505) [(a, true)]
      (index (table 505 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f93081
  · exact f20961
  · exact f93086
  · exact f93152
  · exact f97433
  · exact f88403
  · exact f25965
  · exact f93197
  · exact f20955
  · exact f93225

theorem edges_row_506 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 506) [(a, true)]
      (index (table 506 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f101163
  · exact f93230
  · exact f101165
  · exact f93250
  · exact f134519
  · exact f117009
  · exact f93275
  · exact f101169
  · exact f93282
  · exact f20970

theorem edges_row_507 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 507) [(a, true)]
      (index (table 507 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f93286
  · exact f58175
  · exact f20980
  · exact f93301
  · exact f93362
  · exact f83684
  · exact f62550
  · exact f93445
  · exact f67064
  · exact f93525

theorem edges_row_508 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 508) [(a, true)]
      (index (table 508 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f58727
  · exact f20992
  · exact f93310
  · exact f20985
  · exact f93530
  · exact f58212
  · exact f93594
  · exact f84025
  · exact f53784
  · exact f93800

theorem edges_row_509 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 509) [(a, true)]
      (index (table 509 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f93827
  · exact f25706
  · exact f93374
  · exact f93562
  · exact f81783
  · exact f93832
  · exact f83013
  · exact f80769
  · exact f82936
  · exact f93921

theorem edges_row_510 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 510) [(a, true)]
      (index (table 510 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f93926
  · exact f25640
  · exact f72874
  · exact f89232
  · exact f21001
  · exact f93931
  · exact f81626
  · exact f88760
  · exact f84091
  · exact f94132

theorem edges_row_511 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 511) [(a, true)]
      (index (table 511 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f58739
  · exact f21012
  · exact f83727
  · exact f67067
  · exact f94137
  · exact f21005
  · exact f93720
  · exact f79244
  · exact f51724
  · exact f86480

theorem edges_interval_448 : ∀ i : Fin 1755, 448 ≤ i.val → i.val < 512 →
    ∀ a : ParrottGenerator,
      (CosetEnumeration.Fact.mk (index i) [(a, true)]
        (index (table i (a, true)))).Valid parrottGenerator parrottR1Subgroup input :=
  (interval_join (mid := 480) (interval_join (mid := 464) (interval_join (mid := 456) (interval_join (mid := 452) (interval_join (mid := 450) (interval_join (mid := 449) (interval_singleton (by decide) edges_row_448) (interval_singleton (by decide) edges_row_449)) (interval_join (mid := 451) (interval_singleton (by decide) edges_row_450) (interval_singleton (by decide) edges_row_451))) (interval_join (mid := 454) (interval_join (mid := 453) (interval_singleton (by decide) edges_row_452) (interval_singleton (by decide) edges_row_453)) (interval_join (mid := 455) (interval_singleton (by decide) edges_row_454) (interval_singleton (by decide) edges_row_455)))) (interval_join (mid := 460) (interval_join (mid := 458) (interval_join (mid := 457) (interval_singleton (by decide) edges_row_456) (interval_singleton (by decide) edges_row_457)) (interval_join (mid := 459) (interval_singleton (by decide) edges_row_458) (interval_singleton (by decide) edges_row_459))) (interval_join (mid := 462) (interval_join (mid := 461) (interval_singleton (by decide) edges_row_460) (interval_singleton (by decide) edges_row_461)) (interval_join (mid := 463) (interval_singleton (by decide) edges_row_462) (interval_singleton (by decide) edges_row_463))))) (interval_join (mid := 472) (interval_join (mid := 468) (interval_join (mid := 466) (interval_join (mid := 465) (interval_singleton (by decide) edges_row_464) (interval_singleton (by decide) edges_row_465)) (interval_join (mid := 467) (interval_singleton (by decide) edges_row_466) (interval_singleton (by decide) edges_row_467))) (interval_join (mid := 470) (interval_join (mid := 469) (interval_singleton (by decide) edges_row_468) (interval_singleton (by decide) edges_row_469)) (interval_join (mid := 471) (interval_singleton (by decide) edges_row_470) (interval_singleton (by decide) edges_row_471)))) (interval_join (mid := 476) (interval_join (mid := 474) (interval_join (mid := 473) (interval_singleton (by decide) edges_row_472) (interval_singleton (by decide) edges_row_473)) (interval_join (mid := 475) (interval_singleton (by decide) edges_row_474) (interval_singleton (by decide) edges_row_475))) (interval_join (mid := 478) (interval_join (mid := 477) (interval_singleton (by decide) edges_row_476) (interval_singleton (by decide) edges_row_477)) (interval_join (mid := 479) (interval_singleton (by decide) edges_row_478) (interval_singleton (by decide) edges_row_479)))))) (interval_join (mid := 496) (interval_join (mid := 488) (interval_join (mid := 484) (interval_join (mid := 482) (interval_join (mid := 481) (interval_singleton (by decide) edges_row_480) (interval_singleton (by decide) edges_row_481)) (interval_join (mid := 483) (interval_singleton (by decide) edges_row_482) (interval_singleton (by decide) edges_row_483))) (interval_join (mid := 486) (interval_join (mid := 485) (interval_singleton (by decide) edges_row_484) (interval_singleton (by decide) edges_row_485)) (interval_join (mid := 487) (interval_singleton (by decide) edges_row_486) (interval_singleton (by decide) edges_row_487)))) (interval_join (mid := 492) (interval_join (mid := 490) (interval_join (mid := 489) (interval_singleton (by decide) edges_row_488) (interval_singleton (by decide) edges_row_489)) (interval_join (mid := 491) (interval_singleton (by decide) edges_row_490) (interval_singleton (by decide) edges_row_491))) (interval_join (mid := 494) (interval_join (mid := 493) (interval_singleton (by decide) edges_row_492) (interval_singleton (by decide) edges_row_493)) (interval_join (mid := 495) (interval_singleton (by decide) edges_row_494) (interval_singleton (by decide) edges_row_495))))) (interval_join (mid := 504) (interval_join (mid := 500) (interval_join (mid := 498) (interval_join (mid := 497) (interval_singleton (by decide) edges_row_496) (interval_singleton (by decide) edges_row_497)) (interval_join (mid := 499) (interval_singleton (by decide) edges_row_498) (interval_singleton (by decide) edges_row_499))) (interval_join (mid := 502) (interval_join (mid := 501) (interval_singleton (by decide) edges_row_500) (interval_singleton (by decide) edges_row_501)) (interval_join (mid := 503) (interval_singleton (by decide) edges_row_502) (interval_singleton (by decide) edges_row_503)))) (interval_join (mid := 508) (interval_join (mid := 506) (interval_join (mid := 505) (interval_singleton (by decide) edges_row_504) (interval_singleton (by decide) edges_row_505)) (interval_join (mid := 507) (interval_singleton (by decide) edges_row_506) (interval_singleton (by decide) edges_row_507))) (interval_join (mid := 510) (interval_join (mid := 509) (interval_singleton (by decide) edges_row_508) (interval_singleton (by decide) edges_row_509)) (interval_join (mid := 511) (interval_singleton (by decide) edges_row_510) (interval_singleton (by decide) edges_row_511)))))))

end Tits.R1Certificate
