module

public import Theory.SpecificGroups.Tits.R1Certificate.Table
public import Theory.SpecificGroups.Tits.R1Certificate.Chunk151000

/-!
# Actual-group edges for rows 1472 through 1535

Literal data and kernel-checked finite assembly for the Parrott R₁ coset
certificate. Source: Parrott (1972), §5, p. 683. Generated by
`refs/original/n-group-global/parrott-r1-certificate/emit_table.py`.
-/

@[expose] public section
namespace Tits.R1Certificate
open Theory.GroupTheory Theory.GroupTheory.CosetEnumeration

attribute [local irreducible] input

theorem edges_row_1472 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1472) [(a, true)]
      (index (table 1472 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f111387
  · exact f111304
  · exact f111278
  · exact f111288
  · exact f111361
  · exact f111298
  · exact f111311
  · exact f111371
  · exact f111251
  · exact f127116

theorem edges_row_1473 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1473) [(a, true)]
      (index (table 1473 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f132839
  · exact f139293
  · exact f136644
  · exact f144024
  · exact f136677
  · exact f136033
  · exact f136055
  · exact f132887
  · exact f136002
  · exact f111424

theorem edges_row_1474 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1474) [(a, true)]
      (index (table 1474 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f112883
  · exact f149825
  · exact f111454
  · exact f151056
  · exact f123873
  · exact f123900
  · exact f123820
  · exact f129043
  · exact f135813
  · exact f111429

theorem edges_row_1475 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1475) [(a, true)]
      (index (table 1475 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f121815
  · exact f111515
  · exact f111475
  · exact f111485
  · exact f111561
  · exact f111495
  · exact f111522
  · exact f111579
  · exact f111462
  · exact f144942

theorem edges_row_1476 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1476) [(a, true)]
      (index (table 1476 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f111651
  · exact f117998
  · exact f111646
  · exact f129005
  · exact f120944
  · exact f111656
  · exact f121101
  · exact f151057
  · exact f145350
  · exact f111615

theorem edges_row_1477 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1477) [(a, true)]
      (index (table 1477 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f111666
  · exact f111765
  · exact f111770
  · exact f111724
  · exact f111781
  · exact f111673
  · exact f111755
  · exact f111694
  · exact f111746
  · exact f111985

theorem edges_row_1478 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1478) [(a, true)]
      (index (table 1478 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f130945
  · exact f111906
  · exact f111858
  · exact f112123
  · exact f115985
  · exact f111890
  · exact f111880
  · exact f111920
  · exact f114139
  · exact f148849

theorem edges_row_1479 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1479) [(a, true)]
      (index (table 1479 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f111979
  · exact f119098
  · exact f116064
  · exact f134060
  · exact f116057
  · exact f111992
  · exact f112002
  · exact f116795
  · exact f119156
  · exact f112017

theorem edges_row_1480 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1480) [(a, true)]
      (index (table 1480 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f112108
  · exact f112115
  · exact f112042
  · exact f112086
  · exact f112030
  · exact f112074
  · exact f112064
  · exact f112157
  · exact f112170
  · exact f125427

theorem edges_row_1481 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1481) [(a, true)]
      (index (table 1481 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f112232
  · exact f124978
  · exact f119789
  · exact f123935
  · exact f122572
  · exact f151060
  · exact f122963
  · exact f112243
  · exact f125006
  · exact f112220

theorem edges_row_1482 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1482) [(a, true)]
      (index (table 1482 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f112247
  · exact f120177
  · exact f115809
  · exact f118562
  · exact f112291
  · exact f138686
  · exact f115855
  · exact f112270
  · exact f149759
  · exact f112265

theorem edges_row_1483 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1483) [(a, true)]
      (index (table 1483 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f112460
  · exact f112512
  · exact f112401
  · exact f112471
  · exact f112502
  · exact f112427
  · exact f112389
  · exact f112480
  · exact f112525
  · exact f133369

theorem edges_row_1484 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1484) [(a, true)]
      (index (table 1484 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f112592
  · exact f112559
  · exact f112587
  · exact f124947
  · exact f112607
  · exact f118013
  · exact f151062
  · exact f123715
  · exact f113065
  · exact f112568

theorem edges_row_1485 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1485) [(a, true)]
      (index (table 1485 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f112768
  · exact f112775
  · exact f112722
  · exact f112746
  · exact f119643
  · exact f112790
  · exact f112800
  · exact f121803
  · exact f140645
  · exact f112735

theorem edges_row_1486 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1486) [(a, true)]
      (index (table 1486 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f112853
  · exact f123760
  · exact f112839
  · exact f112826
  · exact f112869
  · exact f129031
  · exact f128837
  · exact f123953
  · exact f146308
  · exact f112847

theorem edges_row_1487 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1487) [(a, true)]
      (index (table 1487 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f116107
  · exact f116135
  · exact f116069
  · exact f141962
  · exact f112891
  · exact f138838
  · exact f151063
  · exact f141895
  · exact f117375
  · exact f116095

theorem edges_row_1488 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1488) [(a, true)]
      (index (table 1488 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f112946
  · exact f148142
  · exact f112899
  · exact f146963
  · exact f125399
  · exact f112956
  · exact f112893
  · exact f144223
  · exact f128079
  · exact f112927

theorem edges_row_1489 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1489) [(a, true)]
      (index (table 1489 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f112997
  · exact f113043
  · exact f112981
  · exact f134133
  · exact f139608
  · exact f133580
  · exact f112971
  · exact f151064
  · exact f117605
  · exact f113014

theorem edges_row_1490 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1490) [(a, true)]
      (index (table 1490 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f135983
  · exact f113058
  · exact f135985
  · exact f135987
  · exact f135989
  · exact f135990
  · exact f135992
  · exact f135994
  · exact f113051
  · exact f135996

theorem edges_row_1491 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1491) [(a, true)]
      (index (table 1491 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f113111
  · exact f113079
  · exact f151065
  · exact f113099
  · exact f124155
  · exact f121519
  · exact f113133
  · exact f131472
  · exact f117411
  · exact f113070

theorem edges_row_1492 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1492) [(a, true)]
      (index (table 1492 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f113173
  · exact f117718
  · exact f113168
  · exact f136754
  · exact f120714
  · exact f117833
  · exact f113187
  · exact f113193
  · exact f117857
  · exact f113137

theorem edges_row_1493 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1493) [(a, true)]
      (index (table 1493 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f113279
  · exact f113306
  · exact f113204
  · exact f113211
  · exact f113223
  · exact f113336
  · exact f113700
  · exact f113245
  · exact f113269
  · exact f134607

theorem edges_row_1494 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1494) [(a, true)]
      (index (table 1494 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f113357
  · exact f123890
  · exact f118431
  · exact f121369
  · exact f139298
  · exact f140084
  · exact f146268
  · exact f113368
  · exact f146562
  · exact f113345

theorem edges_row_1495 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1495) [(a, true)]
      (index (table 1495 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f113425
  · exact f113399
  · exact f124713
  · exact f151066
  · exact f124776
  · exact f151068
  · exact f124749
  · exact f134432
  · exact f132821
  · exact f113390

theorem edges_row_1496 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1496) [(a, true)]
      (index (table 1496 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f113507
  · exact f123339
  · exact f113502
  · exact f137179
  · exact f144909
  · exact f149096
  · exact f148519
  · exact f113518
  · exact f123508
  · exact f113471

theorem edges_row_1497 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1497) [(a, true)]
      (index (table 1497 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f113575
  · exact f113531
  · exact f140386
  · exact f113563
  · exact f147871
  · exact f113580
  · exact f124801
  · exact f122539
  · exact f132531
  · exact f113522

theorem edges_row_1498 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1498) [(a, true)]
      (index (table 1498 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f113652
  · exact f122556
  · exact f113640
  · exact f113610
  · exact f126436
  · exact f113657
  · exact f121068
  · exact f113667
  · exact f123574
  · exact f113601

theorem edges_row_1499 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1499) [(a, true)]
      (index (table 1499 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f113725
  · exact f113738
  · exact f113676
  · exact f114345
  · exact f113683
  · exact f113812
  · exact f113695
  · exact f113760
  · exact f113715
  · exact f125500

theorem edges_row_1500 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1500) [(a, true)]
      (index (table 1500 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f113828
  · exact f131301
  · exact f120904
  · exact f146548
  · exact f124499
  · exact f146792
  · exact f124781
  · exact f113848
  · exact f130373
  · exact f113816

theorem edges_row_1501 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1501) [(a, true)]
      (index (table 1501 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f113876
  · exact f124254
  · exact f113852
  · exact f148719
  · exact f132080
  · exact f148844
  · exact f120223
  · exact f118633
  · exact f124922
  · exact f113866

theorem edges_row_1502 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1502) [(a, true)]
      (index (table 1502 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f151071
  · exact f113967
  · exact f148821
  · exact f113912
  · exact f113923
  · exact f113929
  · exact f149255
  · exact f113941
  · exact f124079
  · exact f113955

theorem edges_row_1503 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1503) [(a, true)]
      (index (table 1503 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f132223
  · exact f146723
  · exact f132142
  · exact f132177
  · exact f147774
  · exact f132240
  · exact f132208
  · exact f138277
  · exact f139575
  · exact f132199

theorem edges_row_1504 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1504) [(a, true)]
      (index (table 1504 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f137947
  · exact f114028
  · exact f113990
  · exact f143745
  · exact f113984
  · exact f114038
  · exact f148668
  · exact f130067
  · exact f136463
  · exact f114008

theorem edges_row_1505 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1505) [(a, true)]
      (index (table 1505 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f128657
  · exact f122307
  · exact f120239
  · exact f127994
  · exact f120245
  · exact f127698
  · exact f122269
  · exact f146347
  · exact f122294
  · exact f120257

theorem edges_row_1506 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1506) [(a, true)]
      (index (table 1506 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f132909
  · exact f132968
  · exact f149768
  · exact f132869
  · exact f132937
  · exact f132833
  · exact f132962
  · exact f132904
  · exact f114051
  · exact f132921

theorem edges_row_1507 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1507) [(a, true)]
      (index (table 1507 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f148077
  · exact f114117
  · exact f114071
  · exact f114095
  · exact f114059
  · exact f114198
  · exact f114083
  · exact f114176
  · exact f114189
  · exact f141941

theorem edges_row_1508 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1508) [(a, true)]
      (index (table 1508 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f114249
  · exact f114268
  · exact f140048
  · exact f145920
  · exact f137354
  · exact f121054
  · exact f132390
  · exact f139722
  · exact f128717
  · exact f114261

theorem edges_row_1509 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1509) [(a, true)]
      (index (table 1509 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f128820
  · exact f114400
  · exact f114290
  · exact f114379
  · exact f114308
  · exact f114330
  · exact f114278
  · exact f114406
  · exact f114368
  · exact f127688

theorem edges_row_1510 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1510) [(a, true)]
      (index (table 1510 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f145886
  · exact f114420
  · exact f140797
  · exact f147333
  · exact f129070
  · exact f148467
  · exact f129095
  · exact f133200
  · exact f128100
  · exact f114410

theorem edges_row_1511 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1511) [(a, true)]
      (index (table 1511 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f118062
  · exact f114501
  · exact f114482
  · exact f114446
  · exact f114567
  · exact f114456
  · exact f114508
  · exact f114551
  · exact f114436
  · exact f146412

theorem edges_row_1512 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1512) [(a, true)]
      (index (table 1512 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f136747
  · exact f121319
  · exact f140251
  · exact f151073
  · exact f124850
  · exact f117699
  · exact f128130
  · exact f124688
  · exact f128387
  · exact f114605

theorem edges_row_1513 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1513) [(a, true)]
      (index (table 1513 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f116759
  · exact f114700
  · exact f114640
  · exact f114684
  · exact f114628
  · exact f114672
  · exact f114662
  · exact f114748
  · exact f114761
  · exact f114775

theorem edges_row_1514 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1514) [(a, true)]
      (index (table 1514 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f114806
  · exact f133233
  · exact f138574
  · exact f114801
  · exact f138509
  · exact f130792
  · exact f130798
  · exact f114818
  · exact f130701
  · exact f114780

theorem edges_row_1515 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1515) [(a, true)]
      (index (table 1515 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f145571
  · exact f147584
  · exact f119046
  · exact f141103
  · exact f124525
  · exact f136035
  · exact f127573
  · exact f149939
  · exact f129274
  · exact f114822

theorem edges_row_1516 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1516) [(a, true)]
      (index (table 1516 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f134363
  · exact f114827
  · exact f114867
  · exact f114834
  · exact f114893
  · exact f114846
  · exact f114930
  · exact f114898
  · exact f114886
  · exact f148370

theorem edges_row_1517 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1517) [(a, true)]
      (index (table 1517 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f115025
  · exact f115049
  · exact f114934
  · exact f114941
  · exact f115105
  · exact f115111
  · exact f114959
  · exact f114975
  · exact f115000
  · exact f115114

theorem edges_row_1518 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1518) [(a, true)]
      (index (table 1518 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f121979
  · exact f115183
  · exact f115133
  · exact f115169
  · exact f115121
  · exact f115157
  · exact f115145
  · exact f115685
  · exact f115235
  · exact f142829

theorem edges_row_1519 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1519) [(a, true)]
      (index (table 1519 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f129580
  · exact f139085
  · exact f143143
  · exact f129399
  · exact f144190
  · exact f139805
  · exact f138791
  · exact f140266
  · exact f139033
  · exact f115239

theorem edges_row_1520 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1520) [(a, true)]
      (index (table 1520 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f115308
  · exact f115314
  · exact f115267
  · exact f115257
  · exact f115338
  · exact f115244
  · exact f115302
  · exact f115348
  · exact f115280
  · exact f144636

theorem edges_row_1521 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1521) [(a, true)]
      (index (table 1521 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f122845
  · exact f115366
  · exact f115406
  · exact f115373
  · exact f115432
  · exact f115386
  · exact f115477
  · exact f151074
  · exact f115425
  · exact f135623

theorem edges_row_1522 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1522) [(a, true)]
      (index (table 1522 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f119174
  · exact f115571
  · exact f115499
  · exact f115533
  · exact f115584
  · exact f115558
  · exact f115604
  · exact f115624
  · exact f115479
  · exact f142519

theorem edges_row_1523 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1523) [(a, true)]
      (index (table 1523 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f115787
  · exact f115714
  · exact f115628
  · exact f115635
  · exact f115647
  · exact f115754
  · exact f115659
  · exact f115675
  · exact f115700
  · exact f137184

theorem edges_row_1524 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1524) [(a, true)]
      (index (table 1524 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f115871
  · exact f115890
  · exact f115944
  · exact f116022
  · exact f116042
  · exact f151076
  · exact f116031
  · exact f115966
  · exact f116003
  · exact f122805

theorem edges_row_1525 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1525) [(a, true)]
      (index (table 1525 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f116327
  · exact f116226
  · exact f116150
  · exact f116157
  · exact f116283
  · exact f116312
  · exact f116175
  · exact f116191
  · exact f116213
  · exact f144249

theorem edges_row_1526 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1526) [(a, true)]
      (index (table 1526 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f117915
  · exact f116436
  · exact f116366
  · exact f116422
  · exact f116354
  · exact f116410
  · exact f116400
  · exact f116484
  · exact f116497
  · exact f142162

theorem edges_row_1527 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1527) [(a, true)]
      (index (table 1527 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f116542
  · exact f136868
  · exact f116523
  · exact f116537
  · exact f116572
  · exact f116547
  · exact f116557
  · exact f149489
  · exact f122361
  · exact f116504

theorem edges_row_1528 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1528) [(a, true)]
      (index (table 1528 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f116708
  · exact f116721
  · exact f116608
  · exact f116615
  · exact f119497
  · exact f116688
  · exact f116633
  · exact f116649
  · exact f116663
  · exact f123245

theorem edges_row_1529 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1529) [(a, true)]
      (index (table 1529 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f116791
  · exact f116773
  · exact f142424
  · exact f126615
  · exact f116811
  · exact f126081
  · exact f138973
  · exact f116817
  · exact f128174
  · exact f116764

theorem edges_row_1530 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1530) [(a, true)]
      (index (table 1530 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f129750
  · exact f116821
  · exact f116859
  · exact f116828
  · exact f116885
  · exact f116840
  · exact f116930
  · exact f116897
  · exact f116878
  · exact f135239

theorem edges_row_1531 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1531) [(a, true)]
      (index (table 1531 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f116935
  · exact f116992
  · exact f116948
  · exact f139853
  · exact f116985
  · exact f129363
  · exact f138428
  · exact f129653
  · exact f126008
  · exact f116980

theorem edges_row_1532 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1532) [(a, true)]
      (index (table 1532 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f117079
  · exact f117023
  · exact f117053
  · exact f117067
  · exact f151078
  · exact f117087
  · exact f117107
  · exact f117082
  · exact f128778
  · exact f117004

theorem edges_row_1533 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1533) [(a, true)]
      (index (table 1533 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f117168
  · exact f117149
  · exact f125238
  · exact f144959
  · exact f142387
  · exact f117173
  · exact f125250
  · exact f149188
  · exact f127851
  · exact f117139

theorem edges_row_1534 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1534) [(a, true)]
      (index (table 1534 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f117225
  · exact f151079
  · exact f151080
  · exact f124662
  · exact f117302
  · exact f117238
  · exact f117285
  · exact f134509
  · exact f151082
  · exact f117249

theorem edges_row_1535 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1535) [(a, true)]
      (index (table 1535 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f124699
  · exact f117315
  · exact f117339
  · exact f117747
  · exact f132372
  · exact f136780
  · exact f121964
  · exact f126167
  · exact f128148
  · exact f117306

theorem edges_interval_1472 : ∀ i : Fin 1755, 1472 ≤ i.val → i.val < 1536 →
    ∀ a : ParrottGenerator,
      (CosetEnumeration.Fact.mk (index i) [(a, true)]
        (index (table i (a, true)))).Valid parrottGenerator parrottR1Subgroup input :=
  (interval_join (mid := 1504) (interval_join (mid := 1488) (interval_join (mid := 1480) (interval_join (mid := 1476) (interval_join (mid := 1474) (interval_join (mid := 1473) (interval_singleton (by decide) edges_row_1472) (interval_singleton (by decide) edges_row_1473)) (interval_join (mid := 1475) (interval_singleton (by decide) edges_row_1474) (interval_singleton (by decide) edges_row_1475))) (interval_join (mid := 1478) (interval_join (mid := 1477) (interval_singleton (by decide) edges_row_1476) (interval_singleton (by decide) edges_row_1477)) (interval_join (mid := 1479) (interval_singleton (by decide) edges_row_1478) (interval_singleton (by decide) edges_row_1479)))) (interval_join (mid := 1484) (interval_join (mid := 1482) (interval_join (mid := 1481) (interval_singleton (by decide) edges_row_1480) (interval_singleton (by decide) edges_row_1481)) (interval_join (mid := 1483) (interval_singleton (by decide) edges_row_1482) (interval_singleton (by decide) edges_row_1483))) (interval_join (mid := 1486) (interval_join (mid := 1485) (interval_singleton (by decide) edges_row_1484) (interval_singleton (by decide) edges_row_1485)) (interval_join (mid := 1487) (interval_singleton (by decide) edges_row_1486) (interval_singleton (by decide) edges_row_1487))))) (interval_join (mid := 1496) (interval_join (mid := 1492) (interval_join (mid := 1490) (interval_join (mid := 1489) (interval_singleton (by decide) edges_row_1488) (interval_singleton (by decide) edges_row_1489)) (interval_join (mid := 1491) (interval_singleton (by decide) edges_row_1490) (interval_singleton (by decide) edges_row_1491))) (interval_join (mid := 1494) (interval_join (mid := 1493) (interval_singleton (by decide) edges_row_1492) (interval_singleton (by decide) edges_row_1493)) (interval_join (mid := 1495) (interval_singleton (by decide) edges_row_1494) (interval_singleton (by decide) edges_row_1495)))) (interval_join (mid := 1500) (interval_join (mid := 1498) (interval_join (mid := 1497) (interval_singleton (by decide) edges_row_1496) (interval_singleton (by decide) edges_row_1497)) (interval_join (mid := 1499) (interval_singleton (by decide) edges_row_1498) (interval_singleton (by decide) edges_row_1499))) (interval_join (mid := 1502) (interval_join (mid := 1501) (interval_singleton (by decide) edges_row_1500) (interval_singleton (by decide) edges_row_1501)) (interval_join (mid := 1503) (interval_singleton (by decide) edges_row_1502) (interval_singleton (by decide) edges_row_1503)))))) (interval_join (mid := 1520) (interval_join (mid := 1512) (interval_join (mid := 1508) (interval_join (mid := 1506) (interval_join (mid := 1505) (interval_singleton (by decide) edges_row_1504) (interval_singleton (by decide) edges_row_1505)) (interval_join (mid := 1507) (interval_singleton (by decide) edges_row_1506) (interval_singleton (by decide) edges_row_1507))) (interval_join (mid := 1510) (interval_join (mid := 1509) (interval_singleton (by decide) edges_row_1508) (interval_singleton (by decide) edges_row_1509)) (interval_join (mid := 1511) (interval_singleton (by decide) edges_row_1510) (interval_singleton (by decide) edges_row_1511)))) (interval_join (mid := 1516) (interval_join (mid := 1514) (interval_join (mid := 1513) (interval_singleton (by decide) edges_row_1512) (interval_singleton (by decide) edges_row_1513)) (interval_join (mid := 1515) (interval_singleton (by decide) edges_row_1514) (interval_singleton (by decide) edges_row_1515))) (interval_join (mid := 1518) (interval_join (mid := 1517) (interval_singleton (by decide) edges_row_1516) (interval_singleton (by decide) edges_row_1517)) (interval_join (mid := 1519) (interval_singleton (by decide) edges_row_1518) (interval_singleton (by decide) edges_row_1519))))) (interval_join (mid := 1528) (interval_join (mid := 1524) (interval_join (mid := 1522) (interval_join (mid := 1521) (interval_singleton (by decide) edges_row_1520) (interval_singleton (by decide) edges_row_1521)) (interval_join (mid := 1523) (interval_singleton (by decide) edges_row_1522) (interval_singleton (by decide) edges_row_1523))) (interval_join (mid := 1526) (interval_join (mid := 1525) (interval_singleton (by decide) edges_row_1524) (interval_singleton (by decide) edges_row_1525)) (interval_join (mid := 1527) (interval_singleton (by decide) edges_row_1526) (interval_singleton (by decide) edges_row_1527)))) (interval_join (mid := 1532) (interval_join (mid := 1530) (interval_join (mid := 1529) (interval_singleton (by decide) edges_row_1528) (interval_singleton (by decide) edges_row_1529)) (interval_join (mid := 1531) (interval_singleton (by decide) edges_row_1530) (interval_singleton (by decide) edges_row_1531))) (interval_join (mid := 1534) (interval_join (mid := 1533) (interval_singleton (by decide) edges_row_1532) (interval_singleton (by decide) edges_row_1533)) (interval_join (mid := 1535) (interval_singleton (by decide) edges_row_1534) (interval_singleton (by decide) edges_row_1535)))))))

end Tits.R1Certificate
