module

public import Theory.SpecificGroups.Tits.R1Certificate.Table
public import Theory.SpecificGroups.Tits.R1Certificate.Chunk151000

/-!
# Actual-group edges for rows 1728 through 1754

Literal data and kernel-checked finite assembly for the Parrott R₁ coset
certificate. Source: Parrott (1972), §5, p. 683. Generated by
`refs/original/n-group-global/parrott-r1-certificate/emit_table.py`.
-/

@[expose] public section
namespace Tits.R1Certificate
open Theory.GroupTheory Theory.GroupTheory.CosetEnumeration

attribute [local irreducible] input

theorem edges_row_1728 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1728) [(a, true)]
      (index (table 1728 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f145631
  · exact f145523
  · exact f145483
  · exact f145583
  · exact f145471
  · exact f145496
  · exact f145516
  · exact f145638
  · exact f145596
  · exact f145620

theorem edges_row_1729 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1729) [(a, true)]
      (index (table 1729 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f145748
  · exact f145818
  · exact f145658
  · exact f145777
  · exact f145676
  · exact f145709
  · exact f145646
  · exact f145786
  · exact f145765
  · exact f145807

theorem edges_row_1730 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1730) [(a, true)]
      (index (table 1730 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f145943
  · exact f145900
  · exact f145871
  · exact f145857
  · exact f145932
  · exact f146057
  · exact f145907
  · exact f145958
  · exact f145981
  · exact f145965

theorem edges_row_1731 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1731) [(a, true)]
      (index (table 1731 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f146087
  · exact f146094
  · exact f146013
  · exact f146048
  · exact f146121
  · exact f146109
  · exact f146115
  · exact f146135
  · exact f145994
  · exact f146156

theorem edges_row_1732 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1732) [(a, true)]
      (index (table 1732 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f146259
  · exact f146234
  · exact f146210
  · exact f146226
  · exact f146264
  · exact f146323
  · exact f146274
  · exact f146296
  · exact f146287
  · exact f146183

theorem edges_row_1733 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1733) [(a, true)]
      (index (table 1733 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f146446
  · exact f146327
  · exact f146373
  · exact f146342
  · exact f146399
  · exact f146354
  · exact f146460
  · exact f146418
  · exact f146392
  · exact f146336

theorem edges_row_1734 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1734) [(a, true)]
      (index (table 1734 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f146634
  · exact f146540
  · exact f146480
  · exact f146525
  · exact f146468
  · exact f146513
  · exact f146503
  · exact f146588
  · exact f146601
  · exact f146625

theorem edges_row_1735 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1735) [(a, true)]
      (index (table 1735 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f146729
  · exact f146704
  · exact f146680
  · exact f146696
  · exact f146739
  · exact f146798
  · exact f146749
  · exact f146758
  · exact f146771
  · exact f146653

theorem edges_row_1736 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1736) [(a, true)]
      (index (table 1736 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f146878
  · exact f146853
  · exact f146829
  · exact f146845
  · exact f146888
  · exact f146947
  · exact f146898
  · exact f146907
  · exact f146920
  · exact f146802

theorem edges_row_1737 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1737) [(a, true)]
      (index (table 1737 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f147053
  · exact f147066
  · exact f146951
  · exact f146958
  · exact f146970
  · exact f147116
  · exact f149995
  · exact f146992
  · exact f147015
  · exact f147028

theorem edges_row_1738 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1738) [(a, true)]
      (index (table 1738 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f147165
  · exact f147146
  · exact f147211
  · exact f147179
  · exact f147237
  · exact f147191
  · exact f147304
  · exact f147273
  · exact f147230
  · exact f147173

theorem edges_row_1739 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1739) [(a, true)]
      (index (table 1739 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f147455
  · exact f147461
  · exact f147318
  · exact f147425
  · exact f147306
  · exact f147433
  · exact f147372
  · exact f147470
  · exact f147413
  · exact f147482

theorem edges_row_1740 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1740) [(a, true)]
      (index (table 1740 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f147634
  · exact f147640
  · exact f147508
  · exact f147605
  · exact f147496
  · exact f147613
  · exact f147562
  · exact f147649
  · exact f147662
  · exact f147674

theorem edges_row_1741 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1741) [(a, true)]
      (index (table 1741 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f147765
  · exact f147728
  · exact f147703
  · exact f151165
  · exact f147770
  · exact f147835
  · exact f147780
  · exact f147795
  · exact f147808
  · exact f147689

theorem edges_row_1742 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1742) [(a, true)]
      (index (table 1742 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f148036
  · exact f147982
  · exact f147878
  · exact f147962
  · exact f147866
  · exact f147970
  · exact f147919
  · exact f147991
  · exact f148004
  · exact f148016

theorem edges_row_1743 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1743) [(a, true)]
      (index (table 1743 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f148123
  · exact f148207
  · exact f148050
  · exact f148148
  · exact f148068
  · exact f148114
  · exact f148038
  · exact f148162
  · exact f148137
  · exact f148184

theorem edges_row_1744 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1744) [(a, true)]
      (index (table 1744 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f148296
  · exact f148303
  · exact f148227
  · exact f148271
  · exact f148215
  · exact f148259
  · exact f148249
  · exact f148347
  · exact f148359
  · exact f148383

theorem edges_row_1745 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1745) [(a, true)]
      (index (table 1745 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f148480
  · exact f148487
  · exact f148413
  · exact f148460
  · exact f148401
  · exact f148448
  · exact f148437
  · exact f148550
  · exact f148562
  · exact f148586

theorem edges_row_1746 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1746) [(a, true)]
      (index (table 1746 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f148685
  · exact f149161
  · exact f148603
  · exact f148590
  · exact f148613
  · exact f148633
  · exact f149545
  · exact f148645
  · exact f148679
  · exact f148659

theorem edges_row_1747 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1747) [(a, true)]
      (index (table 1747 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f148776
  · exact f148782
  · exact f148817
  · exact f148727
  · exact f148830
  · exact f148712
  · exact f148807
  · exact f148735
  · exact f148748
  · exact f148842

theorem edges_row_1748 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1748) [(a, true)]
      (index (table 1748 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f148937
  · exact f148943
  · exact f148885
  · exact f148867
  · exact f148976
  · exact f148854
  · exact f148931
  · exact f148875
  · exact f148911
  · exact f148988

theorem edges_row_1749 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1749) [(a, true)]
      (index (table 1749 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f149129
  · exact f149234
  · exact f149066
  · exact f149179
  · exact f149109
  · exact f149119
  · exact f149054
  · exact f149198
  · exact f149155
  · exact f149222

theorem edges_row_1750 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1750) [(a, true)]
      (index (table 1750 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f149358
  · exact f149525
  · exact f149269
  · exact f149279
  · exact f149369
  · exact f149289
  · exact f149313
  · exact f149383
  · exact f149242
  · exact f149404

theorem edges_row_1751 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1751) [(a, true)]
      (index (table 1751 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f149531
  · exact f149506
  · exact f149482
  · exact f149498
  · exact f149541
  · exact f149600
  · exact f149551
  · exact f149560
  · exact f149573
  · exact f149455

theorem edges_row_1752 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1752) [(a, true)]
      (index (table 1752 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f149680
  · exact f149655
  · exact f149631
  · exact f149647
  · exact f149690
  · exact f149750
  · exact f149700
  · exact f149709
  · exact f149723
  · exact f149604

theorem edges_row_1753 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1753) [(a, true)]
      (index (table 1753 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f149831
  · exact f149806
  · exact f149782
  · exact f149798
  · exact f149841
  · exact f149901
  · exact f149851
  · exact f149860
  · exact f149873
  · exact f149754

theorem edges_row_1754 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 1754) [(a, true)]
      (index (table 1754 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f149981
  · exact f149956
  · exact f149932
  · exact f149948
  · exact f149991
  · exact f150050
  · exact f150001
  · exact f150010
  · exact f150023
  · exact f149905

theorem edges_interval_1728 : ∀ i : Fin 1755, 1728 ≤ i.val → i.val < 1755 →
    ∀ a : ParrottGenerator,
      (CosetEnumeration.Fact.mk (index i) [(a, true)]
        (index (table i (a, true)))).Valid parrottGenerator parrottR1Subgroup input :=
  (interval_join (mid := 1741) (interval_join (mid := 1734) (interval_join (mid := 1731) (interval_join (mid := 1729) (interval_singleton (by decide) edges_row_1728) (interval_join (mid := 1730) (interval_singleton (by decide) edges_row_1729) (interval_singleton (by decide) edges_row_1730))) (interval_join (mid := 1732) (interval_singleton (by decide) edges_row_1731) (interval_join (mid := 1733) (interval_singleton (by decide) edges_row_1732) (interval_singleton (by decide) edges_row_1733)))) (interval_join (mid := 1737) (interval_join (mid := 1735) (interval_singleton (by decide) edges_row_1734) (interval_join (mid := 1736) (interval_singleton (by decide) edges_row_1735) (interval_singleton (by decide) edges_row_1736))) (interval_join (mid := 1739) (interval_join (mid := 1738) (interval_singleton (by decide) edges_row_1737) (interval_singleton (by decide) edges_row_1738)) (interval_join (mid := 1740) (interval_singleton (by decide) edges_row_1739) (interval_singleton (by decide) edges_row_1740))))) (interval_join (mid := 1748) (interval_join (mid := 1744) (interval_join (mid := 1742) (interval_singleton (by decide) edges_row_1741) (interval_join (mid := 1743) (interval_singleton (by decide) edges_row_1742) (interval_singleton (by decide) edges_row_1743))) (interval_join (mid := 1746) (interval_join (mid := 1745) (interval_singleton (by decide) edges_row_1744) (interval_singleton (by decide) edges_row_1745)) (interval_join (mid := 1747) (interval_singleton (by decide) edges_row_1746) (interval_singleton (by decide) edges_row_1747)))) (interval_join (mid := 1751) (interval_join (mid := 1749) (interval_singleton (by decide) edges_row_1748) (interval_join (mid := 1750) (interval_singleton (by decide) edges_row_1749) (interval_singleton (by decide) edges_row_1750))) (interval_join (mid := 1753) (interval_join (mid := 1752) (interval_singleton (by decide) edges_row_1751) (interval_singleton (by decide) edges_row_1752)) (interval_join (mid := 1754) (interval_singleton (by decide) edges_row_1753) (interval_singleton (by decide) edges_row_1754))))))

end Tits.R1Certificate
