module

public import Theory.SpecificGroups.Tits.R1Certificate.Table
public import Theory.SpecificGroups.Tits.R1Certificate.Chunk146000

/-!
# Actual-group edges for rows 768 through 831

Literal data and kernel-checked finite assembly for the Parrott R₁ coset
certificate. Source: Parrott (1972), §5, p. 683. Generated by
`refs/original/n-group-global/parrott-r1-certificate/emit_table.py`.
-/

@[expose] public section
namespace Tits.R1Certificate
open Theory.GroupTheory Theory.GroupTheory.CosetEnumeration

attribute [local irreducible] input

theorem edges_row_768 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 768) [(a, true)]
      (index (table 768 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f150685
  · exact f83844
  · exact f24485
  · exact f75174
  · exact f98180
  · exact f87630
  · exact f57614
  · exact f110698
  · exact f63352
  · exact f113387

theorem edges_row_769 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 769) [(a, true)]
      (index (table 769 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f104297
  · exact f24497
  · exact f76813
  · exact f24490
  · exact f98006
  · exact f58770
  · exact f84764
  · exact f79215
  · exact f58721
  · exact f150687

theorem edges_row_770 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 770) [(a, true)]
      (index (table 770 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f103339
  · exact f103341
  · exact f98114
  · exact f98103
  · exact f80444
  · exact f103701
  · exact f99212
  · exact f103269
  · exact f90718
  · exact f113468

theorem edges_row_771 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 771) [(a, true)]
      (index (table 771 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f104279
  · exact f24532
  · exact f87620
  · exact f74676
  · exact f102139
  · exact f24525
  · exact f84817
  · exact f102511
  · exact f80542
  · exact f113519

theorem edges_row_772 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 772) [(a, true)]
      (index (table 772 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f106393
  · exact f24782
  · exact f72261
  · exact f54673
  · exact f99241
  · exact f67073
  · exact f24541
  · exact f107119
  · exact f48614
  · exact f113598

theorem edges_row_773 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 773) [(a, true)]
      (index (table 773 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f104273
  · exact f24557
  · exact f90815
  · exact f76295
  · exact f64038
  · exact f102523
  · exact f91810
  · exact f24545
  · exact f106279
  · exact f104302

theorem edges_row_774 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 774) [(a, true)]
      (index (table 774 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f95886
  · exact f24574
  · exact f113673
  · exact f95888
  · exact f98797
  · exact f95889
  · exact f57601
  · exact f50487
  · exact f24559
  · exact f113813

theorem edges_row_775 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 775) [(a, true)]
      (index (table 775 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f104320
  · exact f90869
  · exact f113849
  · exact f113909
  · exact f113981
  · exact f113584
  · exact f114039
  · exact f104354
  · exact f150689
  · exact f24578

theorem edges_row_776 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 776) [(a, true)]
      (index (table 776 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f78513
  · exact f86764
  · exact f86767
  · exact f86786
  · exact f78519
  · exact f150691
  · exact f78523
  · exact f78525
  · exact f78527
  · exact f78528

theorem edges_row_777 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 777) [(a, true)]
      (index (table 777 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f74932
  · exact f86619
  · exact f74934
  · exact f74936
  · exact f74938
  · exact f46945
  · exact f74942
  · exact f76673
  · exact f24743
  · exact f75069

theorem edges_row_778 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 778) [(a, true)]
      (index (table 778 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f24747
  · exact f110514
  · exact f75063
  · exact f60035
  · exact f150694
  · exact f60037
  · exact f76873
  · exact f45678
  · exact f60039
  · exact f70325

theorem edges_row_779 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 779) [(a, true)]
      (index (table 779 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f97571
  · exact f24752
  · exact f102356
  · exact f111543
  · exact f114052
  · exact f92171
  · exact f110293
  · exact f43008
  · exact f24759
  · exact f150695

theorem edges_row_780 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 780) [(a, true)]
      (index (table 780 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f75757
  · exact f111507
  · exact f56419
  · exact f66449
  · exact f72726
  · exact f72082
  · exact f68202
  · exact f24772
  · exact f68771
  · exact f65858

theorem edges_row_781 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 781) [(a, true)]
      (index (table 781 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f51743
  · exact f24786
  · exact f59132
  · exact f62175
  · exact f59150
  · exact f62179
  · exact f51745
  · exact f62176
  · exact f24777
  · exact f54719

theorem edges_row_782 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 782) [(a, true)]
      (index (table 782 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f60017
  · exact f109067
  · exact f60020
  · exact f52260
  · exact f77422
  · exact f77080
  · exact f65130
  · exact f60023
  · exact f150697
  · exact f24790

theorem edges_row_783 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 783) [(a, true)]
      (index (table 783 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f62998
  · exact f53561
  · exact f24834
  · exact f150698
  · exact f75670
  · exact f62999
  · exact f63001
  · exact f80841
  · exact f80842
  · exact f74774

theorem edges_row_784 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 784) [(a, true)]
      (index (table 784 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f67810
  · exact f87541
  · exact f66317
  · exact f66319
  · exact f72185
  · exact f69868
  · exact f24906
  · exact f80900
  · exact f150700
  · exact f76766

theorem edges_row_785 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 785) [(a, true)]
      (index (table 785 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f150701
  · exact f95757
  · exact f73099
  · exact f101762
  · exact f74803
  · exact f71389
  · exact f75034
  · exact f24910
  · exact f95846
  · exact f73091

theorem edges_row_786 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 786) [(a, true)]
      (index (table 786 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f51218
  · exact f24950
  · exact f67307
  · exact f24943
  · exact f80964
  · exact f56269
  · exact f65817
  · exact f51220
  · exact f86848
  · exact f56271

theorem edges_row_787 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 787) [(a, true)]
      (index (table 787 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f74090
  · exact f87338
  · exact f150702
  · exact f87120
  · exact f86770
  · exact f150704
  · exact f100068
  · exact f78460
  · exact f80535
  · exact f80343

theorem edges_row_788 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 788) [(a, true)]
      (index (table 788 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f82171
  · exact f24975
  · exact f81685
  · exact f107189
  · exact f75352
  · exact f79232
  · exact f110756
  · exact f79239
  · exact f75690
  · exact f90827

theorem edges_row_789 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 789) [(a, true)]
      (index (table 789 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f61261
  · exact f85473
  · exact f70549
  · exact f61265
  · exact f70816
  · exact f61267
  · exact f63552
  · exact f150707
  · exact f85516
  · exact f61272

theorem edges_row_790 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 790) [(a, true)]
      (index (table 790 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f150709
  · exact f96346
  · exact f65573
  · exact f65575
  · exact f87039
  · exact f66453
  · exact f65579
  · exact f65581
  · exact f65583
  · exact f77369

theorem edges_row_791 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 791) [(a, true)]
      (index (table 791 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f114246
  · exact f25009
  · exact f109012
  · exact f37903
  · exact f96801
  · exact f96232
  · exact f86201
  · exact f103643
  · exact f86282
  · exact f114407

theorem edges_row_792 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 792) [(a, true)]
      (index (table 792 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f57202
  · exact f85542
  · exact f25026
  · exact f57205
  · exact f25020
  · exact f57207
  · exact f57209
  · exact f57211
  · exact f72791
  · exact f57213

theorem edges_row_793 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 793) [(a, true)]
      (index (table 793 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f113143
  · exact f25082
  · exact f77248
  · exact f82448
  · exact f74596
  · exact f82441
  · exact f83000
  · exact f93031
  · exact f114429
  · exact f114602

theorem edges_row_794 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 794) [(a, true)]
      (index (table 794 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f74545
  · exact f74547
  · exact f74549
  · exact f74552
  · exact f74554
  · exact f25099
  · exact f74589
  · exact f74556
  · exact f74558
  · exact f74559

theorem edges_row_795 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 795) [(a, true)]
      (index (table 795 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f75656
  · exact f114494
  · exact f74532
  · exact f74534
  · exact f74536
  · exact f78679
  · exact f104018
  · exact f74539
  · exact f25108
  · exact f80256

theorem edges_row_796 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 796) [(a, true)]
      (index (table 796 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f25117
  · exact f89760
  · exact f71292
  · exact f71324
  · exact f57218
  · exact f57219
  · exact f57221
  · exact f57222
  · exact f71221
  · exact f150710

theorem edges_row_797 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 797) [(a, true)]
      (index (table 797 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f144688
  · exact f25122
  · exact f58190
  · exact f71189
  · exact f114621
  · exact f71165
  · exact f82779
  · exact f94202
  · exact f25129
  · exact f114777

theorem edges_row_798 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 798) [(a, true)]
      (index (table 798 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f71374
  · exact f94555
  · exact f57189
  · exact f100152
  · exact f78241
  · exact f57191
  · exact f25136
  · exact f57195
  · exact f71495
  · exact f82386

theorem edges_row_799 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 799) [(a, true)]
      (index (table 799 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f77982
  · exact f94112
  · exact f80399
  · exact f79964
  · exact f79996
  · exact f79879
  · exact f83350
  · exact f80389
  · exact f80074
  · exact f25152

theorem edges_row_800 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 800) [(a, true)]
      (index (table 800 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f104480
  · exact f25171
  · exact f82250
  · exact f88960
  · exact f88165
  · exact f64030
  · exact f110435
  · exact f107551
  · exact f94070
  · exact f114819

theorem edges_row_801 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 801) [(a, true)]
      (index (table 801 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f68694
  · exact f107528
  · exact f72639
  · exact f25182
  · exact f49453
  · exact f80949
  · exact f59285
  · exact f73185
  · exact f81256
  · exact f72946

theorem edges_row_802 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 802) [(a, true)]
      (index (table 802 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f65426
  · exact f85738
  · exact f66235
  · exact f65428
  · exact f25187
  · exact f65430
  · exact f65418
  · exact f65433
  · exact f66238
  · exact f65436

theorem edges_row_803 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 803) [(a, true)]
      (index (table 803 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f150715
  · exact f114824
  · exact f49448
  · exact f54003
  · exact f75365
  · exact f80067
  · exact f25200
  · exact f58360
  · exact f68310
  · exact f150717

theorem edges_row_804 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 804) [(a, true)]
      (index (table 804 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f104221
  · exact f25221
  · exact f114931
  · exact f93688
  · exact f115115
  · exact f93772
  · exact f93774
  · exact f103084
  · exact f50923
  · exact f115236

theorem edges_row_805 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 805) [(a, true)]
      (index (table 805 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f74011
  · exact f103063
  · exact f74014
  · exact f25226
  · exact f74017
  · exact f74019
  · exact f74021
  · exact f150719
  · exact f78969
  · exact f67354

theorem edges_row_806 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 806) [(a, true)]
      (index (table 806 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f58362
  · exact f100483
  · exact f57306
  · exact f58366
  · exact f25229
  · exact f100274
  · exact f50286
  · exact f58369
  · exact f62306
  · exact f58371

theorem edges_row_807 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 807) [(a, true)]
      (index (table 807 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f73718
  · exact f84743
  · exact f73693
  · exact f78396
  · exact f82491
  · exact f25289
  · exact f50948
  · exact f74981
  · exact f73719
  · exact f78976

theorem edges_row_808 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 808) [(a, true)]
      (index (table 808 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f76044
  · exact f87279
  · exact f76046
  · exact f76048
  · exact f76050
  · exact f76052
  · exact f76054
  · exact f76056
  · exact f76058
  · exact f25317

theorem edges_row_809 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 809) [(a, true)]
      (index (table 809 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f25322
  · exact f114156
  · exact f81375
  · exact f83872
  · exact f81379
  · exact f82324
  · exact f81433
  · exact f81382
  · exact f81384
  · exact f81386

theorem edges_row_810 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 810) [(a, true)]
      (index (table 810 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f81302
  · exact f107891
  · exact f25327
  · exact f78731
  · exact f81306
  · exact f73178
  · exact f81426
  · exact f78724
  · exact f71899
  · exact f82621

theorem edges_row_811 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 811) [(a, true)]
      (index (table 811 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f81347
  · exact f96548
  · exact f81349
  · exact f81351
  · exact f81353
  · exact f81354
  · exact f81356
  · exact f81358
  · exact f81360
  · exact f81362

theorem edges_row_812 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 812) [(a, true)]
      (index (table 812 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f81323
  · exact f84358
  · exact f81325
  · exact f81328
  · exact f81331
  · exact f25339
  · exact f81334
  · exact f81336
  · exact f81338
  · exact f81340

theorem edges_row_813 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 813) [(a, true)]
      (index (table 813 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f77976
  · exact f101466
  · exact f64549
  · exact f58495
  · exact f53629
  · exact f150723
  · exact f25441
  · exact f72823
  · exact f72833
  · exact f150724

theorem edges_row_814 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 814) [(a, true)]
      (index (table 814 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f81915
  · exact f89085
  · exact f81917
  · exact f81919
  · exact f81921
  · exact f81923
  · exact f81925
  · exact f81928
  · exact f25462
  · exact f81932

theorem edges_row_815 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 815) [(a, true)]
      (index (table 815 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f68902
  · exact f113793
  · exact f60669
  · exact f60671
  · exact f25574
  · exact f78659
  · exact f150726
  · exact f83465
  · exact f60678
  · exact f75148

theorem edges_row_816 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 816) [(a, true)]
      (index (table 816 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f48397
  · exact f111759
  · exact f76607
  · exact f63908
  · exact f76609
  · exact f48401
  · exact f71827
  · exact f48403
  · exact f61828
  · exact f48405

theorem edges_row_817 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 817) [(a, true)]
      (index (table 817 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f72584
  · exact f101684
  · exact f57777
  · exact f72538
  · exact f90750
  · exact f50624
  · exact f25578
  · exact f72590
  · exact f150727
  · exact f79107

theorem edges_row_818 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 818) [(a, true)]
      (index (table 818 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f71659
  · exact f86309
  · exact f71661
  · exact f71663
  · exact f71665
  · exact f59584
  · exact f75314
  · exact f62602
  · exact f86332
  · exact f25587

theorem edges_row_819 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 819) [(a, true)]
      (index (table 819 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f94021
  · exact f25609
  · exact f98227
  · exact f104560
  · exact f104529
  · exact f115241
  · exact f83066
  · exact f78823
  · exact f25645
  · exact f106354

theorem edges_row_820 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 820) [(a, true)]
      (index (table 820 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f48339
  · exact f115319
  · exact f51605
  · exact f150729
  · exact f72609
  · exact f25623
  · exact f150730
  · exact f150732
  · exact f100028
  · exact f73083

theorem edges_row_821 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 821) [(a, true)]
      (index (table 821 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f81098
  · exact f25638
  · exact f77236
  · exact f63633
  · exact f79305
  · exact f77294
  · exact f81100
  · exact f81102
  · exact f25631
  · exact f81104

theorem edges_row_822 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 822) [(a, true)]
      (index (table 822 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f52852
  · exact f95791
  · exact f62345
  · exact f150733
  · exact f75922
  · exact f73096
  · exact f73544
  · exact f75924
  · exact f75926
  · exact f25650

theorem edges_row_823 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 823) [(a, true)]
      (index (table 823 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f71002
  · exact f115363
  · exact f71004
  · exact f71007
  · exact f71009
  · exact f115381
  · exact f25669
  · exact f71012
  · exact f71014
  · exact f72484

theorem edges_row_824 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 824) [(a, true)]
      (index (table 824 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f150735
  · exact f92026
  · exact f61787
  · exact f61789
  · exact f61791
  · exact f61794
  · exact f61796
  · exact f100199
  · exact f92053
  · exact f61799

theorem edges_row_825 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 825) [(a, true)]
      (index (table 825 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f150737
  · exact f93206
  · exact f66302
  · exact f25684
  · exact f75310
  · exact f66306
  · exact f66308
  · exact f66310
  · exact f66312
  · exact f79910

theorem edges_row_826 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 826) [(a, true)]
      (index (table 826 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f75572
  · exact f25710
  · exact f75574
  · exact f75576
  · exact f75578
  · exact f75580
  · exact f75582
  · exact f75583
  · exact f78193
  · exact f75586

theorem edges_row_827 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 827) [(a, true)]
      (index (table 827 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f66275
  · exact f93178
  · exact f66277
  · exact f66279
  · exact f66281
  · exact f66283
  · exact f66285
  · exact f25714
  · exact f101553
  · exact f67429

theorem edges_row_828 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 828) [(a, true)]
      (index (table 828 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f66257
  · exact f113330
  · exact f66260
  · exact f66262
  · exact f66264
  · exact f66266
  · exact f66268
  · exact f66270
  · exact f66272
  · exact f25719

theorem edges_row_829 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 829) [(a, true)]
      (index (table 829 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f113536
  · exact f25724
  · exact f105853
  · exact f76302
  · exact f83059
  · exact f86319
  · exact f93516
  · exact f79220
  · exact f82690
  · exact f86545

theorem edges_row_830 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 830) [(a, true)]
      (index (table 830 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f68287
  · exact f86940
  · exact f79391
  · exact f68289
  · exact f69629
  · exact f68292
  · exact f150739
  · exact f68296
  · exact f70151
  · exact f68299

theorem edges_row_831 (a : ParrottGenerator) :
    (CosetEnumeration.Fact.mk (index 831) [(a, true)]
      (index (table 831 (a, true)))).Valid parrottGenerator parrottR1Subgroup input := by
  cases a
  · exact f82628
  · exact f115563
  · exact f82630
  · exact f82632
  · exact f82634
  · exact f82637
  · exact f82640
  · exact f82643
  · exact f82645
  · exact f82646

theorem edges_interval_768 : ∀ i : Fin 1755, 768 ≤ i.val → i.val < 832 →
    ∀ a : ParrottGenerator,
      (CosetEnumeration.Fact.mk (index i) [(a, true)]
        (index (table i (a, true)))).Valid parrottGenerator parrottR1Subgroup input :=
  (interval_join (mid := 800) (interval_join (mid := 784) (interval_join (mid := 776) (interval_join (mid := 772) (interval_join (mid := 770) (interval_join (mid := 769) (interval_singleton (by decide) edges_row_768) (interval_singleton (by decide) edges_row_769)) (interval_join (mid := 771) (interval_singleton (by decide) edges_row_770) (interval_singleton (by decide) edges_row_771))) (interval_join (mid := 774) (interval_join (mid := 773) (interval_singleton (by decide) edges_row_772) (interval_singleton (by decide) edges_row_773)) (interval_join (mid := 775) (interval_singleton (by decide) edges_row_774) (interval_singleton (by decide) edges_row_775)))) (interval_join (mid := 780) (interval_join (mid := 778) (interval_join (mid := 777) (interval_singleton (by decide) edges_row_776) (interval_singleton (by decide) edges_row_777)) (interval_join (mid := 779) (interval_singleton (by decide) edges_row_778) (interval_singleton (by decide) edges_row_779))) (interval_join (mid := 782) (interval_join (mid := 781) (interval_singleton (by decide) edges_row_780) (interval_singleton (by decide) edges_row_781)) (interval_join (mid := 783) (interval_singleton (by decide) edges_row_782) (interval_singleton (by decide) edges_row_783))))) (interval_join (mid := 792) (interval_join (mid := 788) (interval_join (mid := 786) (interval_join (mid := 785) (interval_singleton (by decide) edges_row_784) (interval_singleton (by decide) edges_row_785)) (interval_join (mid := 787) (interval_singleton (by decide) edges_row_786) (interval_singleton (by decide) edges_row_787))) (interval_join (mid := 790) (interval_join (mid := 789) (interval_singleton (by decide) edges_row_788) (interval_singleton (by decide) edges_row_789)) (interval_join (mid := 791) (interval_singleton (by decide) edges_row_790) (interval_singleton (by decide) edges_row_791)))) (interval_join (mid := 796) (interval_join (mid := 794) (interval_join (mid := 793) (interval_singleton (by decide) edges_row_792) (interval_singleton (by decide) edges_row_793)) (interval_join (mid := 795) (interval_singleton (by decide) edges_row_794) (interval_singleton (by decide) edges_row_795))) (interval_join (mid := 798) (interval_join (mid := 797) (interval_singleton (by decide) edges_row_796) (interval_singleton (by decide) edges_row_797)) (interval_join (mid := 799) (interval_singleton (by decide) edges_row_798) (interval_singleton (by decide) edges_row_799)))))) (interval_join (mid := 816) (interval_join (mid := 808) (interval_join (mid := 804) (interval_join (mid := 802) (interval_join (mid := 801) (interval_singleton (by decide) edges_row_800) (interval_singleton (by decide) edges_row_801)) (interval_join (mid := 803) (interval_singleton (by decide) edges_row_802) (interval_singleton (by decide) edges_row_803))) (interval_join (mid := 806) (interval_join (mid := 805) (interval_singleton (by decide) edges_row_804) (interval_singleton (by decide) edges_row_805)) (interval_join (mid := 807) (interval_singleton (by decide) edges_row_806) (interval_singleton (by decide) edges_row_807)))) (interval_join (mid := 812) (interval_join (mid := 810) (interval_join (mid := 809) (interval_singleton (by decide) edges_row_808) (interval_singleton (by decide) edges_row_809)) (interval_join (mid := 811) (interval_singleton (by decide) edges_row_810) (interval_singleton (by decide) edges_row_811))) (interval_join (mid := 814) (interval_join (mid := 813) (interval_singleton (by decide) edges_row_812) (interval_singleton (by decide) edges_row_813)) (interval_join (mid := 815) (interval_singleton (by decide) edges_row_814) (interval_singleton (by decide) edges_row_815))))) (interval_join (mid := 824) (interval_join (mid := 820) (interval_join (mid := 818) (interval_join (mid := 817) (interval_singleton (by decide) edges_row_816) (interval_singleton (by decide) edges_row_817)) (interval_join (mid := 819) (interval_singleton (by decide) edges_row_818) (interval_singleton (by decide) edges_row_819))) (interval_join (mid := 822) (interval_join (mid := 821) (interval_singleton (by decide) edges_row_820) (interval_singleton (by decide) edges_row_821)) (interval_join (mid := 823) (interval_singleton (by decide) edges_row_822) (interval_singleton (by decide) edges_row_823)))) (interval_join (mid := 828) (interval_join (mid := 826) (interval_join (mid := 825) (interval_singleton (by decide) edges_row_824) (interval_singleton (by decide) edges_row_825)) (interval_join (mid := 827) (interval_singleton (by decide) edges_row_826) (interval_singleton (by decide) edges_row_827))) (interval_join (mid := 830) (interval_join (mid := 829) (interval_singleton (by decide) edges_row_828) (interval_singleton (by decide) edges_row_829)) (interval_join (mid := 831) (interval_singleton (by decide) edges_row_830) (interval_singleton (by decide) edges_row_831)))))))

end Tits.R1Certificate
