module  -- shake: keep-all --deprecated_module: ignore

public import Submission.Theory.Character
public import Submission.Theory.Character.BrauerPermutation
public import Submission.Theory.Character.BrauerSuzuki
public import Submission.Theory.Character.CharacterValues
public import Submission.Theory.Character.ClassFunction
public import Submission.Theory.Character.Completeness
public import Submission.Theory.Character.ConjClassFunction
public import Submission.Theory.Character.CrossCharBrauer
public import Submission.Theory.Character.Cyclotomic
public import Submission.Theory.Character.DegreeBounds
public import Submission.Theory.Character.Divisibility
public import Submission.Theory.Character.Induction
public import Submission.Theory.Character.Integrality
public import Submission.Theory.Character.Orthogonality
public import Submission.Theory.Character.SimpleCriteria
public import Submission.Theory.Representation
public import Submission.Theory.Representation.AbsolutelyIrreducible
public import Submission.Theory.Representation.Clifford
public import Submission.Theory.Representation.CompleteReducibility
public import Submission.Theory.Representation.ConjugateRep
public import Submission.Theory.Representation.CyclicQuotientExtension
public import Submission.Theory.Representation.ElementaryAbelianAction
public import Submission.Theory.Representation.ExtendScalars
public import Submission.Theory.Representation.ExtraspecialFixedPoints
public import Submission.Theory.Representation.FreeBasis
public import Submission.Theory.Representation.InducedIrreducible
public import Submission.Theory.Representation.Induction
public import Submission.Theory.Representation.Isotypic
public import Submission.Theory.Representation.JacobsonDensity
public import Submission.Theory.Representation.KrullSchmidt
public import Submission.Theory.Representation.Maschke
public import Submission.Theory.Representation.PermutationBasisOrbits
public import Submission.Theory.Representation.RepEnd
public import Submission.Theory.Representation.RepEquiv
public import Submission.Theory.Representation.RepMap
public import Submission.Theory.Representation.ScalarDescent
public import Submission.Theory.Representation.SolvableDimension
public import Submission.Theory.Representation.SubrepresentationLattice
public import Submission.Theory.Representation.TwoDimensionalOddOrder
public import Submission.Theory.Representation.Unbundled
public import Submission.Theory.Representation.kerRepresentation
