import Stellmacher.SectionOne.LemmaOneFive
#check Subgroup.index_mul_card
#check Subgroup.card_mul_index
#check Subgroup.card_eq_card_quotient_mul_card_subgroup
#check Subgroup.card_subgroup_dvd_card
#check Subgroup.index_mul_card
#check Nat.card_pos
#check Nat.cast_ne_zero
#check Rat.cast_ne_zero
#check div_inv_eq_mul
#check inv_div
#check inv_mul_cancel₀
#check Rat.div_eq_iff
#check div_eq_iff
#check inv_ne_zero
#check Nat.cast_pos.mpr
#check Nat.card_pos_iff
#check Subgroup.one_mem
#check Nat.card_pos
