module

public import Mathlib.Algebra.Group.Hom.Instances
public import Mathlib.GroupTheory.Index

/-!
# The canonical radical span of a binary pencil

For a group pairing `b`, `radicalOver b L` consists of the vectors whose
pairing values all belong to `L`. The subgroup `radicalSpan b` is generated
by these radicals as `L` ranges over target subgroups of order two.
Compatible automorphisms permute the radicals and therefore preserve this
canonical subgroup. Target transitivity also makes all radical orders equal.

For an alternating pairing whose line radicals have order two, the span is
isotropic: two vectors in the same radical are equal unless one is the
identity; a value between distinct radicals belongs to both target lines.
This is the canonical-subgroup part of the binary pencil argument in
MacWilliams, Trans. AMS 150 (1970), §4 (cf. JT 1.4(c), p.386).
The cardinality and dimension arguments are separate from these functorial
and isotropy facts.
-/

public section

namespace BinaryAlternatingPencil
variable {V W : Type*} [Group V] [CommGroup W]

/-- The inverse image of a target subgroup under every row of the pairing. -/
@[expose] def radicalOver (b : V →* (V →* W)) (L : Subgroup W) : Subgroup V :=
  ⨅ y : V, L.comap (b.flip y)

/-- Membership in a radical means that every pairing value lies in its target subgroup. -/
theorem mem_radicalOver (b : V →* (V →* W)) (L : Subgroup W) (x : V) :
    x ∈ radicalOver b L ↔ ∀ y, b x y ∈ L := by
  simp [radicalOver]

/-- The subgroup generated by the radicals above all target subgroups of order two. -/
@[expose] def radicalSpan (b : V →* (V →* W)) : Subgroup V :=
  ⨆ (L : Subgroup W) (_ : Nat.card L = 2), radicalOver b L

/-- Each radical above an order-two subgroup lies in the canonical span. -/
theorem radicalOver_le_radicalSpan (b : V →* (V →* W))
    (L : Subgroup W) (hL : Nat.card L = 2) : radicalOver b L ≤ radicalSpan b :=
  le_iSup_of_le L (le_iSup_of_le hL le_rfl)

/-- Compatible automorphisms transport radicals to the corresponding target subgroups. -/
theorem radicalOver_map (b : V →* (V →* W)) (a : MulAut V) (c : MulAut W)
    (h : ∀ x y, b (a x) (a y) = c (b x y)) (L : Subgroup W) :
    (radicalOver b L).map a.toMonoidHom = radicalOver b (L.map c.toMonoidHom) := by
  ext x
  constructor
  · rintro ⟨v, hv, rfl⟩
    change v ∈ radicalOver b L at hv
    rw [mem_radicalOver] at hv ⊢
    intro y
    obtain ⟨w, rfl⟩ := a.surjective y
    change b (a v) (a w) ∈ _
    rw [h]
    exact Subgroup.mem_map.mpr ⟨_, hv w, rfl⟩
  · intro hx
    refine Subgroup.mem_map.mpr ⟨a.symm x, ?_, a.apply_symm_apply x⟩
    rw [mem_radicalOver] at hx ⊢
    intro y
    obtain ⟨z, hz, heq⟩ := Subgroup.mem_map.mp (hx (a y))
    have heq' : z = b (a.symm x) y := c.injective (by
      rw [← h, a.apply_symm_apply]
      exact heq)
    exact heq' ▸ hz

private theorem radicalSpan_map_le (b : V →* (V →* W)) (a : MulAut V) (c : MulAut W)
    (h : ∀ x y, b (a x) (a y) = c (b x y)) :
    (radicalSpan b).map a.toMonoidHom ≤ radicalSpan b := by
  unfold radicalSpan
  rw [Subgroup.map_iSup]
  refine iSup_le fun L => ?_
  rw [Subgroup.map_iSup]
  refine iSup_le fun hL => ?_
  rw [radicalOver_map b a c h]
  apply le_iSup_of_le (L.map c.toMonoidHom)
  apply le_iSup_of_le
    ((Nat.card_congr (L.equivMapOfInjective c.toMonoidHom c.injective).toEquiv).symm.trans hL)
  exact le_rfl

/-- The canonical span is invariant under every compatible pair of automorphisms. -/
theorem radicalSpan_map (b : V →* (V →* W)) (a : MulAut V) (c : MulAut W)
    (h : ∀ x y, b (a x) (a y) = c (b x y)) :
    (radicalSpan b).map a.toMonoidHom = radicalSpan b := by
  apply le_antisymm (radicalSpan_map_le b a c h)
  have hi : ∀ x y, b (a.symm x) (a.symm y) = c.symm (b x y) := by
    intro x y
    apply c.injective
    rw [c.apply_symm_apply, ← h, a.apply_symm_apply, a.apply_symm_apply]
  have hm := Subgroup.map_mono (f := a.toMonoidHom) (radicalSpan_map_le b a.symm c.symm hi)
  have hc : a.toMonoidHom.comp a.symm.toMonoidHom = MonoidHom.id V := by
    ext x
    exact a.apply_symm_apply x
  simpa only [Subgroup.map_map, hc, Subgroup.map_id] using hm

/-- Transport of radicals preserves their orders. -/
theorem radicalOver_card_map (b : V →* (V →* W)) (a : MulAut V) (c : MulAut W)
    (h : ∀ x y, b (a x) (a y) = c (b x y)) (L : Subgroup W) :
    Nat.card (radicalOver b (L.map c.toMonoidHom)) = Nat.card (radicalOver b L) := by
  rw [← radicalOver_map b a c h]
  exact (Nat.card_congr ((radicalOver b L).equivMapOfInjective
    a.toMonoidHom a.injective).toEquiv).symm

private theorem eq_of_card_two {G : Type*} [Group G] (H : Subgroup G)
    (hH : Nat.card H = 2) {x y : G} (hx : x ∈ H) (hy : y ∈ H)
    (hxn : x ≠ 1) (hyn : y ≠ 1) : x = y := by
  obtain ⟨z, _, hz⟩ := (Nat.card_eq_two_iff' (1 : H)).mp hH
  have hx' : (⟨x, hx⟩ : H) ≠ 1 := fun h => hxn (congrArg Subtype.val h)
  have hy' : (⟨y, hy⟩ : H) ≠ 1 := fun h => hyn (congrArg Subtype.val h)
  exact congrArg Subtype.val ((hz _ hx').trans (hz _ hy').symm)

private theorem subgroup_eq_of_card_two {G : Type*} [Group G] (H K : Subgroup G)
    (hH : Nat.card H = 2) (hK : Nat.card K = 2) {z : G}
    (hzH : z ∈ H) (hzK : z ∈ K) (hzn : z ≠ 1) : H = K := by
  ext x
  by_cases hx : x = 1
  · simp [hx]
  constructor
  · intro hxH
    exact eq_of_card_two H hH hxH hzH hx hzn ▸ hzK
  · intro hxK
    exact eq_of_card_two K hK hxK hzK hx hzn ▸ hzH

/-- Distinct target lines have disjoint radicals when the common radical is trivial. -/
theorem radicalOver_disjoint (b : V →* (V →* W))
    (hsep : ∀ x, (∀ y, b x y = 1) → x = 1)
    (L M : Subgroup W) (hL : Nat.card L = 2) (hM : Nat.card M = 2) (hLM : L ≠ M) :
    Disjoint (radicalOver b L) (radicalOver b M) := by
  rw [disjoint_iff_inf_le]
  intro x hx
  change x = 1
  apply hsep x
  intro y
  by_contra hn
  exact hLM (subgroup_eq_of_card_two L M hL hM
    ((mem_radicalOver b L x).mp hx.1 y) ((mem_radicalOver b M x).mp hx.2 y) hn)

/-- Transitivity on nonidentity target elements makes all line radicals have equal orders. -/
theorem radicalOver_card_eq (b : V →* (V →* W))
    (htrans : ∀ z₁ z₂ : W, z₁ ≠ 1 → z₂ ≠ 1 →
      ∃ (a : MulAut V) (c : MulAut W), c z₁ = z₂ ∧
        ∀ x y, b (a x) (a y) = c (b x y))
    (L M : Subgroup W) (hL : Nat.card L = 2) (hM : Nat.card M = 2) :
    Nat.card (radicalOver b L) = Nat.card (radicalOver b M) := by
  obtain ⟨z₁, hz₁, _⟩ := (Nat.card_eq_two_iff' (1 : L)).mp hL
  obtain ⟨z₂, hz₂, _⟩ := (Nat.card_eq_two_iff' (1 : M)).mp hM
  have hn₁ : (z₁ : W) ≠ 1 := fun h => hz₁ (Subtype.ext h)
  have hn₂ : (z₂ : W) ≠ 1 := fun h => hz₂ (Subtype.ext h)
  obtain ⟨a, c, hc, hab⟩ := htrans z₁ z₂ hn₁ hn₂
  have heq : L.map c.toMonoidHom = M := subgroup_eq_of_card_two _ _
    ((Nat.card_congr (L.equivMapOfInjective c.toMonoidHom c.injective).toEquiv).symm.trans hL)
    hM (Subgroup.mem_map.mpr ⟨z₁, z₁.property, hc⟩) z₂.property hn₂
  rw [← heq]
  exact (radicalOver_card_map b a c hab L).symm

/-- An alternating group pairing changes to its inverse when its arguments are interchanged. -/
theorem swap_eq_inv (b : V →* (V →* W)) (halt : ∀ x, b x x = 1) (x y : V) :
    b y x = (b x y)⁻¹ := by
  have h := halt (x * y)
  simp only [map_mul, MonoidHom.mul_apply, halt, one_mul, mul_one] at h
  exact eq_inv_of_mul_eq_one_left h

/-- If every line radical has order two, their generated subgroup is isotropic. -/
theorem radicalSpan_isotropic (b : V →* (V →* W)) (halt : ∀ x, b x x = 1)
    (hr : ∀ L : Subgroup W, Nat.card L = 2 → Nat.card (radicalOver b L) = 2) :
    ∀ x ∈ radicalSpan b, ∀ y ∈ radicalSpan b, b x y = 1 := by
  have hgen (L M : Subgroup W) (hL : Nat.card L = 2) (hM : Nat.card M = 2)
      (x : V) (hx : x ∈ radicalOver b L) (y : V) (hy : y ∈ radicalOver b M) :
      b x y = 1 := by
    by_cases hLM : L = M
    · subst M
      by_cases hxn : x = 1
      · simp [hxn]
      by_cases hyn : y = 1
      · simp [hyn]
      rw [eq_of_card_two _ (hr L hL) hx hy hxn hyn]
      exact halt y
    · by_contra hn
      apply hLM
      apply subgroup_eq_of_card_two L M hL hM
        ((mem_radicalOver b L x).mp hx y) _ hn
      have hm := (mem_radicalOver b M y).mp hy x
      rw [swap_eq_inv b halt] at hm
      exact M.inv_mem_iff.mp hm
  have hleft (L : Subgroup W) (hL : Nat.card L = 2) (x : V)
      (hx : x ∈ radicalOver b L) : radicalSpan b ≤ (b x).ker := by
    refine iSup_le fun M => iSup_le fun hM => ?_
    intro y hy
    exact hgen L M hL hM x hx y hy
  intro x hx y hy
  have hright : radicalSpan b ≤ (b.flip y).ker := by
    refine iSup_le fun L => iSup_le fun hL => ?_
    intro z hz
    exact hleft L hL z hz hy
  exact hright hx

end BinaryAlternatingPencil
