module

public import Theory.GroupTheory.PGroup.BinaryModular
public import Theory.GroupTheory.PGroup.Omega
public import Theory.GroupTheory.PGroup.CyclicInvolution
public import Mathlib.GroupTheory.IndexNormal
import Mathlib.Tactic

/-!
# Omega subgroups of modular two-groups

For the modular presentation with `|a| = 2^n`, `|b| = 2`, and `n ≥ 3`,
the second omega subgroup is generated by `a^(2^(n-2))` and `b` and is
abelian. The first omega subgroup contains two distinct involutions and
therefore is not cyclic.

The cyclic subgroup has index two, giving the normal forms `a^i` and
`a^i*b`. The conjugation relation gives `(a^i*b)^4 = a^(4*i)`, so the
fourth-power bound forces the indicated divisibility of `i`. Finally `b`
centralizes `a²`, and hence centralizes the indicated generator of omega-two.

Source: Gorenstein, *Finite Groups*, Section 5.4, Theorem 4.3(i) and the
proof of Theorem 4.9, especially printed page 199. This calculation is
independent of cyclic self-centralizer classification.
-/

open Subgroup

/-- Fourth-power torsion in a modular join has a cyclic component of order at most four. -/
private theorem modular_fourth_power_normal_form
    {G : Type*} [Group G] [Finite G] (hG : IsPGroup 2 G)
    (a e : G) (n : ℕ) [(zpowers a).Normal] (hn : 3 ≤ n)
    (he : e ^ 2 = 1) (heA : e ∉ zpowers a)
    (hact : e * a * e⁻¹ = a ^ (1 + 2 ^ (n - 1)))
    (x : G) (hx : x ∈ zpowers a ⊔ zpowers e) (hx4 : x ^ 4 = 1) :
    ∃ d t : G, d ∈ zpowers a ∧ d ^ 4 = 1 ∧ (t = 1 ∨ t = e) ∧ x = d * t := by
  classical
  obtain ⟨d, hd, t, ht, rfl⟩ := mem_sup_of_normal_left.mp hx
  have htcase : t = 1 ∨ t = e := by
    have heorder : orderOf e = 2 := orderOf_eq_prime he
      (fun h => heA (h ▸ (zpowers a).one_mem))
    obtain ⟨i, hi, rfl⟩ := Finset.mem_image.mp (mem_zpowers_iff_mem_range_orderOf.mp ht)
    have hi2 : i < 2 := by simpa only [heorder] using Finset.mem_range.mp hi
    interval_cases i <;> simp
  refine ⟨d, t, hd, ?_, htcase, rfl⟩
  rcases htcase with ht1 | hte
  · simpa [ht1] using hx4
  subst t
  have haction : e * d * e⁻¹ = d ^ (1 + 2 ^ (n - 1)) := by
    obtain ⟨k, _, rfl⟩ := Finset.mem_image.mp (mem_zpowers_iff_mem_range_orderOf.mp hd)
    change MulAut.conj e (a ^ k) = _
    rw [map_pow, MulAut.conj_apply, hact, ← pow_mul, ← pow_mul, Nat.mul_comm]
  have hsq : (d * e) ^ 2 = d ^ (2 + 2 ^ (n - 1)) := by
    calc
      (d * e) ^ 2 = d * (e * d * e⁻¹) * e ^ 2 := by simp only [pow_two]; group
      _ = d * d ^ (1 + 2 ^ (n - 1)) := by rw [haction, he, mul_one]
      _ = d ^ (2 + 2 ^ (n - 1)) := by rw [← pow_succ']; congr 1; omega
  have hdPow : d ^ ((2 + 2 ^ (n - 1)) * 2) = 1 := by
    rw [pow_mul, ← hsq, ← pow_mul]
    exact hx4
  have hhalf : 2 ^ (n - 1) = 2 ^ (n - 2) * 2 := by
    conv_lhs => rw [show n - 1 = (n - 2) + 1 by omega]
    rw [pow_succ]
  have hodd : Nat.Coprime 2 (1 + 2 ^ (n - 2)) := by
    apply Nat.coprime_two_left.mpr
    exact Odd.add_even (by decide : Odd (1 : ℕ))
      (Nat.even_pow.mpr ⟨by decide, by omega⟩)
  apply (hG.powEquiv hodd).injective
  simp only [IsPGroup.powEquiv_apply, one_pow, ← pow_mul]
  convert hdPow using 1
  rw [hhalf]
  congr 1
  ring

private theorem modular_commute_of_fourth_power
    {G : Type*} [Group G] [Finite G] (a e : G) (n : ℕ) (hn : 3 ≤ n)
    (hact : e * a * e⁻¹ = a ^ (1 + 2 ^ (n - 1)))
    (d : G) (hd : d ∈ zpowers a) (hd4 : d ^ 4 = 1) : Commute e d := by
  classical
  have haction : e * d * e⁻¹ = d ^ (1 + 2 ^ (n - 1)) := by
    obtain ⟨k, _, rfl⟩ := Finset.mem_image.mp (mem_zpowers_iff_mem_range_orderOf.mp hd)
    change MulAut.conj e (a ^ k) = _
    rw [map_pow, MulAut.conj_apply, hact, ← pow_mul, ← pow_mul, Nat.mul_comm]
  have hhalf : 2 ^ (n - 1) = 4 * 2 ^ (n - 3) := by
    rw [show n - 1 = 2 + (n - 3) by omega, pow_add]
    norm_num
  have hfix : e * d * e⁻¹ = d := by
    rw [haction, pow_add, pow_one, hhalf, pow_mul, hd4, one_pow, mul_one]
  exact mul_inv_eq_iff_eq_mul.mp hfix

/-- The second omega subgroup of a modular join is abelian. -/
public theorem IsPGroup.isMulCommutative_omega_two_of_modular_join
    {G : Type*} [Group G] [Finite G] (hG : IsPGroup 2 G)
    (a e : G) (n : ℕ) [(zpowers a).Normal] (hn : 3 ≤ n)
    (he : e ^ 2 = 1) (heA : e ∉ zpowers a)
    (hact : e * a * e⁻¹ = a ^ (1 + 2 ^ (n - 1)))
    (M : Subgroup G) (hM : M = zpowers a ⊔ zpowers e) :
    IsMulCommutative (omega M (p := 2) 2) := by
  apply isMulCommutative_closure
  intro x hx y hy
  have hx4 : (x : G) ^ 4 = 1 := congrArg Subtype.val (show x ^ 4 = 1 from hx)
  have hy4 : (y : G) ^ 4 = 1 := congrArg Subtype.val (show y ^ 4 = 1 from hy)
  obtain ⟨d, t, hd, hd4, ht, hxt⟩ := modular_fourth_power_normal_form hG a e n hn he heA hact
    x (hM ▸ x.property) hx4
  obtain ⟨f, u, hf, hf4, hu, hyu⟩ := modular_fourth_power_normal_form hG a e n hn he heA hact
    y (hM ▸ y.property) hy4
  have hdf : Commute d f := ((zpowers a).le_centralizer hf d hd)
  have hed := modular_commute_of_fourth_power a e n hn hact d hd hd4
  have hef := modular_commute_of_fourth_power a e n hn hact f hf hf4
  apply Subtype.ext
  change (x : G) * (y : G) = (y : G) * (x : G)
  rw [hxt, hyu]
  rcases ht with ht | ht <;> rcases hu with hu | hu <;> rw [ht, hu]
  · simpa using hdf.eq
  · simpa using (hdf.mul_right hed.symm).eq
  · simpa using (hdf.mul_left hef).eq
  · exact ((hdf.mul_right hed.symm).mul_left (hef.mul_right (Commute.refl e))).eq

/-- An outside involution and the cyclic factor's involution prevent first
omega from being cyclic. -/
public theorem Subgroup.not_isCyclic_omega_one_of_modular_join
    {G : Type*} [Group G] [Finite G]
    (a e : G) (n : ℕ) (hn : 3 ≤ n) (ha : orderOf a = 2 ^ n)
    (he : e ^ 2 = 1) (heA : e ∉ zpowers a)
    (M : Subgroup G) (hM : M = zpowers a ⊔ zpowers e) :
    ¬ IsCyclic (omega₁ M (p := 2)) := by
  intro hc
  let : IsCyclic (omega₁ M (p := 2)) := hc
  have hsplit : 2 ^ n = 2 ^ (n - 1) * 2 := by
    conv_lhs => rw [show n = (n - 1) + 1 by omega]
    rw [pow_succ]
  have hzorder : orderOf (a ^ (2 ^ (n - 1))) = 2 := by
    have hh := orderOf_pow_orderOf_div (Nat.ne_of_gt (orderOf_pos a))
      (show 2 ∣ orderOf a by rw [ha, hsplit]; exact dvd_mul_left _ _)
    simpa [ha, hsplit] using hh
  have heorder : orderOf e = 2 := orderOf_eq_prime he
    (fun h => heA (h ▸ (zpowers a).one_mem))
  have heM : e ∈ M := hM ▸ (le_sup_right : zpowers e ≤ zpowers a ⊔ zpowers e) (mem_zpowers e)
  have hzM : a ^ (2 ^ (n - 1)) ∈ M :=
    hM ▸ (le_sup_left : zpowers a ≤ zpowers a ⊔ zpowers e) (pow_mem (mem_zpowers a) _)
  let eM : M := ⟨e, heM⟩
  let zM : M := ⟨a ^ (2 ^ (n - 1)), hzM⟩
  have heO : eM ∈ omega₁ M (p := 2) := subset_closure (by
    change eM ^ (2 ^ 1) = 1
    apply Subtype.ext
    simpa using he)
  have hzO : zM ∈ omega₁ M (p := 2) := subset_closure (by
    change zM ^ (2 ^ 1) = 1
    apply Subtype.ext
    change (a ^ (2 ^ (n - 1))) ^ 2 = 1
    have hzpow := pow_orderOf_eq_one (a ^ (2 ^ (n - 1)))
    rw [hzorder] at hzpow
    exact hzpow)
  have hh := IsCyclic.eq_of_orderOf_eq_two
    (x := (⟨eM, heO⟩ : omega₁ M (p := 2))) (y := ⟨zM, hzO⟩)
    (by simpa [eM] using heorder) (by simpa [zM] using hzorder)
  have hez : e = a ^ (2 ^ (n - 1)) :=
    congrArg (fun x : omega₁ M (p := 2) => ((x : M) : G)) hh
  exact heA (hez ▸ pow_mem (mem_zpowers a) _)

namespace IsBinaryModularGroup

private theorem mem_zpowers_two {G : Type*} [Group G] [Finite G]
    {b x : G} (hb : orderOf b = 2) (hx : x ∈ zpowers b) : x = 1 ∨ x = b := by
  classical
  rw [mem_zpowers_iff_mem_range_orderOf, hb] at hx
  obtain ⟨i, hi, hix⟩ := Finset.mem_image.mp hx
  have hiNat : i < 2 := Finset.mem_range.mp hi
  have hi' : i = 0 ∨ i = 1 := by omega
  rcases hi' with rfl | rfl
  · exact Or.inl (by simpa using hix.symm)
  · exact Or.inr (by simpa using hix.symm)

private theorem normal_form
    {G : Type*} [Group G] [Finite G] (n : ℕ) (a b : G)
    (ha : orderOf a = 2 ^ n) (hb : orderOf b = 2)
    (hcard : Nat.card G = 2 ^ (n + 1))
    (hgen : closure ({a, b} : Set G) = ⊤) :
    ∀ x : G, ∃ i : ℕ, x = a ^ i ∨ x = a ^ i * b := by
  classical
  let A := zpowers a
  have hindex : A.index = 2 := by
    have hc := A.index_mul_card
    rw [Nat.card_zpowers, ha] at hc
    rw [hcard] at hc
    have hp : 0 < 2 ^ n := by positivity
    rw [show 2 ^ (n + 1) = 2 * 2 ^ n by rw [pow_succ, mul_comm]] at hc
    exact Nat.mul_right_cancel hp (by simpa [mul_comm] using hc)
  let : A.Normal := normal_of_index_eq_two hindex
  have hsup : A ⊔ zpowers b = ⊤ := by
    apply top_unique
    rw [← hgen]
    rw [closure_le]
    intro x hx
    have hcases : x = a ∨ x = b := by simpa using hx
    rcases hcases with hxa | hxb
    · rw [hxa]
      exact (le_sup_left : A ≤ A ⊔ zpowers b) (mem_zpowers a)
    · rw [hxb]
      exact (le_sup_right : zpowers b ≤ A ⊔ zpowers b) (mem_zpowers b)
  intro x
  obtain ⟨y, hy, z, hz, rfl⟩ := mem_sup_of_normal_left.mp (hsup ▸ mem_top x)
  obtain ⟨i, hi, hiy⟩ := Finset.mem_image.mp
    (mem_zpowers_iff_mem_range_orderOf.mp hy)
  rw [← hiy]
  rcases mem_zpowers_two hb hz with hz | hz
  · exact ⟨i, Or.inl (by simp [hz])⟩
  · exact ⟨i, Or.inr (by simp [hz])⟩


private theorem coset_pow_four
    {G : Type*} [Group G] (n : ℕ) (hn : 1 ≤ n) (a b : G)
    (ha : orderOf a = 2 ^ n)
    (hrel : b * a * b⁻¹ = a ^ (1 + 2 ^ (n - 1)))
    (hb : b ^ 2 = 1) (r : ℕ) :
    (a ^ r * b) ^ 4 = a ^ (4 * r) := by
  have hrelpow : b * a ^ r * b⁻¹ = a ^ ((1 + 2 ^ (n - 1)) * r) := by
    change MulAut.conj b (a ^ r) = _
    rw [map_pow, MulAut.conj_apply, hrel, ← pow_mul]
  have hbi : b⁻¹ = b := inv_eq_of_mul_eq_one_left (by simpa [pow_two] using hb)
  have hs : (a ^ r * b) ^ 2 = a ^ (r + (1 + 2 ^ (n - 1)) * r) := by
    rw [pow_add, ← hrelpow, hbi, pow_two]
    simp only [mul_assoc]
  have hsplit : 2 ^ (n - 1) * 2 = 2 ^ n := by
    rw [← pow_succ, Nat.sub_add_cancel hn]
  have hpa : a ^ (2 ^ n) = 1 := ha ▸ pow_orderOf_eq_one a
  calc
    (a ^ r * b) ^ 4 = ((a ^ r * b) ^ 2) ^ 2 := by rw [← pow_mul]
    _ = a ^ ((r + (1 + 2 ^ (n - 1)) * r) * 2) := by rw [hs, ← pow_mul]
    _ = a ^ (4 * r + 2 ^ n * r) := by
      congr 1
      rw [← hsplit]
      ring
    _ = a ^ (4 * r) := by simp only [pow_add, pow_mul, hpa, one_pow, mul_one]

private theorem square_commute
    {G : Type*} [Group G] (n : ℕ) (hn : 1 ≤ n) (a b : G)
    (ha : orderOf a = 2 ^ n)
    (hrel : b * a * b⁻¹ = a ^ (1 + 2 ^ (n - 1))) : Commute (a ^ 2) b := by
  have hsplit : 2 ^ (n - 1) * 2 = 2 ^ n := by
    rw [← pow_succ, Nat.sub_add_cancel hn]
  have hpa : a ^ (2 ^ n) = 1 := ha ▸ pow_orderOf_eq_one a
  have hfix : b * a ^ 2 * b⁻¹ = a ^ 2 := by
    change MulAut.conj b (a ^ 2) = _
    rw [map_pow, MulAut.conj_apply, hrel, ← pow_mul]
    rw [show (1 + 2 ^ (n - 1)) * 2 = 2 + 2 ^ n by rw [← hsplit]; ring]
    rw [pow_add, hpa, mul_one]
  exact (mul_inv_eq_iff_eq_mul.mp hfix).symm

private theorem omega_two_eq
    {G : Type*} [Group G] [Finite G] (n : ℕ) (hn : 3 ≤ n) (a b : G)
    (ha : orderOf a = 2 ^ n) (hb : orderOf b = 2)
    (hrel : b * a * b⁻¹ = a ^ (1 + 2 ^ (n - 1)))
    (hcard : Nat.card G = 2 ^ (n + 1))
    (hgen : closure ({a, b} : Set G) = ⊤) :
    omega G (p := 2) 2 = closure ({a ^ (2 ^ (n - 2)), b} : Set G) := by
  have hsplit : 2 ^ n = 4 * 2 ^ (n - 2) := by
    calc
      2 ^ n = 2 ^ ((n - 2) + 2) := by congr 1; omega
      _ = 4 * 2 ^ (n - 2) := by rw [pow_add]; ring
  have hb2 : b ^ 2 = 1 := hb ▸ pow_orderOf_eq_one b
  have hpa : a ^ (2 ^ n) = 1 := ha ▸ pow_orderOf_eq_one a
  apply le_antisymm
  · apply (closure_le _).mpr
    intro x hx
    have hx4 : x ^ 4 = 1 := hx
    obtain ⟨i, hi | hi⟩ := normal_form n a b ha hb hcard hgen x
    all_goals
      have hi4 : a ^ (4 * i) = 1 := by
        first
        | simpa only [hi, ← pow_mul, Nat.mul_comm] using hx4
        | rw [hi, coset_pow_four n (by omega) a b ha hrel hb2] at hx4; exact hx4
      have hdiv : 2 ^ (n - 2) ∣ i := by
        have hd := orderOf_dvd_of_pow_eq_one hi4
        rw [ha, hsplit] at hd
        exact (Nat.mul_dvd_mul_iff_left (by decide : 0 < 4)).mp hd
      obtain ⟨j, rfl⟩ := hdiv
      have hm : a ^ (2 ^ (n - 2) * j) ∈ closure ({a ^ (2 ^ (n - 2)), b} : Set G) := by
        rw [pow_mul]
        exact pow_mem (subset_closure (by simp)) j
    · rw [hi]
      exact hm
    · rw [hi]
      exact mul_mem hm (subset_closure (by simp))
  · apply (closure_le _).mpr
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with hx | hx
    · rw [hx]
      apply Subgroup.subset_closure
      change (a ^ (2 ^ (n - 2))) ^ 4 = 1
      rw [← pow_mul, mul_comm, ← hsplit, hpa]
    · rw [hx]
      apply Subgroup.subset_closure
      change b ^ 4 = 1
      calc
        b ^ 4 = (b ^ 2) ^ 2 := by rw [← pow_mul]
        _ = 1 := by rw [hb2, one_pow]

/-- The second omega subgroup of a modular two-group is abelian. -/
public theorem isMulCommutative_omega_two
    {G : Type*} [Group G] [Finite G] (h : IsBinaryModularGroup G) :
    IsMulCommutative (omega G (p := 2) 2) := by
  obtain ⟨n, hn, hcard, a, b, ha, hb, hrel, hgen⟩ := h
  rw [omega_two_eq n hn a b ha hb hrel hcard hgen]
  have hq : Commute (a ^ (2 ^ (n - 2))) b := by
    have hs : 2 ^ (n - 2) = 2 * 2 ^ (n - 3) := by
      calc
        2 ^ (n - 2) = 2 ^ ((n - 3) + 1) := by congr 1; omega
        _ = 2 * 2 ^ (n - 3) := by rw [pow_succ, mul_comm]
    rw [hs, pow_mul]
    exact (square_commute n (by omega) a b ha hrel).pow_left _
  apply isMulCommutative_closure
  intro x hx y hy
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx hy
  rcases hx with rfl | rfl <;> rcases hy with rfl | rfl
  · rfl
  · exact hq.eq
  · exact hq.eq.symm
  · rfl

/-- The first omega subgroup of a modular two-group is not cyclic: it
contains both the involution of the long cyclic subgroup and the external
involution in the presentation. -/
public theorem not_isCyclic_omega_one
    {G : Type*} [Group G] [Finite G] (h : IsBinaryModularGroup G) :
    ¬ IsCyclic (omega₁ G (p := 2)) := by
  obtain ⟨n, hn, hcard, a, b, ha, hb, hrel, hgen⟩ := h
  have hsplit : 2 ^ n = 2 ^ (n - 1) * 2 := by
    rw [← pow_succ, Nat.sub_add_cancel (show 1 ≤ n by omega)]
  have hbA : b ∉ zpowers a := by
    intro hmem
    have htop : zpowers a = ⊤ := by
      apply top_unique
      rw [← hgen, closure_le]
      intro x hx
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
      rcases hx with rfl | rfl
      · exact mem_zpowers _
      · exact hmem
    have hc := Nat.card_zpowers a
    rw [htop, Subgroup.card_top, hcard, ha, pow_succ] at hc
    have hp : 0 < 2 ^ n := by positivity
    omega
  let z := a ^ (2 ^ (n - 1))
  have hzorder : orderOf z = 2 := by
    have hh := orderOf_pow_orderOf_div (Nat.ne_of_gt (orderOf_pos a))
      (show 2 ∣ orderOf a by rw [ha, hsplit]; exact dvd_mul_left _ _)
    simpa [ha, hsplit, z] using hh
  have hzmem : z ∈ omega₁ G (p := 2) := by
    apply Subgroup.subset_closure
    change z ^ 2 = 1
    exact hzorder ▸ pow_orderOf_eq_one z
  have hbmem : b ∈ omega₁ G (p := 2) := by
    apply Subgroup.subset_closure
    change b ^ 2 = 1
    exact hb ▸ pow_orderOf_eq_one b
  intro hcyclic
  let : IsCyclic (omega₁ G (p := 2)) := hcyclic
  have heq : (⟨b, hbmem⟩ : omega₁ G (p := 2)) = ⟨z, hzmem⟩ :=
    IsCyclic.eq_of_orderOf_eq_two (by simpa using hb) (by simpa using hzorder)
  have hbz : b = z := congrArg Subtype.val heq
  exact hbA (hbz ▸ pow_mem (mem_zpowers a) _)

end IsBinaryModularGroup
