module

public import Theory.GroupTheory.PGroup.SymplecticType
public import Theory.GroupTheory.PGroup.CriticalSubgroup
public import Theory.GroupTheory.PGroup.ClassTwoCyclicCenterFactor
public import Theory.GroupTheory.PGroup.ExtraspecialCentralizer
public import Theory.ElementaryAbelian.ExtraspecialEquiv

/-!
# Assembling the binary Hall core from a critical subgroup

Once the critical subgroup is generated by its cyclic center and an
extraspecial subgroup with central ambient commutators, the ambient centralizer
of that extraspecial subgroup is the required remaining factor. An element of
this factor centralizing the cyclic center centralizes the whole critical
subgroup, so belongs to the cyclic center.

The characteristic-abelian hypothesis passes to the critical subgroup, so the
internal factor-extraction theorem supplies this extraspecial supplement to its
center. This proves existence of the binary Hall core for every finite two-group
whose characteristic abelian subgroups are cyclic.

Sources: Gorenstein, *Finite Groups*, Theorem 5.3.11 and Lemmas 5.4.6–5.4.7.
The internal factor extraction is Lemma 5.4.7(i); the ambient assembly proves
the implications in part (ii), using Lemma 5.4.6.
-/

open Subgroup
open scoped commutatorElement

namespace IsCriticalPSubgroup

/-- The center of a critical subgroup is cyclic under Hall's hypothesis. -/
public theorem isCyclic_center_image
    {P : Type*} [Group P] {C : Subgroup P} (hC : IsCriticalPSubgroup 2 C)
    (hchar : ∀ A : Subgroup P, A.Characteristic → IsMulCommutative A → IsCyclic A) :
    IsCyclic ((center C).map C.subtype) := by
  let : C.Characteristic := hC.characteristic
  exact hchar _ inferInstance inferInstance

/-- Splitting off an extraspecial factor of a critical subgroup yields Hall's
core with the actual ambient centralizer as its second factor. -/
public theorem binaryHallCore_of_factor
    {P : Type*} [Group P] [Finite P] {C : Subgroup P}
    (hC : IsCriticalPSubgroup 2 C)
    (hchar : ∀ A : Subgroup P, A.Characteristic → IsMulCommutative A → IsCyclic A)
    (E : Subgroup P) (hE : E = ⊥ ∨ IsExtraspecial 2 E)
    (hgen : E ⊔ (center C).map C.subtype = C)
    (hcomm : ⁅(⊤ : Subgroup P), E⁆ ≤ (center E).map E.subtype) :
    BinaryHallCore E (centralizer (E : Set P)) ((center C).map C.subtype) := by
  let : C.Characteristic := hC.characteristic
  let Z : Subgroup P := (center C).map C.subtype
  have hZC : Z ≤ C := map_subtype_le _
  have hZcentral : Z ≤ centralizer (C : Set P) := by
    rw [show Z = C ⊓ centralizer (C : Set P) from
      map_center_subtype_eq_inf_centralizer C]
    exact inf_le_right
  have hEC : E ≤ C := hgen ▸ (le_sup_left : E ≤ E ⊔ Z)
  have hZtail : Z ≤ centralizer (E : Set P) :=
    hZcentral.trans (centralizer_le hEC)
  have hZself : Z ≤ centralizer (Z : Set P) :=
    hZcentral.trans (centralizer_le hZC)
  refine ⟨hE, le_rfl, ?_, hC.isCyclic_center_image hchar, inferInstance, hZtail, ?_⟩
  · rcases hE with rfl | hE
    · simp
    · let : IsExtraspecial 2 E := hE
      exact sup_centralizer_eq_top_of_extraspecial_two E hcomm
  · apply le_antisymm ?_ (le_inf hZtail hZself)
    have hle : centralizer (E : Set P) ⊓ centralizer (Z : Set P) ≤
        centralizer (C : Set P) := by
      apply le_centralizer_iff.mpr
      rw [← hgen]
      exact sup_le (le_centralizer_iff.mp inf_le_left) (le_centralizer_iff.mp inf_le_right)
    exact hle.trans hC.centralizer_eq.le

/-- The ambient commutator condition follows from generation by the
extraspecial factor and the cyclic center of the critical subgroup. -/
public theorem binaryHallCore_of_central_factor
    {P : Type*} [Group P] [Finite P] {C : Subgroup P}
    (hC : IsCriticalPSubgroup 2 C)
    (hchar : ∀ A : Subgroup P, A.Characteristic → IsMulCommutative A → IsCyclic A)
    (E : Subgroup P) (hE : E = ⊥ ∨ IsExtraspecial 2 E)
    (hgen : E ⊔ (center C).map C.subtype = C) :
    BinaryHallCore E (centralizer (E : Set P)) ((center C).map C.subtype) := by
  apply hC.binaryHallCore_of_factor hchar E hE hgen
  rcases hE with rfl | hE
  · simp
  let : IsExtraspecial 2 E := hE
  let : C.Characteristic := hC.characteristic
  let Z : Subgroup P := (center C).map C.subtype
  let : IsCyclic Z := hC.isCyclic_center_image hchar
  have hEC : E ≤ C := hgen ▸ (le_sup_left : E ≤ E ⊔ Z)
  have hZcentral : Z ≤ centralizer (C : Set P) := by
    rw [show Z = C ⊓ centralizer (C : Set P) from
      map_center_subtype_eq_inf_centralizer C]
    exact inf_le_right
  have hZE : Z ≤ centralizer (E : Set P) :=
    hZcentral.trans (centralizer_le hEC)
  apply commutator_le_center_image_of_extraspecial_two E Z ?_ hZE
    ((commutator_mono le_rfl hEC).trans hC.commutator_le)
  rw [map_center_subtype_eq_inf_centralizer]
  have hle : E ⊓ centralizer (E : Set P) ≤ centralizer (C : Set P) := by
    apply le_centralizer_iff.mpr
    rw [← hgen]
    exact sup_le (le_centralizer_iff.mp inf_le_right)
      (hZE.trans (centralizer_le inf_le_left))
  exact hle.trans hC.centralizer_eq.le

/-- An internal extraspecial supplement to the critical subgroup's center
gives the embedded Hall core in the original group. -/
public theorem binaryHallCore_of_internal_factor
    {P : Type*} [Group P] [Finite P] {C : Subgroup P}
    (hC : IsCriticalPSubgroup 2 C)
    (hchar : ∀ A : Subgroup P, A.Characteristic → IsMulCommutative A → IsCyclic A)
    (F : Subgroup C) (hF : F = ⊥ ∨ IsExtraspecial 2 F)
    (hgen : F ⊔ center C = ⊤) :
    BinaryHallCore (F.map C.subtype) (centralizer (F.map C.subtype : Set P))
      ((center C).map C.subtype) := by
  apply hC.binaryHallCore_of_central_factor hchar (F.map C.subtype)
  · rcases hF with rfl | hF
    · exact Or.inl (map_bot _)
    · exact Or.inr (hF.of_mulEquiv (F.equivMapOfInjective C.subtype C.subtype_injective))
  · rw [← Subgroup.map_sup, hgen, ← MonoidHom.range_eq_map, range_subtype]

/-- Hall's characteristic-abelian hypothesis passes to a characteristic
subgroup, in particular to the critical subgroup. -/
public theorem characteristic_abelian_isCyclic
    {P : Type*} [Group P] {C : Subgroup P} (hC : IsCriticalPSubgroup 2 C)
    (hchar : ∀ A : Subgroup P, A.Characteristic → IsMulCommutative A → IsCyclic A)
    (A : Subgroup C) (hA : A.Characteristic) (hcomm : IsMulCommutative A) :
    IsCyclic A := by
  let : C.Characteristic := hC.characteristic
  let : A.Characteristic := hA
  let : IsMulCommutative A := hcomm
  have h := hchar (A.map C.subtype) inferInstance inferInstance
  exact (A.equivMapOfInjective C.subtype C.subtype_injective).isCyclic.mpr h

/-- An abelian critical subgroup directly supplies Hall's core. -/
public theorem binaryHallCore_of_isMulCommutative
    {P : Type*} [Group P] [Finite P] {C : Subgroup P}
    (hC : IsCriticalPSubgroup 2 C) [IsMulCommutative C]
    (hchar : ∀ A : Subgroup P, A.Characteristic → IsMulCommutative A → IsCyclic A) :
    BinaryHallCore (⊥ : Subgroup P) ⊤ ((center C).map C.subtype) := by
  have h := hC.binaryHallCore_of_factor hchar ⊥ (Or.inl rfl)
    (by rw [bot_sup_eq, center_eq_top, ← MonoidHom.range_eq_map, range_subtype]) (by simp)
  have hb : centralizer ((⊥ : Subgroup P) : Set P) = ⊤ := by
    apply top_unique
    intro x _ y hy
    have hy1 : y = 1 := mem_bot.mp hy
    simp [hy1]
  rwa [hb] at h

end IsCriticalPSubgroup

namespace IsPGroup

/-- A finite two-group whose characteristic abelian subgroups are cyclic has
an extraspecial or trivial factor with a centralizer supplement containing a
cyclic characteristic subgroup that is self-centralizing in the supplement. -/
public theorem exists_binaryHallCore
    {P : Type*} [Group P] [Finite P] (hP : IsPGroup 2 P)
    (hchar : ∀ A : Subgroup P, A.Characteristic → IsMulCommutative A → IsCyclic A) :
    ∃ E D Z : Subgroup P, BinaryHallCore E D Z := by
  obtain ⟨C, hC⟩ := hP.exists_criticalPSubgroup
  obtain ⟨F, hF, hgen⟩ := (hP.to_subgroup C).exists_extraspecial_center_supplement
    hC.quotient_elementary (hC.characteristic_abelian_isCyclic hchar)
  exact ⟨F.map C.subtype, centralizer (F.map C.subtype : Set P),
    (center C).map C.subtype, hC.binaryHallCore_of_internal_factor hchar F hF hgen⟩

end IsPGroup
