module

public import Theory.GroupTheory.PGroup.ExtraspecialCentralProductOrder
public import Theory.GroupTheory.PGroup.ExtraspecialInvolution
public import Theory.GroupTheory.NormalFourCentralizer

/-!
# Squares and fourth roots in extraspecial central products

Let a finite two-group with cyclic center be generated by commuting normal
factors, one extraspecial and the other containing a specified rotation `r`.
If all squares and the center of the second factor lie in `⟨r²⟩`, then all
ambient squares lie in its cyclic image. If `r` has order divisible by eight,
its half-order power is central, and the centralizer of `r²` in that factor
lies in `⟨r⟩`, the central involution has a fourth root commuting with every
element of every normal elementary abelian four-subgroup.

The intersection of the factors is the extraspecial center. The centralizer
of a normal four-subgroup has index at most two, so `r²` centralizes it;
factor decomposition and the specified centralizer condition then show that
`r` centralizes it. The required root is `r^(orderOf r / 8)`, and cyclicity of
the ambient center identifies its fourth power with the central involution.

Source: Janko–Thompson, Math. Z. 113 (1970), §4, Case 1, p.392.
This calculation takes explicit rotation hypotheses and uses no Hall-model
classification.
-/

namespace Subgroup

private theorem center_factor_le_center_of_commuting_sup
    {P : Type*} [Group P] (A D : Subgroup P) [D.Normal]
    (hc : D ≤ centralizer (A : Set P)) (hg : A ⊔ D = ⊤)
    (y : D) (hy : y ∈ center D) : (y : P) ∈ center P := by
  apply mem_center_iff.mpr
  intro p
  have hp : p ∈ A ⊔ D := hg.symm ▸ mem_top p
  obtain ⟨a, ha, d, hd, rfl⟩ := mem_sup_of_normal_right.mp hp
  have hya : Commute a (y : P) := hc y.property a ha
  have hyd : Commute d (y : P) := congrArg Subtype.val (mem_center_iff.mp hy ⟨d, hd⟩)
  exact (hya.mul_left hyd).eq

/-- An extraspecial central product with the specified rotation has a cyclic
subgroup containing all squares, and the central involution has a fourth root
commuting with each element of every normal elementary abelian four-subgroup. -/
public theorem cyclic_squares_and_fourth_roots_of_central_product
    {P : Type*} [Group P] [Finite P] [IsCyclic (center P)]
    (hP : IsPGroup 2 P) (A D : Subgroup P) [A.Normal] [D.Normal]
    [IsExtraspecial 2 A]
    (hc : D ≤ centralizer (A : Set P)) (hg : A ⊔ D = ⊤)
    (r : D) (hr8 : 8 ∣ orderOf r)
    (hsq : ∀ d : D, d ^ 2 ∈ zpowers (r ^ 2))
    (hZ : center D ≤ zpowers (r ^ 2))
    (hcent : centralizer ({r ^ 2} : Set D) ≤ zpowers r)
    (hhalf : r ^ (orderOf r / 2) ∈ center D) :
    ∃ R : Subgroup P, IsCyclic R ∧ (∀ x : P, x ^ 2 ∈ R) ∧
      ∀ F : Subgroup P, F.Normal → IsElementaryAbelian 2 F → Nat.card F = 4 →
        ∀ z t : P, z ∈ center P → orderOf z = 2 → t ∈ F →
          ∃ x : P, x ^ 4 = z ∧ Commute x t := by
  have hD : D ≠ ⊥ := by
    intro h
    have hr1 : (r : P) = 1 := by simpa [h] using r.property
    have hr1' : r = 1 := Subtype.ext hr1
    simp [hr1'] at hr8
  have hinf : A ⊓ D = (center A).map A.subtype := by
    apply eq_of_le_of_card_ge
    · intro a ha
      refine ⟨⟨a, ha.1⟩, mem_center_iff.mpr ?_, rfl⟩
      intro b
      exact Subtype.ext (hc ha.2 b b.property)
    · rw [card_map_of_injective A.subtype_injective,
        IsExtraspecial.center_order_p 2 A,
        card_inf_eq_two_of_extraspecial_of_cyclic_center hP A D hD hc]
  let R := (zpowers (r ^ 2)).map D.subtype
  have haSq (a : A) : (a : P) ^ 2 ∈ R := by
    have ha : (a : P) ^ 2 ∈ A ⊓ D := by
      rw [hinf]
      exact ⟨a ^ 2, IsExtraspecial.square_mem_center a, rfl⟩
    have hz : (⟨(a : P) ^ 2, ha.2⟩ : D) ∈ center D := by
      apply mem_center_iff.mpr
      intro d
      exact Subtype.ext (hc d.property _ ha.1).symm
    exact ⟨⟨(a : P) ^ 2, ha.2⟩, hZ hz, rfl⟩
  refine ⟨R, ?_, ?_, ?_⟩
  · exact ((zpowers (r ^ 2)).equivMapOfInjective D.subtype
      D.subtype_injective).isCyclic.mp inferInstance
  · intro p
    have hp : p ∈ A ⊔ D := hg.symm ▸ mem_top p
    obtain ⟨a, ha, d, hd, rfl⟩ := mem_sup_of_normal_right.mp hp
    have had : Commute a d := hc hd a ha
    rw [had.mul_pow]
    exact R.mul_mem (haSq ⟨a, ha⟩) ⟨(⟨d, hd⟩ : D) ^ 2, hsq ⟨d, hd⟩, rfl⟩
  · intro F hFn hFe hF z t hz hoz ht
    let : F.Normal := hFn
    let : IsElementaryAbelian 2 F := hFe
    have hr2 : (r : P) ^ 2 ∈ centralizer (F : Set P) := by
      have hbound := centralizer_index_le_two_of_normal_four hP F hF
      have hpos := (centralizer (F : Set P)).index_ne_zero_of_finite
      by_cases hidx : (centralizer (F : Set P)).index = 1
      · rw [index_eq_one.mp hidx]
        trivial
      · exact sq_mem_of_index_two (by omega) _
    have hrt : Commute (r : P) t := by
      have htgen : t ∈ A ⊔ D := hg.symm ▸ mem_top t
      obtain ⟨a, ha, d, hd, heq⟩ := mem_sup_of_normal_right.mp htgen
      have hdcent : (⟨d, hd⟩ : D) ∈ centralizer ({r ^ 2} : Set D) := by
        apply mem_centralizer_singleton_iff.mpr
        apply Subtype.ext
        change d * (r : P) ^ 2 = (r : P) ^ 2 * d
        apply mul_left_cancel (a := a)
        calc
          a * (d * (r : P) ^ 2) = (a * d) * (r : P) ^ 2 := (mul_assoc _ _ _).symm
          _ = (r : P) ^ 2 * (a * d) := by rw [heq]; exact hr2 t ht
          _ = a * ((r : P) ^ 2 * d) := by
            rw [← mul_assoc, ← hc (D.pow_mem r.property 2) a ha, mul_assoc]
      have hdr : Commute r (⟨d, hd⟩ : D) := by
        obtain ⟨k, hk⟩ := hcent hdcent
        rw [← hk]
        exact (Commute.refl r).zpow_right k
      rw [← heq]
      exact (show Commute (r : P) a from (hc r.property a ha).symm).mul_right
        (congrArg Subtype.val hdr.eq)
    have hhalfZ : ((r : P) ^ (orderOf r / 2)) ∈ center P :=
      center_factor_le_center_of_commuting_sup A D hc hg _ hhalf
    have hhalfOrder : orderOf ((r : P) ^ (orderOf r / 2)) = 2 := by
      rw [← Subgroup.coe_pow, Subgroup.orderOf_coe]
      exact orderOf_pow_orderOf_div (Nat.ne_of_gt (orderOf_pos r))
        (dvd_trans (by decide : 2 ∣ 8) hr8)
    have hhalfEq : (r : P) ^ (orderOf r / 2) = z := congrArg Subtype.val
      (IsCyclic.eq_of_orderOf_eq_two
        (x := ⟨_, hhalfZ⟩) (y := ⟨z, hz⟩)
        (by rw [← Subgroup.orderOf_coe]; exact hhalfOrder)
        (by rw [← Subgroup.orderOf_coe]; exact hoz))
    refine ⟨(r : P) ^ (orderOf r / 8), ?_, hrt.pow_left _⟩
    rw [← pow_mul, show orderOf r / 8 * 4 = orderOf r / 2 by omega]
    exact hhalfEq

end Subgroup
