module

public import Theory.GroupTheory.PGroup.BinaryPowerSeries
public import Theory.GroupTheory.PGroup.PowerfulBinaryPowerSeries

/-!
# Frattini square roots in powerful finite two-groups

The square-series lifting theorem reduces Frattini root extraction to the
estimate `[Sₙ,G] ≤ Sₙ₊₂` for the iterated square subgroups. The powerful-group
commutator estimate supplies this bound, and the Frattini subgroup of a finite
two-group is its subgroup generated by squares. Consequently every Frattini
element is a square. No bound on the number of generators is needed.

Source motivation: Traustason–Williams, *Powerfully nilpotent groups of rank 2
or small order*, Section 2, arXiv:2002.02694. That section uses power-root
extraction to place a generator of the derived subgroup in a cyclic subgroup
generated outside the Frattini subgroup.
-/

open scoped commutatorElement

/-- The powerful square-series commutator estimate suffices for Frattini
square-root extraction. No bound on the number of generators is needed for
this lifting step. -/
public theorem IsPGroup.exists_square_eq_of_mem_frattini_of_iteratedSquares_commutator_le
    {Q : Type*} [Group Q] [Finite Q] (hQ : IsPGroup 2 Q)
    (hcomm : ∀ n, ⁅Subgroup.iteratedSquares Q n, (⊤ : Subgroup Q)⁆ ≤
      Subgroup.iteratedSquares Q (n + 2))
    {x : Q} (hx : x ∈ frattini Q) : ∃ y : Q, y ^ 2 = x := by
  apply Subgroup.exists_square_of_iteratedSquares_commutator_le hQ hcomm
  rwa [Subgroup.iteratedSquares_one, ← hQ.frattini_eq_closure_squares]

/-- Every Frattini element of a powerful finite two-group is a square in the
ambient group. In particular, this supplies square roots for powerful
two-generated two-groups without needing the generator hypotheses. -/
public theorem IsPGroup.exists_square_eq_of_mem_frattini_of_commutator_le_fourthPowers
    {Q : Type*} [Group Q] [Finite Q] (hQ : IsPGroup 2 Q)
    (hpower : _root_.commutator Q ≤
      Subgroup.closure (Set.range (fun x : Q => x ^ (4 : ℕ))))
    {x : Q} (hx : x ∈ frattini Q) : ∃ y : Q, y ^ 2 = x := by
  exact hQ.exists_square_eq_of_mem_frattini_of_iteratedSquares_commutator_le
    (hQ.iteratedSquares_commutator_le_of_commutator_le_fourthPowers hpower) hx
