module
public import Stellmacher.SectionNine.NineThreeFirstRelationsAtSecondNeighbor

/-!
# Centralizing the mixed center commutator in (9.3)

Retain the actual first and second geometric extractions, with initial
center order greater than four. For their new vertices m,n, the commutator
of Z_n∩G_m and Z_m∩G_n lies in all four old and new centers. Both extracted
groups therefore centralize this commutator, as does their join.

Vertex stabilizers normalize their centers, so the commutator lies in both
new centers. The center-core containment of (7.3) and the two actual
center-intersection relations put it in both old centers as well. Each
extracted group is generated by its original module and that module's
selected conjugate. These lie in the corresponding old and new cores,
which centralize the respective centers by (7.3); hence both generators
centralize the commutator.

This gives the centralizer assertions for R₀, and thus for its subgroups,
in Stellmacher (9.3), Journal of Algebra 190 (1997), pp.49–50,
`refs/files/stellmacher-n-group.pdf`. All extraction witnesses are retained;
no normalization of the pair or conclusion of (9.3) is assumed.
-/
namespace Stellmacher.SectionNine
open Later SectionsFiveToSeven CosetGraphContext SevenSix
universe u

private theorem center_core_bounds
    {G : Type u} [Group G] [Finite G] {T A B : Subgroup G}
    (h : SectionSevenHypotheses G T A B) (Γ : CosetGraphContext G T A B)
    (d l : Γ.Vertex) (hl : l ∈ neighborhood Γ d) :
    ZAt Γ d ≤ QAt Γ d ∧ ZAt Γ d ≤ Subgroup.centralizer (QAt Γ d : Set G) := by
  have hZ := ((lemma_seven_three h Γ).center_core d l hl).trans
    (omegaOneCenter_le_centerAmbient _)
  exact ⟨hZ.trans (Subgroup.map_subtype_le _), hZ.trans (centerAmbient_le_centralizer _)⟩

private theorem extraction_centralizes_common_centers
    {G : Type u} [Group G] [Finite G] {T A B : Subgroup G}
    (h : SectionSevenHypotheses G T A B) (Γ : CosetGraphContext G T A B)
    (d l : Γ.Vertex) (hl : l ∈ neighborhood Γ d)
    (V E A0 : Subgroup G) (actor : G) (hVQ : V ≤ QAt Γ l)
    (data : NineThreeGeometricData Γ d l V E A0 actor)
    (R : Subgroup G) (hRl : R ≤ ZAt Γ l)
    (hRm : R ≤ ZAt Γ (Γ.act data.x⁻¹ l)) :
    E ≤ Subgroup.centralizer (R : Set G) := by
  have hlback : d ∈ neighborhood Γ l :=
    (mem_neighborhood_iff_adjacent Γ).mpr (Γ.adjacent_symm ((mem_neighborhood_iff_adjacent Γ).mp hl))
  have hmback : d ∈ neighborhood Γ (Γ.act data.x⁻¹ l) :=
    (mem_neighborhood_iff_adjacent Γ).mpr
      (Γ.adjacent_symm ((mem_neighborhood_iff_adjacent Γ).mp data.neighbor))
  have hCl := (center_core_bounds h Γ l d hlback).2
  have hCm := (center_core_bounds h Γ _ d hmback).2
  rw [data.generated]
  exact sup_le (hVQ.trans ((Subgroup.le_centralizer_iff.mp hCl).trans
      (Subgroup.centralizer_le hRl)))
    (data.conjugate_core_le.trans ((Subgroup.le_centralizer_iff.mp hCm).trans
      (Subgroup.centralizer_le hRm)))

public theorem nine_three_pair_center_commutator
    {H G : Type u} [Group H] [Finite H] [Group G] [Finite G]
    {S0 : Sylow 2 H} {S P1 P2 : Subgroup H}
    {embedding : G →* H} {T A B : Subgroup G}
    (ctx : AmbientSectionNineContext H S0 S P1 P2 embedding T A B)
    (hb : 1 < ctx.criticalPath.length)
    (hlarge : 4 < Nat.card (ZAt ctx.Γ ctx.criticalPath.a))
    (first : NineThreeFirstConfigurationData ctx)
    (second : NineThreeSecondConfigurationData ctx first) :
    let m := ctx.Γ.act first.extraction.x⁻¹ first.l
    let n := ctx.Γ.act second.extraction.x⁻¹ second.l
    let R := ⁅ZAt ctx.Γ n ⊓ GAt ctx.Γ m, ZAt ctx.Γ m ⊓ GAt ctx.Γ n⁆
    R ≤ ZAt ctx.Γ n ⊓ ZAt ctx.Γ second.l ⊓ ZAt ctx.Γ m ⊓ ZAt ctx.Γ first.l ∧
      first.E ⊔ second.E ≤ Subgroup.centralizer (R : Set G) := by
  let Γ := ctx.Γ
  let cp := ctx.criticalPath
  let m := Γ.act first.extraction.x⁻¹ first.l
  let n := Γ.act second.extraction.x⁻¹ second.l
  let R := ⁅ZAt Γ n ⊓ GAt Γ m, ZAt Γ m ⊓ GAt Γ n⁆
  have hRn : R ≤ ZAt Γ n :=
    (Subgroup.commutator_mono inf_le_left (le_refl _)).trans
      (Subgroup.le_normalizer_iff_commutator_le_left.mp
        (inf_le_right.trans (stabilizer_le_normalizer_z Γ n)))
  have hRm : R ≤ ZAt Γ m :=
    (Subgroup.commutator_mono (le_refl _) inf_le_left).trans
      (Subgroup.le_normalizer_iff_commutator_le_right.mp
        (inf_le_right.trans (stabilizer_le_normalizer_z Γ m)))
  have hmback : cp.a' ∈ neighborhood Γ m :=
    (mem_neighborhood_iff_adjacent Γ).mpr
      (Γ.adjacent_symm ((mem_neighborhood_iff_adjacent Γ).mp first.extraction.neighbor))
  have hnback : cp.firstStep ∈ neighborhood Γ n :=
    (mem_neighborhood_iff_adjacent Γ).mpr
      (Γ.adjacent_symm ((mem_neighborhood_iff_adjacent Γ).mp second.extraction.neighbor))
  have hRQm := hRm.trans (center_core_bounds ctx.sectionSeven Γ m cp.a' hmback).1
  have hRQn := hRn.trans (center_core_bounds ctx.sectionSeven Γ n cp.firstStep hnback).1
  have hRsecond : R ≤ ZAt Γ second.l := by
    have hh := le_inf hRn hRQm
    rw [(nine_three_second_center_relations ctx hb hlarge first second).1] at hh
    exact hh.trans inf_le_right
  have hRfirst : R ≤ ZAt Γ first.l := by
    have hh := le_inf hRm hRQn
    rw [(nine_three_first_relations_at_second_neighbor ctx hb hlarge first second).1] at hh
    exact hh.trans inf_le_right
  refine ⟨le_inf (le_inf (le_inf hRn hRsecond) hRm) hRfirst, sup_le ?_ ?_⟩
  · have hl : first.l ∈ neighborhood Γ cp.a' := by
      rw [first.penultimate]
      exact (nine_three_initial_extraction_inputs ctx.toLocalContext hb).1
    have hVQ : VAt Γ cp.firstStep ≤ QAt Γ first.l := by
      rw [first.penultimate]
      exact (nine_three_initial_extraction_inputs ctx.toLocalContext hb).2.1
    exact extraction_centralizes_common_centers ctx.sectionSeven Γ cp.a' first.l hl
      _ first.E first.A0 first.actor hVQ first.extraction R hRfirst hRm
  · have hl : second.l ∈ neighborhood Γ cp.firstStep := by
      obtain ⟨hsecond,he⟩ := second.second
      rw [he]
      exact (nine_three_second_extraction_inputs ctx.toLocalContext hb).1
    have hVQ : VAt Γ cp.a' ≤ QAt Γ second.l := by
      obtain ⟨hsecond,he⟩ := second.second
      rw [he]
      exact (nine_three_second_extraction_inputs ctx.toLocalContext hb).2.1
    exact extraction_centralizes_common_centers ctx.sectionSeven Γ cp.firstStep second.l hl
      _ second.E second.A0 second.actor hVQ second.extraction R hRsecond hRn
end Stellmacher.SectionNine
