module
public import Stellmacher.PushingUp.FaithfulFourNaturalAction
public import Stellmacher.SectionOne.SL2DistinctInvolutionsGenerate
public import Theory.GroupAction.SubgroupQuotientSupportLift

/-!
# Faithful four-element actions generated by two involutions

An actor acting faithfully on an elementary abelian group of order four embeds
in the matrix group `SL₂(2)` by the shared four-group coordinate construction.
If it contains two distinct involutions, their matrix images generate the full
matrix group, so the embedding is onto and the actor itself is `SL₂(2)`.  This
is the recognition step used for the literal central quotient action in (9.4).

Source: Stellmacher (9.4), printed pp.51--52, where the action on the
four-element quotient is identified from two distinct conjugate involutions.
-/

namespace Stellmacher.SectionNine
open Stellmacher.SectionOne
universe u v

public theorem isSL2Two_of_faithful_four_distinct_involutions
    {A W : Type*} [Group A] [Finite A] [Group W] [Finite W]
    [IsElementaryAbelian 2 W] [MulDistribMulAction A W]
    (hfaithful : fixingSubgroup A (Set.univ : Set W) = ⊥)
    (hWcard : Nat.card W = 4)
    (t u : A) (ht : IsInvolution t) (hu : IsInvolution u) (hne : t ≠ u) :
    IsSL2Two A := by
  obtain ⟨φ, hφ, _eW, _hcoord⟩ :=
    FourGroupMatrixCoordinates.faithful_card_four_embedding hfaithful hWcard
  let M := Matrix.SpecialLinearGroup (Fin 2) (ZMod 2)
  have hM : IsSL2Two (⊤ : Subgroup M) := ⟨Subgroup.topEquiv⟩
  have htin : φ t ∈ (⊤ : Subgroup M) := Subgroup.mem_top _
  have huin : φ u ∈ (⊤ : Subgroup M) := Subgroup.mem_top _
  have htinvol : IsInvolution (φ t) := by
    refine ⟨?_, ?_⟩
    · intro he
      apply ht.1
      exact hφ (by simpa using he)
    · simpa only [map_pow, map_one] using congrArg φ ht.2
  have huinvol : IsInvolution (φ u) := by
    refine ⟨?_, ?_⟩
    · intro he
      apply hu.1
      exact hφ (by simpa using he)
    · simpa only [map_pow, map_one] using congrArg φ hu.2
  have hφne : φ t ≠ φ u := fun h => hne (hφ h)
  have hgen : (⊤ : Subgroup M) = Subgroup.zpowers (φ t) ⊔
      Subgroup.zpowers (φ u) :=
    sl2_distinct_involutions_generate (⊤ : Subgroup M) hM (φ t) (φ u)
      htin huin htinvol huinvol hφne
  have hgenRange : Subgroup.zpowers (φ t) ⊔ Subgroup.zpowers (φ u) ≤ φ.range := by
    apply sup_le
    · exact Subgroup.zpowers_le.mpr ⟨t, rfl⟩
    · exact Subgroup.zpowers_le.mpr ⟨u, rfl⟩
  have hsurj : Function.Surjective φ := by
    apply MonoidHom.range_eq_top.mp
    apply top_unique
    exact hgen ▸ hgenRange
  exact ⟨MulEquiv.ofBijective φ ⟨hφ, hsurj⟩⟩

public theorem action_range_isSL2Two_of_distinct_involutions
    {F W : Type*} [Group F] [Finite F] [Group W] [Finite W]
    [IsElementaryAbelian 2 W] [MulDistribMulAction F W]
    (action : F →* MulAut W) (hWcard : Nat.card W = 4)
    (a b : F)
    (ha : IsInvolution (action.rangeRestrict a))
    (hb : IsInvolution (action.rangeRestrict b))
    (hne : action.rangeRestrict a ≠ action.rangeRestrict b) :
    IsSL2Two action.range := by
  let A := action.range
  have hfaithful : fixingSubgroup A (Set.univ : Set W) = ⊥ := by
    apply le_antisymm
    · intro x hx
      apply Subtype.ext
      apply MulEquiv.ext
      intro w
      exact (mem_fixingSubgroup_iff (M := A) (s := (Set.univ : Set W))).mp hx w
        (Set.mem_univ _)
    · exact bot_le
  exact isSL2Two_of_faithful_four_distinct_involutions hfaithful hWcard
    (action.rangeRestrict a) (action.rangeRestrict b) ha hb hne

public theorem action_ne_of_support_normalizer_contrast
    {G : Type*} [Group G] [Finite G]
    (P U Z N : Subgroup G)
    (hPU : P ≤ Subgroup.normalizer (U : Set G))
    [hZN : (Z.subgroupOf U).Normal]
    (B : Subgroup (U ⧸ Z.subgroupOf U))
    (action : P →* MulAut (U ⧸ Z.subgroupOf U))
    (hact : ∀ mover : P, ∀ point : U,
      action mover (QuotientGroup.mk' (Z.subgroupOf U) point) =
        QuotientGroup.mk' (Z.subgroupOf U)
          ⟨(mover : G) * (point : G) * (mover : G)⁻¹,
            (Subgroup.mem_normalizer_iff.mp (hPU mover.property) point).mp point.property⟩)
    (hBlift : ((B.comap (QuotientGroup.mk' (Z.subgroupOf U))).map U.subtype) = N)
    (g h : P) (hg : (g : G) ∉ Subgroup.normalizer (N : Set G))
    (hBinv : B.map (action h).toMonoidHom = B) :
    action g ≠ action h := by
  intro heq
  have hLg := Subgroup.lift_support_conjugate P U Z hPU action hact B g
  have hNg : N.map (MulAut.conj (g : G)).toMonoidHom = N := by
    calc
      N.map (MulAut.conj (g : G)).toMonoidHom =
          ((B.comap (QuotientGroup.mk' (Z.subgroupOf U))).map U.subtype).map
            (MulAut.conj (g : G)).toMonoidHom := by rw [hBlift]
      _ = ((B.map (action g).toMonoidHom).comap
          (QuotientGroup.mk' (Z.subgroupOf U))).map U.subtype := hLg
      _ = ((B.map (action h).toMonoidHom).comap
          (QuotientGroup.mk' (Z.subgroupOf U))).map U.subtype := by rw [heq]
      _ = ((B.comap (QuotientGroup.mk' (Z.subgroupOf U))).map U.subtype) := by rw [hBinv]
      _ = N := hBlift
  exact hg (Subgroup.mem_normalizer_iff_map_conj_eq.mpr hNg)

public theorem action_preserves_quotient_image_of_normalizer
    {G : Type*} [Group G] [Finite G]
    (P U Z N : Subgroup G)
    (hPU : P ≤ Subgroup.normalizer (U : Set G))
    [hZN : (Z.subgroupOf U).Normal]
    (_hZN' : Z ≤ N) (_hNU : N ≤ U)
    (action : P →* MulAut (U ⧸ Z.subgroupOf U))
    (hact : ∀ mover : P, ∀ point : U,
      action mover (QuotientGroup.mk' (Z.subgroupOf U) point) =
        QuotientGroup.mk' (Z.subgroupOf U)
          ⟨(mover : G) * (point : G) * (mover : G)⁻¹,
            (Subgroup.mem_normalizer_iff.mp (hPU mover.property) point).mp point.property⟩)
    (mover : P) (hmover : (mover : G) ∈ Subgroup.normalizer (N : Set G)) :
    ((N.subgroupOf U).map (QuotientGroup.mk' (Z.subgroupOf U))).map
        (action mover).toMonoidHom =
      (N.subgroupOf U).map (QuotientGroup.mk' (Z.subgroupOf U)) := by
  let q := QuotientGroup.mk' (Z.subgroupOf U)
  apply Subgroup.eq_of_le_of_card_ge
  · rintro point ⟨vector,⟨lift,hlift,rfl⟩,rfl⟩
    change action mover (q lift) ∈ (N.subgroupOf U).map q
    rw [hact]
    exact Subgroup.mem_map_of_mem q
      ((Subgroup.mem_normalizer_iff.mp hmover (lift : G)).mp hlift)
  · exact (Subgroup.card_map_of_injective (K := (N.subgroupOf U).map q)
      (action mover).injective).symm.le

public theorem action_range_isSL2Two_of_normalizer_contrast
    {G W : Type*} [Group G] [Finite G] [Group W] [Finite W]
    [IsElementaryAbelian 2 W] [MulDistribMulAction G W]
    (action : G →* MulAut W) (hWcard : Nat.card W = 4)
    (t u : G) (ht : IsInvolution (action.rangeRestrict t))
    (hu : IsInvolution (action.rangeRestrict u))
    (hdistinct : action.rangeRestrict t ≠ action.rangeRestrict u) :
    IsSL2Two action.range :=
  action_range_isSL2Two_of_distinct_involutions action hWcard t u ht hu hdistinct

end Stellmacher.SectionNine
