module
public import Stellmacher.SectionNine.NineNextFaithfulQuotient
public import Stellmacher.SectionNine.NineSevenCenterJoin
public import Stellmacher.SectionEight.EightFourSourceNineCommutingCore
public import Stellmacher.SectionEight.GeneratedEightSixNextConjugateGeometry
public import Stellmacher.SectionOne.LemmaOneTwo
public import Theory.GroupAction.QuotientFixedGeneration
public import Theory.GroupAction.SylowFixedGeneration


/-!
# Sylow-fixed generation on the actual next quotient module

Under the ambient Section Nine hypotheses with critical length greater than
one, every supplied conjugation action on the literal first-step module
modulo its center is generated by translates of the fixed subgroup of any
native first-step Sylow image. The supplied normality and action are retained;
no replacement quotient, action, or fixed-generation hypothesis is introduced.

The initial center has order four and contains the first-step center of order
two. The original edge Sylow normalizes both and therefore centralizes their
quotient. Local transitivity generates the first-step module from this initial
center, so the generic quotient fixed-generation theorem applies. Sylow
conjugacy transports generation from that edge Sylow to the requested Sylow.

Source: the next-orbit quotient after Stellmacher (9.3), printed p.50, and
its fixed-Sylow generation use in (9.8), printed pp.55–56. This supplies the
actual action input for the Section Three quadratic fixed-hyperplane theorem.
-/

namespace Stellmacher.SectionNine
open Later SectionsFiveToSeven CosetGraphContext SevenSix
universe u

public theorem nine_next_quotient_sylow_fixed_generation
    {H G : Type u} [Group H] [Finite H] [Group G] [Finite G]
    {S0 : Sylow 2 H} {S P1 P2 : Subgroup H}
    {embedding : G →* H} {T A B : Subgroup G}
    (ctx : AmbientSectionNineContext H S0 S P1 P2 embedding T A B)
    (hb : 1 < ctx.criticalPath.length)
    (hN : ((ZAt ctx.Γ ctx.criticalPath.firstStep).subgroupOf
      (VAt ctx.Γ ctx.criticalPath.firstStep)).Normal) :
    let _ := hN
    let P := GAt ctx.Γ ctx.criticalPath.firstStep
    let V := VAt ctx.Γ ctx.criticalPath.firstStep
    let Z := ZAt ctx.Γ ctx.criticalPath.firstStep
    ∀ action : P →* MulAut (V ⧸ Z.subgroupOf V),
      (∀ actor : P, ∀ point : V,
        action actor (QuotientGroup.mk' (Z.subgroupOf V) point) =
          QuotientGroup.mk' (Z.subgroupOf V)
            ⟨(actor : G) * (point : G) * (actor : G)⁻¹,
              (Subgroup.mem_normalizer_iff.mp
                (stabilizer_le_normalizer_v ctx.Γ ctx.criticalPath.firstStep actor.property)
                  point).mp point.property⟩) →
      ∀ sylow : Sylow 2 P,
        (⊤ : Subgroup (V ⧸ Z.subgroupOf V)) =
          SectionOne.actionClosure action.range (V ⧸ Z.subgroupOf V)
            (FixedPoints.subgroup ((sylow : Subgroup P).map action.rangeRestrict)
              (V ⧸ Z.subgroupOf V)) := by
  let _ := hN
  dsimp only
  intro action haction sylow
  let Γ := ctx.Γ
  let cp := ctx.criticalPath
  let P := GAt Γ cp.firstStep
  let V := VAt Γ cp.firstStep
  let Z := ZAt Γ cp.firstStep
  let seed := ZAt Γ cp.a
  have hPV : P ≤ Subgroup.normalizer (V : Set G) :=
    stabilizer_le_normalizer_v Γ cp.firstStep
  have hBV : seed ≤ V := (lemma_seven_four ctx.sectionSeven Γ cp).first_containment.1
  have hV : V = conjugateClosure seed P :=
    SectionEight.eight_six_neighbor_join_eq_conjugate_closure ctx.sectionSeven Γ
      cp.firstStep cp.a ((mem_neighborhood_iff_adjacent Γ).mpr (Γ.adjacent_symm cp.firstStep_adj))
  have hfour : Nat.card seed = 4 :=
    (lemma_nine_three_ambient ctx hb cp.a ⟨1, Γ.act_one _⟩).2
  have htwo : Nat.card Z = 2 :=
    (nine_next_center_and_commutator_of_initial_four ctx.toLocalContext hfour
      cp.firstStep ⟨1, Γ.act_one _⟩).1
  have hline : Z ≤ seed :=
    ((nine_seven_center_join ctx cp.a ⟨1, Γ.act_one _⟩).2 cp.firstStep
      ((mem_neighborhood_iff_adjacent Γ).mpr cp.firstStep_adj)).2
  have hindex : Z.relIndex seed = 2 := by
    have hprod := (Z.subgroupOf seed).index_mul_card
    rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hline).toEquiv, htwo, hfour] at hprod
    change Z.relIndex seed * 2 = 4 at hprod
    omega
  have hedge := edge_sylow_data ctx.sectionSeven Γ cp
  have hBS : ⁅seed,T⁆ ≤ Z := SectionEight.commutator_le_of_normalizing_index_two
    seed Z T hindex
    (hedge.1.1.trans (stabilizer_le_normalizer_z Γ cp.a))
    (hedge.2.1.trans (stabilizer_le_normalizer_z Γ cp.firstStep))
  have hgen := Subgroup.quotient_fixed_generation_of_conjugate_closure P V Z seed T
    hPV hedge.2.1 hBV hV hBS hN action haction
  obtain ⟨_, original, horiginal⟩ := hedge.2
  have hnative : T.subgroupOf P = (original : Subgroup P) := by
    calc
      T.subgroupOf P = ((original : Subgroup P).map P.subtype).subgroupOf P :=
        congrArg (fun subgroup : Subgroup G => subgroup.subgroupOf P) horiginal.symm
      _ = (original : Subgroup P) :=
        Subgroup.comap_map_eq_self_of_injective P.subtype_injective _
  rw [hnative] at hgen
  exact Subgroup.fixed_generation_of_sylow action.rangeRestrict original sylow hgen

end Stellmacher.SectionNine
