module

public import Stellmacher.SectionNine.LemmaNineThree
public import Stellmacher.SectionNine.NineNextCenterCommutator
public import Stellmacher.SectionNine.NineSevenResidualTwoArc

/-!
# Transport by the support and a neighboring core in Stellmacher (9.9)

Suppose a subgroup of the initial edge stabilizer has full nontrivial
commutator with the initial center, equal to the first-step center.
The original first-step two-core formulation is retained as a wrapper.
For any other neighbor of the initial vertex, the subgroup generated by
that neighbor's two-core and the support contains an element carrying
the neighbor to the first step.

The initial SL2(2) quotient from (9.3) gives a cubic local action. Since
the initial core centralizes the initial center, the support commutator
forces the support outside this core. It fixes the first step, so it
moves the chosen neighbor to the third neighbor. Transported (7.6)(b)
places the chosen neighbor's residual two-core outside the initial core;
its full two-core can therefore move the third neighbor to the first step.
The product of these two actual actors is the desired transporter.

This gives the precise consequence of the residual-generation argument
needed in the contained-center branch of (9.8) and after relation (1) in
Stellmacher (9.9), printed pp.55–56/PDF pp.45–46 of
`refs/files/stellmacher-n-group.pdf`. It proves the transporter directly
without assuming a full residual containment in the generated subgroup.
-/

namespace Stellmacher.SectionNine
open Later SectionsFiveToSeven CosetGraphContext SevenSix
universe u

/-- The support and neighboring core transport that neighbor to the first step. -/
public theorem nine_nine_support_transporter_of_edge
    {H G : Type u} [Group H] [Finite H] [Group G] [Finite G]
    {S0 : Sylow 2 H} {S P1 P2 : Subgroup H}
    {embedding : G →* H} {T A B : Subgroup G}
    (ctx : AmbientSectionNineContext H S0 S P1 P2 embedding T A B)
    (hb : 1 < ctx.criticalPath.length)
    (previous : ctx.Γ.Vertex)
    (hprevious : previous ∈ Neighborhood ctx.Γ ctx.criticalPath.a)
    (hne : previous ≠ ctx.criticalPath.firstStep)
    (support : Subgroup G)
    (hsupportEdge : support ≤ GAt ctx.Γ ctx.criticalPath.a ⊓
      GAt ctx.Γ ctx.criticalPath.firstStep)
    (hcomm : ⁅support, ZAt ctx.Γ ctx.criticalPath.a⁆ =
      ZAt ctx.Γ ctx.criticalPath.firstStep) :
    ∃ mover : G, mover ∈ QAt ctx.Γ previous ⊔ support ∧
      ctx.Γ.act mover previous = ctx.criticalPath.firstStep := by
  classical
  let Γ := ctx.Γ
  let cp := ctx.criticalPath
  have hmodel := lemma_nine_three_ambient ctx hb cp.a ⟨1, Γ.act_one _⟩
  have hcubic := cubic_local_action_of_sl2Two_quotient Γ ctx.sectionSeven cp.a hmodel.1
  have hfirstCard := nine_next_center_order_of_initial_four ctx.toLocalContext hmodel.2
  change Nat.card (ZAt Γ cp.firstStep) = 2 at hfirstCard
  have hfirstNe : ZAt Γ cp.firstStep ≠ ⊥ := by
    intro hbot
    rw [hbot, Subgroup.card_bot] at hfirstCard
    omega
  have hcenter := (lemma_seven_three ctx.sectionSeven Γ).center_core cp.a cp.firstStep
    ((mem_neighborhood_iff_adjacent Γ).mpr cp.firstStep_adj)
  have hsupportNot : ¬ support ≤ QAt Γ cp.a := by
    intro hle
    apply hfirstNe
    rw [← hcomm, Subgroup.commutator_eq_bot_iff_le_centralizer]
    exact hle.trans (Subgroup.le_centralizer_iff.mp
      (hcenter.trans ((omegaOneCenter_le_centerAmbient _).trans
        (centerAmbient_le_centralizer _))))
  let Neighbors := {vertex // Γ.adjacent cp.a vertex}
  let first : Neighbors := ⟨cp.firstStep, cp.firstStep_adj⟩
  let prev : Neighbors := ⟨previous, (mem_neighborhood_iff_adjacent Γ).mp hprevious⟩
  let _ : Finite Neighbors := Nat.finite_of_card_ne_zero (by rw [hcubic.degree]; decide)
  let _ := Fintype.ofFinite Neighbors
  have hsmall : ({first, prev} : Finset Neighbors).card < (Finset.univ : Finset Neighbors).card := by
    have hbound : ({first, prev} : Finset Neighbors).card ≤ 2 := by
      simpa only [Finset.card_singleton] using
        Finset.card_insert_le first ({prev} : Finset Neighbors)
    have hcard : (Finset.univ : Finset Neighbors).card = 3 := by
      rw [Finset.card_univ, ← Nat.card_eq_fintype_card]
      exact hcubic.degree
    omega
  obtain ⟨other, _, hother⟩ := Finset.exists_mem_notMem_of_card_lt_card hsmall
  have hotherFirst : other.val ≠ cp.firstStep := by
    intro heq
    exact hother (by simp only [Finset.mem_insert, Finset.mem_singleton]; exact Or.inl (Subtype.ext heq))
  have hotherPrevious : other.val ≠ previous := by
    intro heq
    exact hother (by simp only [Finset.mem_insert, Finset.mem_singleton]; exact Or.inr (Subtype.ext heq))
  obtain ⟨firstMover, hfirstMove⟩ := hcubic.punctured_transitivity cp.firstStep cp.firstStep_adj
    support hsupportEdge hsupportNot
      ⟨hprevious, hne⟩
      ⟨(mem_neighborhood_iff_adjacent Γ).mpr other.property, hotherFirst⟩
  have hpreviousAdj := (mem_neighborhood_iff_adjacent Γ).mp hprevious
  obtain ⟨aligner, haligner⟩ := (lemma_seven_one ctx.sectionSeven Γ).local_transitivity cp.a
    ((mem_neighborhood_iff_adjacent Γ).mpr cp.firstStep_adj) hprevious
  have horbit : IsConjugateVertex Γ cp.firstStep previous := ⟨aligner, haligner⟩
  have hpreviousCoreA : QAt Γ previous ≤ GAt Γ cp.a :=
    ((lemma_seven_three ctx.sectionSeven Γ).sylow_and_core previous cp.a
      ((mem_neighborhood_iff_adjacent Γ).mpr (Γ.adjacent_symm hpreviousAdj)) default).2.2
  have hpreviousCoreSelf : QAt Γ previous ≤ GAt Γ previous := by
    rw [QAt, q, Γ.twoCoreAt_def]
    exact twoCoreIn_le _
  have hpreviousNot : ¬ QAt Γ previous ≤ QAt Γ cp.a := by
    intro hle
    apply nine_seven_residual_core_escapes_neighbor ctx.toLocalContext previous cp.a horbit
      (Γ.adjacent_symm hpreviousAdj)
    apply le_trans ?_ hle
    change twoCoreIn (Γ.twoResidualAt previous) ≤ Γ.twoCoreAt previous
    rw [Γ.twoResidualAt_def, Γ.twoCoreAt_def, residual_core_eq_inter_core]
    exact inf_le_right
  obtain ⟨secondMover, hsecondMove⟩ := hcubic.punctured_transitivity previous hpreviousAdj
    (QAt Γ previous) (le_inf hpreviousCoreA hpreviousCoreSelf) hpreviousNot
      ⟨(mem_neighborhood_iff_adjacent Γ).mpr other.property, hotherPrevious⟩
      ⟨(mem_neighborhood_iff_adjacent Γ).mpr cp.firstStep_adj, hne.symm⟩
  refine ⟨(firstMover : G) * (secondMover : G), ?_, ?_⟩
  · exact (QAt Γ previous ⊔ support).mul_mem
      (Subgroup.mem_sup_right firstMover.property) (Subgroup.mem_sup_left secondMover.property)
  · rw [Γ.act_mul, hfirstMove]
    exact hsecondMove

/-- The original core-contained support version. -/
public theorem nine_nine_support_transporter
    {H G : Type u} [Group H] [Finite H] [Group G] [Finite G]
    {S0 : Sylow 2 H} {S P1 P2 : Subgroup H}
    {embedding : G →* H} {T A B : Subgroup G}
    (ctx : AmbientSectionNineContext H S0 S P1 P2 embedding T A B)
    (hb : 1 < ctx.criticalPath.length)
    (previous : ctx.Γ.Vertex)
    (hprevious : previous ∈ Neighborhood ctx.Γ ctx.criticalPath.a)
    (hne : previous ≠ ctx.criticalPath.firstStep)
    (support : Subgroup G)
    (hsupport : support ≤ QAt ctx.Γ ctx.criticalPath.firstStep)
    (hcomm : ⁅support, ZAt ctx.Γ ctx.criticalPath.a⁆ =
      ZAt ctx.Γ ctx.criticalPath.firstStep) :
    ∃ mover : G, mover ∈ QAt ctx.Γ previous ⊔ support ∧
      ctx.Γ.act mover previous = ctx.criticalPath.firstStep := by
  have hfirstCoreA : QAt ctx.Γ ctx.criticalPath.firstStep ≤ GAt ctx.Γ ctx.criticalPath.a :=
    ((lemma_seven_three ctx.sectionSeven ctx.Γ).sylow_and_core
      ctx.criticalPath.firstStep ctx.criticalPath.a
      ((mem_neighborhood_iff_adjacent ctx.Γ).mpr
        (ctx.Γ.adjacent_symm ctx.criticalPath.firstStep_adj)) default).2.2
  have hfirstCoreSelf : QAt ctx.Γ ctx.criticalPath.firstStep ≤
      GAt ctx.Γ ctx.criticalPath.firstStep := by
    rw [QAt, q, ctx.Γ.twoCoreAt_def]
    exact twoCoreIn_le _
  exact nine_nine_support_transporter_of_edge ctx hb previous hprevious hne support
    (le_inf (hsupport.trans hfirstCoreA) (hsupport.trans hfirstCoreSelf)) hcomm

end Stellmacher.SectionNine
