module
import Stellmacher.SectionsOneToFour
open Stellmacher
#check Stellmacher.SectionTwo.lemma_two_four
#check Stellmacher.SectionTwo.lemma_two_five
#check Stellmacher.SectionThree.lemma_three_one
#check Stellmacher.SectionThree.lemma_three_two
#check Stellmacher.SectionThree.lemma_three_three
#check Stellmacher.SectionThree.lemma_three_four
#check Stellmacher.SectionThree.lemma_three_five
#check Stellmacher.SectionThree.lemma_three_six
#check Stellmacher.SectionThree.lemma_three_seven
#check Stellmacher.SectionThree.lemma_three_eight
#check Stellmacher.SectionThree.lemma_three_nine
#check Stellmacher.SectionFour.lemma_four_one
#check Stellmacher.SectionFour.lemma_four_two
#check Stellmacher.SectionFour.lemma_four_three
#check Stellmacher.SectionFour.lemma_four_four
#check Stellmacher.SectionFour.lemma_four_five
#check Stellmacher.SectionFour.lemma_four_six
#check Stellmacher.SectionFour.lemma_four_seven
