module

public import FeitThompson.PFsection10.Basic
public import FeitThompson.PFsection9.PFsection9_11
public import FeitThompson.PFsection10.PFsection10_foundations
public import FeitThompson.PFsection10.PFsection10_supported
public import FeitThompson.PFsection10.PFsection10_late

-- Keep the historical root-level API selective while making the split
-- implementations available to downstream Section 10 users.
export Section10 (
  section10_source_not_typeI_typeII_of_msChoice_tail
  deltaSign_eq_one_or_neg_one_of_section10FourSixNotationSupportedData_early
  theorem_10_3_mu_entry_irreducible_supported
  theorem_10_3_supported
  classFunction_eq_signed_sub_of_norm_two_and_residual_orthogonal_pf105
  finite_orthonormal_virtual_coeff_support_card_le_two_pf105
  finite_orthonormal_coeff_normSq_sum_le_two_pf105
  coefficientNonzeroCount_le_four_of_two_cell_update_pf105
  two_cell_update_base_row_vanish_of_small_shape_pf105
  theorem_10_6
  theorem_10_7_late_source_type_of_typeIIIIVVData
  derivedSupportedFourSixData_of_hypothesis_10_1_supported_data
  hypothesis_4_6_derived_of_hypothesis_10_1_supported_data
  theorem_10_7_typeP_outer_complements_conj_source_data
  theorem_10_8_baseColumnMinusXi_CFOn_A0book_of_supported
  supportedOn_primeDadeA0_of_supportedOn_derivedSubgroup_degree_zero
  alphaChar_supportedOn_primeDadeA0_of_bridge_data
  fourTenTerm_supportedOn_primeDadeA0_of_section10FourSixNotationSupportedData
  theorem_10_7_late_source_type_of_hypothesis_10_1_supported_data
  theorem_10_7_supportedOn_derivedSubgroup_of_mem_hypothesis_10_1_supported_data
  theorem_10_8_supported
  alphaChar_CFOn_source_A0book_of_supported
  theorem_10_9_baseColumnMinusXi_CFOn_A0book_of_supported
  derivedInducedFamily_sub_CFon_A0book_of_supported
  theorem_10_9_mu_entry_muColumn_supported
  theorem_10_10_4_omegaColumnSigma_gram_supported
  exists_irreducible_inducing_muColumn_of_section10FourSixNotationSupportedData
  muColumn_supportedOn_derived_of_section10FourSixNotationSupportedData
  muColumn_mem_of_hypothesis_10_1_supported_and_section10FourSixNotationSupportedData
  theorem_4_10_of_section10FourSixNotationSupportedData
  exists_conjugate_muColumn_index_of_section10FourSixNotationSupportedData
  baseColumn_degree_one_of_section10FourSixNotationSupportedData
  theorem_10_10_4_muColumn_gram_supported
  theorem_10_9_candidate_supportedOn_primeDadeA0_supported
  theorem_10_9_supported_decomposition_source
  theorem_10_9_supported_decomposition_of_orthogonal
  theorem_10_10_exists_derivedInducedFamily
  theorem_10_10)
