module

public import GorensteinWalter.Section4.Defs
public import GorensteinWalter.MinimalCounterexample
public import GorensteinWalter.Section2.Theorem26Core
public import GorensteinWalter.Section2.Bender1970_18
public import GorensteinWalter.PGL2PerfectSubnormal
public import GorensteinWalter.PSL2PerfectSubnormal
public import GorensteinWalter.QuasisimpleNotTwoGroupQuotient
public import GorensteinWalter.NormalSubgroupInvolutionOfOddQuotientImage
public import GorensteinWalter.Section2.ComponentNormalOfInvariantPerfectImage
public import GorensteinWalter.Section2.NormalOfLinearDerivedModel
import FeitThompson.FinalTheorem
import Mathlib.Tactic

/-!
# Section 4: the component selected in the second case

This module proves `secondCase_componentData`.  The route is:

1. A maximal `M` of the minimal counterexample is a `D`-group.
2. A component `E` of `M` is selected from the nontrivial component layer.
3. The image of `E` in `M / O(M)` is the unique nontrivial perfect
   constituent of the `D`-group model, so `E / Z(E)` is `A₇` or `PSL₂(K)`.
4. The distinguished involution `t` lies in `E` by lifting its odd-kernel
   quotient image back through the odd normal subgroup `O(M)`.
-/

noncomputable section

open scoped Pointwise

namespace GorensteinWalter

universe u v

local instance fact_prime_two : Fact (Nat.Prime 2) := ⟨by decide⟩

/-! ## Local component-layer infrastructure -/

/-- The layer is perfect: every component is perfect and contained in the
layer, so the layer is generated by perfect subgroups of itself. -/
private theorem componentLayerOf_isPerfect {G : Type u} [Group G]
    (N : Subgroup G) :
    Group.IsPerfect (↥(componentLayerOf N)) := by
  apply Subgroup.isPerfect_iff.mpr
  let L : Subgroup G := componentLayerOf N
  apply le_antisymm
  · exact (Subgroup.commutator_le_sup L L).trans (sup_idem L).le
  · rw [componentLayerOf]
    refine sSup_le ?_
    intro E hE
    have hEperf : Group.IsPerfect E := (Group.isPerfect_def).2 hE.2.2.2.1
    have hEE : ⁅E, E⁆ = E := (Subgroup.isPerfect_iff).mp hEperf
    rw [← hEE]
    exact Subgroup.commutator_mono (le_sSup hE) (le_sSup hE)

/-- The layer of a subgroup is normal in that subgroup. -/
private theorem componentLayer_subgroupOf_normal {G : Type u} [Group G]
    (M : Subgroup G) :
    ((componentLayerOf M).subgroupOf M).Normal := by
  apply Subgroup.normal_subgroupOf_of_le_normalizer (H := M) (N := componentLayerOf M)
  intro m hm
  rw [Subgroup.mem_normalizer_iff]
  intro x
  constructor
  · exact (componentLayerOf_isNormalIn M).2 m hm x
  · intro hx
    have hback := (componentLayerOf_isNormalIn M).2 m⁻¹ (M.inv_mem hm)
      (m * x * m⁻¹) hx
    simpa [mul_assoc] using hback

/-- A nontrivial layer contains a component. -/
private theorem exists_component_of_componentLayerOf_ne_bot {G : Type u} [Group G]
    (N : Subgroup G) (hE : componentLayerOf N ≠ ⊥) :
    ∃ E : Subgroup G, IsComponentOf E N := by
  by_cases hex : ∃ E : Subgroup G, IsComponentOf E N
  · exact hex
  · exfalso
    apply hE
    rw [componentLayerOf]
    apply le_antisymm
    · refine sSup_le (fun E hcomp => ?_)
      have hEbot : E = ⊥ := by
        by_contra hne
        exact hex ⟨E, hcomp⟩
      rw [hEbot]
    · exact bot_le

/-- The two-group quotient branch of `IsDGroup` cannot contain a component. -/
private theorem component_impossible_of_quotient_isTwoGroup
    {G : Type u} [Group G] [Finite G]
    {N E : Subgroup G} (hE : IsComponentOf E N)
    (hQ : IsPGroup 2 (N ⧸ pPrimeCore 2 N)) : False := by
  let O : Subgroup N := pPrimeCore 2 N
  have hOcop : Nat.Coprime 2 (Nat.card O) := by
    simpa [O] using pPrimeCore_coprime_card (p := 2) (G := N)
  have hOodd : Odd (Nat.card O) := Nat.coprime_two_left.mp hOcop
  have hOsolv : Group.IsSolvable O := odd_order_theorem O hOodd
  letI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  haveI : Group.IsNilpotent (N ⧸ O) :=
    IsPGroup.isNilpotent (by simpa [O] using hQ)
  have hQsolv : Group.IsSolvable (N ⧸ O) := inferInstance
  letI : O.Normal := by
    dsimp [O]
    infer_instance
  letI : Group.IsSolvable O := hOsolv
  letI : Group.IsSolvable (N ⧸ O) := hQsolv
  have hNsolv : Group.IsSolvable N :=
    isSolvable_of_normal_subgroup_and_quotient O
  letI : Group.IsSolvable N := hNsolv
  letI : Group.IsSolvable (E.subgroupOf N) := inferInstance
  have hEsolv : Group.IsSolvable E :=
    isSolvable_of_mulEquiv (Subgroup.subgroupOfEquivOfLe hE.1)
  letI : Nontrivial E := hE.2.2.1
  letI : Group.IsPerfect E :=
    ⟨by simpa [derivedSubgroup] using hE.2.2.2.1⟩
  exact Group.IsPerfect.not_isSolvable E hEsolv

/-- Every involution of a finite group lies in a normal subgroup of odd
index. -/
private theorem involution_mem_normal_odd_index_local
    {Q : Type u} [Group Q] [Finite Q]
    (L : Subgroup Q) [L.Normal] (hLindex : Odd L.index)
    {x : Q} (hx : IsInvolution x) : x ∈ L := by
  let pi : Q →* Q ⧸ L := QuotientGroup.mk' L
  have hquotOdd : Odd (Nat.card (Q ⧸ L)) := by
    simpa only [Subgroup.index_eq_card] using hLindex
  have hsquare : (pi x) ^ 2 = 1 := by
    simpa using congrArg pi hx.2
  have hone : pi x = 1 :=
    eq_one_of_sq_eq_one_of_coprime_two hquotOdd.coprime_two_left hsquare
  exact (QuotientGroup.eq_one_iff (N := L) x).mp hone

/-- The quotient image of an involution is an involution. -/
private theorem quotient_involution_of_involution
    {Q : Type u} [Group Q]
    (N : Subgroup Q) [N.Normal] (hNodd : Odd (Nat.card N))
    {x : Q} (hx : IsInvolution x) :
    IsInvolution (QuotientGroup.mk' N x) := by
  constructor
  · intro hqx
    have hxN : x ∈ N :=
      (QuotientGroup.eq_one_iff (N := N) x).mp hqx
    let xN : N := ⟨x, hxN⟩
    have hxNI : IsInvolution xN := by
      constructor
      · intro hone
        exact hx.1 (congrArg Subtype.val hone)
      · exact Subtype.ext hx.2
    have hxNOrder : orderOf xN = 2 :=
      orderOf_eq_prime hxNI.2 hxNI.1
    have htwo : 2 ∣ Nat.card N := by
      rw [← hxNOrder]
      exact orderOf_dvd_natCard xN
    exact hNodd.not_two_dvd_nat htwo
  · simpa using congrArg (QuotientGroup.mk' N) hx.2

private def a7a : Equiv.Perm (Fin 7) := Equiv.swap (0 : Fin 7) 1 * Equiv.swap 1 2
private def a7b : Equiv.Perm (Fin 7) := Equiv.swap (0 : Fin 7) 1 * Equiv.swap 2 3

private lemma a7a_mem : a7a ∈ alternatingGroup (Fin 7) := by
  change Equiv.Perm.sign a7a = 1
  rw [a7a, Equiv.Perm.sign_mul, Equiv.Perm.sign_swap (by decide : (0 : Fin 7) ≠ 1),
    Equiv.Perm.sign_swap (by decide : (1 : Fin 7) ≠ 2)]
  norm_num

private lemma a7b_mem : a7b ∈ alternatingGroup (Fin 7) := by
  change Equiv.Perm.sign a7b = 1
  rw [a7b, Equiv.Perm.sign_mul, Equiv.Perm.sign_swap (by decide : (0 : Fin 7) ≠ 1),
    Equiv.Perm.sign_swap (by decide : (2 : Fin 7) ≠ 3)]
  norm_num

private lemma a7_not_comm : ¬ IsMulCommutative (alternatingGroup (Fin 7)) := by
  intro h
  have h1 : (⟨a7a, a7a_mem⟩ : alternatingGroup (Fin 7)) * ⟨a7b, a7b_mem⟩ =
      ⟨a7b, a7b_mem⟩ * ⟨a7a, a7a_mem⟩ := h.is_comm.comm _ _
  have h2 : a7a * a7b ≠ a7b * a7a := by
    decide
  exact h2 (by
    apply_fun (fun x : alternatingGroup (Fin 7) => (x : Equiv.Perm (Fin 7))) at h1
    simpa [Subgroup.coe_mul] using h1)

/-- The center of `A₇` is trivial. -/
private lemma center_eq_bot_alternatingGroupSeven :
    Subgroup.center (alternatingGroup (Fin 7)) = ⊥ := by
  have hsimple : IsSimpleGroup (alternatingGroup (Fin 7)) :=
    alternatingGroup.isSimpleGroup (by norm_num)
  rcases (hsimple.eq_bot_or_eq_top_of_normal
      (Subgroup.center (alternatingGroup (Fin 7))) inferInstance) with hbot | htop
  · exact hbot
  · exfalso
    have hcomm : IsMulCommutative (alternatingGroup (Fin 7)) := by
      refine ⟨⟨fun x y => ?_⟩⟩
      have hx : (x : alternatingGroup (Fin 7)) ∈ Subgroup.center (alternatingGroup (Fin 7)) := by
        rw [htop]
        trivial
      exact (Subgroup.mem_center_iff.mp hx y).symm
    exact a7_not_comm hcomm

/-- The image of the center under a group equivalence is the center. -/
public lemma map_center_eq_center_of_mulEquiv
    {A B : Type u} [Group A] [Group B]
    (e : A ≃* B) :
    (Subgroup.center A).map e.toMonoidHom = Subgroup.center B := by
  apply le_antisymm
  · intro x hx
    rcases hx with ⟨y, hy, rfl⟩
    exact (Subgroup.centerCongr e ⟨y, hy⟩).2
  · intro x hx
    refine ⟨e.symm x, ?_, ?_⟩
    · exact ((Subgroup.centerCongr e).symm ⟨x, hx⟩).2
    · exact e.apply_symm_apply x

/-- If the image of a quasisimple component modulo an odd normal kernel is
isomorphic to a centerless group, then the component's odd core is exactly
its center and the central quotient is that centerless group. -/
private theorem quasisimple_center_quotient_of_simple_image
    {H : Type u} [Group H] [Finite H]
    (E : Subgroup H) (hEq : IsQuasisimple E)
    (O : Subgroup H) [O.Normal] (hOodd : Odd (Nat.card O))
    (S : Type v) [Group S] [Finite S]
    (hScenter : Subgroup.center S = ⊥)
    (e : E.map (QuotientGroup.mk' O) ≃* S) :
    pPrimeCore 2 E = Subgroup.center E ∧
      Nonempty (E ⧸ Subgroup.center E ≃* S) := by
  classical
  let g : E →* E.map (QuotientGroup.mk' O) :=
    ((QuotientGroup.mk' O).comp E.subtype).codRestrict
      (E.map (QuotientGroup.mk' O)) (fun x =>
      Subgroup.mem_map.mpr ⟨x, x.2, rfl⟩)
  have hgsurj : Function.Surjective g := by
    intro y
    rcases Subgroup.mem_map.mp y.2 with ⟨x, hx, hyq⟩
    refine ⟨⟨x, hx⟩, ?_⟩
    apply Subtype.ext
    simpa [g] using hyq
  let f : E →* S := e.toMonoidHom.comp g
  have hfsurj : Function.Surjective f := e.surjective.comp hgsurj
  let N : Subgroup E := f.ker
  have hNleO : N ≤ O.comap E.subtype := by
    intro x hx
    rw [Subgroup.mem_comap]
    have hf1 : (QuotientGroup.mk' O) (E.subtype x) = 1 := by
      have hcomp : e.toMonoidHom (g x) = 1 := MonoidHom.mem_ker.mp hx
      exact congrArg Subtype.val (e.injective (by simpa using hcomp))
    exact (QuotientGroup.eq_one_iff (N := O) (E.subtype x)).mp hf1
  have hNodd : Odd (Nat.card N) := by
    have hNleOcard : Nat.card N ∣ Nat.card (O.comap E.subtype) :=
      Subgroup.card_dvd_of_le hNleO
    have hOcomap_dvd : Nat.card (O.comap E.subtype) ∣ Nat.card O :=
      Subgroup.card_comap_dvd_of_injective O E.subtype E.subtype_injective
    exact Odd.of_dvd_nat hOodd (hNleOcard.trans hOcomap_dvd)
  have hNcop : Nat.Coprime 2 (Nat.card N) := Nat.coprime_two_left.mpr hNodd
  have hNleCore : N ≤ pPrimeCore 2 E := le_sSup ⟨inferInstance, hNcop⟩
  have hZleN : Subgroup.center E ≤ N := by
    intro x hx
    apply MonoidHom.mem_ker.mpr
    have hxcentS : e.toMonoidHom (g x) ∈ Subgroup.center S := by
      rw [Subgroup.mem_center_iff]
      intro y
      rcases hfsurj y with ⟨z, rfl⟩
      have hcommE : z * x = x * z := (Subgroup.mem_center_iff.mp hx z)
      have hf : f (z * x) = f (x * z) := congrArg f hcommE
      simpa [f, g, map_mul] using hf
    have hxbot : e.toMonoidHom (g x) ∈ (⊥ : Subgroup S) := by
      simpa [hScenter] using hxcentS
    exact Subgroup.mem_bot.mp hxbot
  have hP_le_N : pPrimeCore 2 E ≤ N :=
    (pPrimeCore_le_center_of_isQuasisimple hEq).trans hZleN
  have hN_eq_core : N = pPrimeCore 2 E := le_antisymm hNleCore hP_le_N
  have hcore_eq : pPrimeCore 2 E = Subgroup.center E :=
    le_antisymm (pPrimeCore_le_center_of_isQuasisimple hEq)
      (hZleN.trans hNleCore)
  have hker : N = Subgroup.center E := hN_eq_core.trans hcore_eq
  let eQuot : E ⧸ f.ker ≃* S :=
    QuotientGroup.quotientKerEquivOfSurjective f hfsurj
  exact ⟨hcore_eq,
    ⟨(QuotientGroup.quotientMulEquivOfEq (M := Subgroup.center E) (N := f.ker) hker.symm).trans
      eQuot⟩⟩

/-- Transport a central-quotient model of `E.subgroupOf M` to the ambient
component `E`. -/
private theorem component_centerQuotient_transport
    {G : Type u} [Group G] [Finite G]
    {M E : Subgroup G} (hE : IsComponentOf E M)
    (S : Type u) [Group S] [Finite S] :
    Nonempty (((E.subgroupOf M) ⧸ Subgroup.center (E.subgroupOf M)) ≃* S) →
      Nonempty ((E ⧸ Subgroup.center E) ≃* S) := by
  intro hmodel
  let eEi : E.subgroupOf M ≃* E := Subgroup.subgroupOfEquivOfLe hE.1
  exact ⟨(QuotientGroup.congr (Subgroup.center (E.subgroupOf M))
    (Subgroup.center E) eEi (map_center_eq_center_of_mulEquiv eEi)).symm.trans
      hmodel.some⟩

/-- Convert normality of `E.subgroupOf M` inside `M` into the ambient
`IsNormalIn E M`. -/
private theorem normal_ambient_of_normal_subgroupOf
    {G : Type u} [Group G] {M E : Subgroup G} (hE : E ≤ M)
    (hEi : (E.subgroupOf M).Normal) :
    IsNormalIn E M := by
  refine ⟨hE, ?_⟩
  intro m hm e he
  have hnormal : ∀ (a b : G), a ∈ E → b ∈ M → b * a * b⁻¹ ∈ E :=
    (Subgroup.normal_subgroupOf_iff (H := E) (K := M) hE).mp hEi
  exact hnormal e m he hm

/-- The ambient center of `E` is odd when the odd part of the local subgroup
is exactly its local center. -/
private theorem center_odd_of_core_eq_center
    {G : Type u} [Group G] [Finite G]
    {M E : Subgroup G} (hE : E ≤ M)
    (hcore : pPrimeCore 2 (E.subgroupOf M) = Subgroup.center (E.subgroupOf M)) :
    Odd (Nat.card (Subgroup.center E)) := by
  let Ei : Subgroup M := E.subgroupOf M
  have hcopEi : Nat.Coprime 2 (Nat.card (Subgroup.center Ei)) := by
    have hcop : Nat.Coprime 2 (Nat.card (pPrimeCore 2 Ei)) :=
      pPrimeCore_coprime_card (p := 2) (G := Ei)
    simpa [Ei, hcore] using hcop
  have hoddEi : Odd (Nat.card (Subgroup.center Ei)) := Nat.coprime_two_left.mp hcopEi
  let eEi : Ei ≃* E := Subgroup.subgroupOfEquivOfLe hE
  have hcard : Nat.card (Subgroup.center Ei) = Nat.card (Subgroup.center E) :=
    Nat.card_congr (Subgroup.centerCongr eEi).toEquiv
  exact hcard ▸ hoddEi

/-- The selected component of the second-case maximal subgroup, together
with the odd-core quotient machinery. -/
public theorem secondCase_componentData
    {G : Type u} [Group G] [Finite G]
    (hmin : IsMinimalCounterexample G)
    (c : CentralizerSetup G)
    (w : SecondCaseWitness c) :
    Nonempty (SecondCaseComponentData w) := by
  classical
  let M : Subgroup G := w.M
  have hMmax : IsCoatom M := w.M_maximal
  have hD : IsDGroup (↥M) := properSubgroups_areDGroups hmin M hMmax.ne_top
  have htcM : c.t ∈ M := (componentLayerOf_isNormalIn M).1 w.t_mem_componentLayer
  have hLayer_ne : componentLayerOf M ≠ ⊥ := by
    intro hbot
    have htbot : c.t ∈ (⊥ : Subgroup G) := by
      rw [← hbot]
      exact w.t_mem_componentLayer
    exact c.t_involution.1 (Subgroup.mem_bot.mp htbot)
  obtain ⟨E, hE⟩ := exists_component_of_componentLayerOf_ne_bot M hLayer_ne
  let Ei : Subgroup M := E.subgroupOf M
  have hEi_ne : Ei ≠ ⊥ := by
    intro hbot
    have hmap : Ei.map M.subtype = E := Subgroup.map_subgroupOf_eq_of_le hE.1
    rw [hbot, Subgroup.map_bot] at hmap
    exact (Subgroup.nontrivial_iff_ne_bot E).mp hE.2.2.1 hmap.symm
  have hEi_perf : Group.IsPerfect Ei := by
    let eEi : Ei ≃* E := Subgroup.subgroupOfEquivOfLe hE.1
    letI : Group.IsPerfect E := (Group.isPerfect_def).2 hE.2.2.2.1
    exact Group.IsPerfect.ofSurjective (f := eEi.symm.toMonoidHom) eEi.symm.surjective
  have hEisn : Ei.IsSubnormal := hE.2.1
  have hEtopComp : IsComponentOf Ei (⊤ : Subgroup M) :=
    fstar_isComponentOf_subgroupOf_top hE
  have hEq : IsQuasisimple Ei :=
    isQuasisimple_mulEquiv_local (Subgroup.subgroupOfEquivOfLe hE.1).symm hE.2.2
  let O : Subgroup M := pPrimeCore 2 M
  letI : O.Normal := by dsimp [O]; infer_instance
  have hOodd : Odd (Nat.card O) := by
    have hcop : Nat.Coprime 2 (Nat.card O) := by
      simpa [O] using pPrimeCore_coprime_card (p := 2) (G := M)
    exact Nat.coprime_two_left.mp hcop
  have hOsolv : Group.IsSolvable O := odd_order_theorem O hOodd
  let q : M →* M ⧸ O := QuotientGroup.mk' O
  let Ebar : Subgroup (M ⧸ O) := Ei.map q
  let tM : M := ⟨c.t, htcM⟩
  have htM : IsInvolution tM := by
    constructor
    · intro h1
      exact c.t_involution.1 (Subtype.ext_iff.mp h1)
    · exact Subtype.ext (by simpa [pow_two] using c.t_involution.2)
  have htqM : IsInvolution (q tM) :=
    quotient_involution_of_involution O hOodd htM
  rcases hD with ⟨_hSylow, htwo⟩ | ⟨_hSylow, hA7⟩ |
    ⟨_hSylow, K, hK, L, hLnormal, hLindex, hLmodel⟩
  · exfalso
    exact component_impossible_of_quotient_isTwoGroup hE htwo
  · -- The `A₇` quotient branch.
    have hEbar_ne : Ebar ≠ ⊥ := by
      intro hbot
      have hEi_le_O : Ei ≤ O := by
        have hker : Ei ≤ q.ker := (Subgroup.map_eq_bot_iff (H := Ei) (f := q)).mp hbot
        simpa [q, QuotientGroup.ker_mk'] using hker
      letI : Group.IsSolvable O := hOsolv
      haveI : Group.IsSolvable Ei := by
        haveI : Group.IsSolvable (Ei.subgroupOf O) := inferInstance
        exact isSolvable_of_mulEquiv (Subgroup.subgroupOfEquivOfLe hEi_le_O)
      have hE_solv : Group.IsSolvable E := by
        let eEi : Ei ≃* E := Subgroup.subgroupOfEquivOfLe hE.1
        exact isSolvable_of_mulEquiv eEi
      haveI : Nontrivial E := hE.2.2.1
      haveI : Group.IsPerfect E := (Group.isPerfect_def).2 hE.2.2.2.1
      exact Group.IsPerfect.not_isSolvable E hE_solv
    have hEbar_perf : Group.IsPerfect Ebar := perfect_map_subgroup Ei q hEi_perf
    have hEbar_sn : Ebar.IsSubnormal :=
      hEisn.map (QuotientGroup.mk'_surjective O)
    have hsimpleQ : IsSimpleGroup (M ⧸ O) :=
      (MulEquiv.isSimpleGroup_congr hA7.some).mpr
        (alternatingGroup.isSimpleGroup (by norm_num))
    have hEbar_top : Ebar = ⊤ := by
      rcases Subgroup.IsSubnormal.eq_bot_or_top_of_isSimpleGroup
        hsimpleQ hEbar_sn with hbot | htop
      · exact False.elim (hEbar_ne hbot)
      · exact htop
    have hEbar_normal : Ebar.Normal := by
      rw [hEbar_top]
      infer_instance
    have hEi_normal : Ei.Normal :=
      component_normal_of_nontrivial_perfect_normal_image
        Ei hEtopComp q hEbar_ne hEbar_perf hEbar_normal
    let eEbar : Ebar ≃* alternatingGroup (Fin 7) :=
      (MulEquiv.subgroupCongr hEbar_top).trans (Subgroup.topEquiv.trans hA7.some)
    let eEbarULift : Ebar ≃* ULift.{u} (alternatingGroup (Fin 7)) :=
      eEbar.trans MulEquiv.ulift.symm
    have hcenterULift :
        Subgroup.center (ULift.{u} (alternatingGroup (Fin 7))) = ⊥ :=
      center_eq_bot_of_mulEquiv
        (MulEquiv.ulift : ULift.{u} (alternatingGroup (Fin 7)) ≃*
          alternatingGroup (Fin 7))
        center_eq_bot_alternatingGroupSeven
    have hmodel := quasisimple_center_quotient_of_simple_image
      Ei hEq O hOodd (ULift.{u} (alternatingGroup (Fin 7)))
      hcenterULift eEbarULift
    have hmodelA7 : Nonempty ((E ⧸ Subgroup.center E) ≃*
        alternatingGroup (Fin 7)) :=
      ⟨(component_centerQuotient_transport hE
        (ULift.{u} (alternatingGroup (Fin 7))) hmodel.2).some.trans
          MulEquiv.ulift⟩
    have htEi : tM ∈ Ei :=
      involution_mem_normal_subgroup_of_quotient_mem_map_odd_kernel
        Ei O hEi_normal (by dsimp [O]; infer_instance) hOodd htM (by
          change q tM ∈ Ebar
          rw [hEbar_top]
          trivial)
    have htE : c.t ∈ E := Subgroup.mem_subgroupOf.mp htEi
    exact ⟨⟨E, hE, htE,
      ComponentQuotientModel.alternating hmodelA7,
      normal_ambient_of_normal_subgroupOf hE.1 hEi_normal,
      center_odd_of_core_eq_center hE.1 hmodel.1⟩⟩
  · -- The linear quotient branch: `PSL₂(K)` or `PGL₂(K)`.
    rcases hLmodel with hPSL | hPGL
    · rcases hPSL with ⟨eL⟩
      have hIm := perfect_subnormal_image_le_normal_odd_index
        Ei hEi_perf hEi_ne hEisn O hOsolv L hLnormal hLindex
      have hEbar_ne : Ebar ≠ ⊥ := hIm.1
      have hEbar_perf : Group.IsPerfect Ebar := hIm.2.1
      have hEbar_sn : Ebar.IsSubnormal := hIm.2.2.1
      have hEbarL : Ebar ≤ L := hIm.2.2.2
      let EL : Subgroup L := Ebar.subgroupOf L
      have hEL_ne : EL ≠ ⊥ := by
        intro hbot
        have hmap : EL.map L.subtype = Ebar :=
          Subgroup.map_subgroupOf_eq_of_le hEbarL
        rw [hbot, Subgroup.map_bot] at hmap
        exact hEbar_ne hmap.symm
      have hEL_perf : Group.IsPerfect EL := by
        let eEL : EL ≃* Ebar := Subgroup.subgroupOfEquivOfLe hEbarL
        letI : Group.IsPerfect Ebar := hEbar_perf
        exact Group.IsPerfect.ofSurjective (f := eEL.symm.toMonoidHom) eEL.symm.surjective
      have hEL_sn : EL.IsSubnormal := hEbar_sn.subgroupOf
      let J : Subgroup (PSL2 K) := EL.map eL.toMonoidHom
      have hJ_ne : J ≠ ⊥ := by
        exact (Subgroup.map_eq_bot_iff_of_injective
          (H := EL) (f := eL.toMonoidHom) eL.injective).not.mpr hEL_ne
      have hJ_perf : Group.IsPerfect J := perfect_map_subgroup EL eL.toMonoidHom hEL_perf
      have hJ_sn : J.IsSubnormal := hEL_sn.map eL.surjective
      have hJtop := psl2_perfect_subnormal_eq_top K hK J hJ_ne hJ_perf hJ_sn
      have hEL_top : EL = ⊤ := by
        have hmap : (EL.map eL.toMonoidHom) = ⊤ := by
          have hJ : J = ⊤ := hJtop.2
          simpa [J] using hJ
        apply (Subgroup.map_injective (f := eL.toMonoidHom) eL.injective)
        simpa [J] using hmap
      have hEbar_L : Ebar = L := by
        apply le_antisymm hEbarL
        intro x hxL
        have hxEL : (⟨x, hxL⟩ : L) ∈ EL := by
          rw [hEL_top]
          trivial
        exact Subgroup.mem_subgroupOf.mp hxEL
      have hEbar_normal : Ebar.Normal := by
        rw [hEbar_L]
        infer_instance
      have hEi_normal : Ei.Normal :=
        component_normal_of_nontrivial_perfect_normal_image
          Ei hEtopComp q hEbar_ne hEbar_perf hEbar_normal
      let eEbar : Ebar ≃* PSL2 K :=
        (MulEquiv.subgroupCongr hEbar_L).trans eL
      have hmodel := quasisimple_center_quotient_of_simple_image
        Ei hEq O hOodd (PSL2 K) (psl2_center_eq_bot K) eEbar
      have htqE : q tM ∈ Ebar := by
        rw [hEbar_L]
        haveI : L.Normal := hLnormal
        exact involution_mem_normal_odd_index_local L hLindex htqM
      have htEi : tM ∈ Ei :=
        involution_mem_normal_subgroup_of_quotient_mem_map_odd_kernel
          Ei O hEi_normal (by dsimp [O]; infer_instance) hOodd htM htqE
      have htE : c.t ∈ E := Subgroup.mem_subgroupOf.mp htEi
      exact ⟨⟨E, hE, htE,
        ComponentQuotientModel.projectiveSpecialLinear K hK
          (component_centerQuotient_transport hE (PSL2 K) hmodel.2),
        normal_ambient_of_normal_subgroupOf hE.1 hEi_normal,
        center_odd_of_core_eq_center hE.1 hmodel.1⟩⟩
    · rcases hPGL with ⟨eL⟩
      have hcenter := quasisimple_component_kernel_eq_center_and_quotient_psl2
        Ei hEq hEisn O hOsolv K hK L hLnormal hLindex eL
      let f : Ei →* Ebar :=
        (q.comp Ei.subtype).codRestrict Ebar (fun x =>
          Subgroup.mem_map.mpr ⟨x, x.2, rfl⟩)
      have hker_eq : f.ker = Subgroup.center Ei := by
        simpa [f] using hcenter.1
      have hker_le_O : f.ker ≤ O.comap Ei.subtype := by
        intro x hx
        rw [Subgroup.mem_comap]
        have hf1 : f x = 1 := MonoidHom.mem_ker.mp hx
        have hq1 : q (Ei.subtype x) = 1 := congrArg Subtype.val hf1
        exact (QuotientGroup.eq_one_iff (N := O) (Ei.subtype x)).mp hq1
      have hker_odd : Odd (Nat.card f.ker) := by
        have hlecard : Nat.card f.ker ∣ Nat.card (O.comap Ei.subtype) :=
          Subgroup.card_dvd_of_le hker_le_O
        have hOcomap_dvd : Nat.card (O.comap Ei.subtype) ∣ Nat.card O :=
          Subgroup.card_comap_dvd_of_injective O Ei.subtype Ei.subtype_injective
        exact Odd.of_dvd_nat hOodd (hlecard.trans hOcomap_dvd)
      have hker_cop : Nat.Coprime 2 (Nat.card f.ker) :=
        Nat.coprime_two_left.mpr hker_odd
      have hker_le_core : f.ker ≤ pPrimeCore 2 Ei := le_sSup ⟨inferInstance, hker_cop⟩
      have hcore_le_center : pPrimeCore 2 Ei ≤ Subgroup.center Ei :=
        pPrimeCore_le_center_of_isQuasisimple hEq
      have hcore_eq_center : pPrimeCore 2 Ei = Subgroup.center Ei := by
        apply le_antisymm hcore_le_center
        simpa [hker_eq] using hker_le_core
      let LE : Subgroup M := (componentLayerOf M).subgroupOf M
      have hLE_normal : LE.Normal := componentLayer_subgroupOf_normal M
      have hLE_perf : Group.IsPerfect LE := by
        let eLE : LE ≃* componentLayerOf M :=
          Subgroup.subgroupOfEquivOfLe (componentLayerOf_isNormalIn M).1
        letI : Group.IsPerfect (componentLayerOf M) := componentLayerOf_isPerfect M
        exact Group.IsPerfect.ofSurjective (f := eLE.symm.toMonoidHom) eLE.symm.surjective
      have hLE_ne : LE ≠ ⊥ := by
        intro hbot
        have hEi_le_LE : Ei ≤ LE := by
          intro x hx
          exact Subgroup.mem_subgroupOf.mpr
            ((le_sSup (s := {E' : Subgroup G | IsComponentOf E' M}) hE)
              (Subgroup.mem_subgroupOf.mp hx))
        have hEi_bot : Ei = ⊥ := le_bot_iff.mp (hEi_le_LE.trans (le_of_eq hbot))
        exact hEi_ne hEi_bot
      have hLE_sn : LE.IsSubnormal := hLE_normal.isSubnormal
      let LEbar : Subgroup (M ⧸ O) := LE.map q
      obtain ⟨_, hLEbar_ne, hLEbar_perf, hLEbar_sn, hLEbarL, hJLE⟩ :=
        perfect_subnormal_component_image_in_pgl2
          LE hLE_perf hLE_ne hLE_sn O hOsolv K hK L hLnormal hLindex eL
      obtain ⟨_, hEbar_ne, hEbar_perf, hEbar_sn, hEbarL, hJE⟩ :=
        perfect_subnormal_component_image_in_pgl2
          Ei hEi_perf hEi_ne hEisn O hOsolv K hK L hLnormal hLindex eL
      have hEbar_normal : Ebar.Normal :=
        normal_of_subgroupOf_map_eq_commutator L Ebar hLnormal hEbarL eL hJE
      have hEi_normal : Ei.Normal :=
        component_normal_of_nontrivial_perfect_normal_image
          Ei hEtopComp q hEbar_ne hEbar_perf hEbar_normal
      have hLEbar_le_Ebar : LEbar ≤ Ebar := by
        intro x hx
        have hxL : x ∈ L := hLEbarL hx
        let xL : L := ⟨x, hxL⟩
        have hxJ : eL xL ∈ commutator (PGL2 K) := by
          have hxLL : (⟨x, hxL⟩ : L) ∈ LEbar.subgroupOf L := hx
          have hmem : eL xL ∈ (LEbar.subgroupOf L).map eL.toMonoidHom :=
            Subgroup.mem_map.mpr ⟨⟨x, hxL⟩, hxLL, rfl⟩
          rw [← hJLE]
          exact hmem
        have hmemE : eL xL ∈ (Ebar.subgroupOf L).map eL.toMonoidHom := by
          rw [hJE]
          exact hxJ
        rcases Subgroup.mem_map.mp hmemE with ⟨y, hy, hyeq⟩
        exact Subgroup.mem_subgroupOf.mp (by simpa [eL.injective hyeq] using hy)
      have htqE : q tM ∈ Ebar := by
        have htLE : tM ∈ LE := by
          exact Subgroup.mem_subgroupOf.mpr w.t_mem_componentLayer
        exact hLEbar_le_Ebar (Subgroup.mem_map.mpr ⟨tM, htLE, rfl⟩)
      have htEi : tM ∈ Ei :=
        involution_mem_normal_subgroup_of_quotient_mem_map_odd_kernel
          Ei O hEi_normal (by dsimp [O]; infer_instance) hOodd htM htqE
      have htE : c.t ∈ E := Subgroup.mem_subgroupOf.mp htEi
      exact ⟨⟨E, hE, htE,
        ComponentQuotientModel.projectiveSpecialLinear K hK
          (component_centerQuotient_transport hE (PSL2 K) hcenter.2),
        normal_ambient_of_normal_subgroupOf hE.1 hEi_normal,
        center_odd_of_core_eq_center hE.1 hcore_eq_center⟩⟩

end GorensteinWalter
