module
public import Stellmacher.SectionEight.EightSixSelectedOrbitFirstCommutator
public import Stellmacher.SectionEight.EightSixNextResidualCoreAction
public import Stellmacher.SectionEight.GeneratedEightSixNextCoreResidual

/-!
The selected orbit closure lies in the commutator of the next two-core with
the selected group's two-residual. The actual geometric witnesses imply that
the group is generated by its residual and the predecessor actor. Consequently
the orbit closure lies in the initial center joined with that commutator.
The first-commutator identity then puts it in the commutator joined with the
terminal center line.

The terminal line is also in the commutator: otherwise its order two and the
nontrivial core commutator make the residual commutator centralize the whole
next core. All next-stabilizer translates of the initial center would then
centralize that core, contradicting the actual first-commutator identity.
This local geometry is essential; abstract split modules do not satisfy the
claimed containment. Source: Stellmacher (8.6), printed p.43, assertion (12).
-/

namespace Stellmacher.SectionEight
open Later SectionsFiveToSeven CosetGraphContext
open scoped commutatorElement Pointwise
universe u

public theorem eight_six_selected_orbit_le_residual_commutator
    {G : Type u} [Group G] [Finite G] {S P1 P2 : Subgroup G}
    (ctx : SectionEightLocalContext G S P1 P2)
    (hcenter : ZAt ctx.Γ ctx.criticalPath.firstStep ≤
      CenterAmbient (GAt ctx.Γ ctx.criticalPath.firstStep))
    (hquot : QuotientIsModel (GAt ctx.Γ ctx.criticalPath.a)
      (QAt ctx.Γ ctx.criticalPath.a) SL2Two)
    (hlength : ctx.criticalPath.length = 2)
    (hcard : Nat.card (ZAt ctx.Γ ctx.criticalPath.a) = 4)
    (previous : ctx.Γ.Vertex) (D L Q : Subgroup G)
    (hprev : previous ∈ Neighborhood ctx.Γ ctx.criticalPath.a ∧
      previous ≠ ctx.criticalPath.firstStep)
    (data : EightSixEquationOneData ctx.Γ ctx.criticalPath previous D L Q)
    (E A0 : Subgroup G) (actor : G)
    (geom : SectionNine.NineThreeGeometricData ctx.Γ
      ctx.criticalPath.firstStep ctx.criticalPath.a
      (VAt ctx.Γ previous ⊓ QAt ctx.Γ ctx.criticalPath.a) E A0 actor)
    (hcore : conjugateClosure (ZAt ctx.Γ ctx.criticalPath.a) E ≤
      QAt ctx.Γ ctx.criticalPath.a)
    (hedge : E ⊔ (GAt ctx.Γ ctx.criticalPath.a ⊓ GAt ctx.Γ ctx.criticalPath.firstStep) =
      GAt ctx.Γ ctx.criticalPath.firstStep)
    (hD : D = QAt ctx.Γ previous ⊓ QAt ctx.Γ ctx.criticalPath.firstStep)
    (hL : L = conjugateClosure (QAt ctx.Γ previous) (GAt ctx.Γ ctx.criticalPath.a)) :
    conjugateClosure (ZAt ctx.Γ ctx.criticalPath.a) E ≤
      ⁅QAt ctx.Γ ctx.criticalPath.firstStep, twoResidualIn E⁆ := by
  classical
  let Γ := ctx.Γ
  let cp := ctx.criticalPath
  let A := VAt Γ previous ⊓ QAt Γ cp.a
  let U := conjugateClosure (ZAt Γ cp.a) E
  let Z := ZAt Γ cp.firstStep
  let V := VAt Γ cp.firstStep
  let P := GAt Γ cp.firstStep
  let R := QAt Γ cp.firstStep
  let B := twoResidualIn E
  let Y := ⁅R,B⁆
  have hBE : B ≤ E := SevenSix.twoResidualIn_le E
  have hAE : A ≤ E := geom.generated ▸ le_sup_left
  have hENB : E ≤ Subgroup.normalizer (B : Set G) :=
    (Subgroup.normal_subgroupOf_iff_le_normalizer hBE).mp (SevenSix.twoResidualIn_normal E)
  have hPNR : P ≤ Subgroup.normalizer (R : Set G) := SevenSix.stabilizer_le_normalizer_q Γ _
  have hENR : E ≤ Subgroup.normalizer (R : Set G) := geom.group_le.trans hPNR
  have hENY : E ≤ Subgroup.normalizer (Y : Set G) := by
    intro e he
    apply Subgroup.mem_normalizer_iff_map_conj_eq.mpr
    change (⁅R,B⁆).map (MulAut.conj e).toMonoidHom = ⁅R,B⁆
    rw [Subgroup.map_commutator]
    exact congrArg₂ (fun K J : Subgroup G => ⁅K,J⁆)
      (Subgroup.mem_normalizer_iff_map_conj_eq.mp (hENR he))
      (Subgroup.mem_normalizer_iff_map_conj_eq.mp (hENB he))
  have hVR : V ≤ R := SevenSix.neighbor_join_le_core_of_length_gt_one Γ cp
    (by exact hlength ▸ by decide) _
  have hUV : U ≤ V := by
    apply (Subgroup.closure_le _).mpr
    rintro g ⟨e,z,rfl⟩
    exact (Subgroup.mem_normalizer_iff.mp
      (stabilizer_le_normalizer_v Γ cp.firstStep (geom.group_le e.property)) z).mp
        ((lemma_seven_four ctx.sectionSeven Γ cp).first_containment.1 z.property)
  have hUR : U ≤ R := hUV.trans hVR
  have hseed : ZAt Γ cp.a ≤ U := by
    intro z hz
    exact Subgroup.subset_closure ⟨(1:E),⟨z,hz⟩,by simp⟩
  have hnot : ¬ A ≤ R := by
    intro hAR
    have hRG : R ≤ GAt Γ (Γ.act geom.x⁻¹ cp.a) :=
      ((lemma_seven_three ctx.sectionSeven Γ).sylow_and_core cp.firstStep _
        geom.neighbor default).2.2
    have hA0 : A0 = A := geom.coatom_eq.trans (inf_eq_left.mpr (hAR.trans hRG))
    have hcoatom := geom.coatom_card
    rw [hA0] at hcoatom
    have hpos : 0 < Nat.card A := Nat.card_pos
    change Nat.card A = 2 * Nat.card A at hcoatom
    omega
  have hBP : B ≤ EAt Γ cp.firstStep := by
    have hs := (SevenSix.edge_sylow_data ctx.sectionSeven Γ cp).2
    have hgen : twoResidualIn P ⊔ S = P := SevenSix.twoResidualIn_sup_sylow hs
    have hnorm : ((twoResidualIn P).subgroupOf (twoResidualIn P ⊔ S)).Normal := by
      rw [hgen]
      exact SevenSix.twoResidualIn_normal P
    have hp : IsPGroup 2 S := by
      obtain ⟨_,s,hs⟩ := hs
      exact hs ▸ s.isPGroup'.map P.subtype
    change B ≤ Γ.twoResidualAt cp.firstStep
    rw [Γ.twoResidualAt_def]
    exact SectionThree.twoResidualAmbient_le_left_of_le_sup (twoResidualIn P) S E
      hnorm hp (geom.group_le.trans_eq hgen.symm)
  have hYV : Y ≤ V := (Subgroup.commutator_mono le_rfl hBP).trans
    (eight_six_next_residual_core_commutator_le_v ctx hcenter hlength previous D L Q
      hprev.1 hD hL data hnot)
  have hspan := eight_six_selected_orbit_commutator_sup_line ctx hcenter hquot hlength hcard
    previous D L Q hprev data E A0 actor geom hcore hedge hD hL
  have hdouble := eight_six_selected_orbit_double_commutator_eq_bot ctx hcenter hquot hlength
    hcard previous D L Q hprev data E A0 actor geom hcore
  have hZC : Z ≤ Subgroup.centralizer (P : Set G) :=
    hcenter.trans (SevenSix.centerAmbient_le_centralizer _)
  have hZaC : ZAt Γ cp.a ≤ Subgroup.centralizer (A : Set G) := by
    rw [← hspan]
    exact sup_le (Subgroup.commutator_eq_bot_iff_le_centralizer.mp hdouble)
      (hZC.trans (Subgroup.centralizer_le (hAE.trans geom.group_le)))
  have hBA : B ⊔ A = E := by
    refine le_antisymm (sup_le hBE hAE) ?_
    rw [geom.generated]
    apply sup_le le_sup_right
    rintro g ⟨a,ha,rfl⟩
    exact (B ⊔ A).mul_mem
      ((B ⊔ A).mul_mem ((show B ≤ B ⊔ A from le_sup_left) geom.residual_mem)
        ((show A ≤ B ⊔ A from le_sup_right) ha))
      ((B ⊔ A).inv_mem ((show B ≤ B ⊔ A from le_sup_left) geom.residual_mem))
  have hUZaY : U ≤ ZAt Γ cp.a ⊔ Y := by
    have heq := eight_six_closure_eq_seed_sup_residual_commutator (ZAt Γ cp.a) E B A U
      hBE hAE (SevenSix.twoResidualIn_normal E) hBA
      ((Subgroup.le_centralizer_iff.mp hZaC).trans (Subgroup.centralizer_le_normalizer _))
      hseed (eight_six_conjugate_closure_normalizer _ _) rfl
    rw [heq]
    exact sup_le_sup le_rfl (Subgroup.commutator_mono hUR le_rfl)
  have hRNY : R ≤ Subgroup.normalizer (Y : Set G) := Subgroup.normalizer_commutator_ge_left R B
  have hZaNY := (hseed.trans hUR).trans hRNY
  have hCAY : ⁅U,A⁆ ≤ Y := by
    apply Subgroup.commutator_le.mpr
    intro u hu a ha
    have hum : u ∈ (ZAt Γ cp.a : Set G) * (Y : Set G) := by
      rw [← Subgroup.coe_mul_of_left_le_normalizer_right _ _ hZaNY]
      exact hUZaY hu
    obtain ⟨z,hz,y,hy,rfl⟩ := hum
    rw [commutatorElement_mul_left_eq_conj_mul]
    have hya : ⁅y,a⁆ ∈ Y := (Subgroup.le_normalizer_iff_commutator_le_left.mp
      (hAE.trans hENY)) (Subgroup.commutator_mem_commutator hy ha)
    have hza : ⁅z,a⁆ = 1 := by
      apply commutatorElement_eq_one_iff_mul_comm.mpr
      exact (Subgroup.mem_centralizer_iff.mp (hZaC hz) a ha).symm
    rw [hza,mul_one]
    exact (Subgroup.mem_normalizer_iff.mp (hZaNY hz) _).mp hya
  have hZaYZ : ZAt Γ cp.a ≤ Y ⊔ Z := by
    rw [← hspan]
    exact sup_le_sup hCAY le_rfl
  have hENZ : E ≤ Subgroup.normalizer (Z : Set G) :=
    geom.group_le.trans (stabilizer_le_normalizer_z Γ cp.firstStep)
  have hENYZ : E ≤ Subgroup.normalizer ((Y ⊔ Z : Subgroup G) : Set G) :=
    (le_inf hENY hENZ).trans (Subgroup.normalizer_inf_normalizer_le_normalizer_sup Y Z)
  have hUYZ : U ≤ Y ⊔ Z := by
    apply (Subgroup.closure_le _).mpr
    rintro g ⟨e,z,rfl⟩
    exact (Subgroup.mem_normalizer_iff.mp (hENYZ e.property) z).mp (hZaYZ z.property)
  have hZY : Z ≤ Y := by
    by_contra hn
    have hcardZ : Nat.card Z = 2 := (eight_six_first_step_fixed_line_local ctx hcenter hcard).1
    have hmeet : Y ⊓ Z = ⊥ := by
      have hdvd : Nat.card (Y ⊓ Z : Subgroup G) ∣ 2 :=
        hcardZ ▸ Subgroup.card_dvd_of_le (show Y ⊓ Z ≤ Z from inf_le_right)
      rcases (Nat.dvd_prime Nat.prime_two).mp hdvd with hc | hc
      · exact Subgroup.card_eq_one.mp hc
      · have heq : Y ⊓ Z = Z := Subgroup.eq_of_le_of_card_ge inf_le_right (by omega)
        exact (hn (heq ▸ inf_le_left)).elim
    have hYC : Y ≤ Subgroup.centralizer (R : Set G) := by
      apply Subgroup.commutator_eq_bot_iff_le_centralizer.mp
      apply le_bot_iff.mp
      rw [← hmeet]
      exact le_inf (Subgroup.le_normalizer_iff_commutator_le_left.mp hRNY)
        ((Subgroup.commutator_mono hYV le_rfl).trans_eq data.first_commutator)
    have hRG : R ≤ P := by
      change Γ.twoCoreAt _ ≤ Γ.vertexStabilizer _
      rw [Γ.twoCoreAt_def]
      exact Subgroup.map_subtype_le _
    have hZaCR : ZAt Γ cp.a ≤ Subgroup.centralizer (R : Set G) :=
      hZaYZ.trans (sup_le hYC (hZC.trans (Subgroup.centralizer_le hRG)))
    have hPC : P ≤ Subgroup.normalizer ((Subgroup.centralizer (R : Set G)) : Set G) :=
      hPNR.trans ((Subgroup.normal_subgroupOf_iff_le_normalizer
        (Subgroup.centralizer_le_normalizer (R : Set G))).mp inferInstance)
    have hVC : V ≤ Subgroup.centralizer (R : Set G) := by
      have hback : cp.a ∈ neighborhood Γ cp.firstStep :=
        (SevenSix.mem_neighborhood_iff_adjacent Γ).mpr (Γ.adjacent_symm cp.firstStep_adj)
      change VAt Γ cp.firstStep ≤ _
      rw [eight_six_neighbor_join_eq_conjugate_closure ctx.sectionSeven Γ cp.firstStep cp.a hback]
      apply (Subgroup.closure_le _).mpr
      rintro g ⟨p,z,rfl⟩
      exact (Subgroup.mem_normalizer_iff.mp (hPC p.property) z).mp (hZaCR z.property)
    have hzbot : Z = ⊥ := data.first_commutator.symm.trans
      (Subgroup.commutator_eq_bot_iff_le_centralizer.mpr hVC)
    have hc : Nat.card Z = 1 := Subgroup.card_eq_one.mpr hzbot
    omega
  exact hUYZ.trans (sup_le le_rfl hZY)

end Stellmacher.SectionEight
