module
public import Stellmacher.SectionEight.EightSixNextQuotientModule
public import Stellmacher.SectionEight.GeneratedEightSixSubgroupForcingHelper
public import Stellmacher.SectionEight.GeneratedEightSixResidualCommutator
public import Stellmacher.SectionThree.PSetQuadraticFixedHyperplane
public import Theory.GroupAction.SubgroupQuotientCommutatorImage
public import Theory.GroupAction.ActorSubtypeCommutator

/-!
# The quadratic actor restriction in Stellmacher (8.6)

Every subgroup Y of the actual predecessor core part A=V_previous∩Q_a that
acts quadratically on V_next/Z_next has image of order at most two modulo
the next ordinary two-core. The ambient double-commutator premise records
the literal quotient action, and the output retains the exact intersection
with D=Q_previous∩Q_next. No action or classification witness is assumed.

The next quotient module is elementary and generated by its Sylow-fixed
vectors. The hereditary (1.2) bridge produces a subgroup of Y of index at
most two with a fixed vector escaping the image of Q_a. Critical
noncommutation ensures that this image is proper. Lift the escaping vector
into V_next; its commutators with the pulled-back subgroup lie in Z_next.
Since V_next lies in Q_next and the vector escapes Q_a, the cubic subgroup
forcing theorem (4) puts that subgroup in D. Its index yields the bound.
The final relative-index corollary uses A≤Q_previous, so intersections with
D and Q_next coincide. This is the no-noncyclic-quadratic-image clause.

Source: Stellmacher (8.6), Journal of Algebra 190 (1997), printed p.42,
source-(5), using source-(4) and the hereditary form of (1.2). The distinct
noncontainment clause uses the ambient (8.3) argument and is left to the
canonical numbered assembly.
-/

namespace Stellmacher.SectionEight
open Later SectionsFiveToSeven CosetGraphContext
open scoped commutatorElement
universe u

private theorem commutator_zpowers_le
    {G : Type*} [Group G] (U Z : Subgroup G) (actor : G)
    (hnorm : actor ∈ Subgroup.normalizer (Z : Set G))
    (hcomm : ∀ u ∈ U, ⁅u, actor⁆ ∈ Z) : ⁅U, Subgroup.zpowers actor⁆ ≤ Z := by
  have hnorms : Subgroup.closure ({actor} : Set G) ≤ Subgroup.normalizer (Z : Set G) :=
    (Subgroup.closure_le _).mpr (Set.singleton_subset_iff.mpr hnorm)
  apply Subgroup.commutator_le.mpr
  intro u hu a ha
  rw [Subgroup.zpowers_eq_closure] at ha
  induction ha using Subgroup.closure_induction with
  | mem a ha => exact Set.mem_singleton_iff.mp ha ▸ hcomm u hu
  | one => simp
  | mul a b ha hb hac hbc =>
    rw [commutatorElement_mul_right_eq_mul_conj]
    simpa only [mul_assoc] using Z.mul_mem hac
      ((Subgroup.mem_normalizer_iff.mp (hnorms ha) _).mp hbc)
  | inv a ha hac =>
    rw [commutatorElement_inv_right, ← commutatorElement_inv]
    simpa only [inv_inv] using (Subgroup.mem_normalizer_iff.mp
      (hnorms ((Subgroup.closure ({actor} : Set G)).inv_mem ha)) _).mp (Z.inv_mem hac)

public theorem eight_six_nonquadratic_actor_local
    {G : Type u} [Group G] [Finite G] {S P1 P2 : Subgroup G}
    (ctx : SectionEightLocalContext G S P1 P2)
    (hcenter : ZAt ctx.Γ ctx.criticalPath.firstStep ≤
      CenterAmbient (GAt ctx.Γ ctx.criticalPath.firstStep))
    (hquot : QuotientIsModel (GAt ctx.Γ ctx.criticalPath.a)
      (QAt ctx.Γ ctx.criticalPath.a) SL2Two)
    (hlength : ctx.criticalPath.length = 2)
    (hcard : Nat.card (ZAt ctx.Γ ctx.criticalPath.a) = 4)
    (previous : ctx.Γ.Vertex) (D L Q : Subgroup G)
    (hprev : previous ∈ Neighborhood ctx.Γ ctx.criticalPath.a ∧
      previous ≠ ctx.criticalPath.firstStep)
    (hD : D = QAt ctx.Γ previous ⊓ QAt ctx.Γ ctx.criticalPath.firstStep)
    (equation : EightSixEquationOneData ctx.Γ ctx.criticalPath previous D L Q)
    (Y : Subgroup G)
    (hY : Y ≤ VAt ctx.Γ previous ⊓ QAt ctx.Γ ctx.criticalPath.a)
    (hquad : ⁅⁅VAt ctx.Γ ctx.criticalPath.firstStep, Y⁆, Y⁆ ≤
      ZAt ctx.Γ ctx.criticalPath.firstStep) :
    Nat.card Y ≤ 2 * Nat.card (Y ⊓ D : Subgroup G) := by
  classical
  let Γ := ctx.Γ
  let cp := ctx.criticalPath
  have hlen : cp.length = 2 := hlength
  let P := GAt Γ cp.firstStep
  let V := VAt Γ cp.firstStep
  let Z := ZAt Γ cp.firstStep
  let Qa := QAt Γ cp.a
  have hfirst : cp.firstStep ∈ Neighborhood Γ cp.a :=
    (SevenSix.mem_neighborhood_iff_adjacent Γ).mpr cp.firstStep_adj
  have hVQ : V ≤ QAt Γ cp.firstStep :=
    SevenSix.neighbor_join_le_core_of_length_gt_one Γ cp (by omega) _
  have hQaS : Qa ≤ S := (SevenSix.local_cores_le_edge_sylow ctx.sectionSeven Γ cp).1
  have hSP : S ≤ P := (SevenSix.edge_sylow_data ctx.sectionSeven Γ cp).2.1
  have hYP : Y ≤ P := (hY.trans inf_le_right).trans (hQaS.trans hSP)
  have hYprevious : Y ≤ QAt Γ previous := (hY.trans inf_le_left).trans
    (eight_six_neighbor_join_le_core Γ cp (by omega) previous)
  have hZaQ : ZAt Γ cp.a ≤ Qa :=
    ((lemma_seven_three ctx.sectionSeven Γ).center_core _ _ hfirst).trans
      ((SevenSix.omegaOneCenter_le_centerAmbient _).trans (Subgroup.map_subtype_le _))
  have hZQa : Z ≤ Qa := (eight_six_first_step_fixed_line_local ctx hcenter hcard).2.trans hZaQ
  have hVnot : ¬ V ≤ Qa := by
    intro hV
    have hZaC : ZAt Γ cp.a ≤ Subgroup.centralizer (Qa : Set G) :=
      ((lemma_seven_three ctx.sectionSeven Γ).center_core _ _ hfirst).trans
        ((SevenSix.omegaOneCenter_le_centerAmbient _).trans
          (SevenSix.centerAmbient_le_centralizer _))
    exact ctx.commutator_ne (Subgroup.commutator_eq_bot_iff_le_centralizer.mpr
      (hZaC.trans (Subgroup.centralizer_le
        ((eight_six_terminal_center_le_next_v Γ cp hlength).trans hV))))
  obtain ⟨hN, hW, action, haction, hkernel, hgenerate⟩ :=
    eight_six_next_quotient_module_data_local ctx hcenter hlength hcard equation.first_commutator
  let _ := hN
  let _ := hW
  let W := V ⧸ Z.subgroupOf V
  let q : V →* W := QuotientGroup.mk' (Z.subgroupOf V)
  let R : Subgroup W := (Qa.subgroupOf V).map q
  have hR : R ≠ ⊤ := by
    intro heq
    apply hVnot
    intro v hv
    have hmem : q ⟨v,hv⟩ ∈ R := heq ▸ Subgroup.mem_top _
    obtain ⟨b, hb, heqb⟩ := hmem
    have hd : b / (⟨v,hv⟩ : V) ∈ Z.subgroupOf V :=
      QuotientGroup.eq_iff_div_mem.mp heqb
    have hvQ := Qa.mul_mem (Qa.inv_mem (hZQa hd)) hb
    change ((b : G) / v)⁻¹ * (b : G) ∈ Qa at hvQ
    simpa [div_eq_mul_inv, mul_assoc] using hvQ
  obtain ⟨_, sylow, hsylow⟩ := (SevenSix.edge_sylow_data ctx.sectionSeven Γ cp).2
  have hSnative : (sylow : Subgroup P) = S.subgroupOf P := by
    apply Subgroup.map_injective P.subtype_injective
    rw [hsylow, Subgroup.map_subgroupOf_eq_of_le hSP]
  let Ynative := Y.subgroupOf P
  have hYsylow : Ynative ≤ (sylow : Subgroup P) := by
    rw [hSnative]
    exact Subgroup.subgroupOf_mono P ((hY.trans inf_le_right).trans hQaS)
  have hqgen : (⊤ : Subgroup W) = SectionOne.actionClosure action.range W
      (FixedPoints.subgroup ((sylow : Subgroup P).map action.rangeRestrict) W) := by
    rw [hSnative]
    exact hgenerate
  have hquadratic : IsQuadraticAction (Ynative.map action.rangeRestrict) W := by
    have hh := Subgroup.quotient_conjugation_quadratic_of_double_commutator_le
      P V Z Y (stabilizer_le_normalizer_v Γ cp.firstStep) hYP hN hquad action haction
    change commutatorAction₂ (Ynative.map action.rangeRestrict) W = ⊥
    rw [← commutatorAction₂_map_actor_subtype action.range (Ynative.map action.rangeRestrict),
      Subgroup.map_map]
    exact hh
  have hlocal := (SevenSix.edge_local_data ctx.sectionSeven Γ cp).2
  obtain ⟨Y₀, hY₀, hcount, hescape⟩ := SectionThree.pSet_quadratic_fixed_hyperplane_lift
    S P (SevenSix.sectionThreeHypotheses ctx.sectionSeven)
    ((pFamily_iff_pSet _ _ _).mp hlocal.1) hlocal.2 action hkernel sylow
    hqgen Ynative hYsylow hquadratic R hR
  obtain ⟨point, hpoint, hout⟩ := SetLike.not_le_iff_exists.mp hescape
  obtain ⟨x, rfl⟩ := QuotientGroup.mk'_surjective (Z.subgroupOf V) point
  have hxout : (x : G) ∉ Qa := fun hx => hout (Subgroup.mem_map_of_mem q hx)
  let U := Y₀.map P.subtype
  have hUY : U ≤ Y := by
    exact (Subgroup.map_mono hY₀).trans_eq (Subgroup.map_subgroupOf_eq_of_le hYP)
  have hcomm : ∀ y ∈ U, ⁅y, (x : G)⁆ ∈ Z := by
    rintro y ⟨yn, hyn, rfl⟩
    have hh := hpoint ⟨action.rangeRestrict yn, Subgroup.mem_map_of_mem action.rangeRestrict hyn⟩
    change action yn (q x) = q x at hh
    rw [haction] at hh
    have hd := QuotientGroup.eq_iff_div_mem.mp hh
    change (yn : G) * (x : G) * (yn : G)⁻¹ / (x : G) ∈ Z at hd
    change ⁅(yn : G), (x : G)⁆ ∈ Z
    simpa only [commutatorElement_def, div_eq_mul_inv] using hd
  have hUD : U ≤ D := by
    apply eight_six_cubic_subgroup_forcing ctx.sectionSeven Γ cp.a cp.firstStep previous
      hquot hfirst hprev.1 hprev.2 D hD equation.intersection_normal x (hVQ x.property)
      hxout U (hUY.trans hYprevious)
    exact (commutator_zpowers_le U Z x
      (stabilizer_le_normalizer_z Γ cp.firstStep (hSP
        ((SevenSix.local_cores_le_edge_sylow ctx.sectionSeven Γ cp).2 (hVQ x.property))))
      hcomm).trans ((eight_six_first_step_fixed_line_local ctx hcenter hcard).2.trans
        (eight_six_initial_center_le_intersection_of_length_two Γ cp hlength previous hprev.1 D hD))
  have hUcount : Nat.card U = Nat.card Y₀ := Subgroup.card_map_of_injective P.subtype_injective
  have hYcount : Nat.card Ynative = Nat.card Y :=
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe hYP).toEquiv
  have hUDcount := Subgroup.card_le_of_le (le_inf hUY hUD)
  rw [hYcount, ← hUcount] at hcount
  exact hcount.trans (Nat.mul_le_mul_left 2 hUDcount)

public theorem eight_six_quadratic_actor_core_index_le_two_local
    {G : Type u} [Group G] [Finite G] {S P1 P2 : Subgroup G}
    (ctx : SectionEightLocalContext G S P1 P2)
    (hcenter : ZAt ctx.Γ ctx.criticalPath.firstStep ≤
      CenterAmbient (GAt ctx.Γ ctx.criticalPath.firstStep))
    (hquot : QuotientIsModel (GAt ctx.Γ ctx.criticalPath.a)
      (QAt ctx.Γ ctx.criticalPath.a) SL2Two)
    (hlength : ctx.criticalPath.length = 2)
    (hcard : Nat.card (ZAt ctx.Γ ctx.criticalPath.a) = 4)
    (previous : ctx.Γ.Vertex) (D L Q : Subgroup G)
    (hprev : previous ∈ Neighborhood ctx.Γ ctx.criticalPath.a ∧
      previous ≠ ctx.criticalPath.firstStep)
    (hD : D = QAt ctx.Γ previous ⊓ QAt ctx.Γ ctx.criticalPath.firstStep)
    (equation : EightSixEquationOneData ctx.Γ ctx.criticalPath previous D L Q)
    (Y : Subgroup G)
    (hY : Y ≤ VAt ctx.Γ previous ⊓ QAt ctx.Γ ctx.criticalPath.a)
    (hquad : ⁅⁅VAt ctx.Γ ctx.criticalPath.firstStep, Y⁆, Y⁆ ≤
      ZAt ctx.Γ ctx.criticalPath.firstStep) :
    (Y ⊓ QAt ctx.Γ ctx.criticalPath.firstStep).relIndex Y ≤ 2 := by
  have hbound := eight_six_nonquadratic_actor_local ctx hcenter hquot hlength hcard
    previous D L Q hprev hD equation Y hY hquad
  have hYprevious : Y ≤ QAt ctx.Γ previous :=
    (hY.trans inf_le_left).trans (eight_six_neighbor_join_le_core ctx.Γ ctx.criticalPath (by omega) previous)
  have hintersection : Y ⊓ D = Y ⊓ QAt ctx.Γ ctx.criticalPath.firstStep := by
    rw [hD, ← inf_assoc, inf_eq_left.mpr hYprevious]
  rw [hintersection] at hbound
  have hcount := Subgroup.relIndex_mul_relIndex (⊥ : Subgroup G)
    (Y ⊓ QAt ctx.Γ ctx.criticalPath.firstStep) Y bot_le inf_le_left
  simp only [Subgroup.relIndex_bot_left] at hcount
  have hpos : 0 < Nat.card (Y ⊓ QAt ctx.Γ ctx.criticalPath.firstStep : Subgroup G) := Nat.card_pos
  nlinarith

end Stellmacher.SectionEight
