module

public import Stellmacher.SectionEight.GeneratedContext

public import Theory.GroupTheory.CentralFourFactorQuotient
public import Stellmacher.SectionFiveToSeven.SixThreeNativeQuotients
public import Stellmacher.SectionEight.NoncentralSylowCenterAction
public import Stellmacher.SectionFiveToSeven.Result7_6.LocalFacts
public import Stellmacher.SectionOne.RankOneThreeGroupAssembly.Defs

/-!
# Actual two-core quotients from the distance-one structural factor

For either distinguished edge stabilizer in the noncentral Section Eight
context, an elementary two-core generated by a normal subgroup of order
four and the ambient center has actual two-core quotient S3. This is a
conditional bridge for the central decomposition in the final paragraph
of Stellmacher (8.2), Journal of Algebra 190 (1997), p.38,
`refs/latex/stellmacher-n-group.tex`.

The edge characteristic data give self-centralization of the two-core.
The native (6.3) nested Frattini quotient has order six, giving a lower
bound on the actual core quotient. The conjugation action on the three
nonidentity elements of the supplied four-group then identifies that
actual quotient, with no identification of centralizer kernels assumed.
The two possible orders of the distinguished stabilizers P1 and P2 are
handled explicitly. No backward-edge transfer or distance hypothesis is
needed for this conditional bridge.

The supplemental theorem uses `SectionEightLocalContext` and its genuine
Section Seven hypotheses. The original public theorem remains a wrapper
through `SectionEightContext.toLocalContext`, preserving the graph and
critical path definitionally. No additional Sylow hypothesis is imposed
on the ambient group of the supplemental theorem.
-/

namespace Stellmacher.SectionEight

open Later SectionsFiveToSeven CosetGraphContext

universe u

public theorem eight_two_actual_core_quotient_of_four_factor_local
    {G : Type u} [Group G] [Finite G]
    {S P1 P2 : Subgroup G}
    (ctx : SectionEightLocalContext G S P1 P2)
    (hcenter : ¬ ZAt ctx.Γ ctx.criticalPath.firstStep ≤
      CenterAmbient (GAt ctx.Γ ctx.criticalPath.firstStep))
    (d : ctx.Γ.Vertex)
    (hd : d = ctx.criticalPath.a ∨ d = ctx.criticalPath.firstStep)
    [IsElementaryAbelian 2 (pCore 2 (GAt ctx.Γ d))]
    (U : Subgroup (GAt ctx.Γ d)) [U.Normal]
    (hQ : pCore 2 (GAt ctx.Γ d) = U ⊔ Subgroup.center (GAt ctx.Γ d))
    (hU : Nat.card U = 4) :
    Nonempty ((GAt ctx.Γ d ⧸ pCore 2 (GAt ctx.Γ d)) ≃* Equiv.Perm (Fin 3)) := by
  have h7 := ctx.sectionSeven
  have hcharacteristic := SevenSix.edge_characteristic_data h7 ctx.Γ ctx.criticalPath
  have hcent : Subgroup.centralizer
      (pCore 2 (GAt ctx.Γ d) : Set (GAt ctx.Γ d)) ≤ pCore 2 (GAt ctx.Γ d) := by
    rcases hd with rfl | rfl
    · exact hcharacteristic.1
    · exact hcharacteristic.2
  obtain ⟨_hleft, hright⟩ := eight_two_noncentral_sylow_center_action_local ctx hcenter
  obtain ⟨hP1, hP2⟩ := ctx.sixThree.nativeSL2 hright
  have hnested : IsSL2Two
      ((GAt ctx.Γ d ⧸ pCore 2 (GAt ctx.Γ d)) ⧸
        frattini (GAt ctx.Γ d ⧸ pCore 2 (GAt ctx.Γ d))) := by
    rcases hd with rfl | rfl
    · rcases ctx.criticalPath.edge_stabilizers_are_P with hedge | hedge
      · change IsSL2Two ((ctx.Γ.stabilizer ctx.criticalPath.a ⧸
          pCore 2 (ctx.Γ.stabilizer ctx.criticalPath.a)) ⧸
            frattini (ctx.Γ.stabilizer ctx.criticalPath.a ⧸
              pCore 2 (ctx.Γ.stabilizer ctx.criticalPath.a)))
        rw [hedge.1]
        exact hP1
      · change IsSL2Two ((ctx.Γ.stabilizer ctx.criticalPath.a ⧸
          pCore 2 (ctx.Γ.stabilizer ctx.criticalPath.a)) ⧸
            frattini (ctx.Γ.stabilizer ctx.criticalPath.a ⧸
              pCore 2 (ctx.Γ.stabilizer ctx.criticalPath.a)))
        rw [hedge.1]
        exact hP2
    · rcases ctx.criticalPath.edge_stabilizers_are_P with hedge | hedge
      · change IsSL2Two ((ctx.Γ.stabilizer ctx.criticalPath.firstStep ⧸
          pCore 2 (ctx.Γ.stabilizer ctx.criticalPath.firstStep)) ⧸
            frattini (ctx.Γ.stabilizer ctx.criticalPath.firstStep ⧸
              pCore 2 (ctx.Γ.stabilizer ctx.criticalPath.firstStep)))
        rw [hedge.2]
        exact hP2
      · change IsSL2Two ((ctx.Γ.stabilizer ctx.criticalPath.firstStep ⧸
          pCore 2 (ctx.Γ.stabilizer ctx.criticalPath.firstStep)) ⧸
            frattini (ctx.Γ.stabilizer ctx.criticalPath.firstStep ⧸
              pCore 2 (ctx.Γ.stabilizer ctx.criticalPath.firstStep)))
        rw [hedge.2]
        exact hP1
  have hlower : 6 ≤ Nat.card (GAt ctx.Γ d ⧸ pCore 2 (GAt ctx.Γ d)) := by
    rw [← SectionOne.RankOneThreeGroupAssembly.isSL2Two_card hnested]
    exact Nat.card_le_card_of_surjective _ (QuotientGroup.mk'_surjective _)
  exact quotient_perm_three_of_central_four_factor
    (pCore 2 (GAt ctx.Γ d)) U hQ hcent hU hlower

public theorem eight_two_actual_core_quotient_of_four_factor
    {G : Type u} [Group G] [Finite G]
    {S0 : Sylow 2 G} {S P1 P2 : Subgroup G}
    (ctx : SectionEightContext G S0 S P1 P2)
    (hcenter : ¬ ZAt ctx.Γ ctx.criticalPath.firstStep ≤
      CenterAmbient (GAt ctx.Γ ctx.criticalPath.firstStep))
    (d : ctx.Γ.Vertex)
    (hd : d = ctx.criticalPath.a ∨ d = ctx.criticalPath.firstStep)
    [IsElementaryAbelian 2 (pCore 2 (GAt ctx.Γ d))]
    (U : Subgroup (GAt ctx.Γ d)) [U.Normal]
    (hQ : pCore 2 (GAt ctx.Γ d) = U ⊔ Subgroup.center (GAt ctx.Γ d))
    (hU : Nat.card U = 4) :
    Nonempty ((GAt ctx.Γ d ⧸ pCore 2 (GAt ctx.Γ d)) ≃* Equiv.Perm (Fin 3)) :=
  @eight_two_actual_core_quotient_of_four_factor_local G _ _ S P1 P2
    ctx.toLocalContext hcenter d hd
    (inferInstance : IsElementaryAbelian 2 (pCore 2 (GAt ctx.Γ d)))
    U (inferInstance : U.Normal) hQ hU

end Stellmacher.SectionEight
