module

public import Theory.Character.CharacterValues
public import Theory.Character.Divisibility
public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
public import Mathlib.NumberTheory.NumberField.Cyclotomic.Basic
public import Mathlib.RingTheory.Ideal.GoingUp
public import Mathlib.RingTheory.Ideal.Int

/-!
# Central-character preliminaries for ordinary `2`-blocks

The ordinary central character of an irreducible representation takes its
values in the same cyclotomic integer ring as the character itself.  This is
the integrality bridge needed to define ordinary blocks by congruence of
central characters modulo a prime above `2`.

The proof embeds the class-sum scalar in the cyclotomic field, uses the
integrality of class sums, and identifies the integers of that field with
the order generated by the primitive root. Lying over then supplies a
maximal ideal above two. Equality of the reduced central characters defines
the block equivalence relation and its finite character-family classes.
These definitions are exposed because downstream block constructions reduce
them directly. The generator and integer-adjoin conversion lemmas also serve
the cyclotomic DVR development; the remaining implementation stays private.

Ported from `public/lean-eval/glauberman_zStar`,
`Submission/ZStar/BlockPreliminaries.lean` (revision `c3503435`), with the
current conjugacy-class character API. This is the central-character
congruence criterion for ordinary blocks, used in the modular proof of Z*.
-/

public section

noncomputable section

namespace ModularBlock

namespace BlockPreliminaries

open scoped IntermediateField

attribute [local instance] Fintype.ofFinite

universe u v

private lemma cyclotomicOrder_le_adjoin
    {η : ℂ} :
    cyclotomicOrder η ≤
      (IntermediateField.adjoin ℚ ({η} : Set ℂ)).toSubfield.toSubring := by
  rw [cyclotomicOrder, Subring.closure_le]
  intro z hz
  simp only [Set.mem_singleton_iff] at hz
  subst z
  exact IntermediateField.subset_adjoin ℚ ({η} : Set ℂ) (by simp)

lemma adjoin_generator_eq_top
    {η : ℂ} :
    let K := IntermediateField.adjoin ℚ ({η} : Set ℂ)
    let ηK : K := ⟨η, IntermediateField.subset_adjoin ℚ ({η} : Set ℂ) (by simp)⟩
    IntermediateField.adjoin ℚ ({ηK} : Set K) = ⊤ := by
  let K := IntermediateField.adjoin ℚ ({η} : Set ℂ)
  let : Algebra ℚ K := K.algebra'
  let ηK : K :=
    ⟨η, IntermediateField.subset_adjoin ℚ ({η} : Set ℂ) (by simp)⟩
  apply (IntermediateField.lift_inj
    (IntermediateField.adjoin ℚ ({ηK} : Set K)) (⊤ : IntermediateField ℚ K)).mp
  rw [IntermediateField.lift_adjoin, IntermediateField.lift_top]
  have himage : Subtype.val '' ({ηK} : Set K) = ({η} : Set ℂ) := by
    ext z
    simp [ηK]
  rw [himage]

private lemma classSumScalar_mem_adjoin
    {G : Type u} [Group G] [Finite G]
    {V : Type v} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G))
    (ρ : Representation ℂ G V) [Representation.IsIrreducible ρ]
    (c : ConjClasses G) :
    classSumScalar (ρ := ρ) c ∈
      IntermediateField.adjoin ℚ ({η} : Set ℂ) := by
  classical
  let K := IntermediateField.adjoin ℚ ({η} : Set ℂ)
  obtain ⟨x, hx⟩ := ConjClasses.exists_rep c
  have hxc : x ∈ c.carrier :=
    ConjClasses.mem_carrier_iff_mk_eq.mpr hx
  rw [classSumScalar_eq_card_mul_character_div ρ c hxc]
  have hcharA : ρ.character x ∈ cyclotomicOrder η :=
    representation_character_mem_cyclotomicOrder hη ρ x
  have hdegreeA : ρ.character 1 ∈ cyclotomicOrder η :=
    representation_character_mem_cyclotomicOrder hη ρ 1
  have hAK := cyclotomicOrder_le_adjoin (η := η)
  exact K.div_mem
    (K.mul_mem (K.natCast_mem (Nat.card c.carrier)) (hAK hcharA))
    (hAK hdegreeA)

private lemma isIntegral_adjoinElement_of_isIntegral_coe
    {η z : ℂ}
    (hzK : z ∈ IntermediateField.adjoin ℚ ({η} : Set ℂ))
    (hz : IsIntegral ℤ z) :
    IsIntegral ℤ
      (⟨z, hzK⟩ : IntermediateField.adjoin ℚ ({η} : Set ℂ)) := by
  rcases hz with ⟨P, hPmonic, hPzero⟩
  refine ⟨P, hPmonic, ?_⟩
  let K := IntermediateField.adjoin ℚ ({η} : Set ℂ)
  change Polynomial.eval₂ (Int.castRingHom K) (⟨z, hzK⟩ : K) P = 0
  apply Subtype.ext
  change K.val.toRingHom
    (Polynomial.eval₂ (Int.castRingHom K) (⟨z, hzK⟩ : K) P) = 0
  exact (Polynomial.ringHom_eval₂_intCastRingHom P K.val.toRingHom
    (⟨z, hzK⟩ : K)).trans (by simpa using hPzero)

lemma intAdjoin_coe_mem_cyclotomicOrder
    {η : ℂ}
    (K := IntermediateField.adjoin ℚ ({η} : Set ℂ))
    (ηK : K) (hηK : (ηK : ℂ) = η)
    (z : Algebra.adjoin ℤ ({ηK} : Set K)) :
    ((z : K) : ℂ) ∈ cyclotomicOrder η := by
  let A := cyclotomicOrder η
  refine Algebra.adjoin_induction
    (p := fun x _hx => ((x : K) : ℂ) ∈ A) ?_ ?_ ?_ ?_ z.property
  · intro x hx
    simp only [Set.mem_singleton_iff] at hx
    subst x
    simpa [hηK] using eta_mem_cyclotomicOrder η
  · intro m
    simp
  · intro x y _hx _hy hxA hyA
    simpa using A.add_mem hxA hyA
  · intro x y _hx _hy hxA hyA
    simpa using A.mul_mem hxA hyA

private def cyclotomicOrderSubalgebra (η : ℂ) : Subalgebra ℤ ℂ where
  carrier := cyclotomicOrder η
  zero_mem' := (cyclotomicOrder η).zero_mem
  add_mem' := (cyclotomicOrder η).add_mem
  one_mem' := (cyclotomicOrder η).one_mem
  mul_mem' := (cyclotomicOrder η).mul_mem
  algebraMap_mem' := by
    intro z
    exact intCast_mem_cyclotomicOrder η z

private lemma cyclotomicOrderSubalgebra_integral
    {η : ℂ} (hη : IsIntegral ℤ η) :
    Algebra.IsIntegral ℤ (cyclotomicOrderSubalgebra η) := by
  let B := Algebra.adjoin ℤ ({η} : Set ℂ)
  let : Algebra.IsIntegral ℤ B :=
    Algebra.IsIntegral.adjoin (by
      intro z hz
      simp only [Set.mem_singleton_iff] at hz
      subst z
      exact IsIntegral.algebraMap hη)
  have hBA : B = cyclotomicOrderSubalgebra η := by
    apply le_antisymm
    · apply Algebra.adjoin_le
      rw [Set.singleton_subset_iff]
      change η ∈ cyclotomicOrder η
      exact eta_mem_cyclotomicOrder η
    · intro z hz
      change z ∈ Subring.closure ({η} : Set ℂ) at hz
      have hle : Subring.closure ({η} : Set ℂ) ≤ B.toSubring := by
        apply Subring.closure_le.mpr
        intro x hx
        exact Algebra.subset_adjoin hx
      exact hle hz
  let e : B ≃ₐ[ℤ] cyclotomicOrderSubalgebra η :=
    Subalgebra.equivOfEq B (cyclotomicOrderSubalgebra η) hBA
  exact (e.isIntegral_iff).mp inferInstance

private lemma cyclotomicOrder_integral
    {G : Type u} [Group G] [Finite G]
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G)) :
    Algebra.IsIntegral ℤ (cyclotomicOrder η) := by
  let : Algebra.IsIntegral ℤ (cyclotomicOrderSubalgebra η) :=
    cyclotomicOrderSubalgebra_integral (hη := hη.isIntegral (Nat.card_pos (α := G)))
  let e : cyclotomicOrderSubalgebra η ≃ₐ[ℤ]
      cyclotomicOrder η :=
    { toFun := fun z => ⟨z, z.2⟩
      invFun := fun z => ⟨z, z.2⟩
      left_inv := fun _ => rfl
      right_inv := fun _ => rfl
      map_add' := fun _ _ => rfl
      map_mul' := fun _ _ => rfl
      commutes' := fun _ => rfl }
  apply Algebra.IsIntegral.mk
  intro z
  let z' : cyclotomicOrderSubalgebra η := ⟨z, z.2⟩
  have hz' : IsIntegral ℤ z' :=
    Algebra.IsIntegral.isIntegral z'
  simpa [e, z'] using hz'.map e

/-- A maximal ideal of `ℤ[η]` lying above the prime `2`. -/
theorem exists_maximalIdeal_above_two
    {G : Type u} [Group G] [Finite G]
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G)) :
    ∃ P : Ideal (cyclotomicOrder η),
      P.IsMaximal ∧ P.LiesOver (Ideal.span ({(2 : ℤ)} : Set ℤ)) := by
  classical
  let : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  let : (Ideal.span ({(2 : ℤ)} : Set ℤ)).IsMaximal :=
    Int.ideal_span_isMaximal_of_prime 2
  let : Algebra.IsIntegral ℤ (cyclotomicOrder η) :=
    cyclotomicOrder_integral hη
  exact Ideal.exists_maximal_ideal_liesOver_of_isIntegral
    (Ideal.span ({(2 : ℤ)} : Set ℤ))

/-- The scalar by which a conjugacy-class sum acts in an irreducible complex
representation belongs to the cyclotomic integer ring generated by a
primitive `|G|`-th root of unity. -/
theorem classSumScalar_mem_cyclotomicOrder
    {G : Type u} [Group G] [Finite G]
    {V : Type v} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G))
    (ρ : Representation ℂ G V) [Representation.IsIrreducible ρ]
    (c : ConjClasses G) :
    classSumScalar (ρ := ρ) c ∈
      cyclotomicOrder η := by
  classical
  let n := Nat.card G
  have hn : n ≠ 0 := (Nat.card_pos (α := G)).ne'
  let K := IntermediateField.adjoin ℚ ({η} : Set ℂ)
  let ηK : K :=
    ⟨η, IntermediateField.subset_adjoin ℚ ({η} : Set ℂ) (by simp)⟩
  have hηKcoe : (ηK : ℂ) = η := rfl
  have hηK : IsPrimitiveRoot ηK n := by
    apply IsPrimitiveRoot.of_map_of_injective (f := K.val) (by simpa [n, ηK] using hη)
    exact K.val.injective
  let : NeZero n := ⟨hn⟩
  have htopIF : IntermediateField.adjoin ℚ ({ηK} : Set K) = ⊤ := by
    exact adjoin_generator_eq_top (η := η)
  have hηKalg : IsAlgebraic ℚ ηK := by
    apply IsAlgebraic.of_pow (Nat.pos_of_ne_zero hn)
    rw [hηK.pow_eq_one]
    exact isAlgebraic_one
  have htopAlg : Algebra.adjoin ℚ ({ηK} : Set K) = ⊤ :=
    Algebra.adjoin_eq_top_of_intermediateField
      (by
        intro x hx
        simp only [Set.mem_singleton_iff] at hx
        subst x
        exact hηKalg) htopIF
  let e : (Algebra.adjoin ℚ ({ηK} : Set K)) ≃ₐ[ℚ] K :=
    (Subalgebra.equivOfEq _ _ htopAlg).trans Subalgebra.topEquiv
  let hcyclAdjoin : IsCyclotomicExtension {n} ℚ
      (Algebra.adjoin ℚ ({ηK} : Set K)) :=
    hηK.adjoin_isCyclotomicExtension ℚ
  let : IsCyclotomicExtension {n} ℚ K :=
    IsCyclotomicExtension.equiv {n} ℚ _ e
  let : Algebra ℤ K := Ring.toIntAlgebra K
  let Aint := Algebra.adjoin ℤ ({ηK} : Set K)
  let : IsIntegralClosure Aint ℤ K := by
    simpa [Aint] using
      (IsCyclotomicExtension.Rat.isIntegralClosure_adjoin_singleton hηK)
  let a := classSumScalar (ρ := ρ) c
  have haK : a ∈ K := by
    simpa [a, K, n] using classSumScalar_mem_adjoin hη ρ c
  let aK : K := ⟨a, haK⟩
  have haKint : IsIntegral ℤ aK :=
    isIntegral_adjoinElement_of_isIntegral_coe haK
      (classSumScalar_isIntegral ρ c)
  let aA : Aint := IsIntegralClosure.mk' Aint aK haKint
  have haA : algebraMap Aint K aA = aK :=
    IsIntegralClosure.algebraMap_mk' Aint aK haKint
  have haAcycl : (((aA : Aint) : K) : ℂ) ∈
      cyclotomicOrder η := by
    exact intAdjoin_coe_mem_cyclotomicOrder K ηK hηKcoe aA
  have hacoe : (((aA : Aint) : K) : ℂ) = a := by
    exact congrArg (fun z : K => (z : ℂ)) haA
  simpa [a, hacoe] using haAcycl

/-! ## Congruence central characters -/

/-- The scalar by which a class sum acts on an irreducible character, written
without choosing an affording representation. -/
@[expose] def ordinaryCentralCharacterValue
    {G : Type u} [Group G] [Finite G]
    (χ : ConjClassFunction G) (c : ConjClasses G) : ℂ :=
  (Nat.card c.carrier : ℂ) * χ c /
    χ (ConjClasses.mk (1 : G))

theorem ordinaryCentralCharacterValue_mem_cyclotomicOrder
    {G : Type u} [Group G] [Finite G]
    {χ : ConjClassFunction G}
    (hχ : IsIrreducibleConjCharacter χ)
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G))
    (c : ConjClasses G) :
    ordinaryCentralCharacterValue χ c ∈ cyclotomicOrder η := by
  classical
  rcases hχ.1 with ⟨n, ρ, hρχ⟩
  have hρirr : Representation.IsIrreducible ρ := by
    apply (irreducible_iff_character_norm_one (ρ := ρ)).2
    simpa [hρχ] using hχ.2
  let : Representation.IsIrreducible ρ := hρirr
  obtain ⟨x, hx⟩ := ConjClasses.exists_rep c
  have hxc : x ∈ c.carrier := ConjClasses.mem_carrier_iff_mk_eq.mpr hx
  have hscalar := classSumScalar_mem_cyclotomicOrder hη ρ c
  have hscalar_eq := classSumScalar_eq_card_mul_character_div ρ c hxc
  have hchar_eq : χ c = ρ.character x := by
    rw [hρχ, ← hx]
    rfl
  have hdegree_eq : χ (ConjClasses.mk (1 : G)) = ρ.character 1 := by
    rw [hρχ]
    rfl
  rw [ordinaryCentralCharacterValue, hchar_eq, hdegree_eq]
  rw [← hscalar_eq]
  exact hscalar

/-- The order-valued ordinary central character. -/
@[expose] def centralCharacterInCyclotomicOrder
    {G : Type u} [Group G] [Finite G]
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G))
    (χ : ConjClassFunction G)
    (hχ : IsIrreducibleConjCharacter χ)
    (c : ConjClasses G) : cyclotomicOrder η :=
  ⟨ordinaryCentralCharacterValue χ c,
    ordinaryCentralCharacterValue_mem_cyclotomicOrder hχ hη c⟩

/-- The reduction of a central character modulo an ideal of the cyclotomic
order. -/
@[expose] def reducedCentralCharacter
    {G : Type u} [Group G] [Finite G]
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G))
    (P : Ideal (cyclotomicOrder η))
    (χ : ConjClassFunction G)
    (hχ : IsIrreducibleConjCharacter χ) :
    ConjClasses G → (cyclotomicOrder η) ⧸ P :=
  fun c => Ideal.Quotient.mk P (centralCharacterInCyclotomicOrder hη χ hχ c)

/-- Two irreducible ordinary characters lie in the same congruence block when
all of their central-character values have the same reduction modulo `P`. -/
@[expose] def SameTwoBlock
    {G : Type u} [Group G] [Finite G]
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G))
    (P : Ideal (cyclotomicOrder η))
    (χ ψ : ConjClassFunction G)
    (hχ : IsIrreducibleConjCharacter χ)
    (hψ : IsIrreducibleConjCharacter ψ) : Prop :=
  reducedCentralCharacter hη P χ hχ = reducedCentralCharacter hη P ψ hψ

theorem sameTwoBlock_iff
    {G : Type u} [Group G] [Finite G]
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G))
    (P : Ideal (cyclotomicOrder η))
    (χ ψ : ConjClassFunction G)
    (hχ : IsIrreducibleConjCharacter χ)
    (hψ : IsIrreducibleConjCharacter ψ) :
    SameTwoBlock hη P χ ψ hχ hψ ↔
      ∀ c : ConjClasses G,
        centralCharacterInCyclotomicOrder hη χ hχ c -
          centralCharacterInCyclotomicOrder hη ψ hψ c ∈ P := by
  constructor
  · intro h c
    exact Ideal.Quotient.eq.mp (congrFun h c)
  · intro h
    funext c
    exact Ideal.Quotient.eq.mpr (h c)

theorem sameTwoBlock_refl
    {G : Type u} [Group G] [Finite G]
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G))
    (P : Ideal (cyclotomicOrder η))
    (χ : ConjClassFunction G)
    (hχ : IsIrreducibleConjCharacter χ) :
    SameTwoBlock hη P χ χ hχ hχ := rfl

theorem sameTwoBlock_symm
    {G : Type u} [Group G] [Finite G]
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G))
    (P : Ideal (cyclotomicOrder η))
    {χ ψ : ConjClassFunction G}
    {hχ : IsIrreducibleConjCharacter χ}
    {hψ : IsIrreducibleConjCharacter ψ}
    (h : SameTwoBlock hη P χ ψ hχ hψ) :
    SameTwoBlock hη P ψ χ hψ hχ := h.symm

theorem sameTwoBlock_trans
    {G : Type u} [Group G] [Finite G]
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G))
    (P : Ideal (cyclotomicOrder η))
    {χ ψ φ : ConjClassFunction G}
    {hχ : IsIrreducibleConjCharacter χ}
    {hψ : IsIrreducibleConjCharacter ψ}
    {hφ : IsIrreducibleConjCharacter φ}
    (h₁ : SameTwoBlock hη P χ ψ hχ hψ)
    (h₂ : SameTwoBlock hη P ψ φ hψ hφ) :
    SameTwoBlock hη P χ φ hχ hφ := h₁.trans h₂

/-- The congruence block of a chosen member of a finite irreducible-character
family. -/
@[expose] def ordinaryTwoBlock
    {G : Type u} [Group G] [Finite G]
    {I : Type v} [Fintype I] [DecidableEq I]
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G))
    (P : Ideal (cyclotomicOrder η))
    (χ : I → ConjClassFunction G)
    (hχ : ∀ i, IsIrreducibleConjCharacter (χ i))
    (base : I) : Finset I := by
  classical
  exact Finset.univ.filter fun i => SameTwoBlock hη P (χ i) (χ base) (hχ i) (hχ base)

@[simp] theorem mem_ordinaryTwoBlock_iff
    {G : Type u} [Group G] [Finite G]
    {I : Type v} [Fintype I] [DecidableEq I]
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G))
    (P : Ideal (cyclotomicOrder η))
    (χ : I → ConjClassFunction G)
    (hχ : ∀ i, IsIrreducibleConjCharacter (χ i))
    (base i : I) :
    i ∈ ordinaryTwoBlock hη P χ hχ base ↔
      SameTwoBlock hη P (χ i) (χ base) (hχ i) (hχ base) := by
  classical
  simp [ordinaryTwoBlock]

@[simp] theorem base_mem_ordinaryTwoBlock
    {G : Type u} [Group G] [Finite G]
    {I : Type v} [Fintype I] [DecidableEq I]
    {η : ℂ} (hη : IsPrimitiveRoot η (Nat.card G))
    (P : Ideal (cyclotomicOrder η))
    (χ : I → ConjClassFunction G)
    (hχ : ∀ i, IsIrreducibleConjCharacter (χ i))
    (base : I) :
    base ∈ ordinaryTwoBlock hη P χ hχ base := by
  rw [mem_ordinaryTwoBlock_iff]
  exact sameTwoBlock_refl hη P (χ base) (hχ base)

theorem two_mem_of_liesOver
    {η : ℂ} (P : Ideal (cyclotomicOrder η))
    (hP : P.LiesOver (Ideal.span ({(2 : ℤ)} : Set ℤ))) :
    (2 : cyclotomicOrder η) ∈ P := by
  let : P.LiesOver (Ideal.span ({(2 : ℤ)} : Set ℤ)) := hP
  apply (Ideal.mem_of_liesOver P (Ideal.span ({(2 : ℤ)} : Set ℤ)) 2).mp
  exact Ideal.subset_span (by simp)

theorem two_eq_zero_mod_liesOver
    {η : ℂ} (P : Ideal (cyclotomicOrder η))
    (hP : P.LiesOver (Ideal.span ({(2 : ℤ)} : Set ℤ))) :
    Ideal.Quotient.mk P (2 : cyclotomicOrder η) = 0 := by
  exact Ideal.Quotient.eq_zero_iff_mem.mpr (two_mem_of_liesOver P hP)

end BlockPreliminaries

end ModularBlock
