module

public import Theory.SpecificGroups.ReeTwo.CorePresentation
public import Theory.GroupTheory.TwoCosetExtension
public import Mathlib.Data.Nat.Init

/-!
# The order bound for the Ree two core presentation

The square of each generator and its commutators with later generators
involve strictly later roots. Starting with the trivial tail, adjoining
successive roots therefore at most doubles the order. Ten such steps bound
the presented core by 1024, without assuming consistency or a finite model.

The relations are Shinoda (1975), (2.3), pp. 81–82, as transcribed in
`Relations`. The bound applies to any group satisfying those relations.
-/

@[expose] public section
namespace ReeTwo

variable {G : Type*} [Group G]

/-- The subgroup generated by roots whose indices are at least `k`. -/
def coreTail (x : CoreRoot → G) (k : ℕ) : Subgroup G :=
  Subgroup.closure {g | ∃ i : CoreRoot, k ≤ i.val ∧ x i = g}

theorem rootWord_mem {x : CoreRoot → G} {K : Subgroup G} {w : List CoreRoot}
    (h : ∀ i ∈ w, x i ∈ K) : rootWord x w ∈ K := by
  induction w with
  | nil => exact K.one_mem
  | cons i w ih =>
    exact K.mul_mem (h i List.mem_cons_self) (ih (fun j hj => h j (List.mem_cons_of_mem i hj)))

theorem coreSquare_triangular : ∀ i j : CoreRoot, j ∈ coreSquare i → i < j := by decide

theorem coreCommutator_triangular :
    ∀ i j k : CoreRoot, i < j → k ∈ coreCommutator i j → i < k := by decide

theorem coreTail_square (x : CoreRoot → G) (h : CoreRelations x) (i : CoreRoot) :
    x i * x i ∈ coreTail x (i.val + 1) := by
  rw [h.square]
  apply rootWord_mem
  intro j hj
  exact Subgroup.subset_closure ⟨j, coreSquare_triangular i j hj, rfl⟩

theorem coreTail_conj (x : CoreRoot → G) (h : CoreRelations x) (i : CoreRoot) :
    ∀ g ∈ coreTail x (i.val + 1), (x i)⁻¹ * g * x i ∈ coreTail x (i.val + 1) := by
  have ht : coreTail x (i.val + 1) ≤
      (coreTail x (i.val + 1)).comap (MulAut.conj (x i)⁻¹).toMonoidHom := by
    apply (Subgroup.closure_le _).mpr
    rintro _ ⟨j, hj, rfl⟩
    change MulAut.conj (x i)⁻¹ (x j) ∈ coreTail x (i.val + 1)
    rw [rightConj_of_rightComm (h.commutator i j hj)]
    refine (coreTail x (i.val + 1)).mul_mem (Subgroup.subset_closure ⟨j, hj, rfl⟩)
      ((coreTail x (i.val + 1)).inv_mem (rootWord_mem ?_))
    intro k hk
    exact Subgroup.subset_closure ⟨k, coreCommutator_triangular i j k hj hk, rfl⟩
  intro g hg
  simpa using ht hg

theorem coreTail_le_twoCosetExtension (x : CoreRoot → G) (h : CoreRelations x) (i : CoreRoot) :
    coreTail x i.val ≤ Subgroup.twoCosetExtension (coreTail x (i.val + 1)) (x i)
      (coreTail_square x h i) (coreTail_conj x h i) := by
  apply (Subgroup.closure_le _).mpr
  rintro _ ⟨j, hj, rfl⟩
  by_cases he : j = i
  · subst j
    exact Or.inr ⟨1, (coreTail x (i.val + 1)).one_mem, (mul_one _).symm⟩
  · apply Or.inl
    have hv : j.val ≠ i.val := fun hv => he (Fin.ext hv)
    exact Subgroup.subset_closure ⟨j, by omega, rfl⟩

theorem coreTail_ten (x : CoreRoot → G) : coreTail x 10 = ⊥ := by
  apply le_antisymm _ bot_le
  apply (Subgroup.closure_le _).mpr
  rintro _ ⟨j, hj, _⟩
  have := j.isLt
  omega

/-- Every tail is finite, with at most one binary choice per remaining root. -/
theorem coreTail_finite_card (x : CoreRoot → G) (h : CoreRelations x) (k : ℕ) (hk : k ≤ 10) :
    Finite (coreTail x k) ∧ Nat.card (coreTail x k) ≤ 2 ^ (10 - k) := by
  induction hk using Nat.decreasingInduction with
  | self =>
    rw [coreTail_ten]
    exact ⟨inferInstance, by simp⟩
  | of_succ k hk ih =>
    let i : CoreRoot := ⟨k, hk⟩
    let : Finite (coreTail x (k + 1)) := ih.1
    have he := coreTail_le_twoCosetExtension x h i
    have hf := Subgroup.inclusion_injective he
    let : Finite (coreTail x k) := Finite.of_injective _ hf
    refine ⟨inferInstance, ?_⟩
    have hb := (Nat.card_le_card_of_injective _ hf).trans
      (Subgroup.twoCosetExtension_card (coreTail x (k + 1)) (x i)
        (coreTail_square x h i) (coreTail_conj x h i))
    have hm := Nat.mul_le_mul_left 2 ih.2
    have hn : 10 - k = (10 - (k + 1)) + 1 := by omega
    rw [hn, pow_succ, Nat.mul_comm]
    exact hb.trans hm

/-- The defining relations alone give the required upper bound. -/
theorem presentedCore_finite_card : Finite PresentedCore ∧ Nat.card PresentedCore ≤ 1024 := by
  have ht : coreTail presentedRoot 0 = ⊤ := by
    have he : {g | ∃ i : CoreRoot, 0 ≤ i.val ∧ presentedRoot i = g} = Set.range presentedRoot := by
      ext g
      simp
    rw [coreTail, he, presentedCore_generated]
  have hi := coreTail_finite_card presentedRoot presentedCore_relations 0 (by omega)
  rw [ht] at hi
  let : Finite (⊤ : Subgroup PresentedCore) := hi.1
  exact ⟨Finite.of_equiv _ Subgroup.topEquiv.toEquiv, by simpa using hi.2⟩

instance : Finite PresentedCore := presentedCore_finite_card.1

end ReeTwo
