module

public import Theory.SpecificGroups.ReeTwo.CoreMarkedCenter
public import Theory.SpecificGroups.ReeTwo.InvertingModelFirstCore
public import Theory.GroupTheory.UpperCentralSeriesCentralizerTransport

/-!
# Marked first cores of inverting Ree extensions

The mark is central in every extension generated by the core and one actor:
it commutes with the core and every automorphism of the core fixes it.
Consequently it belongs to the centralizer of the second upper central term,
without requiring a split extension. A marked ambient isomorphism transports
the automorphism fixed-point property of this intrinsic subgroup. The exhaustive
action census and the forty marked model certificates therefore prove that
every automorphism of the first core fixes the mark, for either action orbit
and either fourth power of the actor.

Source: the verified Shinoda (1975), pp.81–83 core coordinates, together with
the functoriality of the upper central series, the cyclic carry construction
in `CyclicFourCentralExtension`, and the kernel-checked certificates in
`InvertingModelFirstCore`.
-/

namespace ReeTwo.InvertingExtension

/-- The intrinsic first core of an extension. -/
@[expose] public def firstCore (H : Type*) [Group H] : Subgroup H :=
  Subgroup.centralizer (Subgroup.upperCentralSeries H 2 : Set H)

/-- The mark is central in any group generated by the core and an actor. -/
public theorem root_nine_mem_center {H : Type*} [Group H]
    (j : Core →* H) (s : H) (beta : MulAut Core)
    (hgen : j.range ⊔ Subgroup.zpowers s = ⊤)
    (hconj : ∀ q, s * j q * s⁻¹ = j (beta q)) :
    j (Core.root 9) ∈ Subgroup.center H := by
  have hc : j.range ⊔ Subgroup.zpowers s ≤
      Subgroup.centralizer ({j (Core.root 9)} : Set H) := by
    apply sup_le
    · rintro _ ⟨q, rfl⟩
      apply Subgroup.mem_centralizer_singleton_iff.mpr
      simpa only [map_mul] using
        congrArg j (Subgroup.mem_center_iff.mp Core.root_nine_mem_center q)
    · apply Subgroup.zpowers_le.mpr
      apply Subgroup.mem_centralizer_singleton_iff.mpr
      have he := hconj (Core.root 9)
      rw [Core.aut_root_nine] at he
      have hm := congrArg (fun x => x * s) he
      simpa only [mul_assoc, inv_mul_cancel, mul_one] using hm
  rw [hgen] at hc
  apply Subgroup.mem_center_iff.mpr
  intro x
  exact Subgroup.mem_centralizer_singleton_iff.mp (hc (Subgroup.mem_top x))

/-- Membership holds for both action orbits and both fourth-power choices. -/
public theorem root_nine_mem_firstCore {H : Type*} [Group H]
    (j : Core →* H) (s : H) (beta : MulAut Core)
    (hgen : j.range ⊔ Subgroup.zpowers s = ⊤)
    (hconj : ∀ q, s * j q * s⁻¹ = j (beta q)) :
    j (Core.root 9) ∈ firstCore H :=
  Subgroup.center_le_centralizer _ (root_nine_mem_center j s beta hgen hconj)

/-- Transfer a fixed mark from any marked model of the whole extension. -/
public theorem root_nine_fixed_of_marked_equiv
    {H M : Type*} [Group H] [Group M]
    (j : Core →* H) (hz : j (Core.root 9) ∈ firstCore H)
    (e : H ≃* M) (z : firstCore M) (he : e (j (Core.root 9)) = z.val)
    (hfixed : ∀ b : MulAut (firstCore M), b z = z)
    (a : MulAut (firstCore H)) : a ⟨j (Core.root 9), hz⟩ = ⟨j (Core.root 9), hz⟩ := by
  let f : firstCore H ≃* firstCore M :=
    Subgroup.centralizerUpperCentralSeriesEquiv e 2
  let x : firstCore H := ⟨j (Core.root 9), hz⟩
  have hx : f x = z := Subtype.ext he
  apply f.injective
  have hf := hfixed (f.symm.trans (a.trans f))
  rw [← hx] at hf
  change f (a (f.symm (f x))) = f x at hf
  simpa only [f.symm_apply_apply] using hf

/-- Every automorphism of the first core fixes the mark in an inverting
extension of order 4096. This includes both action orbits and both fourth-power
choices. Injectivity of the core map and normality of its range follow from
the model identification and need not be assumed separately. -/
public theorem root_nine_fixed {H : Type*} [Group H] [Finite H]
    (hcard : Nat.card H = 4096) (j : Core →* H) (s : H) (beta : MulAut Core)
    (hgen : j.range ⊔ Subgroup.zpowers s = ⊤)
    (hbeta : beta ^ 4 = 1)
    (hc : beta * Core.c * beta⁻¹ = Core.c ^ 2)
    (hinv : beta (Core.root 2) = (Core.root 2)⁻¹)
    (hconj : ∀ q, s * j q * s⁻¹ = j (beta q))
    (hfour : s ^ 4 = 1 ∨ s ^ 4 = j (Core.root 9))
    (hz : j (Core.root 9) ∈ firstCore H)
    (a : MulAut (firstCore H)) :
    a ⟨j (Core.root 9), hz⟩ = ⟨j (Core.root 9), hz⟩ := by
  obtain ⟨ε, hε⟩ : ∃ ε : Bool, s ^ 4 = j (CyclicFourCentralExtension.mark ε) := by
    rcases hfour with h | h
    · exact ⟨false, by simpa [CyclicFourCentralExtension.mark] using h⟩
    · exact ⟨true, by simpa [CyclicFourCentralExtension.mark] using h⟩
  obtain ⟨i, rfl⟩ := Core.InvertingActionCensus.exhaustive beta hbeta hc hinv
  let e : InvertingModel.Model i ε ≃* H :=
    CyclicFourCentralExtension.equiv j s hconj hε hcard hgen
  apply root_nine_fixed_of_marked_equiv j hz e.symm
    (InvertingModel.centralInvolution i ε) ?_
    (InvertingModel.centralInvolution_fixed i ε) a
  apply e.injective
  rw [e.apply_symm_apply]
  exact (CyclicFourCentralExtension.equiv_root_nine j s hconj hε hcard hgen).symm


/-- The marked first-core obstruction, with membership and the fixed-point
conclusion packaged together for an arbitrary inverting extension. -/
public theorem root_nine_firstCore_obstruction {H : Type*} [Group H] [Finite H]
    (hcard : Nat.card H = 4096) (j : Core →* H) (s : H) (beta : MulAut Core)
    (hgen : j.range ⊔ Subgroup.zpowers s = ⊤)
    (hbeta : beta ^ 4 = 1)
    (hc : beta * Core.c * beta⁻¹ = Core.c ^ 2)
    (hinv : beta (Core.root 2) = (Core.root 2)⁻¹)
    (hconj : ∀ q, s * j q * s⁻¹ = j (beta q))
    (hfour : s ^ 4 = 1 ∨ s ^ 4 = j (Core.root 9)) :
    ∃ hz : j (Core.root 9) ∈ firstCore H,
      ∀ a : MulAut (firstCore H),
        a ⟨j (Core.root 9), hz⟩ = ⟨j (Core.root 9), hz⟩ :=
  ⟨root_nine_mem_firstCore j s beta hgen hconj,
    root_nine_fixed hcard j s beta hgen hbeta hc hinv hconj hfour _⟩

end ReeTwo.InvertingExtension
