module

public import ABG.ChapterII.Section1.WreathedDefs
public import Mathlib.GroupTheory.IndexNormal
public import Mathlib.GroupTheory.SpecificGroups.Cyclic
public import Mathlib.Tactic.Group

/-!
# A wreath group of order 32 from its two maximal subgroups

`ABG.isWreathedOfHeight_two_of_normal_c4_square` recognizes the actual
wreathed presentation of height two in a group of order 32. It assumes a
normal subgroup `A` isomorphic to `C₄ × C₄` and an order-sixteen subgroup
`B` with cyclic center which is generated by its square-one elements.
The alternative criterion
`ABG.isWreathedOfHeight_two_of_cyclic_center_of_normal_c4_square`
needs just the normal base and a cyclic center in the ambient group.
No ambient simplicity, fusion, or local-solvability hypothesis is needed.

The second subgroup cannot be contained in `A`, so its involutions supply
an element `z` outside `A`. If `z` fixed every square of `A`, the index-two
coset decomposition would make all these squares central. They also lie
in `B`, contradicting the two distinct nonidentity involutions of `A`
inside the cyclic center of `B`. Thus some `x` has its square moved.
The elements `x` and its conjugate by `z` have distinct nontrivial squares
and form a basis of `C₄ × C₄`. A small kernel-checked coordinate calculation
expresses the two standard basis vectors in terms of them; group arithmetic
then gives every element. In the cyclic-center variant, the same moved-square
argument supplies a swapped basis for the action of an arbitrary element
outside the base. Its square lies on the diagonal; multiplying by a suitable
basis power produces an involution outside the base. Together with `z` the
basis elements satisfy the exact wreath
relations and generate the whole group.

This elementary recognition step supplies the order-32 entry from
Stellmacher (8.6)(a₁,a₂), printed p. 41, to the wreathed presentation in
Alperin–Brauer–Gorenstein, article p. 2. The concrete local-type transport
is separate from this small-group criterion.
-/

namespace ABG

private abbrev Square := Multiplicative (ZMod 4) × Multiplicative (ZMod 4)

set_option maxRecDepth 20000 in
set_option maxHeartbeats 4000000 in
set_option synthInstance.maxSize 1024 in
private theorem square_generators : ∀ x y : Square,
    x ^ 2 ≠ 1 → y ^ 2 ≠ 1 → x ^ 2 ≠ y ^ 2 →
      (∃ i j : Fin 4, x ^ i.val * y ^ j.val = (Multiplicative.ofAdd 1, 1)) ∧
      (∃ i j : Fin 4, x ^ i.val * y ^ j.val = (1, Multiplicative.ofAdd 1)) := by decide

private theorem square_basis (x y a : Square)
    (hx : x ^ 2 ≠ 1) (hy : y ^ 2 ≠ 1) (hxy : x ^ 2 ≠ y ^ 2) :
    ∃ i j : ℕ, x ^ i * y ^ j = a := by
  obtain ⟨⟨i, j, hij⟩, ⟨k, l, hkl⟩⟩ := square_generators x y hx hy hxy
  let u := a.1.toAdd.val
  let v := a.2.toAdd.val
  refine ⟨i.val * u + k.val * v, j.val * u + l.val * v, ?_⟩
  calc
    _ = (x ^ i.val * y ^ j.val) ^ u * (x ^ k.val * y ^ l.val) ^ v := by
      simp only [mul_pow, pow_mul, pow_add]
      ac_rfl
    _ = (Multiplicative.ofAdd 1, 1) ^ u * (1, Multiplicative.ofAdd 1) ^ v := by rw [hij, hkl]
    _ = a := by
      have h : ∀ a : Square, (Multiplicative.ofAdd 1, 1) ^ a.1.toAdd.val *
          (1, Multiplicative.ofAdd 1) ^ a.2.toAdd.val = a := by decide
      exact h a

private theorem square_pow_four : ∀ x : Square, x ^ 4 = 1 := by decide

private theorem cyclic_involutions_eq
    {C : Type*} [Group C] [Finite C] [IsCyclic C]
    (x y : C) (hx : x ^ 2 = 1) (hy : y ^ 2 = 1)
    (hx1 : x ≠ 1) (hy1 : y ≠ 1) : x = y := by
  classical
  let := Fintype.ofFinite C
  by_contra hxy
  have hs : ({1, x, y} : Finset C) ⊆ Finset.univ.filter (fun a : C => a ^ 2 = 1) := by
    intro a ha
    simp only [Finset.mem_insert, Finset.mem_singleton] at ha
    rw [Finset.mem_filter]
    refine ⟨Finset.mem_univ _, ?_⟩
    rcases ha with rfl | rfl | rfl
    · exact one_pow 2
    · exact hx
    · exact hy
  have hcard := Finset.card_le_card hs
  have hbound := IsCyclic.card_pow_eq_one_le (α := C) (n := 2) (by decide)
  have hthree : ({1, x, y} : Finset C).card = 3 := by
    simp [hxy, Ne.symm hx1, Ne.symm hy1]
  omega

private theorem exists_moved_square
    {S : Type*} [Group S] [Finite S]
    (A B : Subgroup S) (eA : A ≃* Square)
    (hAi : A.index = 2) (hBsquares : ∀ x : A, (x : S) ^ 2 ∈ B)
    (hBC : IsCyclic (Subgroup.center B))
    (z : S) (hzA : z ∉ A) :
    ∃ x : A, z * (x : S) ^ 2 ≠ (x : S) ^ 2 * z := by
  classical
  by_contra! hfix
  have hcomm (x y : A) : (x : S) * y = (y : S) * x := by
    have hh : x * y = y * x := eA.injective (by
      simp only [map_mul]
      exact mul_comm _ _)
    exact congrArg Subtype.val hh
  have hc (x : A) (g : S) : g * (x : S) ^ 2 = (x : S) ^ 2 * g := by
    by_cases hg : g ∈ A
    · exact hcomm ⟨g, hg⟩ (x ^ 2)
    have hgz : g * z ∈ A := (A.mul_mem_iff_of_index_two hAi).mpr (by simp [hg, hzA])
    have h₁ : Commute (g * z) ((x : S) ^ 2) := by
      change (g * z) * (x : S) ^ 2 = (x : S) ^ 2 * (g * z)
      exact hcomm ⟨g * z, hgz⟩ (x ^ 2)
    have h₂ : Commute z ((x : S) ^ 2) := hfix x
    have hh := (h₁.mul_left h₂.inv_left).eq
    simpa only [mul_assoc, mul_inv_cancel, mul_one] using hh
  let f : A → Subgroup.center B := fun x =>
    ⟨⟨(x : S) ^ 2, hBsquares x⟩,
      Subgroup.mem_center_iff.mpr fun y => Subtype.ext (hc x y)⟩
  let x : A := eA.symm (Multiplicative.ofAdd 1, 1)
  let y : A := eA.symm (1, Multiplicative.ofAdd 1)
  have hfour (a : A) : a ^ 4 = 1 := eA.injective (by
    rw [map_pow, map_one]
    exact square_pow_four _)
  have hx : (f x) ^ 2 = 1 := by
    apply Subtype.ext
    apply Subtype.ext
    change ((x : S) ^ 2) ^ 2 = 1
    rw [← pow_mul]
    exact congrArg Subtype.val (hfour x)
  have hy : (f y) ^ 2 = 1 := by
    apply Subtype.ext
    apply Subtype.ext
    change ((y : S) ^ 2) ^ 2 = 1
    rw [← pow_mul]
    exact congrArg Subtype.val (hfour y)
  have hx1 : f x ≠ 1 := by
    intro h
    have h' : x ^ 2 = 1 := Subtype.ext (congrArg (fun a : Subgroup.center B => (a.val : S)) h)
    have hh := congrArg eA h'
    change eA (x ^ 2) = eA 1 at hh
    simp only [map_pow, map_one, x, eA.apply_symm_apply] at hh
    exact (by decide : ((Multiplicative.ofAdd 1, 1) : Square) ^ 2 ≠ 1) hh
  have hy1 : f y ≠ 1 := by
    intro h
    have h' : y ^ 2 = 1 := Subtype.ext (congrArg (fun a : Subgroup.center B => (a.val : S)) h)
    have hh := congrArg eA h'
    simp only [map_pow, map_one, y, eA.apply_symm_apply] at hh
    exact (by decide : ((1, Multiplicative.ofAdd 1) : Square) ^ 2 ≠ 1) hh
  let := hBC
  have hxy := cyclic_involutions_eq (f x) (f y) hx hy hx1 hy1
  have h' : x ^ 2 = y ^ 2 :=
    Subtype.ext (congrArg (fun a : Subgroup.center B => (a.val : S)) hxy)
  have hh := congrArg eA h'
  simp only [map_pow, x, y, eA.apply_symm_apply] at hh
  exact (by decide : ((Multiplicative.ofAdd 1, 1) : Square) ^ 2 ≠
    ((1, Multiplicative.ofAdd 1) : Square) ^ 2) hh

/-- A moved square and an involution outside a normal `C₄ × C₄` base
supply the generators and relations of the order-32 wreath group. -/
private theorem isWreathedOfHeight_two_of_moved_square
    {S : Type*} [Group S] [Finite S] (hS : Nat.card S = 32)
    (A : Subgroup S) (hAN : A.Normal)
    (eA : A ≃* (Multiplicative (ZMod 4) × Multiplicative (ZMod 4)))
    (z : S) (hzA : z ∉ A) (hz2 : z ^ 2 = 1)
    (x : A) (hmove : z * (x : S) ^ 2 ≠ (x : S) ^ 2 * z) :
    IsWreathedOfHeight S 2 := by
  classical
  let := hAN
  let : IsMulCommutative A := IsMulCommutative.of_comm fun x y => eA.injective (by
    simp only [map_mul]
    exact mul_comm _ _)
  have hfour (a : A) : a ^ 4 = 1 := eA.injective (by
    rw [map_pow, map_one]
    exact square_pow_four _)
  have hAi : A.index = 2 := by
    have hcardA : Nat.card A = 16 := by
      rw [Nat.card_congr eA.toEquiv, Nat.card_prod]
      norm_num
    have h := A.card_mul_index
    rw [hcardA, hS] at h
    omega
  have hzz : z * z = 1 := by simpa only [pow_two] using hz2
  have hzinv : z⁻¹ = z := inv_eq_of_mul_eq_one_left hzz
  let α : MulAut A := A.normalizerMonoidHom ⟨z, by rw [A.normalizer_eq_top]; trivial⟩
  let y := α x
  have hx2 : x ^ 2 ≠ 1 := by
    intro h
    apply hmove
    have hh : (x : S) ^ 2 = 1 := congrArg Subtype.val h
    rw [hh, mul_one, one_mul]
  have hy2 : y ^ 2 ≠ 1 := by
    intro h
    apply hx2
    apply α.injective
    exact (map_pow α x 2).trans (h.trans α.map_one.symm)
  have hxy2 : x ^ 2 ≠ y ^ 2 := by
    intro h
    apply hmove
    have hh : α (x ^ 2) = x ^ 2 := (map_pow α x 2).trans h.symm
    have hh' : z * (x : S) ^ 2 * z⁻¹ = (x : S) ^ 2 := congrArg Subtype.val hh
    exact mul_inv_eq_iff_eq_mul.mp hh'
  have hbasis (a : A) : ∃ i j : ℕ, x ^ i * y ^ j = a := by
    obtain ⟨i, j, hij⟩ := square_basis (eA x) (eA y) (eA a)
      (by simpa only [← map_pow, ← map_one eA, eA.injective.ne_iff] using hx2)
      (by simpa only [← map_pow, ← map_one eA, eA.injective.ne_iff] using hy2)
      (by simpa only [← map_pow, eA.injective.ne_iff] using hxy2)
    exact ⟨i, j, eA.injective (by simpa only [map_mul, map_pow] using hij)⟩
  have hyval : (y : S) = z * (x : S) * z := by
    change z * (x : S) * z⁻¹ = _
    rw [hzinv]
  refine ⟨by decide, hS, (x : S), (y : S), z,
    congrArg Subtype.val (hfour x), congrArg Subtype.val (hfour y), hz2, ?_, ?_, ?_, ?_⟩
  · rw [hzinv]
    exact hyval.symm
  · rw [hzinv, hyval]
    calc
      z * (z * (x : S) * z) * z = (z * z) * (x : S) * (z * z) := by group
      _ = x := by rw [hzz, one_mul, mul_one]
  · exact congrArg Subtype.val (IsMulCommutative.is_comm.comm x y)
  · let U := Subgroup.closure ({(x : S), (y : S), z} : Set S)
    have hxU : (x : S) ∈ U := Subgroup.subset_closure (by simp)
    have hyU : (y : S) ∈ U := Subgroup.subset_closure (by simp)
    have hzU : z ∈ U := Subgroup.subset_closure (by simp)
    have hAU : A ≤ U := by
      intro a ha
      obtain ⟨i, j, hij⟩ := hbasis ⟨a, ha⟩
      have hh : (x : S) ^ i * (y : S) ^ j = a := congrArg Subtype.val hij
      rw [← hh]
      exact U.mul_mem (U.pow_mem hxU _) (U.pow_mem hyU _)
    apply top_unique
    intro g _
    by_cases hg : g ∈ A
    · exact hAU hg
    have hgz : g * z ∈ A := (A.mul_mem_iff_of_index_two hAi).mpr (by simp [hg, hzA])
    have hh := U.mul_mem (hAU hgz) hzU
    simpa only [mul_assoc, hzz, mul_one] using hh

/-- The specified normal abelian base and cyclic-center maximal subgroup
force the wreathed presentation of order 32. -/
public theorem isWreathedOfHeight_two_of_normal_c4_square
    {S : Type*} [Group S] [Finite S] (hS : Nat.card S = 32)
    (A B : Subgroup S) (hAN : A.Normal)
    (hA : Nonempty (A ≃* (Multiplicative (ZMod 4) × Multiplicative (ZMod 4))))
    (hB : Nat.card B = 16) (hBC : IsCyclic (Subgroup.center B))
    (hBI : Subgroup.closure {x : S | x ∈ B ∧ x ^ 2 = 1} = B) :
    IsWreathedOfHeight S 2 := by
  classical
  let := hAN
  obtain ⟨eA⟩ := hA
  have hcardA : Nat.card A = 16 := by
    rw [Nat.card_congr eA.toEquiv, Nat.card_prod]
    norm_num
  have hfour (x : A) : x ^ 4 = 1 := eA.injective (by
    rw [map_pow, map_one]
    exact square_pow_four _)
  let : IsMulCommutative A := IsMulCommutative.of_comm fun x y => eA.injective (by
    simp only [map_mul]
    exact mul_comm _ _)
  have hAi : A.index = 2 := by
    have h := A.card_mul_index
    rw [hcardA, hS] at h
    omega
  have hBi : B.index = 2 := by
    have h := B.card_mul_index
    rw [hB, hS] at h
    omega
  have hncyc : ¬ IsCyclic A := by
    intro hcyc
    let := hcyc
    have hd := Monoid.exponent_dvd_iff_forall_pow_eq_one.mpr hfour
    rw [IsCyclic.exponent_eq_card, hcardA] at hd
    norm_num at hd
  have hBA : ¬ B ≤ A := by
    intro hle
    have hEq : B = A := Subgroup.eq_of_le_of_card_ge hle (by rw [hcardA, hB])
    rw [hEq, Subgroup.center_eq_top] at hBC
    exact hncyc ((Subgroup.topEquiv : (⊤ : Subgroup A) ≃* A).isCyclic.mp hBC)
  obtain ⟨z, hzB, hz2, hzA⟩ : ∃ z : S, z ∈ B ∧ z ^ 2 = 1 ∧ z ∉ A := by
    by_contra! h
    apply hBA
    rw [← hBI]
    exact (Subgroup.closure_le _).mpr (fun x hx => h x hx.1 hx.2)
  obtain ⟨x, hmove⟩ := exists_moved_square A B eA hAi
    (fun x => B.sq_mem_of_index_two hBi x) hBC z hzA
  exact isWreathedOfHeight_two_of_moved_square hS A hAN eA z hzA hz2 x hmove

/-- A cyclic center makes any involution outside the normal `C₄ × C₄`
base move a square, and hence gives the wreath presentation. -/
private theorem isWreathedOfHeight_two_of_cyclic_center_of_involution_outside
    {S : Type*} [Group S] [Finite S] (hS : Nat.card S = 32)
    (hC : IsCyclic (Subgroup.center S))
    (A : Subgroup S) (hAN : A.Normal)
    (hA : Nonempty (A ≃* (Multiplicative (ZMod 4) × Multiplicative (ZMod 4))))
    (z : S) (hzA : z ∉ A) (hz2 : z ^ 2 = 1) :
    IsWreathedOfHeight S 2 := by
  obtain ⟨eA⟩ := hA
  have hcardA : Nat.card A = 16 := by
    rw [Nat.card_congr eA.toEquiv, Nat.card_prod]
    norm_num
  have hAi : A.index = 2 := by
    have h := A.card_mul_index
    rw [hcardA, hS] at h
    omega
  have hBC : IsCyclic (Subgroup.center (⊤ : Subgroup S)) :=
    (Subgroup.centerCongr (Subgroup.topEquiv : (⊤ : Subgroup S) ≃* S)).isCyclic.mpr hC
  obtain ⟨x, hmove⟩ := exists_moved_square A ⊤ eA hAi (fun _ => Subgroup.mem_top _) hBC
    z hzA
  exact isWreathedOfHeight_two_of_moved_square hS A hAN eA z hzA hz2 x hmove

set_option maxRecDepth 20000 in
set_option maxHeartbeats 4000000 in
private theorem square_unique_coordinates : ∀ x y : Square,
    x ^ 2 ≠ 1 → y ^ 2 ≠ 1 → x ^ 2 ≠ y ^ 2 →
      ∀ i j : Fin 4, x ^ i.val * y ^ j.val = x ^ j.val * y ^ i.val → i = j := by decide

/-- Cyclic center forces an index-two `C₄ × C₄` extension of order 32 to split
with the swapping action, hence to be wreathed. -/
public theorem isWreathedOfHeight_two_of_cyclic_center_of_normal_c4_square
    {S : Type*} [Group S] [Finite S] (hS : Nat.card S = 32)
    (hC : IsCyclic (Subgroup.center S))
    (A : Subgroup S) (hAN : A.Normal)
    (hA : Nonempty (A ≃* (Multiplicative (ZMod 4) × Multiplicative (ZMod 4)))) :
    IsWreathedOfHeight S 2 := by
  classical
  let := hAN
  obtain ⟨eA⟩ := hA
  let : IsMulCommutative A := IsMulCommutative.of_comm fun x y => eA.injective (by
    simp only [map_mul]
    exact mul_comm _ _)
  have hfour (a : A) : a ^ 4 = 1 := eA.injective (by
    rw [map_pow, map_one]
    exact square_pow_four _)
  have hcardA : Nat.card A = 16 := by
    rw [Nat.card_congr eA.toEquiv, Nat.card_prod]
    norm_num
  have hAi : A.index = 2 := by
    have h := A.card_mul_index
    rw [hcardA, hS] at h
    omega
  have hAtop : A ≠ ⊤ := by
    intro h
    simp [h] at hAi
  obtain ⟨g, _, hg⟩ := SetLike.exists_of_lt (lt_top_iff_ne_top.mpr hAtop)
  have hBC : IsCyclic (Subgroup.center (⊤ : Subgroup S)) :=
    (Subgroup.centerCongr (Subgroup.topEquiv : (⊤ : Subgroup S) ≃* S)).isCyclic.mpr hC
  obtain ⟨x, hmove⟩ := exists_moved_square A ⊤ eA hAi (fun _ => Subgroup.mem_top _) hBC g hg
  let α : MulAut A := A.normalizerMonoidHom ⟨g, by rw [A.normalizer_eq_top]; trivial⟩
  let y := α x
  have hx2 : x ^ 2 ≠ 1 := by
    intro h
    apply hmove
    have hh : (x : S) ^ 2 = 1 := congrArg Subtype.val h
    rw [hh, mul_one, one_mul]
  have hy2 : y ^ 2 ≠ 1 := by
    intro h
    apply hx2
    apply α.injective
    exact (map_pow α x 2).trans (h.trans α.map_one.symm)
  have hxy2 : x ^ 2 ≠ y ^ 2 := by
    intro h
    apply hmove
    have hh : α (x ^ 2) = x ^ 2 := (map_pow α x 2).trans h.symm
    have hh' : g * (x : S) ^ 2 * g⁻¹ = (x : S) ^ 2 := congrArg Subtype.val hh
    exact mul_inv_eq_iff_eq_mul.mp hh'
  let c : A := ⟨g ^ 2, A.sq_mem_of_index_two hAi g⟩
  have hαc : α c = c := by
    apply Subtype.ext
    change g * g ^ 2 * g⁻¹ = g ^ 2
    group
  have hαy : α y = x := by
    apply Subtype.ext
    change g * (g * (x : S) * g⁻¹) * g⁻¹ = (x : S)
    have hccomm : (g ^ 2) * (x : S) = (x : S) * g ^ 2 :=
      congrArg Subtype.val (IsMulCommutative.is_comm.comm c x)
    calc
      _ = g ^ 2 * (x : S) * (g ^ 2)⁻¹ := by simp only [pow_two]; group
      _ = x := by rw [hccomm, mul_assoc, mul_inv_cancel, mul_one]
  obtain ⟨i, j, hij⟩ := square_basis (eA x) (eA y) (eA c)
    (by simpa only [← map_pow, ← map_one eA, eA.injective.ne_iff] using hx2)
    (by simpa only [← map_pow, ← map_one eA, eA.injective.ne_iff] using hy2)
    (by simpa only [← map_pow, eA.injective.ne_iff] using hxy2)
  have hijA : x ^ i * y ^ j = c := eA.injective (by simpa only [map_mul, map_pow] using hij)
  have hjiA : x ^ j * y ^ i = c := by
    have hh := congrArg α hijA
    simpa only [map_mul, map_pow, show α x = y from rfl, hαy, hαc,
      IsMulCommutative.is_comm.comm (y ^ i) (x ^ j)] using hh
  have hmod (a : A) (n : ℕ) : a ^ n = a ^ (n % 4) := by
    conv_lhs => rw [← Nat.mod_add_div n 4, pow_add, pow_mul, hfour, one_pow, mul_one]
  have hequal : (⟨i % 4, Nat.mod_lt _ (by decide)⟩ : Fin 4) =
      ⟨j % 4, Nat.mod_lt _ (by decide)⟩ := by
    apply square_unique_coordinates (eA x) (eA y)
      (by simpa only [← map_pow, ← map_one eA, eA.injective.ne_iff] using hx2)
      (by simpa only [← map_pow, ← map_one eA, eA.injective.ne_iff] using hy2)
      (by simpa only [← map_pow, eA.injective.ne_iff] using hxy2)
    have hh := congrArg eA (hijA.trans hjiA.symm)
    rw [hmod x i, hmod y j, hmod x j, hmod y i] at hh
    simpa only [map_mul, map_pow] using hh
  have heq : i % 4 = j % 4 := congrArg Fin.val hequal
  have hc : c = x ^ i * y ^ i := by
    rw [← hijA, hmod y j, ← heq, ← hmod y i]
  let u : S := (x : S) ^ i
  let v : S := (y : S) ^ i
  have hgsq : g ^ 2 = u * v := congrArg Subtype.val hc
  have hgu : g * u * g⁻¹ = v := by
    exact congrArg Subtype.val (map_pow α x i)
  have hguinv : g * u⁻¹ = v⁻¹ * g := by
    have h := congrArg Inv.inv hgu
    simp only [mul_inv_rev, inv_inv] at h
    calc
      g * u⁻¹ = (g * u⁻¹ * g⁻¹) * g := by group
      _ = v⁻¹ * g := by rw [mul_assoc g, h]
  have huv : Commute u v :=
    congrArg Subtype.val (IsMulCommutative.is_comm.comm (x ^ i) (y ^ i))
  have hzsq : (u⁻¹ * g) ^ 2 = 1 := by
    calc
      _ = u⁻¹ * (g * u⁻¹) * g := by simp only [pow_two]; group
      _ = u⁻¹ * (v⁻¹ * g) * g := by rw [hguinv]
      _ = u⁻¹ * v⁻¹ * (g ^ 2) := by simp only [pow_two]; group
      _ = 1 := by rw [hgsq, huv.inv_inv.eq]; group
  have hzA : u⁻¹ * g ∉ A := by
    intro h
    apply hg
    have huA : u ∈ A := A.pow_mem x.property i
    simpa only [mul_inv_cancel_left] using A.mul_mem huA h
  exact isWreathedOfHeight_two_of_cyclic_center_of_involution_outside hS hC A hAN
    ⟨eA⟩ (u⁻¹ * g) hzA hzsq

end ABG
