module

public import ABG.ChapterII.Section1.NormalForm
public import Theory.Frattini.PGroup

/-!
# The derived and Frattini subgroups of a quasi-dihedral group

In the quasi-dihedral presentation of order 2^n, n ≥ 4, both the derived
subgroup and the Frattini subgroup are generated by a². This subgroup is
cyclic of order 2^(n-2). This is Chapter II, §1, Lemma 1(iv), article page 9
of `refs/latex/alperin-brauer-gorenstein.tex`; its exponent parameter is one
smaller than the existing Stellmacher presentation parameter used here.

The proof first shows that the subgroup generated by a² is normal, using the
two normal forms. Its quotient has order four and is therefore commutative,
which bounds the derived subgroup above. The generator commutator is an odd
power of a², so it generates the same cyclic 2-group and gives the reverse
containment. Every square also belongs to this subgroup: the commutative
quotient is generated by two involutions. The finite p-group formula expressing
the Frattini subgroup through commutators and pth powers then identifies it.
These explicit-generator equalities support the classification of maximal
subgroups and the subsequent fusion analysis.
-/

open scoped commutatorElement IsMulCommutative
namespace ABG.QuasiDihedral
variable {G : Type*} [Group G]

private theorem square_zpowers_normal (a b : G) (m k : ℕ)
    (hm : 0 < m) (ha : orderOf a = m) (hb : b ^ 2 = 1)
    (hab : b * a * b⁻¹ = a ^ k)
    (hgen : Subgroup.closure ({a, b} : Set G) = ⊤) :
    (Subgroup.zpowers (a ^ 2)).Normal := by
  let K := Subgroup.zpowers (a ^ 2)
  have hc (g : G) : g * a ^ 2 * g⁻¹ ∈ K := by
    obtain ⟨i, _, rfl | rfl⟩ := normal_form a b m k hm ha hb hab hgen g
    · have heq : a ^ i * a ^ 2 * (a ^ i)⁻¹ = a ^ 2 := by group
      rw [heq]
      exact Subgroup.mem_zpowers _
    · have hconj : b * a ^ 2 * b⁻¹ = (a ^ 2) ^ k := by
        have h := congrArg (fun y : G => y ^ 2) hab
        rw [← MulAut.conj_apply, ← map_pow, MulAut.conj_apply] at h
        simpa only [pow_right_comm] using h
      have heq : (a ^ i * b) * a ^ 2 * (a ^ i * b)⁻¹ = (a ^ 2) ^ k := by
        calc
          _ = a ^ i * (b * a ^ 2 * b⁻¹) * (a ^ i)⁻¹ := by group
          _ = a ^ i * (a ^ 2) ^ k * (a ^ i)⁻¹ := by rw [hconj]
          _ = (a ^ 2) ^ k := by group
      rw [heq]
      exact K.pow_mem (Subgroup.mem_zpowers _) k
  constructor
  intro x hx g
  obtain ⟨j, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx
  have h := K.zpow_mem (hc g) j
  simpa only [← MulAut.conj_apply, ← map_zpow] using h

private theorem square_generator_order {n : ℕ} (hn : 4 ≤ n) (a : G)
    (ha : orderOf a = 2 ^ (n - 1)) : orderOf (a ^ 2) = 2 ^ (n - 2) := by
  rw [orderOf_pow_of_dvd (by decide) (by rw [ha]; exact dvd_pow_self 2 (by omega)), ha]
  have hn' : n - 1 = (n - 2) + 1 := by omega
  rw [hn', pow_succ, Nat.mul_div_cancel _ (by decide)]

private theorem square_generator_mem_commutator {n : ℕ} (hn : 4 ≤ n) (a b : G)
    (ha : orderOf a = 2 ^ (n - 1))
    (hab : b * a * b⁻¹ = a ^ (2 ^ (n - 2) - 1)) :
    a ^ 2 ∈ commutator G := by
  let t := 2 ^ (n - 3) - 1
  have ht : 2 ^ (n - 2) - 1 = 2 * t + 1 := by
    have he : n - 2 = (n - 3) + 1 := by omega
    have hp : 0 < 2 ^ (n - 3) := by positivity
    dsimp [t]
    rw [he, pow_succ]
    omega
  have hc : (a ^ 2) ^ t ∈ commutator G := by
    have hmem : ⁅b, a⁆ ∈ commutator G :=
      Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)
    have he : ⁅b, a⁆ = (a ^ 2) ^ t := by
      rw [commutatorElement_def, hab, ht, pow_succ, mul_assoc,
        mul_inv_cancel, mul_one, pow_mul]
    rwa [he] at hmem
  have htodd : Odd t := by
    rw [Nat.odd_iff]
    dsimp [t]
    have he : n - 3 = (n - 4) + 1 := by omega
    rw [he, pow_succ]
    have hp : 0 < 2 ^ (n - 4) := by positivity
    omega
  have hcop : t.Coprime (orderOf (a ^ 2)) := by
    rw [square_generator_order hn a ha]
    exact htodd.coprime_two_right.pow_right _
  exact (Subgroup.zpowers_le.mpr hc) (mem_zpowers_pow_iff.mpr hcop.gcd_eq_one)

/-- The derived and Frattini subgroups coincide with the cyclic subgroup generated by a². -/
public theorem derived_eq_frattini {n : ℕ} (hn : 4 ≤ n)
    (hcard : Nat.card G = 2 ^ n) (a b : G)
    (ha : orderOf a = 2 ^ (n - 1)) (hb : orderOf b = 2)
    (hab : b * a * b⁻¹ = a ^ (2 ^ (n - 2) - 1))
    (hgen : Subgroup.closure ({a, b} : Set G) = ⊤) :
    commutator G = frattini G ∧
      frattini G = Subgroup.zpowers (a ^ 2) ∧
      IsCyclic (commutator G) ∧ Nat.card (commutator G) = 2 ^ (n - 2) := by
  let : Finite G := Nat.finite_of_card_ne_zero (hcard ▸ by positivity)
  let : Fact (IsPGroup 2 G) := ⟨IsPGroup.of_card hcard⟩
  let K := Subgroup.zpowers (a ^ 2)
  have hb2 : b ^ 2 = 1 := by rw [← hb]; exact pow_orderOf_eq_one b
  let : K.Normal := square_zpowers_normal a b _ _ (by positivity) ha hb2 hab hgen
  have hKcard : Nat.card K = 2 ^ (n - 2) := by
    rw [Nat.card_zpowers, square_generator_order hn a ha]
  have hQcard : Nat.card (G ⧸ K) = 2 ^ 2 := by
    have hmul := K.card_mul_index
    rw [hKcard, hcard] at hmul
    have he : 2 ^ n = 2 ^ (n - 2) * 2 ^ 2 := by
      rw [← pow_add, Nat.sub_add_cancel (by omega)]
    rw [he] at hmul
    exact Nat.eq_of_mul_eq_mul_left (by positivity) hmul
  let : IsMulCommutative (G ⧸ K) := IsPGroup.isMulCommutative_of_card_eq_prime_sq hQcard
  have hcomm : commutator G = K := by
    apply le_antisymm
    · exact (Subgroup.Normal.quotient_commutative_iff_commutator_le (N := K)).mp inferInstance
    · exact Subgroup.zpowers_le.mpr (square_generator_mem_commutator hn a b ha hab)
  have haQ : (QuotientGroup.mk' K a) ^ 2 = 1 := by
    rw [← map_pow]
    exact (QuotientGroup.eq_one_iff (N := K) (x := a ^ 2)).mpr (Subgroup.mem_zpowers _)
  have hbQ : (QuotientGroup.mk' K b) ^ 2 = 1 := by rw [← map_pow, hb2, map_one]
  have hsquare (x : G) : x ^ 2 ∈ K := by
    apply (QuotientGroup.eq_one_iff (N := K) (x := x ^ 2)).mp
    change (QuotientGroup.mk' K) (x ^ 2) = 1
    rw [map_pow]
    obtain ⟨i, _, rfl | rfl⟩ := normal_form a b _ _ (by positivity) ha hb2 hab hgen x
    · rw [map_pow, pow_right_comm, haQ, one_pow]
    · rw [map_mul, map_pow, mul_pow, pow_right_comm, haQ, one_pow, hbQ, one_mul]
  have hphi : frattini G = K := by
    apply le_antisymm
    · rw [frattini_eq_closure_commutator_union_powers (p := 2)]
      apply K.closure_le.mpr
      rintro x (hx | ⟨y, rfl⟩)
      · exact hcomm ▸ hx
      · exact hsquare y
    · exact Subgroup.zpowers_le.mpr (pth_power_mem_frattini_of_isPGroup (p := 2) a)
  refine ⟨hcomm.trans hphi.symm, hphi, ?_, hcomm ▸ hKcard⟩
  rw [hcomm]
  infer_instance

end ABG.QuasiDihedral
