module
public import ABG.ChapterII.Section1.FourRepresentative
public import ABG.ChapterII.Section1.PresentationCalculus

/-!
# The conjugacy class of quasi-dihedral four subgroups

Every Klein four subgroup in a semidihedral group is conjugate to the
subgroup generated by the central half-order power of the cyclic generator
and the involutory generator `b`. This representative is self-centralizing,
and its normalizer has twice its order.

A Klein four subgroup cannot lie in the cyclic subgroup, so it contains an
outer involution. The square calculation forces that involution's exponent
to be even; the explicit conjugation calculation sends it to `b`. Since a
Klein four group is commutative, the conjugated subgroup lies in `C(b)`.
The canonical centralizer calculation and equality of orders give equality.
The representative's local structure is imported from `FourRepresentative`.

This proves the four-subgroup branch of ABG Chapter II, §1, Lemma 1(ii),
article page 9 of `refs/latex/alperin-brauer-gorenstein.tex`. The assembly
module transfers the representative properties to every conjugate and
combines this result with the quaternion-subgroup branch.
-/

namespace ABG.QuasiDihedral
variable {G : Type*} [Group G]

private theorem exists_outer_involution (a : G) (T : Subgroup G) (hT : IsKleinFour T) :
    ∃ x : G, x ∈ T ∧ x ∉ Subgroup.zpowers a ∧ orderOf x = 2 := by
  let := hT
  have hnot : ¬ T ≤ Subgroup.zpowers a := by
    intro hle
    exact IsKleinFour.not_isCyclic (Subgroup.isCyclic_of_le hle)
  obtain ⟨x, hx, hxa⟩ := Set.not_subset.mp hnot
  refine ⟨x, hx, hxa, orderOf_eq_prime ?_ ?_⟩
  · have h := congrArg (fun y : T => (y : G)) (IsKleinFour.mul_self (⟨x, hx⟩ : T))
    simpa [pow_two] using h
  · intro he
    exact hxa (he ▸ (Subgroup.zpowers a).one_mem)

private theorem outer_involution_conj_b {n : ℕ} (hn : 4 ≤ n) (a b : G)
    (ha : orderOf a = 2 ^ (n - 1)) (hb : orderOf b = 2)
    (hconj : b * a * b⁻¹ = a ^ (2 ^ (n - 2) - 1))
    (hgen : Subgroup.closure ({a,b} : Set G) = ⊤)
    {x : G} (hx : x ∉ Subgroup.zpowers a) (hxo : orderOf x = 2) : IsConj x b := by
  obtain ⟨i, _, rfl | rfl⟩ := normal_form a b _ _ (by positivity) ha
    (by rw [← hb]; exact pow_orderOf_eq_one b) hconj hgen x
  · exact (hx (Subgroup.pow_mem _ (Subgroup.mem_zpowers _) _)).elim
  · have hd : 2 ^ (n - 1) ∣ 2 ^ (n - 2) * i := by
      rw [← ha, orderOf_dvd_iff_pow_eq_one, ← outer_square hn a b hb hconj i, ← hxo]
      exact pow_orderOf_eq_one _
    have hm : 2 ^ (n - 1) = 2 ^ (n - 2) * 2 := by
      rw [show n - 1 = (n - 2) + 1 by omega, pow_succ]
    rw [hm] at hd
    have heven : 2 ∣ i := (Nat.mul_dvd_mul_iff_left (by positivity)).mp hd
    obtain ⟨t, rfl⟩ := heven
    simpa using (outer_even_shift_isConj hn a b ha hconj 0 t).symm

private theorem conjugate_four_of_centralizer (b : G) (U T : Subgroup G)
    (hU : IsKleinFour U) (hT : IsKleinFour T)
    (hcent : Subgroup.centralizer ({b} : Set G) ≤ U)
    {x : G} (hx : x ∈ T) (hxb : IsConj x b) :
    ∃ g : G, U.map (MulAut.conj g).toMonoidHom = T := by
  let := hT
  let : IsMulCommutative T := IsKleinFour.isMulCommutative
  let : Finite U := Nat.finite_of_card_ne_zero (by rw [hU.card_four]; decide)
  obtain ⟨g, hg⟩ := isConj_iff.mp hxb
  let e := MulAut.conj g
  have he : e x = b := hg
  have hmap : T.map e.toMonoidHom = U := by
    apply Subgroup.eq_of_le_of_card_ge
    · rintro y ⟨t, ht, rfl⟩
      apply hcent
      rw [Subgroup.mem_centralizer_singleton_iff, ← he]
      change e t * e x = e x * e t
      rw [← map_mul, ← map_mul]
      apply congrArg e
      exact congrArg (fun t : T => (t : G)) (IsMulCommutative.is_comm.comm (⟨t, ht⟩ : T) (⟨x, hx⟩ : T))
    · rw [Subgroup.card_map_of_injective e.injective, hU.card_four, hT.card_four]
  refine ⟨g⁻¹, ?_⟩
  rw [← hmap, Subgroup.map_map]
  convert Subgroup.map_id T using 1
  ext t
  simp [e, MulAut.conj_apply, mul_assoc]

/-- Every four subgroup is conjugate to the canonical self-centralizing one,
whose normalizer has relative index two (ABG II.1.1(ii), four subgroup branch). -/
public theorem four_subgroups (hG : Stellmacher.IsSemidihedralGroup G) :
    ∃ U : Subgroup G, IsKleinFour U ∧
      (∀ T : Subgroup G, IsKleinFour T →
        ∃ g : G, U.map (MulAut.conj g).toMonoidHom = T) ∧
      Subgroup.centralizer (U : Set G) ≤ U ∧
      U.relIndex (Subgroup.normalizer (U : Set G)) = 2 := by
  obtain ⟨n, hn, hcard, a, b, ha, hb, hconj, hgen⟩ := hG
  obtain ⟨hU, hUC, hUN⟩ := four_representative_local hn hcard a b ha hb hconj hgen
  refine ⟨Subgroup.closure ({a^(2^(n-2)),b} : Set G), hU, ?_, hUC, hUN⟩
  intro T hT
  obtain ⟨x,hx,hxa,hxo⟩ := exists_outer_involution a T hT
  exact conjugate_four_of_centralizer b _ T hU hT
    (centralizer_b_le_four hn a b ha hb hconj hgen) hx
    (outer_involution_conj_b hn a b ha hb hconj hgen hxa hxo)
end ABG.QuasiDihedral
