module
public import ABG.ChapterII.Section1.WreathedMaximalQuaternion
public import Mathlib.GroupTheory.Commutator.Basic

/-!
# The derived subgroup of a wreathed group

ABG Chapter II §1 Lemma 2(vi), article p.10, identifies the derived subgroup
of the chosen wreathed presentation with the cyclic subgroup generated by
`r = s*t⁻¹`, of order `2^n`.

Conjugation by the generators fixes or inverts `r`, so its cyclic subgroup
is normal. In the quotient, the images of `s` and `t` agree, and the image
of `z` commutes with them. Normal forms then show that the quotient is
abelian, giving one containment. The commutator `[s,z]` equals `r`, giving
the other. Cyclicity and cardinality follow from the previously proved exact
order of `r`, whose proof uses the full cardinality hypothesis of the
presentation through uniqueness of coordinates.
-/

namespace ABG.Wreathed.Presentation
variable {S : Type*} [Group S] {n : ℕ} (P : Presentation S n)
open scoped commutatorElement

private theorem cyclic_difference_normal : (Subgroup.zpowers P.r).Normal := by
  apply Subgroup.normalizer_eq_top_iff.mp
  apply top_unique
  rw [← P.generate]
  apply (Subgroup.closure_le _).mpr
  intro g hg
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
  change g ∈ Subgroup.normalizer (Subgroup.zpowers P.r : Set S)
  rw [Subgroup.mem_normalizer_iff_map_conj_eq, MonoidHom.map_zpowers]
  have hc : Commute P.s P.t := P.commute
  have hs : Commute P.s P.r := (Commute.refl _).mul_right hc.inv_right
  have ht : Commute P.t P.r := hc.symm.mul_right (Commute.refl _).inv_right
  change Subgroup.zpowers (g * P.r * g⁻¹) = Subgroup.zpowers P.r
  rcases hg with rfl | rfl | rfl
  · rw [hs.eq, mul_inv_cancel_right]
  · rw [ht.eq, mul_inv_cancel_right]
  · rw [P.z_conj_r, Subgroup.zpowers_inv]

private theorem commutator_le_cyclic_difference :
    _root_.commutator S ≤ Subgroup.zpowers P.r := by
  let := P.cyclic_difference_normal
  apply Subgroup.Normal.quotient_commutative_iff_commutator_le.mp
  let f := QuotientGroup.mk' (Subgroup.zpowers P.r)
  have hr : f P.r = 1 := (QuotientGroup.eq_one_iff _).mpr (Subgroup.mem_zpowers _)
  have hst : f P.s = f P.t := by
    apply mul_inv_eq_one.mp
    calc
      f P.s * (f P.t)⁻¹ = f (P.s * P.t⁻¹) := by rw [f.map_mul, f.map_inv]
      _ = 1 := hr
  have hsz : Commute (f P.s) (f P.z) := by
    have h := congrArg f P.z_mul_s
    simp only [map_mul, ← hst] at h
    exact h.symm
  have hall (g : S) : Commute (f P.s) (f g) ∧ Commute (f P.z) (f g) := by
    rcases P.exists_normal_form g with ⟨i,j,b,rfl⟩
    simp only [map_mul, map_pow, ← hst]
    exact ⟨(((Commute.refl _).pow_right _).mul_right ((Commute.refl _).pow_right _)).mul_right
      (hsz.pow_right _), ((hsz.symm.pow_right _).mul_right (hsz.symm.pow_right _)).mul_right
      ((Commute.refl _).pow_right _)⟩
  refine ⟨⟨?_⟩⟩
  intro a b
  obtain ⟨g,rfl⟩ := QuotientGroup.mk'_surjective (Subgroup.zpowers P.r) a
  obtain ⟨h,rfl⟩ := QuotientGroup.mk'_surjective (Subgroup.zpowers P.r) b
  rcases P.exists_normal_form g with ⟨i,j,k,rfl⟩
  change Commute (f _) (f h)
  simp only [map_mul, map_pow, ← hst]
  exact (((hall h).1.pow_left _).mul_left ((hall h).1.pow_left _)).mul_left
    ((hall h).2.pow_left _)

public theorem derived_structure :
    _root_.commutator S = Subgroup.zpowers P.r ∧
      IsCyclic (_root_.commutator S) ∧ Nat.card (_root_.commutator S) = 2 ^ n := by
  have he : _root_.commutator S = Subgroup.zpowers P.r := by
    apply le_antisymm P.commutator_le_cyclic_difference
    apply (Subgroup.zpowers_le).mpr
    have hr : ⁅P.s, P.z⁆ = P.r := by
      rw [commutatorElement_def]
      have hz : P.z * P.s⁻¹ * P.z⁻¹ = P.t⁻¹ := by
        have h := congrArg Inv.inv P.conj_s
        simpa only [mul_inv_rev, inv_inv, P.z_inv, mul_assoc] using h
      calc
        P.s * P.z * P.s⁻¹ * P.z⁻¹ = P.s * (P.z * P.s⁻¹ * P.z⁻¹) := by group
        _ = P.r := by rw [hz]; rfl
    rw [← hr]
    exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)
  refine ⟨he, ?_, ?_⟩
  · rw [he]
    infer_instance
  · rw [he, Nat.card_zpowers, P.r_order]

end ABG.Wreathed.Presentation
