import Stellmacher.SectionOne.Defs
#check Subgroup.Normalizes
#check Subgroup.Normalizes.le_normalizer
#check Subgroup.le_normalizer_of_normal
#check Subgroup.conjMulDistribMulActionOfLeNormalizer
#check Subgroup.conjMulDistribMulActionOfLeNormalizer_smul_coe
#check Subgroup.normalizer
#check Subgroup.normal_subgroupOf_iff_le_normalizer
#check pPrimeCore_normal
#check IsPGroup.isNilpotent
#check Sylow.isPGroup'
#check Nat.Coprime.of_dvd_right
#check Nat.Coprime.of_dvd_left
#check Nat.card_subtype_iff
#check Subgroup.card_subgroup_dvd_card
#check Subgroup.card_quotient_dvd_card
#check Subgroup.map_subgroupOf_eq_of_le
#check Subgroup.map_subgroupOf_eq
#check Subgroup.map_comap
#check Subgroup.comap_map
#check Subgroup.map_eq_top
#check Subgroup.map_sup
#check Subgroup.map_inf
#check Subgroup.subgroupOf_le
#check subgroupCentralizerIn
#check subgroupCentralizerIn_subgroupOf
#check Subgroup.map_subgroupOf_eq_of_le
#check Subgroup.subgroupOf_map_subtype_eq
