import Stellmacher.SectionOne.Defs
open scoped BigOperators Pointwise
#check fixedPointSubgroup_sup_commutatorAction_eq_top_of_solvable_coprime
#check commutatorAction_subgroup_conj_map_eq_commutator
#check fixedPointSubgroup_subgroup_conj_eq_subgroupCentralizerIn
#check fixedPointSubgroup_map_subtype_eq_inf
#check proposition_1_16_a
#check proposition_1_16_b
#check iSup_fixedPointSubgroup_zpowers_eq_top_of_noncyclic_abelian_pGroup_action
#check iSup_fixedPointSubgroup_cyclicQuot_eq_top_of_noncyclic_abelian_pGroup_action
#check Subgroup.centralizer
#check subgroupCentralizerIn
#check Subgroup.subgroupOf
#check Subgroup.map_iSup
#check Subgroup.commutator
#check Subgroup.commutator_comm
#check Sylow.isPGroup'
#check IsPGroup.isNilpotent
#check Nat.card_pos
#check Nat.Coprime
#check IsElementaryAbelian.of_exponent
#check isElementaryAbelian_iff
#check IsElementaryAbelian
#check commutatorAction₂
#check IsInvolution
#check Theory.Comparator.IsInvolution
#check IsPGroup.of_card
#check IsPGroup.exists_card_eq
#check pPrimeCore_coprime_card
#check pPrimeCore_normal
#check oddCore
