module
public import Theory.GroupAction.KleinFourPGroupCardinality
public import Theory.GroupAction.KleinFourFixedCardInequality
public import Theory.GroupAction.OddInvariantSylow
public import Theory.GroupTheory.SpecificGroups.KleinFourGenerators

/-!
# The Brauer--Wielandt formula for a Klein-four action

For commuting involutive automorphisms `a` and `b` of a finite odd-order group,
the group order times the square of the common fixed-subgroup order equals
the product of the three fixed-subgroup orders for `a`, `b`, and `a*b`.
The action may have a kernel, and no solvability hypothesis is imposed.

The proof transfers the p-group formula prime by prime. For a prime p,
extend a Sylow p-subgroup of the common fixed subgroup to a Sylow subgroup
of the whole group invariant under the two-group generated by `a` and `b`.
Its common fixed subgroup has the full p-part of the common fixed subgroup
order. Applying the p-group formula gives divisibility of the required
left side into the right side. The independent four-factor injection gives
the reverse numerical bound, forcing equality.

This proves the relation cited as Lemma 3 in Gorenstein--Walter, *On finite
groups with dihedral Sylow 2-subgroups*, Section 2, using their Lemma 4
uniqueness calculation for the bound. Only injectivity is used here;
surjectivity of the three-fixed-subgroup factorization remains a consequence
of this formula. The p-group input uses abelian simultaneous fixed/inverted
factors and induction through the center, following the elementary
Brauer--Wielandt fixed-point relation.
-/

open scoped Pointwise

namespace Theory.GroupAction

private theorem card_subgroupOf_eq_sylow_card
    {G : Type*} [Group G] [Finite G] {p : ℕ} [Fact p.Prime]
    (C P : Subgroup G) (hP : IsPGroup p P) (R : Sylow p C)
    (hRP : (R : Subgroup C).map C.subtype ≤ P) :
    Nat.card (C.subgroupOf P) = Nat.card R := by
  have hCP : IsPGroup p (C.subgroupOf P) := hP.to_subgroup _
  obtain ⟨n, hn⟩ := hCP.exists_card_eq
  have hdivC : Nat.card (C.subgroupOf P) ∣ Nat.card C :=
    Subgroup.card_comap_dvd_of_injective C P.subtype P.subtype_injective
  have hdivR : Nat.card (C.subgroupOf P) ∣ Nat.card R := by
    rw [hn] at hdivC ⊢
    exact R.pow_dvd_card_of_pow_dvd_card hdivC
  let f : R →* C.subgroupOf P :=
    { toFun x := ⟨⟨x.val.val, hRP ⟨x.val, x.property, rfl⟩⟩, x.val.property⟩
      map_one' := rfl
      map_mul' _ _ := rfl }
  have hf : Function.Injective f := by
    intro x y h
    exact Subtype.ext (Subtype.ext (congrArg (fun z : C.subgroupOf P => (z : G)) h))
  exact Nat.dvd_antisymm hdivR (Subgroup.card_dvd_of_injective f hf)

universe u
private theorem fixed_card_dvd
    {G : Type u} [Group G] [Finite G]
    (hodd : Odd (Nat.card G)) (a b : MulAut G)
    (ha : Function.Involutive a) (hb : Function.Involutive b) (hab : Commute a b) :
    Nat.card G * Nat.card ↥(a.fixedSubgroup ⊓ b.fixedSubgroup)^2 ∣
      Nat.card a.fixedSubgroup * Nat.card b.fixedSubgroup * Nat.card (a*b).fixedSubgroup := by
  classical
  let A : Subgroup (MulAut G) := Subgroup.closure ({a,b} : Set (MulAut G))
  have haa : a*a=1 := by ext x; exact ha x
  have hbb : b*b=1 := by ext x; exact hb x
  have hAA : IsPGroup 2 A := by
    intro x
    refine ⟨1, ?_⟩
    apply Subtype.ext
    change x.val ^ (2^1) = 1
    have hx := (Subgroup.mem_closure_pair_iff a b haa hbb hab x.val).mp x.property
    rcases hx with hx | hx | hx | hx
    · simp [hx]
    · simpa [hx, pow_two] using haa
    · simpa [hx, pow_two] using hbb
    · simp only [hx, pow_one, hab.mul_pow, pow_two, haa, hbb, mul_one]
  let _ : MulDistribMulAction A G := MulDistribMulAction.compHom G A.subtype
  let C := a.fixedSubgroup ⊓ b.fixedSubgroup
  have hCfix (s : A) (x : G) (hx : x ∈ C) : s • x = x := by
    change s.val x = x
    have hs := (Subgroup.mem_closure_pair_iff a b haa hbb hab s.val).mp s.property
    have hax : a x=x := (MulAut.mem_fixedSubgroup a x).mp hx.1
    have hbx : b x=x := (MulAut.mem_fixedSubgroup b x).mp hx.2
    rcases hs with hs | hs | hs | hs
    · simp [hs]
    · simpa [hs] using hax
    · simpa [hs] using hbx
    · simp [hs, MulAut.mul_apply, hax, hbx]
  apply (Nat.dvd_iff_prime_pow_dvd_dvd _ _).mpr
  intro p k hp hpk
  let _ : Fact p.Prime := ⟨hp⟩
  let R : Sylow p C := Classical.choice inferInstance
  let RG : Subgroup G := (R : Subgroup C).map C.subtype
  have hRG : IsPGroup p RG := R.isPGroup'.map _
  have hRGI : IsInvariant A G RG := by
    refine ⟨fun s x => ?_⟩
    constructor
    · intro hx
      have hxC : x ∈ C := Subgroup.map_subtype_le (R : Subgroup C) hx
      rwa [hCfix s x hxC]
    · intro hx
      have hxC : s • x ∈ C := Subgroup.map_subtype_le (R : Subgroup C) hx
      have hfixed : s⁻¹ • (s • x) = s • x := hCfix s⁻¹ (s • x) hxC
      have hxeq : x = s • x := by simpa using hfixed
      rwa [hxeq]
  obtain ⟨P, hRP, hPI⟩ := exists_invariant_sylow_le_of_isPGroup hAA hodd RG hRG hRGI
  let _ : IsInvariant A G (P : Subgroup G) := hPI
  let aa : A := ⟨a, Subgroup.subset_closure (by simp)⟩
  let bb : A := ⟨b, Subgroup.subset_closure (by simp)⟩
  let ap : MulAut P := MulDistribMulAction.toMulAut A P aa
  let bp : MulAut P := MulDistribMulAction.toMulAut A P bb
  have hap : Function.Involutive ap := by
    intro x
    apply Subtype.ext
    exact ha x.val
  have hbp : Function.Involutive bp := by
    intro x
    apply Subtype.ext
    exact hb x.val
  have habp : Commute ap bp := by
    apply MulEquiv.ext
    intro x
    apply Subtype.ext
    exact congrArg (fun f : MulAut G => f x.val) hab.eq
  have haeq : ap.fixedSubgroup = a.fixedSubgroup.subgroupOf (P : Subgroup G) := by
    ext x
    simp only [MulAut.mem_fixedSubgroup, Subgroup.mem_subgroupOf]
    exact Subtype.ext_iff
  have hbeq : bp.fixedSubgroup = b.fixedSubgroup.subgroupOf (P : Subgroup G) := by
    ext x
    simp only [MulAut.mem_fixedSubgroup, Subgroup.mem_subgroupOf]
    exact Subtype.ext_iff
  have habeq : (ap*bp).fixedSubgroup = (a*b).fixedSubgroup.subgroupOf (P : Subgroup G) := by
    ext x
    simp only [MulAut.mem_fixedSubgroup, Subgroup.mem_subgroupOf]
    exact Subtype.ext_iff
  have hcomeq : ap.fixedSubgroup ⊓ bp.fixedSubgroup = C.subgroupOf (P : Subgroup G) := by
    rw [haeq, hbeq]
    rfl
  have hcommon := card_subgroupOf_eq_sylow_card C (P : Subgroup G) P.isPGroup' R hRP
  have hPformula := brauerWielandt_fixedSubgroup_card_of_isPGroup P.isPGroup'
    (hodd.of_dvd_nat (Subgroup.card_subgroup_dvd_card (P : Subgroup G))) ap bp hap hbp habp
  rw [hcomeq, haeq, hbeq, habeq] at hPformula
  have hfixdiv (f : MulAut G) :
      Nat.card (f.fixedSubgroup.subgroupOf (P : Subgroup G)) ∣ Nat.card f.fixedSubgroup :=
    Subgroup.card_comap_dvd_of_injective f.fixedSubgroup
      (P : Subgroup G).subtype (P : Subgroup G).subtype_injective
  have hdiv : Nat.card P * Nat.card R ^ 2 ∣
      Nat.card a.fixedSubgroup * Nat.card b.fixedSubgroup * Nat.card (a*b).fixedSubgroup := by
    rw [← hcommon]
    change Nat.card P * Nat.card ((a.fixedSubgroup ⊓ b.fixedSubgroup).subgroupOf (P : Subgroup G))^2 ∣ _
    rw [hPformula]
    exact Nat.mul_dvd_mul (Nat.mul_dvd_mul (hfixdiv a) (hfixdiv b)) (hfixdiv (a*b))
  apply dvd_trans (b := Nat.card P * Nat.card R ^ 2) ?_ hdiv
  rw [P.card_eq_multiplicity, R.card_eq_multiplicity]
  change p^k ∣ Nat.card G * Nat.card C^2 at hpk
  have hGpos : Nat.card G ≠ 0 := Nat.card_pos.ne'
  have hCpos : Nat.card C ≠ 0 := Nat.card_pos.ne'
  have hproj := (hp.pow_dvd_iff_dvd_ordProj (mul_ne_zero hGpos (pow_ne_zero 2 hCpos))).mp hpk
  have hpow : p^(Nat.card C^2).factorization p = (p^(Nat.card C).factorization p)^2 := by
    rw [pow_two, Nat.ordProj_mul p hCpos hCpos, ← pow_two]
  rw [Nat.ordProj_mul p hGpos (pow_ne_zero 2 hCpos), hpow] at hproj
  exact hproj

/-- The Brauer--Wielandt order formula for three involutions in a Klein-four
action on a finite odd-order group. Trivial action images are permitted. -/
public theorem brauerWielandt_fixedSubgroup_card
    {G : Type u} [Group G] [Finite G]
    (hodd : Odd (Nat.card G)) (a b : MulAut G)
    (ha : Function.Involutive a) (hb : Function.Involutive b) (hab : Commute a b) :
    Nat.card G * Nat.card ↥(a.fixedSubgroup ⊓ b.fixedSubgroup)^2 =
      Nat.card a.fixedSubgroup * Nat.card b.fixedSubgroup * Nat.card (a*b).fixedSubgroup := by
  have hpositive : 0 < Nat.card a.fixedSubgroup * Nat.card b.fixedSubgroup *
      Nat.card (a*b).fixedSubgroup :=
    Nat.mul_pos (Nat.mul_pos Nat.card_pos Nat.card_pos) Nat.card_pos
  exact Nat.le_antisymm
    (Nat.le_of_dvd hpositive (fixed_card_dvd hodd a b ha hb hab))
    (MulAut.fixedSubgroup_card_product_le hodd a b ha hb hab)

end Theory.GroupAction
